// Français
I18N.addLang('fr', {
  help: {
    title: '64 Pad Explorer',
    description: 'Un outil pour explorer les gammes, accords et voicings sur une grille de 64 pads.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choisir parmi 12 tonalités',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonique, mineur harmonique, mineur mélodique, pentatonique, Bebop et plus \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Affiche les accords diatoniques de la gamme sélectionnée. Cliquer pour passer en mode Chord',
    chord_mode: 'Chord Mode (3 étapes)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Sélectionner la fondamentale sur le clavier',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choisir le type d\'accord (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Ajouter des tensions (9, b9, #9, 11, #11, 13, b13, etc.). Sélection multiple possible',
    chord_text: '<strong>Saisie texte</strong> \u2014 Appuyez sur "/" pour activer. Tapez Cm7, G7(b9,#11), Am7/G etc. directement. Suggestions automatiques',
    chord_onchord: '<strong>On Chord</strong> \u2014 Utiliser le bouton "/" pour les accords sur basse (accord / note de basse)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettre des notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 pour ajouter des notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Renversements (Root, 1st, 2nd, 3rd)',
    inv_1: '1er renversement',
    inv_2: '2e renversement',
    inv_3: '3e renversement',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Appuyer pour parcourir les dispositions sur le pad (badge pulsant = dispositions alternatives disponibles)',
    display: 'Affichage',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Activer/désactiver le manche de guitare, la basse, le clavier et la portée indépendamment. Note : Les positions guitare/basse montrent des doigtés jouables sur l\u2019instrument, elles ne correspondent pas à la disposition du pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Affiche le cycle des quintes. Lié à la sélection de tonalité, affichant les accords diatoniques et les fonctions (T/SD/D). Changement en mode mineur pris en charge',
    display_label: '<strong>Nom / Degré</strong> \u2014 Basculer entre noms de notes (C, D, E) et degrés (R, 2, 3) sur la guitare et les pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Décaler la tessiture des pads par octave',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Activer/désactiver le son avec l\u2019icône du haut-parleur',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Modélisation physique Rhodes. Les membres HPS peuvent sélectionner le preset Suitcase (chaîne d\'ampli modélisée physiquement). \u25BC ouvre le panneau de détails',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Modélisation physique Peterson Vactrol (stéréo). Utilisez TREM/T.SPD pour la profondeur et la vitesse',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtre enveloppe (Auto-Wah). 3 types : Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturation analogique. Ajoute une distorsion chaleureuse au son',
    sound_fx: '<strong>Effets</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Cliquer sur un pad ou une voicing box pour jouer le son',
    midi: 'MIDI',
    midi_detect: 'Détection automatique des appareils compatibles WebMIDI',
    midi_push: 'Support de la sortie MIDI série Ableton Push',
    midi_chord: 'Identification automatique des accords à partir des notes jouées',
    midi_sustain: '<strong>Pédale de sustain</strong> \u2014 Compatible MIDI CC64 (Hold Pedal)',
    color_title: 'Légende des couleurs',
    color_root: '<strong>Root</strong> \u2014 Fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notes de la gamme / Notes de l\'accord',
    color_char: '<strong>Caractéristique</strong> \u2014 Notes qui définissent la gamme/l\'accord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (tierce)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (septième)',
    color_tension: '<strong>Tension</strong> \u2014 Notes de tension',
    color_avoid: '<strong>Avoid</strong> \u2014 Note de la gamme un demi-ton au-dessus d\'une note d\'accord (en mode Chord)',
    color_palette: 'Palette de couleurs : Okabe-Ito (accessible aux daltoniens)',
    input_title: 'Input Mode',
    input_desc1: 'Cliquer librement sur les pads pour sélectionner des notes \u2192 Identification d\'accord en temps réel',
    input_desc2: 'Sans filtre théorique. Explorer \u2192 découvrir \u2192 apprendre la théorie ensuite',
    input_desc3: 'Lorsqu\'un accord est détecté, des étiquettes de degré (R, 3, 5, b7, etc.) s\'affichent sur les pads. Guitare, basse, piano et portée se mettent à jour automatiquement',
    input_memory: '<strong>Memory</strong> \u2014 Sauvegarder et rappeler des accords dans 16 emplacements',
    input_banks: '<strong>Banks</strong> \u2014 16 emplacements \u00D7 jusqu\u0027à 16 banques. Changer avec <kbd>[</kbd> <kbd>]</kbd>. Duplication et renommage pris en charge',
    input_export: '<strong>MIDI Export</strong> \u2014 Exporter les accords en mémoire en fichier MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bouton ou touche <kbd>p</kbd> pour basculer',
    perform_desc1: 'Jouez les accords des Memory Slots en temps réel avec un layout de 16 pads',
    perform_desc2: 'Déclenchez via le clavier (grille 4\u00D74) ou des pads MIDI',
    perform_desc3: 'Glissez-déposez les Slots pour réordonner',
    shortcut_title: 'Raccourcis clavier',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Sélectionner un accord diatonique (gammes à 7 notes)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Sélectionner une voicing box (parcourir les alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Parcourir les renversements (mode Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposer chromatiquement la fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Activer/désactiver Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Activer/désactiver Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycler Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycler Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: '<kbd>v</kbd> \u2014 Refléter sur pad / cycler disposition (style guitare \u2194 compact)',
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Cycler position de guitare (précédent / suivant)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Changer la position de basse (précédent / suivant)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Effacer l\'accord (mode Chord)',
    sc_pad_explore: '<b>Pad (mode Chord)</b> \u2014 Clic pour activer/désactiver une note \u2014 constructeur mis à jour',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Démarrer Capture / sauvegarder dans l\'emplacement suivant',
    sp_end: '<kbd>e</kbd> \u2014 Terminer Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Rappeler un emplacement mémoire (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposition chromatique (toutes les notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Renversement (la plus basse \u21911oct / la plus haute \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Tout effacer',
    sp_transfer: '<b>Chord switch</b> \u2014 Transférer l\'accord détecté en mode Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grille 4\u00D74 déclenche les Slots 1\u201316',
    pf_midi: 'Les pads MIDI (notes 36\u201354) déclenchent aussi les Slots',
    shortcut_common: 'Commun (tous les modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Basculer la vue Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annuler les Memory Slots (jusqu\u0027à 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd> \u2014 Sauvegarder dans un emplacement Input (depuis n\'importe quel mode)',
    sc_space: '<kbd>Space</kbd> \u2014 Jouer un accord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Désélectionner la voicing box / fermer l\'aide',
    sc_help: '<kbd>?</kbd> \u2014 Afficher/masquer l\'aide',
    sc_slash: '<kbd>/</kbd> \u2014 Activer la saisie texte d\'accord',
    sc_tasty_nav: '<kbd>z</kbd> / <kbd>x</kbd> \u2014 Voicing TASTY/STOCK précédent/suivant',
    shortcut_display: 'Bascules d\'affichage (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitare',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Basse',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Cycle des quintes',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Portée',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Saisie texte',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Affichage des tonalités',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 En-tête / Barre d\'info',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: 'Afficher les astuces au démarrage',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Verrouiller en Do majeur',
    c_fixed_tip: 'Le pad affiche toujours la gamme Do majeur, indépendamment de Key/Scale/Chord.',
    push_voicing_toggle: 'Voicing overview',
    layout: 'Disposition',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caractéristique',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Fermer',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> save(all 16)</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Sauvegarder',
    sound_hint: 'Sélectionnez un preset pour activer le son',
    tap_to_start: 'Appuyez pour activer le son',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: 'Appuyez sur un pad pour jouer !',
    load_vst: 'Charger un plugin VST/AU...',
    affiliate_label: '',
    staff: 'Partition',
    circle: 'Cycle',
    help: 'Aide',
    view_settings: 'Réglages d’affichage',
    view_focus: 'Affichage',
    view_layout: 'Disposition',
    view_all: 'Tous les panneaux',
    view_pad: 'Pad seulement',
    view_chord: 'Constructeur d’accords seulement',
    view_info: 'Info / mémoire seulement',
    layout_abc: 'Pad → Accord → Cycle',
    layout_acb: 'Pad → Cycle → Accord',
    layout_bac: 'Accord → Pad → Cycle',
    layout_bca: 'Accord → Cycle → Pad',
    layout_cab: 'Cycle → Pad → Accord',
    layout_cba: 'Cycle → Accord → Pad',
    view_setup_note: 'Dans la version Desktop, Push 3 Setup ouvre aussi cet écran. Jog Wheel gauche/droite choisit l’affichage ou la disposition, tourner change la valeur, et appuyer sur Jog Wheel ou Setup ferme l’écran.',
    oct_down: 'Baisser d\u0027une octave',
    oct_up: 'Monter d\u0027une octave',
    toggle_guitar: 'Afficher/masquer le manche de guitare (\u2318\u2325G)',
    toggle_bass: 'Afficher/masquer le manche de basse (\u2318\u2325B)',
    toggle_piano: 'Afficher/masquer le clavier de piano (\u2318\u2325P)',
    mode_scale: 'Mode Scale \u2014 voir les notes de gamme sur les pads (Tab pour changer)',
    mode_chord: 'Mode Chord \u2014 construire des accords avec voicings (Tab pour changer)',
    mode_input: 'Mode Input \u2014 cliquer librement sur les pads pour détecter les accords (Tab pour changer)',
    play_chord: 'Jouer l\u0027accord actuel (Space)',
    toggle_staff: 'Afficher/masquer la portée (\u2318\u2325S)',
    toggle_circle: 'Afficher/masquer le cycle des quintes (\u2318\u2325F)',
    toggle_sound: 'Afficher/masquer les contrôles de son',
    sound_mute: 'Son ON/OFF',
    sound_expand: 'Afficher/masquer les réglages de son détaillés',
    input_keys_disabled: 'La sélection de tonalité n\u0027est pas utilisée en mode Input',
  },
  label: {
    note_name: 'Note',
    degree: 'Degré',
    chord_input: 'Saisir un accord',
    chord_hint: 'Tensions entre ( ): C7(b9,#11) | dim, h=m7\u266D5 acceptés',
    key_hint: 'Aussi configurable via le mode Scale ou le Cycle des quintes',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mon Blog',
    guide: 'Guide',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Appuyer sur Capture pour commencer à construire des accords',
    status_capturing: 'Capture : Slot {slot}/16 \u2014 Cliquer sur les pads, puis Capture pour sauvegarder',
    status_editing: 'Édition : Slot {slot} \u2014 Cliquer sur les pads pour modifier',
    notes_label: 'Notes : ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    slot_selected: 'Slot {slot} sélectionné',
    slot_cleared: 'Slot {slot} effacé',
    undo: 'Annuler',
    settings_saved: 'Paramètres sauvegardés',
    no_chords: 'Aucun accord dans les emplacements mémoire',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    note_count: '{n} notes',
    default: 'Survolez n\'importe quel contrôle pour voir ce qu\'il fait',
    mode_scale: 'Mode Scale \u2014 Affiche les notes de gamme sur la grille 64 pads [Tab]',
    mode_chord: 'Mode Chord \u2014 Construisez des accords étape par étape : Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Mode Input \u2014 Cliquez librement sur les pads, les accords sont détectés automatiquement [Tab]',
    guitar: 'Afficher/masquer le manche de guitare [\u2318\u2325G]',
    bass: 'Afficher/masquer le manche de basse [\u2318\u2325B]',
    piano: 'Afficher/masquer le clavier de piano [\u2318\u2325P]',
    link_mode: 'Link Mode \u2014 les notes jouées se synchronisent sur tous les instruments en temps réel [\u2318\u2325L]',
    staff: 'Afficher/masquer la portée [\u2318\u2325S]',
    circle: 'Cycle des quintes \u2014 Tonique, Sous-dominante, Dominante affichées dans les couleurs correspondantes [\u2318\u2325F]',
    cof_major: 'Anneau extérieur \u2014 sélectionner une tonalité majeure',
    cof_minor: 'Anneau intérieur \u2014 sélectionner une tonalité mineure',
    cof_natural: 'Mineur naturel',
    cof_harmonic: 'Mineur harmonique',
    cof_melodic: 'Mineur mélodique',
    sound: 'Afficher/masquer le panneau audio [\u2318\u2325A]',
    memory: 'Afficher/masquer les Memory Slots \u2014 sauvegarder/rappeler des accords dans 16 emplacements [\u2318\u2325M]',
    sect_key: 'Afficher/masquer les tonalités',
    sect_input: 'Afficher/masquer la saisie texte d\'accord [\u2318\u2325T]',
    sect_quality: 'Afficher/masquer les sélecteurs Root/Quality/Tension [\u2318\u2325Q]',
    sect_voicing: 'Afficher/masquer les contrôles de voicing (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Saisir le nom d\'accord directement \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Afficher les gammes disponibles pour l\'accord actuel. Les slash chords avec basse non harmonique sont réinterprétés depuis la note de basse',
    sort_practical: 'Tri pratique \u2014 priorise les gammes couramment utilisées. Inclut les gammes de dominante secondaire (ex. Mixolydien b13 pour V7/ii)',
    sort_diatonic: 'Tri diatonique \u2014 trie par distance théorique depuis la tonalité actuelle',
    omit5: 'Supprimer la 5te du voicing [O]',
    rootless: 'Supprimer la fondamentale [R]',
    omit3: 'Supprimer la 3ce du voicing',
    shell137: 'Shell voicing : Root-3ce-7e [S]',
    shell173: 'Shell voicing : Root-7e-3ce [S]',
    shell_off: 'Désactiver le shell voicing [S]',
    shell_ext: 'Ajouter des notes au shell voicing (+1 ou +2 notes d\'accord)',
    inv_root: 'Position fondamentale [\u2193]',
    inv: 'Renversement [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 voicings raffinés triés par note supérieure. Fonctionne avec \u25B37, m7, 7 (exclusif HPS) [T]',
    tasty_nav: 'Parcourir les variations [Z / X]',
    stock: 'Stock Voicing \u2014 voicings piano courants (exclusif HPS) [K]',
    stock_nav: 'Parcourir les variations [Z / X]',
    root_notation: 'Basculer entre notation \u266F et \u266D',
    root_grid: 'Sélectionner la fondamentale',
    quality_grid: 'Sélectionner la qualité d\'accord (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Ajouter des tensions à l\'accord (9, b9, #9, 11, #11, 13, b13) \u2014 sélection multiple',
    diatonic: 'Accords diatoniques de la gamme actuelle \u2014 cliquer pour passer en mode Chord [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Comparer les accords diatoniques mineur harmonique et mélodique côte à côte [\u2318\u2325N]',
    parallel_key: 'Parallel Key \u2014 Afficher les accords diatoniques majeurs/mineurs pour la même fondamentale. Voir d\'où viennent les accords empruntés [\u2318\u2325R]',
    secdom: 'Dominante secondaire \u2014 Afficher le V7 résolvant vers chaque accord diatonique. Cliquer pour l\'affichage automatique Available Scale [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: 'Commencer à capturer les frappes de pads dans un emplacement mémoire [C]',
    capture_end: 'Terminer la capture et sauvegarder dans l\'emplacement actuel [E]',
    save: 'Sauvegarder tous les paramètres actuels (tonalité, gamme, son, mémoire, disposition)',
    tutorial: 'Tutoriels interactifs \u2014 apprendre les bases étape par étape',
    help: 'Ouvrir l\'aide avec la référence complète des raccourcis clavier [?]',
    affiliate: 'L\'achat via ces liens soutient le développement\u2026',
    lang: 'Changer la langue d\'affichage',
    octave: 'Décaler la tessiture des pads par octave \u2014 Push/Launchpad peuvent aussi contrôler via les boutons d\'octave',
    play: 'Jouer l\'accord actuel [Space]',
    scale_select: 'Sélectionner une gamme',
    chord_key: 'Basculer entre tonalité majeure et mineure',
    chord_key_picker: 'Ouvrir le sélecteur de tonalité pour changer de tonalité sans passer en mode Scale',
    builder_clear: 'Effacer l\'accord actuel et recommencer [X]',
    builder_back: 'Annuler la dernière étape de construction d\'accord [\u232B]',
    slash_chord: 'Slash chord (accord sur basse)',
    guitar_diagram: 'Les voicings de guitare courants sont affichés lorsqu\'un accord est sélectionné dans le constructeur',
    guitar_label: 'Afficher/masquer les noms de notes sur le manche de guitare',
    genre_preset: 'Changer le genre de voicing guitare \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul',
    pos_nav: 'Parcourir les positions de voicing guitare/basse [, .]',
    to_pad: 'Refléter le voicing guitare/stock sur la grille 64 pads [V]',
    inst_clear: 'Effacer les notes saisies sur le diagramme d\'instrument',
    inst_play: 'Jouer les notes saisies sur le diagramme d\'instrument',
    plain_clear: 'Effacer toutes les notes en mode Input [X]',
    midi_export: 'Exporter tous les emplacements mémoire en fichier MIDI pour votre DAW',
    chs_export: 'Exporter tous les emplacements mémoire au format CHS (Clover Chord Systems)',
    midi_import: 'Importer un fichier MIDI dans les emplacements mémoire',
    chs_import: 'Importer un fichier CHS dans les emplacements mémoire',
    midi_device: 'Sélectionner l\'entrée MIDI',
    midi_panic: 'All Notes Off \u2014 couper toutes les notes MIDI bloquées',
    sound_mute: 'Son ON/OFF',
    sound_preset: 'Sélectionner un preset sonore',
    volume: 'Volume principal',
    sound_fx: 'Effets \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 le filtre s\'ouvre/se ferme à chaque note. Type LP/BP, pente 2P/4P',
    velocity: 'Courbe de vélocité',
    mem_view: 'Vue mémoire \u2014 sauvegarder et organiser des accords dans 16 emplacements [M]',
    perform_view: 'Vue Perform \u2014 jouer les accords sauvegardés en temps réel avec 16 pads [P]',
    bank: 'Banques mémoire \u2014 16 emplacements \u00D7 jusqu\'à 16 banques. [ ] pour changer',
    slot_save: 'Sauvegarder l\'accord actuel dans l\'emplacement sélectionné',
    play_slots: 'Jouer tous les accords sauvegardés en séquence',
    locut: 'Lo-cut \u2014 Supprime les graves pour la clart\u00E9 (case ON/OFF, curseur = fr\u00E9quence de coupure)',
    hicut: 'Hi-cut \u2014 Supprime les aigus pour un ton plus rond (case ON/OFF, curseur = fr\u00E9quence)',
    drive: 'Drive \u2014 Quantit\u00E9 d\'overdrive. Plus haut = plus de distorsion',
    tremolo: 'Profondeur de tr\u00E9molo \u2014 Profondeur de modulation d\'amplitude (mod\u00E9lisation physique Peterson + CdS)',
    tremolo_speed: 'Vitesse de tr\u00E9molo \u2014 Fr\u00E9quence de modulation (Hz)',
    phaser: 'Phaser \u2014 Balayage avec d\u00E9calage de phase',
    flanger: 'Flanger \u2014 Delay tr\u00E8s court, balayage m\u00E9tallique',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Type de filtre \u2014 LP=Passe-bas / BP=Passe-bande',
    af_poles: 'Pente \u2014 2P=12dB/oct (douce) / 4P=24dB/oct (raide)',
    af_depth: 'Depth \u2014 Amplitude d\'ouverture/fermeture du filtre',
    af_decay: 'Decay \u2014 Vitesse de fermeture du filtre (plus petit = plus rapide)',
    af_q: 'Q \u2014 R\u00E9sonance (acuit\u00E9 du pic)',
    af_wet: 'WET \u2014 Niveau de l\'effet (0 = totalement dry, 10 = totalement wet)',
    af_vol: 'VOL \u2014 Trim de sortie (baisse si l\'ampli sature)',
    eq_bass: 'Baxandall Bass \u2014 EQ shelving graves. Centre = plat',
    eq_treble: 'Baxandall Treble \u2014 EQ shelving aigus. Centre = plat',
    reverb_type: 'Type de reverb \u2014 Spring (tra\u00EEne ondulante style Twin) / Plate (tra\u00EEne dense m\u00E9tallique)',
    reverb_amount: 'Quantit\u00E9 de reverb \u2014 Mix signal wet',
    reverb_decay: 'Decay reverb \u2014 Longueur de la tra\u00EEne',
    reverb_stereo: 'St\u00E9r\u00E9o \u2014 ON \u00E9tale la reverb sur L/R',
    reverb_dwell: 'Dwell \u2014 Drive d\'entr\u00E9e dans le tank \u00E0 ressorts',
    vel_thresh: 'Seuil de v\u00E9locit\u00E9 \u2014 Les frappes plus douces sont trait\u00E9es comme v\u00E9locit\u00E9 minimum',
    vel_drive: 'Velocity Drive \u2014 Inclinaison de la courbe (positif = accentue, n\u00E9gatif = aplatit)',
    vel_compand: 'Compand \u2014 Comprime/\u00E9tend autour de la v\u00E9locit\u00E9 m\u00E9diane',
    vel_range: 'Range \u2014 Plafond de v\u00E9locit\u00E9 maximum',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Sélectionner la fondamentale',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'Tous les appareils',
  },
  memory: {
    slot_empty: 'Slot {slot} : Vide',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS : {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play : {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Cliquer pour renommer',
    rename: 'Renommer',
    duplicate: 'Dupliquer',
    delete: 'Supprimer',
    rename_prompt: 'Nom de la banque :',
    confirm_delete: 'Supprimer "{name}" ?',
    limit_reached: 'Maximum 16 banques',
    cannot_delete_last: 'Impossible de supprimer la dernière banque',
  },
  diatonic: {
    parallel: 'Tonalité parallèle',
    relative: 'Relatif',
    harm_mel: 'Harm/Mel',
    secdom: 'Dominante secondaire',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Tout afficher',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'Un outil navigateur pour explorer les gammes, accords et voicings sur une grille de 64 pads.<br>Aucune source sonore requise \u2014 juste Chrome.',
    cta: 'Ouvrir l\u0027appli',
    features: 'Fonctionnalités',
    feat_sound: '<strong>Aucune source sonore requise</strong> \u2014 Le son est joué directement dans Chrome. 4 presets orgue + 8 presets piano électrique intégrés. Effets (drive, reverb, phaser, flanger, tremolo, lo cut, hi cut, auto filter) inclus',
    feat_input: '<strong>Aucune compétence de pad requise</strong> \u2014 Construisez des accords en 3 étapes. Tensions affichées. Cliquez sur les pads pour saisir directement',
    feat_text_input: '<strong>Saisie texte d\'accords</strong> \u2014 Appuyez "/" pour saisir Cm7, G7(b9,#11), Am7/G etc. directement. Auto-complétion. Abréviations dim, h(=m7\u266D5) acceptées',
    feat_detect: '<strong>Détection d\u0027accords</strong> \u2014 Détection en temps réel du nom d\u0027accord à partir des notes cliquées. Supporte omit, accords sur basse et candidats multiples',
    feat_instruments: '<strong>Affichage Guitar / Bass / Keyboard</strong> \u2014 Affiche les notes d\u0027accord sur le manche de guitare, la basse et le piano. La saisie sur le manche de guitare se répercute automatiquement sur les pads. En mode Chord, les positions sont groupées par corde fondamentale',
    feat_scales: '<strong>Affichage des gammes</strong> \u2014 31 gammes \u00D7 12 tonalités. Diatonique, mineur harmonique, mineur mélodique, pentatonique, Bebop et plus',
    feat_diatonic: '<strong>Affichage des accords diatoniques</strong> \u2014 Les accords diatoniques sont affichés sur une barre pour la gamme sélectionnée. Cliquez ou utilisez les raccourcis pour jouer instantanément. Basculement triades/tétrades',
    feat_voicing: '<strong>Opérations de voicing</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Flèches pour les inversions, boutons pour les doigtés multiples',
    feat_memory: '<strong>Mémoire d\u0027accords</strong> \u2014 Sauvegardez vos accords favoris dans 16 emplacements. Exportez en fichiers MIDI pour votre DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Jouez les accords en mémoire en temps réel avec 16 pads ou votre clavier PC',
    feat_parent: '<strong>Recherche inversée Available Scale</strong> \u2014 Trouvez les gammes contenant votre accord. Voyez les Available Tensions d\u0027un coup d\u0027\u0153il. Basculement Practical/Diatonic',
    feat_pivot: '<strong>Pensée accord pivot</strong> \u2014 Saisissez un accord manuellement et la barre diatonique disparaît, affichant toutes les tonalités auxquelles votre accord pourrait appartenir. Idéal pour l\u0027analyse de modulation',
    feat_dimming: '<strong>Affichage pratique des Tensions</strong> \u2014 Pour les accords de 7ème non dominante, les tensions peu courantes (b9, #9, b13, etc.) sont atténuées. Toujours sélectionnables',
    feat_circle: '<strong>Cycle des quintes</strong> \u2014 Affiche le cycle des quintes. Lié à la sélection de tonalité, affichant les accords diatoniques et les fonctions (T/SD/D). Changement en mode mineur pris en charge',
    feat_banks: '<strong>Banques mémoire</strong> \u2014 16 emplacements \u00D7 jusqu\'à 16 banques. Changer, dupliquer et renommer les banques. Touches <kbd>[</kbd> <kbd>]</kbd> pour changer',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtre enveloppe (Auto-Wah). 3 types : Cry Baby / Mu-Tron / Moog. Régler la fréquence, la résonance, la sensibilité et le decay',
    feat_drive: '<strong>Drive</strong> \u2014 Saturation analogique. Ajoute une distorsion chaleureuse au son',
    feat_clav: '<strong>Presets Clavinet</strong> \u2014 2 presets Clavinet ajoutés à E.PIANO (Clav Muted, Clav Bright). Parfait pour le funk',
    feat_midi_sens: '<strong>Sensibilité de vélocité MIDI</strong> \u2014 Réglage de courbe de vélocité à 4 paramètres style Push 3 (Threshold, Drive, Compand, Range). Visualisation en temps réel de la courbe. Fonctionne avec tous les contrôleurs MIDI',
    feat_push_oct: '<strong>Synchronisation d\'octave Push 3</strong> \u2014 Les boutons d\'octave \u25B2\u25BC de Push 3 se synchronisent automatiquement avec le décalage d\'octave de l\'appli',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 langues (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Captures d\u0027écran',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Sélectionnez une tonalité et une gamme pour voir les notes de gamme colorées sur la grille de 64 pads. Choisissez des accords depuis la barre diatonique.',
    ss_scale_alt: 'Scale Mode \u2014 Affichage de la gamme de C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), notes de gamme (bleu), notes caractéristiques (jaune)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construisez des accords en 3 étapes : Root \u2192 Quality \u2192 Tension. Ajustez les voicings avec inversions, Drop, Shell et Omit. Utilisez le panneau Parent Scale pour la recherche inversée.',
    ss_chord_alt: 'Chord Mode \u2014 Affichage de l\u0027accord Dm7 avec grille de tensions',
    ss_chord_caption: 'Dm7 \u2014 Notes d\u0027accord, 3rd (rose), 7th (vert). Vérifiez les dispositions dans les voicing boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Cliquez librement sur les pads pour une détection d\u0027accords en temps réel. Comprenez les accords même sans connaître la théorie.',
    ss_input_alt: 'Input Mode \u2014 Détection en temps réel de C7',
    ss_input_caption: 'C7 \u2014 Cliquez sur les pads pour détecter automatiquement les noms d\u0027accords. Candidats multiples affichés',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Placez les accords sauvegardés sur 16 pads pour une performance en temps réel via clavier ou pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 emplacements avec accords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 sauvegardés dans les emplacements. Jouez avec la grille clavier 4\u00D74',
    ss_parent: 'Available Scale + Accord Pivot',
    ss_parent_desc: 'Recherche inversée des gammes contenant votre accord. Basculez entre tri Practical (par utilité) et Diatonic (par théorie). La saisie manuelle d\u0027accord masque la barre diatonique pour l\u0027analyse d\u0027accords pivot.',
    ss_parent_alt: 'Panneau Parent Scale et affichage du manche de guitare',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions affichées',
    ss_parent_note: '\u203B Les gammes pentatoniques/blues sont modales (approche horizontale) et appartiennent à un système différent de la théorie des gammes par accord (correspondance verticale), elles ne sont donc pas incluses dans Available Scale. En pratique, la pentatonique est souvent le premier choix.',
    ss_velocity: 'Sensibilité de vélocité MIDI',
    ss_velocity_desc: 'Réglez la sensibilité de vélocité du contrôleur MIDI avec 4 paramètres style Push 3. Configurez dans la section VELOCITY SENSITIVITY du panneau Sound. Visualisation en temps réel de la courbe.',
    ss_push_oct: 'Synchronisation des boutons d\'octave Push 3',
    ss_push_oct_desc: 'Les boutons d\'octave \u25B2\u25BC de Push 3 (CC#55/CC#54) se synchronisent automatiquement avec le décalage d\'octave de l\'appli. Appuyez sur les boutons d\'octave de Push 3 et l\'octave affichée se met à jour automatiquement.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Fonctions de Voicing exclusives HPS',
    ss_hps_voicing_intro: 'Les membres HPS disposent de 3 outils de voicing. Chacun propose des voicings issus d\u0027un instrument et d\u0027une classification différents, et tous peuvent être reflétés sur la disposition 64 pads avec \u00AB To Pad \u00BB.',
    ss_tasty: 'TASTY Voicing \u2014 Classé par note supérieure',
    ss_tasty_desc: '129 voicings sophistiqués affichés sous forme de tableaux de degrés. Sélectionnez un accord, appuyez sur <kbd>T</kbd> pour activer, et appuyez à nouveau pour parcourir les voicings. Sélection automatique de la position optimale sur les pads.',
    ss_tasty_target: 'Cible : Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'La zone d\u0027info affiche l\u0027ordre d\u0027empilement des degrés (ex. : <code>m9 (b3-b7-9-5-1)</code>). C\u0027est la structure du voicing \u2014 quelles notes sont empilées du bas vers le haut.',
    ss_tasty_labels_title: 'Signification des étiquettes',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Fondamentale (1er degré) omise. Courant en jazz/R&B/neo-soul où le bassiste couvre la fondamentale.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5te omise. La 5te a peu de caractère tonal, elle est donc remplacée par une tension pour un son plus riche.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3ce omise. Se rapproche d\u0027un son sus ou Quartal.',
    ss_tasty_ops_title: 'Commandes',
    ss_stock: 'STOCK Voicing \u2014 Collection de Voicings piano',
    ss_stock_desc: '154 voicings de piano issus de matériels pédagogiques, affichés en notation de degrés. Couvre Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Visualisez les positions réelles sur l\u0027affichage clavier, puis utilisez \u00AB To Pad \u00BB pour mapper sur la disposition des pads.',
    ss_stock_ops_title: 'Commandes',
    ss_guitar_pos: 'Guitar Position \u2014 Voicings guitare',
    ss_guitar_pos_desc: 'Calcul automatique des positions d\u0027accords sur le manche de guitare. Cliquez sur le manche pour une saisie manuelle. Utilisez <kbd>V</kbd> \u00AB To Pad \u00BB pour convertir les voicings guitare en disposition de pads. Choix entre disposition style guitare (1 note par rangée) et compacte.',
    usecases: 'Cas d\u0027utilisation',
    uc1_q: '\u00AB Je veux trouver comment voicer cet accord sur les pads \u00BB',
    uc1_a: '\u2192 Sélectionnez Root, Quality et Tension en mode <span class="mode-badge chord">Chord</span> \u2192 Vérifiez les dispositions dans les voicing boxes',
    uc2_q: '\u00AB Je veux voir une gamme de ma leçon sur les pads \u00BB',
    uc2_a: '\u2192 Sélectionnez tonalité et gamme en mode <span class="mode-badge scale">Scale</span>. 31 gammes disponibles',
    uc3_q: '\u00AB Je veux créer une progression d\u0027accords pour mon DAW \u00BB',
    uc3_a: '\u2192 Sauvegardez les accords dans les emplacements mémoire \u2192 MIDI Export pour importer dans votre DAW',
    uc4_q: '\u00AB À quelle tonalité appartient cet accord ? \u00BB',
    uc4_a: '\u2192 Recherche inversée dans le panneau Available Scale. Basculez entre tri Practical/Diatonic',
    uc7_q: '\u00AB Je veux trouver des accords pivot pour la modulation \u00BB',
    uc7_a: '\u2192 Saisissez un accord manuellement en mode <span class="mode-badge chord">Chord</span>. La barre diatonique disparaît et Available Scale affiche toutes les tonalités possibles',
    uc5_q: '\u00AB Je veux vérifier des progressions d\u0027accords en les jouant \u00BB',
    uc5_a: '\u2192 Sauvegardez les accords dans les slots mémoire, puis jouez-les avec un contrôleur MIDI ou le clavier du PC',
    uc6_q: '\u00AB Je veux vérifier un accord de guitare sur les pads \u00BB',
    uc6_a: '\u2192 Cliquez sur le manche de guitare pour saisir \u2192 Affichage automatique sur les pads \u2192 Nom d\u0027accord détecté',
    uc8_q: '\u00AB Je veux apprendre des voicings professionnels \u00BB',
    uc8_a: '\u2192 Construisez un accord en mode <span class="mode-badge chord">Chord</span>, puis appuyez sur <kbd>T</kbd> pour TASTY (classification par note supérieure) ou <kbd>K</kbd> pour STOCK (voicings piano). Visualisez avec la notation de degrés, sauvegardez en mémoire et exportez vers le DAW',
    quickstart: 'Démarrage rapide',
    qs_modes: '3 modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Afficher les gammes et accords diatoniques<br><span class="mode-badge chord">Chord</span> Construire des accords en 3 étapes. Opérations de voicing disponibles<br><span class="mode-badge input">Input</span> Cliquer librement sur les pads \u2192 Détection automatique des noms d\u0027accords',
    qs_first: 'Pour commencer',
    qs_step1: 'Choisissez une tonalité (ex : C)',
    qs_step2: 'Choisissez une gamme (ex : Major) \u2192 Les notes de gamme apparaissent sur les pads',
    qs_step3: 'Cliquez sur un accord dans la barre diatonique (ex : Dm7) \u2192 Notes d\u0027accord affichées',
    qs_step4: 'Cliquez sur les pads pour jouer les sons. Changez les dispositions dans les voicing boxes',
    qs_step5: 'Sauvegardez vos accords favoris avec <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Raccourcis clavier',
    qs_shortcuts_desc: 'Appuyez sur <kbd>?</kbd> pour la liste complète des raccourcis.<br><kbd>Space</kbd> pour jouer un accord. <kbd>1</kbd>\u2013<kbd>7</kbd> pour les accords diatoniques, <kbd>\u2191</kbd><kbd>\u2193</kbd> pour les inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> pour le mouvement chromatique.<br>En Perform mode, utilisez <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> comme grille 4\u00D74.',
    footer_open: 'Ouvrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'En savoir plus sur le blog \u2192',
    // Icônes d'en-tête
    header_icons: 'Icônes d\u2019en-tête',
    header_icons_desc: 'Trois boutons d\u2019icônes en haut à droite.',
    icon_save: '<strong>\uD83D\uDCBE Sauvegarder</strong> \u2014 Sauvegarde les paramètres actuels (son, effets, options d\u2019affichage, etc.) dans le navigateur. Restauration automatique à la prochaine visite',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutoriel</strong> \u2014 Parcourez 11 tutoriels interactifs. Apprenez chaque fonction étape par étape',
    icon_help: '<strong>? Aide</strong> \u2014 Affiche les raccourcis clavier, l\u2019historique des versions et la description des modes. S\u2019ouvre aussi avec la touche <kbd>?</kbd>',
    sound_panel: 'Panneau audio',
    sound_panel_desc: 'Sélectionnez les presets et ajustez les effets. Cliquez sur le bouton \u25B6 pour développer le panneau.',
    sound_presets: 'Presets audio',
    sound_presets_desc: 'Le moteur de modélisation physique Rhodes (Clean DI) est le son par défaut. Jouez instantanément sans téléchargement de samples. Utilisez le bouton VOICING pour ajuster la tonalité du pickup.',
    sound_effects: 'Effets',
    sound_effects_desc: 'Faites glisser chaque bouton pour ajuster les valeurs.',
    fx_drive: 'Saturation analogique. Distorsion chaleureuse',
    fx_locut: 'Filtre coupe-bas. Élimine les basses boueuses',
    fx_hicut: 'Filtre coupe-haut. Atténue les aigus agressifs',
    fx_reverb: 'Réverbération. Ajoute de la profondeur spatiale',
    fx_phaser: 'Phaser. Modulation enveloppante',
    fx_flanger: 'Flanger. Modulation type jet',
    fx_tremolo: 'Trémolo. Modulation périodique du volume',
    sound_autofilter: 'Auto-Filtre (Auto-Wah)',
    sound_autofilter_desc: 'Filtre à enveloppe. Ajustez FREQ, RESO, SENS et DECAY.',
    version_history: 'Historique des versions',
    vh_540: '<b>V5.4</b> \u2014 Mod\u00E9lisation physique mise \u00E0 jour. Ajout des param\u00E8tres de filtre (WET / VOL) et d\'un preset r\u00E9serv\u00E9 aux membres HPS (Pad Sensei MK1 AMP Vintage Envelope Filter)',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Mod\u00E9lisation du pr\u00E9amp am\u00E9lior\u00E9e',
    vh_510: '<b>V5.1</b> \u2014 Mode gamme fixe Do majeur ajout\u00E9',
    vh_500: '<b>V5.0</b> \u2014 Moteur sonore et effets autonomes. Spring Reverb (mod\u00E9lisation physique) + Plate Reverb. Mod\u00E8le d\'amplificateur Suitcase am\u00E9lior\u00E9. S\u00E9lecteur de type de Reverb (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Jouez instantan\u00E9ment d\u00E8s l\'ouverture (sans t\u00E9l\u00E9chargement de samples). Basculer les indices de raccourcis clavier. Accords diatoniques NM/HM/MM pour les tonalit\u00E9s mineures parall\u00E8les. PU LEVEL et MECHANICAL ajout\u00E9s au E.PIANO MIXER. Am\u00E9liorations de l\'affichage de d\u00E9tection d\'accords',
    vh_490: '<b>V4.9</b> \u2014 Moteur de mod\u00E9lisation physique Pad Sensei MK1',
    vh_497: '<b>V4.9.7</b> \u2014 Le tr\u00E9molo est maintenant mod\u00E9lis\u00E9 physiquement. Les membres HPS obtiennent Pad Sensei MK1 Suitcase (cha\u00EEne d\'amplification mod\u00E9lis\u00E9e physiquement)',
    vh_3377: '<b>V3.37.7</b> \u2014 Revue utilisateur : correction de la tonalité relative mineure, badges en title case, police sans-serif pour les pads, bascules adaptées aux daltoniens (vert\u2192bleu), panneau Sound ouvert par défaut, correction du décalage de mise en page, superposition spotlight tutoriel, support d\'octave Launchpad + suivi automatique d\'octave pour tous les contrôleurs MIDI',
    vh_340: '<b>V3.40</b> \u2014 Positionnement compact TASTY/Stock : disposition optimale automatique sur la grille 64 pads. Bouton \u00AB To Pad \u00BB supprimé. Boîtes de voicing masquées en mode TASTY/Stock',
    vh_336: '<b>V3.36</b> \u2014 Moteur de voicing guitare v2 : préréglages de genre (Jazz/Bossa/Funk), table de référence (120 types \u00D7 12 tons), assignation automatique des doigts avec détection de barré',
    vh_335: '<b>V3.35</b> \u2014 Améliorations UX des tutoriels (revue débutant). Tous les tooltips traduits en 9 langues. Guide : sections panneau de son et icônes d\u2019en-tête ajoutées',
    vh_333: '<b>V3.33</b> \u2014 Tutoriels interactifs. 11 sujets \u00D7 9 langues. Indices contextuels lors de la première interaction avec chaque fonctionnalité',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing : 154 voicings piano avec affichage clavier spécifique MIDI. Guide mis à jour avec la section fonctions de voicing HPS',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 voicings sophistiqués triés par note supérieure. Affichage tableau de degrés + optimisation automatique d\u2019octave. Réservé aux membres HPS',
    vh_325: '<b>V3.25.0</b> \u2014 Voicing guitare \u2192 reflet sur pad (touche <kbd>V</kbd>). Basculement disposition style guitare (1 note par rangée) / compact. Filtre "Tous" des positions de guitare en premier',
    vh_324: '<b>V3.24</b> \u2014 Presets Clavinet ajoutés (2 dans E.PIANO). Effet Auto Filter (filtre enveloppe / auto-wah) ajouté',
    vh_323: '<b>V3.23</b> \u2014 Saisie texte d\'accords avec auto-complétion. "/" pour activer, abréviations (dim, h=m7\u266D5), tri par tensions',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Basculement triade/tétrade diatonique. Positions guitare/basse groupées par corde fondamentale',
    vh_37: '<b>V3.7</b> \u2014 Préservation de la position de voicing (maintien automatique de la forme du doigté lors des mouvements chromatiques). Grille de pads, portée et détection d\u0027accords pendant la lecture. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Vidéo</a>',
    vh_35: '<b>V3.5</b> \u2014 Lecture de fichier MIDI \u2192 éclairage des pads (lecture en timeline, affichage du nom d\u0027accord, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 presets EP. Interrupteur Sound ON/OFF. Support iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilité vélocité (4 paramètres + visualisation de courbe). Support du bouton d\u0027octave Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Vidéo</a>',
    vh_250: '<b>V2.50</b> \u2014 Plusieurs banques mémoire (16 slots \u00D7 jusqu\u0027à 16 banques, changer/dupliquer/renommer)',
    vh_218: '<b>V2.18</b> \u2014 Sauvegarde/restauration automatique de tous les paramètres (tonalité/gamme/son/MIDI/mémoire)',
    vh_213: '<b>V2.13</b> \u2014 Superposition de gamme d\u0027instrument (guitare/basse/piano affichent Available Scale). Étiquettes de degré sur pads. Lecture liée à l\u0027octave',
    vh_27: '<b>V2.7</b> \u2014 Mode d\u0027ajout de tensions (synthèse d\u0027accords pad/guitare/basse/clavier \u2192 filtrage Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, superposition de gamme sur pads)',
    vh_19: '<b>V1.9</b> \u2014 9 langues',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 emplacements mémoire, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Mode Plain, export MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Version initiale (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6eR',
    root_5: '5eR',
    root_4: '4eR',
    root_3: '3eR',
    root_2: '2eR',
    open: 'Ouvert',
    all: 'Toutes',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'Vers Pad',
    genre_default: 'Standard',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
  },
  tips: [
    'Appuyez sur C pour sauvegarder l\'accord actuel dans Memory',
    'Opt+1~V sauvegarde directement dans un slot (16 touches: 1234 QWER ASDF ZXCV)',
    'Shift+Clic sur un slot Memory pour le supprimer',
    'Opt+Glisser pour copier un slot',
    'Appuyez sur S pour alterner les Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D alterne Drop 2 / Drop 3',
    '\u2318\u2325G affiche le manche de guitare',
    '\u2318\u2325F affiche le Cycle des Quintes',
    'Tab alterne entre les modes Scale / Chord / Input',
    'Espace joue la gamme ou l\'accord actuel',
    'Exportez tous les slots Memory en fichier MIDI',
    'Connectez un contrôleur MIDI pour jouer les pads',
    'Flèches \u2193\u2191 changent le renversement de l\'accord',
    'Appuyez sur R pour un voicing sans fondamentale',
    'Appuyez sur O pour omettre la 5te',
    '\u2318\u2325S affiche la partition',
    'L\'icône de sauvegarde conserve vos réglages entre sessions',
    '[ ] change les banques Memory \u2014 gérez plusieurs morceaux',
    'Mode Perform : Déclenchez des accords avec le clavier (1234 / QWER / ASDF / ZXCV) ou pads MIDI',
    'Appuyez sur / en mode Chord pour saisir des noms d\'accords (ex: Cm7, G7(b9,#11))',
  ],
  tips_off: 'Ne plus afficher',
  whats_new: 'Nouveautés',
  whats_new_497: 'Le tr\u00E9molo est maintenant mod\u00E9lis\u00E9 physiquement ! Les membres HPS obtiennent Pad Sensei MK1 Suitcase.',
  whats_new_61: 'Le manuel en ligne est maintenant accessible depuis le Guide. En cours de construction.',
  whats_new_123: 'Le manuel en ligne est maintenant accessible depuis le Guide. En cours de construction.',
  whats_new_51: 'Mode verrouillé sur Do majeur ajouté ! Active-le depuis Aide (?). Push/Launchpad affiche toujours Do majeur.',
  whats_new_50: 'R\u00E9verb\u00E9rations \u00E0 ressort et \u00E0 plaque ajout\u00E9es ! \u00C9galiseur Baxandall Bass/Treble, ampli Suitcase am\u00E9lior\u00E9.',
  whats_new_32427: 'Voicing guitare \u2192 reflet sur pad (touche V). Basculement disposition style guitare / compact',
  whats_new_33000: 'Système de tutoriels ! Cliquez sur l\'icône livre dans l\'en-tête pour apprendre le mode Scale, le mode Chord et plus encore.',
  whats_new_640: 'V6.4.0 est disponible : détection de trois tensions, analyse UST, affichage Note/Degree et notation # / b selon la tonalité.',

  // Legacy tutorial keys (backward compat for old lang files)
  tutorial: {
    sound_title: 'Preset de son',
    sound_msg: 'Choisissez un preset et appuyez sur un pad pour l\u0027écouter.\nORGAN et E.PIANO \u2014 chacun a plusieurs presets.',
    sound_done: 'Ça sonne bien ! Appuyez sur Suivant pour continuer.',
    midi_title: 'Contrôleur MIDI',
    midi_msg: 'Un contrôleur MIDI a été détecté. Sélectionnez votre appareil dans le menu déroulant.\nLa sensibilité de vélocité peut être ajustée dans le panneau Sound.',
    midi_no_device: 'Aucun contrôleur MIDI détecté \u2014 pas de souci.\nVous pouvez utiliser les clics sur les pads, l\u0027entrée guitare/basse/piano ou la saisie texte d\u0027accords.',
    input_title: 'Trois modes',
    input_msg: 'Scale \u2014 voir les notes de gamme sur la grille de 64 pads\nChord \u2014 construire des accords avec voicings, renversements et tensions\nInput \u2014 cliquer librement sur les pads pour détecter les noms d\u0027accords\n\nChangez avec Tab ou les boutons de mode ci-dessus.',
    instruments_title: 'Entrée instrumentale',
    instruments_msg: 'Guitare, Basse, Piano \u2014 activez chaque affichage et cliquez pour saisir des notes directement.\nClic sur le manche \u2192 détection d\u0027accord \u2192 \u00AB Vers Pad \u00BB (V) pour convertir en disposition de pads.\nSaisie texte : appuyez sur / en mode Chord pour saisir des noms d\u0027accords (ex. Cm7, G7(b9,#11)).',
    done_title: 'Prêt !',
    done_msg: 'Tout est prêt. Explorez librement \u2014 appuyez sur ? pour la liste complète des raccourcis.\nLe Guide contient des captures d\u0027écran, des vidéos et des cas d\u0027utilisation.',
    next: 'Suivant',
    skip_step: 'Suivant',
    skip_all: 'Passer le tutoriel',
    open_guide: 'Ouvrir le Guide',
    close: 'Commencer',
    reset: 'Redémarrer le tutoriel',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutoriels',
    cat_getting_started: 'Pour commencer',
    cat_features: 'Fonctionnalités',
    cat_advanced: 'Avancé',
    steps_label: 'étapes',
    reset_all: 'Réinitialiser toute la progression',
    close_selector: 'Fermer',
    hint_available: 'Tutoriel disponible',
    hint_try: 'Essayer',
    // Button label
    btn_label: 'Tutoriels',
    // Shared action labels
    next: 'Suivant',
    skip_step: 'Suivant',
    skip_all: 'Passer le tutoriel',
    open_guide: 'Ouvrir le Guide',
    close: 'Terminé',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutoriel',
    onboarding_ask_msg: 'Première visite ? Voulez-vous un tour rapide de l\u0027appli ?',
    onboarding_yes: 'Suivant',
    onboarding_no: 'Passer',
    // Onboarding
    onboarding_title: 'Premiers pas',
    onboarding_desc: 'Apprenez les bases de 64 Pad Explorer',
    onboarding: {
      sound_title: 'Preset de son',
      sound_msg: 'Choisissez un preset et appuyez sur un pad pour l\u0027écouter.\nORGAN et E.PIANO \u2014 chacun a plusieurs presets.',
      sound_done: 'Ça sonne bien ! Appuyez sur Suivant pour continuer.',
      midi_title: 'Contrôleur MIDI',
      midi_msg: 'Un contrôleur MIDI a été détecté. Push 3 et Launchpad fonctionnent immédiatement \u2014 aucune configuration requise.\nLa sensibilité de vélocité peut être ajustée dans le panneau Sound.',
      midi_no_device: 'Aucun contrôleur MIDI détecté \u2014 pas de souci.\nVous pouvez utiliser les clics sur les pads, l\u0027entrée guitare/basse/piano ou la saisie texte d\u0027accords.',
      input_title: 'Trois modes',
      input_msg: 'Scale \u2014 voir les notes de gamme sur la grille de 64 pads\nChord \u2014 construire des accords avec voicings, renversements et tensions\nInput \u2014 cliquer librement sur les pads pour détecter les noms d\u0027accords\n\nChangez avec Tab ou les boutons de mode ci-dessus.',
      instruments_title: 'Entrée instrumentale',
      instruments_msg: 'Guitare, Basse, Piano \u2014 activez chaque affichage et cliquez pour saisir des notes directement.\nClic sur le manche \u2192 détection d\u0027accord \u2192 \u00AB Vers Pad \u00BB (V) pour convertir en disposition de pads.\nSaisie texte : appuyez sur / en mode Chord pour saisir des noms d\u0027accords (ex. Cm7, G7(b9,#11)).',
      done_title: 'Prêt !',
      done_msg: 'Tout est prêt. Explorez librement \u2014 appuyez sur ? pour la liste complète des raccourcis.\nLe Guide contient des captures d\u0027écran, des vidéos et des cas d\u0027utilisation.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Mode Scale',
    scale_mode_desc: 'Explorez les gammes sur la grille de 64 pads',
    scale_mode: {
      step1_title: 'Passer en mode Scale',
      step1_msg: 'Le mode Scale illumine les notes de gamme sur la grille.\nAppuyez sur un pad allumé pour entendre la note.',
      step2_title: 'Choisir une tonalité',
      step2_msg: 'Choisissez une tonalité parmi les rangées majeure et mineure (ordre du cycle des quartes).\nVous pouvez aussi définir la tonalité depuis le cycle des quintes. Anneau extérieur = tonalités majeures, anneau intérieur = tonalités mineures. Les tonalités mineures supportent 3 types de gammes mineures.\nEssayez de passer entre C, G, F.',
      step3_title: 'Choisir une gamme',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 gammes disponibles. Les pads se mettent à jour en temps réel.',
      step4_title: 'Barre diatonique',
      step4_msg: 'Les accords diatoniques de votre gamme apparaissent ici.\nAppuyez sur 3 pour les triades, 4 pour les tétrades (accords de septième).\nCliquez sur un accord pour passer en mode Chord avec ce voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Mode Chord',
    chord_mode_desc: 'Construisez des accords étape par étape',
    chord_mode: {
      step1_title: 'Passer en mode Chord',
      step1_msg: 'Le mode Chord offre deux façons de sélectionner des accords.\n\u2460 Choisir dans la barre diatonique en un clic\n\u2461 Construire le vôtre : Root \u2192 Quality \u2192 Tension',
      step_key_title: 'Sélection de tonalité',
      step_key_msg: 'Définir la tonalité de la gamme. Quand une tonalité est définie, la barre diatonique affiche les accords et la disponibilité des tensions est filtrée.\nVous pouvez aussi construire des accords librement depuis Root sans utiliser la tonalité.',
      step_diatonic_title: 'Barre diatonique',
      step_diatonic_msg: 'Accords diatoniques de la tonalité sélectionnée.\nCliquez pour définir instantanément un accord avec filtrage des tensions adapté à la gamme.',
      step2_title: 'Étape 1 : Root',
      step2_msg: 'Choisissez une note fondamentale. C, D, E... les 12 notes.\nL\u0027écran affiche votre accord actuel.',
      step3_title: 'Étape 2 : Quality',
      step3_msg: 'Choisissez le type d\u0027accord : Maj, min, 7, m7, dim, aug...\nLa grille illumine les notes de l\u0027accord.',
      step4_title: 'Étape 3 : Tensions',
      step4_msg: 'Choisissez d\u0027abord une Quality \u2014 les boutons de tension apparaissent automatiquement.\n9, b9, #9, 11, #11, 13, b13. Plusieurs tensions peuvent être sélectionnées.',
      step5_title: 'Saisie texte',
      step5_msg: 'Saisissez les noms d\u0027accords directement avec la touche /.\nLes slash chords et les voicings complexes peuvent être entrés rapidement.',
      step6_title: 'Dominante secondaire',
      step6_msg: 'Activez le bouton "Secondary Dominant" sous la barre diatonique (\u2318\u2325D).\nIl affiche le V7 qui résout vers chaque accord diatonique.\nCliquez sur l\'un d\'eux et Available Scale affiche automatiquement la bonne gamme \u2014 Mixolydien pour les cibles majeures, HMP5\u2193/Altered pour les cibles mineures.',
      step7_title: 'Slash Chords',
      step7_msg: 'Cliquez sur / dans le constructeur d\'accord pour entrer une note de basse pour les Slash Chords.\nVous pouvez aussi saisir C/D ou F\u25B37/G en entrée texte.\nAvailable Scale se met à jour pour correspondre au Slash Chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Mode Input',
    input_mode_desc: 'Saisissez des accords via contrôleur MIDI, pads, manche ou clavier',
    input_mode: {
      step1_title: 'Passer en mode Input',
      step1_msg: 'Saisissez des accords via un contrôleur MIDI, en cliquant sur les pads, le manche ou le clavier.\nLa détection d\'accords fonctionne dans tous les modes.',
      step2_title: 'Cliquez sur quelques pads',
      step2_msg: 'Cliquez sur n\u0027importe quels pads de la grille.\nChaque clic active ou désactive une note.',
      step3_title: 'Détection d\u0027accords',
      step3_msg: 'Le nom de l\u0027accord détecté apparaît au-dessus de la grille.\nDes étiquettes de degré (R, 3, 5, b7...) s\u0027affichent sur chaque pad.',
      step4_title: 'Sauvegarder avec Capture',
      step4_msg: 'La touche <strong>C</strong> sauvegarde l\u0027accord actuel dans le prochain emplacement mémoire.\nConstruisez des progressions d\u0027accords une par une.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Barre diatonique',
    diatonic_desc: 'Accès en un clic aux accords diatoniques',
    diatonic: {
      step1_title: 'La barre diatonique',
      step1_msg: 'Chaque gamme a son propre jeu d\u0027accords diatoniques.\nIls apparaissent ici \u2014 prêts à jouer.',
      step2_title: 'Triade / Tétrade',
      step2_msg: 'Basculez entre triades à 3 notes et accords de septième à 4 notes.\nLa barre se met à jour instantanément.',
      step3_title: 'Cliquez sur un accord',
      step3_msg: 'Cliquez sur un accord de la barre.\nVous pouvez le transformer avec des tensions et plus dans le Chord Builder.',
      step4_title: 'Raccourci clavier',
      step4_msg: 'Appuyez sur 1\u20137 pour sélectionner les accords diatoniques instantanément.\nPas besoin de souris.',
      step5_title: 'Dominante secondaire',
      step5_msg: 'Activez "Secondary Dominant" (\u2318\u2325D).\nLes accords V7 résolvant vers chaque accord diatonique sont affichés.\nCliquez sur l\'un d\'eux et Available Scale s\'affiche automatiquement.\nRésolution majeure \u2192 Mixolydien. Résolution mineure \u2192 HMP5\u2193/Altered.',
      step6_title: 'Raccourcis clavier',
      step6_msg: 'Appuyez sur 1\u20137 pour les accords diatoniques.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Tonalité parallèle) pour les barres d\'extension.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Sauvegardez des accords et jouez-les en direct',
    memory: {
      step1_title: 'Sauvegarder un accord',
      step1_msg: 'Sauvegardez vos accords favoris.\nEnregistrer les voicings que vous aimez aide pour le beat-making et la pratique.',
      step2_title: '16 emplacements mémoire',
      step2_msg: 'Fonctionne comme un layout Drumrack de 16 pads sur PUSH, Launchpad, MPC et Maschine \u2014 intuitif à utiliser.',
      step3_title: 'Banques mémoire',
      step3_msg: 'Sur PUSH et Launchpad, le layout Drumrack le rend intuitif à utiliser.',
      step4_title: 'Mode Perform',
      step4_msg: 'Les touches du clavier PC correspondent aussi aux 16 pads.',
      step5_title: 'Export MIDI',
      step5_msg: 'Exportez tous les accords en mémoire en fichier MIDI.\nGlissez dans votre DAW et commencez à produire.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Façonnez vos voicings d\u0027accords',
    voicing: {
      step1_title: 'Commandes de voicing',
      step1_msg: 'En mode Chord Builder, diverses transformations sont possibles à partir de la forme de base.\nOmit, Shell, Inversion, Drop \u2014 tout est ici.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> est pour le Shell voicing. Apprenez les voicings R37 et R73 de manière fluide sur le pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Les touches de raccourci suivent souvent des mnémotechniques.\n<strong>O</strong>mit = omettre la 5te. <strong>R</strong>ootless = voicing sans fondamentale.',
      step4_title: 'Renversements',
      step4_msg: 'Contrairement à la plupart des logiciels, vous pouvez créer des renversements ultra-rapidement.\nAide aussi à comprendre les slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Pour quand vous voulez mettre en valeur la note du dessus \u2014\nles Drop voicings sont aussi pris en charge.',
      step6_title: 'Voicing Box',
      step6_msg: 'Les pads peuvent avoir plusieurs options de position. Le Voicing Box gère cela.\nCliquez sur a, b, c, d etc. sur le pad, ou tapez la lettre, pour voir plusieurs possibilités de voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, effets et volume',
    sound: {
      step1_title: 'Presets de son',
      step1_msg: 'ORGAN (4 types) et E.PIANO (8 types).\nCliquez sur un pad ou utilisez votre contrôleur MIDI.',
      step2_title: 'Panneau de détails',
      step2_msg: 'Cliquez sur \u25BC pour déplier le panneau de détails.\nEffets, volume et contrôles de filtre sont ici.',
      step3_title: 'Effets',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nRéglez-les dans le panneau de détails.',
      step4_title: 'Son ON/OFF',
      step4_msg: 'Activez/désactivez le son avec l\u0027icône du haut-parleur.\nLe désactiver peut être pratique lors de l\u0027utilisation d\u0027un DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings classés par note supérieure. Réservé aux membres HPS',
    tasty: {
      step1_title: 'Activer TASTY',
      step1_msg: 'Sélectionnez des voicings raffinés que la logique simple ne peut pas produire.\nPenser à partir de la note supérieure est utile pour les arrangements de cordes et de cuivres.\n(Réservé aux membres HPS)',
      step2_title: 'Parcourir les recettes',
      step2_msg: 'Touches Z / X pour parcourir les voicings en avant/arrière.\nLe compteur indique votre position.',
      step3_title: 'Notation en degrés',
      step3_msg: 'La zone d\u0027info affiche l\u0027empilement des degrés \u2014 ex. m9 (b3-b7-9-5-1).\nC\u0027est la structure du voicing du bas vers le haut.',
      step4_title: 'Vers Pad',
      step4_msg: 'Optimisation de pads que les logiciels classiques ne peuvent pas faire.\nProfitez aussi de jouer des voicings élégants sur les pads.',
      fb_step1_title: 'Qu\'est-ce que TASTY Voicing ?',
      fb_step1_msg: '129 voicings sophistiqués triés par note supérieure.\nSupporte Maj7 / Dom7 / Min7. Affiché en notation de degrés.\nRéservé aux membres HPS.',
      fb_step2_title: 'Comment accéder à TASTY',
      fb_step2_msg: 'Disponible en rejoignant HPS (Hardcore Pad Style).\nAppuyez sur T en mode Chord pour activer. Touches Z/X pour parcourir les voicings.\nVoir le Guide pour plus de détails.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicings idiomatiques classiques du piano. Réservé aux membres HPS',
    stock: {
      step1_title: 'Activer STOCK',
      step1_msg: 'Connaître les voicings spécifiques au piano vous aide à sortir du jeu en forme de base uniquement.\n154 voicings piano en notation de degrés.\n(Réservé aux membres HPS)',
      step2_title: 'Parcourir les voicings',
      step2_msg: 'Touches Z / X pour parcourir les voicings en avant/arrière.',
      step3_title: 'Vue clavier',
      step3_msg: 'Activez l\u0027affichage Piano pour voir les positions réelles.\nLe voicing prend vie sur le clavier.',
      step4_title: 'Vers Pad',
      step4_msg: 'Cliquez sur \u00AB Vers Pad \u00BB pour mapper le voicing sur les pads.\nSauvegardez en mémoire et exportez vers votre DAW.',
      fb_step1_title: 'Qu\'est-ce que STOCK Voicing ?',
      fb_step1_msg: 'Présente des voicings de piano couramment utilisés.\nLa notation de degrés vous montre la structure.\nRéservé aux membres HPS.',
      fb_step2_title: 'Comment accéder à STOCK',
      fb_step2_msg: 'Disponible en rejoignant HPS (Hardcore Pad Style).\nAppuyez sur K en mode Chord pour activer.\nVoir le Guide pour plus de détails.',
    },
    // Minor 3 Scales tutorial
    minor_scales_title: 'Comparer 3 gammes mineures',
    minor_scales_desc: 'Naturel, Harmonique et Mélodique côte à côte',
    minor_scales: {
      step1_title: 'Choisir une tonalité mineure',
      step1_msg: 'Am (mineur naturel) est sélectionné.\nLa barre diatonique affiche les accords du mineur naturel.',
      step2_title: 'Activer Harm/Mel',
      step2_msg: 'Cliquez sur "Harm/Mel" (\u2318\u2325N).\nLes accords diatoniques du mineur harmonique et mélodique apparaissent en dessous.',
      step3_title: 'Comparer',
      step3_msg: 'Observez les différences avec le mineur naturel (barre du haut).\nEn HM, le V passe de Em7 à E7 \u2014 permettant le mouvement de dominante.\nEn MM, le IV passe aussi de Dm7 à D7.\nCliquez sur n\'importe quel accord pour le voir sur les pads.',
      step4_title: 'Tonalité parallèle',
      step4_msg: 'Activez "Parallel Key" (\u2318\u2325R) pour voir les accords diatoniques majeurs de la même fondamentale.\nCela révèle l\'origine des accords empruntés (échange modal).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Dominante secondaire',
    secdom_desc: 'Découvrez la porte d\'entrée vers la modulation',
    secdom: {
      step1_title: 'Commencer en C majeur',
      step1_msg: 'C majeur est défini.\nLa barre diatonique affiche C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Activer la dominante secondaire',
      step2_msg: 'Cliquez sur "Secondary Dominant" (\u2318\u2325D).\nLes accords V7 résolvant vers chaque accord diatonique apparaissent.\nEn C majeur : C7, D7, E7, A7, B7 (5 au total).',
      step3_title: 'Résolution vers le majeur',
      step3_msg: 'Cliquez sur C7 (\u2192F\u25B37) ou D7 (\u2192G7).\nAvailable Scale affiche Mixolydien comme premier choix.\nCar la cible de résolution est un accord majeur.',
      step4_title: 'Résolution vers le mineur',
      step4_msg: 'Cliquez sur A7 (\u2192Dm7) ou E7 (\u2192Am7).\nAvailable Scale affiche HMP5\u2193 (Phrygien Dominant) et Altered comme premiers choix.\nCar la cible de résolution est un accord mineur.',
      step5_title: 'La règle : seulement 2 types',
      step5_msg: 'Le choix de gamme pour les dominantes secondaires est simple :\n\u2022 Résolution majeure \u2192 Mixolydien\n\u2022 Résolution mineure \u2192 HMP5\u2193 ou Altered\nC\u2019est tout ce qu\u2019il faut retenir.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Cycle des quintes',
    circle_desc: 'Les relations entre tonalités en un coup d\u0027\u0153il',
    circle: {
      step1_title: 'Ouvrir le cycle',
      step1_msg: 'Appuyez sur \u2318\u2325F ou cliquez sur le bouton Circle.\nLe cycle des quintes apparaît en dessous.',
      step2_title: 'Lien de tonalité',
      step2_msg: 'Vérifiez rapidement les accords de substitution et les diatoniques importants pour l\u0027interprétation et la composition.',
      step3_title: 'Fonctions diatoniques',
      step3_msg: 'Contrairement au cycle des quintes classique, 64 Pad Explorer vous permet de choisir 3 types de mineur (Natural/Harmonic/Melodic) en tonalité mineure.\nFacilite la maîtrise des tonalités mineures complexes.',
      step4_title: 'Sélectionner une tonalité mineure',
      step4_msg: 'L\'anneau intérieur du cycle affiche les tonalités mineures.\nCliquez sur une tonalité de l\'anneau intérieur pour sélectionner une tonalité mineure.\nL\'affichage des accords diatoniques changera.',
      step5_title: '3 types de gamme mineure',
      step5_msg: 'Lorsqu\'une tonalité mineure est sélectionnée, les boutons Nat / Harm / Mel apparaissent au centre.\nNat = Natural Minor (forme standard)\nHarm = Harmonic Minor (V7 apparaît)\nMel = Melodic Minor (les degrés VI, VII changent)',
      step6_title: 'Essayez de changer',
      step6_msg: 'Cliquez sur Nat \u2192 Harm \u2192 Mel et observez les changements dans les accords diatoniques.\nRemarquez comment V7 apparaît dans Harmonic Minor.',
    },
    // Guitar tutorial
    guitar_title: 'Diagramme de guitare',
    guitar_desc: 'Entrez des accords depuis la guitare et réfléchissez-les sur les pads',
    guitar: {
      step1_title: 'Afficher le manche de guitare',
      step1_msg: 'Appuyez sur \u2318\u2325G ou cliquez sur le bouton Guitar.\nLes notes de l\'accord apparaissent sur le manche.',
      step2_title: 'Voir les positions d\'accord',
      step2_msg: 'Sélectionnez un accord en mode Chord et le manche affiche automatiquement les positions correspondantes.\nUtilisez les touches virgule (,) et point (.) pour faire défiler les positions.',
      step3_title: 'Entrer depuis la guitare',
      step3_msg: 'Passé en mode Input. Essayez de cliquer sur les cases du manche pour entrer des notes.\nLes noms d\'accords sont détectés en temps réel.',
      step4_title: 'Réfléchir sur le pad',
      step4_msg: '"Réfléchir sur pad" mappe le voicing de guitare sur la grille de pads.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Raccourcis clavier',
    shortcuts_desc: 'Touches essentielles pour une opération efficace',
    shortcuts: {
      step1_title: 'Changement de mode',
      step1_msg: 'Tab \u2014 Changer de mode (Scale \u2192 Chord \u2192 Input)\nShift+Tab \u2014 Direction inverse\n\nPassez rapidement d\'un mode à l\'autre.',
      step2_title: 'Diatonique & navigation',
      step2_msg: '1\u20137 \u2014 Sélectionner un accord diatonique\n\u2191\u2193 \u2014 Faire défiler les renversements\n\u2190\u2192 \u2014 Transposer la fondamentale d\'un demi-ton (garde la forme)\n\nOpérez les accords sans souris.',
      step3_title: 'Opérations de voicing',
      step3_msg: 'S \u2014 Cycle Shell (off \u2192 1-3-7 \u2192 1-7-3)\nO \u2014 Bascule Omit 5\nR \u2014 Bascule Rootless\nShift+D \u2014 Cycle Drop (off \u2192 Drop2 \u2192 Drop3)\nT \u2014 TASTY ON/OFF, K \u2014 STOCK ON/OFF\nZ / X \u2014 voicing TASTY/STOCK précédent/suivant\n\u2190\u2192 \u2014 Transposer le voicing d\'un demi-ton (pendant TASTY/STOCK)\nV \u2014 Réfléchir sur pad / basculer layout\n/ \u2014 Entrée texte accord',
      step4_title: 'Mémoire & banques',
      step4_msg: 'Option+1234/qwer/asdf/zxcv \u2014 Sauvegarder dans l\'emplacement\n[ ] \u2014 Changer de banque\nM \u2014 Basculer vue mémoire\nP \u2014 Basculer mode Perform\nSpace \u2014 Jouer\nShift+Space \u2014 Jouer tout (séquentiel)',
      step5_title: 'Plus',
      step5_msg: '? \u2014 Aide (liste complète des raccourcis)\n\u2318\u2325+G/B/P/F/S \u2014 Bascules Instrument/Cercle/Portée\n\u2318\u2325+A/M/T/Q/V/K/H \u2014 Bascules de sections\nCmd/Ctrl+Z \u2014 Annuler (jusqu\'à 30 fois)\nEsc \u2014 Désélectionner / Fermer les modales',
    },
    // Link Mode tutorial
    link_title: 'Link Mode',
    link_desc: 'Synchroniser les notes jouées sur tous les instruments',
    link: {
      step1_title: 'Bouton Link',
      step1_msg: 'Le bouton Link est à côté de Guitar / Bass / Piano.\nActivez-le pour voir les notes jouées sur tous les instruments en temps réel.',
      step2_title: 'Link Mode ON',
      step2_msg: 'Quand Link est actif, les affichages d\'instruments sont atténués.\nJouez les pads ou le MIDI \u2014 seules les notes jouées s\'allument.',
      step3_title: 'Jouez les pads',
      step3_msg: 'Appuyez sur un pad et observez la même note s\'allumer sur la guitare, la basse et le piano.\nVoyez quelles positions sur chaque instrument produisent la même hauteur.\nRelâchez pour effacer.',
      step4_title: 'Raccourci',
      step4_msg: '\u2318\u2325+L active/désactive le Link mode.\nParfait pour apprendre comment les notes correspondent entre les instruments.',
    },
    // Settings tutorial
    settings_title: 'Affichage & Réglages',
    settings_desc: 'Personnalisez votre espace de travail',
    settings: {
      step1_title: 'Panneaux d\u0027instruments',
      step1_msg: 'Guitar affiche les voicings courants lorsque vous sélectionnez un accord dans le Chord Builder.\nEn mode Input, vous pouvez aussi saisir depuis guitare, basse et clavier.',
      step2_title: 'Noms / Degrés',
      step2_msg: 'Basculez entre noms de notes (C, D, E) et degrés (R, 2, 3).\nS\u0027applique aux pads et à l\u0027affichage guitare.',
      step3_title: 'Décalage d\u0027octave',
      step3_msg: 'Utilisez \u25B2\u25BC pour décaler la tessiture des pads d\'une octave.\nLes boutons d\'octave de Push 3 et Launchpad se synchronisent automatiquement.',
      step4_title: 'Réduire les sections',
      step4_msg: '\u2318\u2325+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) pour réduire les sections.\nAfficher uniquement ce dont vous avez besoin.',
      step5_title: 'Ordre de disposition',
      step5_msg: 'Dans ? Aide, utilisez le menu déroulant "Layout" pour réorganiser les 3 panneaux.\n6 presets : Chord, Pad, Circle dans n\'importe quel ordre.\nSur mobile, l\'ordre de glissement change aussi.',
      step6_title: 'Tout sauvegarder',
      step6_msg: 'Cliquez sur l\'icône de sauvegarde pour conserver tous les réglages.\nTonalité, gamme, son, mémoire, voicing \u2014 tout est préservé.',
    },
  },
});
