// 中文
I18N.addLang('zh', {
  help: {
    title: '64 Pad Explorer',
    description: '在64键打击垫上探索音阶、和弦与声位的工具。',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 从12个调中选择',
    scale_scale: '<strong>Scale</strong> \u2014 自然音阶、和声小调、旋律小调、五声音阶、Bebop等 \u2014 共31种',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 显示所选音阶的自然和弦。点击进入Chord模式',
    chord_mode: 'Chord Mode（3步）',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 在钢琴键盘上选择根音',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 选择和弦类型（Maj, m, aug, dim, sus 等）',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 添加延伸音（9, b9, #9, 11, #11, 13, b13 等）。可多选',
    chord_text: '<strong>文本输入</strong> \u2014 按"/"聚焦。直接输入 Cm7, G7(b9,#11), Am7/G 等。自动显示候选',
    chord_onchord: '<strong>On Chord</strong> \u2014 使用"/"按钮指定分割和弦（和弦/低音）',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 省略音',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing（+1、+2 添加音）',
    voicing_inv: '<strong>Inversion</strong> \u2014 转位（Root, 1st, 2nd, 3rd）',
    inv_1: '第1转位',
    inv_2: '第2转位',
    inv_3: '第3转位',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicing',
    voicing_box: '<strong>Voicing Box</strong> \u2014 点击切换打击垫排列方案（闪烁标记 = 有替代排列）',
    display: '显示',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 分别开关吉他指板、贝斯、钢琴键盘和五线谱。※吉他/贝斯位置显示的是该乐器可按的指型，与打击垫布局无对应关系',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 显示五度圈。与调选择联动，显示自然和弦与功能（T/SD/D）。支持小调模式切换',
    display_label: '<strong>音名/音级</strong> \u2014 在吉他和打击垫上切换音名（C, D, E）与音级（R, 2, 3）',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 按八度移动打击垫音域',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 点击扬声器图标切换声音开/关',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Rhodes 物理建模。HPS 会员可选择 Suitcase 预设（放大器链物理建模）。按 \u25BC 打开详细面板',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Peterson Vactrol 物理建模（立体声）。使用 TREM/T.SPD 调节深度和速度',
    sound_organ: '<strong>ORGAN</strong> \u2014 4种预设（Jazz, Perc, Full, Gospel）',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8种预设（Rhodes, FM, Clavinet 等）',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 包络滤波器（Auto-Wah）。3种类型：Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 模拟饱和。为声音增添温暖的过载',
    sound_fx: '<strong>效果器</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: '点击打击垫或Voicing Box即可发声',
    midi: 'MIDI',
    midi_detect: '自动检测WebMIDI兼容设备',
    midi_push: '支持Ableton Push串行MIDI输出',
    midi_chord: '根据输入音符自动识别和弦',
    midi_sustain: '<strong>延音踏板</strong> \u2014 支持 MIDI CC64（Hold Pedal）',
    color_title: '颜色说明',
    color_root: '<strong>Root</strong> \u2014 根音',
    color_scale: '<strong>Scale / Chord</strong> \u2014 音阶音·和弦音',
    color_char: '<strong>特征音</strong> \u2014 定义该音阶/和弦特征的音',
    color_3rd: '<strong>3rd</strong> \u2014 引导音（3度）',
    color_7th: '<strong>7th</strong> \u2014 引导音（7度）',
    color_tension: '<strong>Tension</strong> \u2014 延伸音',
    color_avoid: '<strong>Avoid</strong> \u2014 在和弦音上方半音的音阶音（Chord模式下）',
    color_palette: '配色方案：Okabe-Ito（色觉无障碍）',
    input_title: '吉他/钢琴输入',
    input_desc1: '点击吉他指板或钢琴键盘输入音符',
    input_desc2: '自动识别输入音符的和弦并反映到打击垫上',
    input_desc3: '<strong>Clear</strong> \u2014 清除输入，<strong>Play \u25B6</strong> \u2014 播放输入的音符',
    input_title: 'Input Mode',
    input_desc1: '自由点击打击垫选择音符 \u2192 实时和弦识别',
    input_desc2: '无理论过滤。探索 \u2192 发现 \u2192 之后再学习理论',
    input_desc3: '检测到和弦时，打击垫上显示音程标签（R, 3, 5, b7等）。吉他、贝斯、钢琴和五线谱自动联动',
    input_memory: '<strong>Memory</strong> \u2014 在16个插槽中保存和调用和弦',
    input_banks: '<strong>Banks</strong> \u2014 16个插槽 \u00D7 最多16个Bank。用 <kbd>[</kbd> <kbd>]</kbd> 切换。支持复制和重命名',
    input_export: '<strong>MIDI Export</strong> \u2014 将记忆中的和弦导出为MIDI文件',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> 按钮或 <kbd>p</kbd> 键切换',
    perform_desc1: '使用16键打击垫布局实时演奏Memory Slot和弦',
    perform_desc2: '通过键盘（4\u00D74网格）或MIDI打击垫触发',
    perform_desc3: '拖放Slot以重新排序',
    shortcut_title: '键盘快捷键',
    shortcut_scale_chord: 'Scale / Chord 模式',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 选择自然和弦（7音音阶时）',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 选择Voicing Box（循环切换替代排列）',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 切换转位（Chord模式下）',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调根音',
    sc_omit: '<kbd>o</kbd> \u2014 切换Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 切换Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 循环Shell（off \u2192 1-3-7 \u2192 1-7-3 \u2192 off）',
    sc_drop: '<kbd>d</kbd> \u2014 循环Drop（off \u2192 Drop 2 \u2192 Drop 3 \u2192 off）',
    sc_voicing_reflect: "<kbd>v</kbd> — Guitar 引擎 ON/OFF（在 64 打击垫上显示所选吉他 voicing）",
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 切换吉他把位（上一个 / 下一个）',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 切换贝斯指位（上一个 / 下一个）',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 清除和弦（Chord模式）',
    sc_pad_explore: '<b>拍垫（Chord模式）</b> \u2014 点击切换音符 \u2014 构建器自动更新',
    shortcut_input: 'Input 模式',
    sp_capture: '<kbd>c</kbd> \u2014 开始Capture / 保存到下一个插槽',
    sp_end: '<kbd>e</kbd> \u2014 结束Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 调用记忆插槽（Edit）',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 半音移调（所有音符\u00B11）',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 转位（最低音\u21911个八度 / 最高音\u21931个八度）',
    sp_clear: '<kbd>x</kbd> \u2014 全部清除',
    sp_transfer: '<b>Chord切换</b> \u2014 将识别的和弦转移到Chord模式',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74网格触发Slot 1\u201316',
    pf_midi: 'MIDI打击垫（音符36\u201354）也可触发Slot',
    shortcut_common: '通用（所有模式）',
    sc_perform: '<kbd>p</kbd> \u2014 切换Perform视图',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 撤销Memory Slot操作（最多30步）',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 将当前和弦 / voicing 保存到 Memory Slot',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 将当前和弦 / voicing 保存到 Memory Slot',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 直接保存到 Memory Slot',
    sc_space: '<kbd>Space</kbd> \u2014 播放当前和弦',
    sc_esc: '<kbd>Esc</kbd> \u2014 取消Voicing Box选择 / 关闭帮助',
    sc_help: '<kbd>?</kbd> \u2014 切换帮助显示',
    sc_slash: '<kbd>/</kbd> \u2014 聚焦文本和弦输入',
    sc_tasty_nav: "<kbd>z</kbd> / <kbd>x</kbd> — TASTY/STOCK/Guitar 声位 上一个/下一个",
    shortcut_display: '显示切换（\u2318\u2325 / Ctrl+Alt）',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 吉他',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 贝斯',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 钢琴',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 五度圈',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 五线谱',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 音频',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 记忆插槽',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 文本输入',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 调显示',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 标题栏 / 信息栏',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: '启动时显示提示',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: '固定为C大调',
    color_coding_toggle: '为特性音着色',
    c_fixed_tip: '无论 Key/Scale/Chord 如何选择，Pad 始终显示C大调音阶。',
    push_voicing_toggle: 'Voicing overview',
    layout: '布局',
    footer: '64 Pad Explorer \u2014 HPS（Hardcore Pad Style）',
  },
  legend: {
    characteristic: '特征音',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: '关闭',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: '保存设置',
    sound_hint: '请选择音色以启用声音',
    tap_to_start: '轻触以启用声音',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: '轻触任意打击垫即可演奏！',
    load_vst: '加载 VST/AU 插件...',
    affiliate_label: '',
    staff: '乐谱',
    circle: '五度圈',
    help: '\u5E2E\u52A9',
    view_settings: '显示设置',
    view_focus: '显示范围',
    view_layout: '布局',
    view_all: '全部面板',
    view_pad: '仅打击垫',
    view_chord: '仅和弦构建器',
    view_info: '仅信息 / 记忆',
    layout_abc: '打击垫 → 和弦 → 五度圈',
    layout_acb: '打击垫 → 五度圈 → 和弦',
    layout_bac: '和弦 → 打击垫 → 五度圈',
    layout_bca: '和弦 → 五度圈 → 打击垫',
    layout_cab: '五度圈 → 打击垫 → 和弦',
    layout_cba: '五度圈 → 和弦 → 打击垫',
    view_setup_note: '在 Desktop 版中，Push 3 的 Setup 也会打开此画面。Jog Wheel 左右选择显示范围或布局，旋转更改数值，按下 Jog Wheel 或 Setup 关闭。',
    oct_down: '\u964D\u4F4E\u516B\u5EA6',
    oct_up: '\u5347\u9AD8\u516B\u5EA6',
    toggle_guitar: '\u663E\u793A/\u9690\u85CF\u5409\u4ED6\u6307\u677F (⌘⌥G)',
    toggle_bass: '\u663E\u793A/\u9690\u85CF\u8D1D\u65AF\u6307\u677F (⌘⌥B)',
    toggle_piano: '\u663E\u793A/\u9690\u85CF\u94A2\u7434\u952E\u76D8 (⌘⌥P)',
    mode_scale: 'Scale \u6A21\u5F0F \u2014 \u5728\u6253\u51FB\u5757\u4E0A\u67E5\u770B\u97F3\u9636\u97F3 (Tab \u5207\u6362)',
    mode_chord: 'Chord \u6A21\u5F0F \u2014 \u4F7F\u7528\u58F0\u4F4D\u6784\u5EFA\u548C\u5F26 (Tab \u5207\u6362)',
    mode_input: 'Input \u6A21\u5F0F \u2014 \u81EA\u7531\u70B9\u51FB\u6253\u51FB\u5757\u8BC6\u522B\u548C\u5F26 (Tab \u5207\u6362)',
    play_chord: '\u64AD\u653E\u5F53\u524D\u548C\u5F26 (Space)',
    toggle_staff: '\u663E\u793A/\u9690\u85CF\u4E94\u7EBF\u8C31 (⌘⌥S)',
    toggle_circle: '\u663E\u793A/\u9690\u85CF\u4E94\u5EA6\u5708 (\u2318\u2325F)',
    toggle_sound: '\u663E\u793A/\u9690\u85CF\u97F3\u8272\u63A7\u5236',
    sound_mute: '\u58F0\u97F3 ON/OFF',
    sound_expand: '\u663E\u793A/\u9690\u85CF\u8BE6\u7EC6\u97F3\u8272\u8BBE\u7F6E',
    input_keys_disabled: 'Input 模式下不使用调选择',
  },
  label: {
    note_name: '音名',
    degree: '音级',
    chord_input: '输入和弦',
    chord_hint: '延伸音用 ( ): C7(b9,#11) | dim, h=m7♭5 可用',
    key_hint: '也可通过 Scale 模式或五度圈设置',
  },
  header: {
    portal: 'HPS Portal',
    blog: '博客',
    guide: '指南',
    wishlist: '愿望清单',
  },
  input: {
    status_idle: '按Capture开始构建和弦',
    status_capturing: '录入中：插槽 {slot}/16 \u2014 点击打击垫，然后按Capture保存',
    status_editing: '编辑中：插槽 {slot} \u2014 点击打击垫进行修改',
    notes_label: '音符：',
  },
  notify: {
    slot_saved: '插槽 {slot} \u2190 {chord}',
    memory_full: 'Memory Slot 已满',
    no_current_chord: '没有可保存的当前和弦',
    slot_selected: '已选择插槽 {slot}',
    slot_cleared: '已清除插槽 {slot}',
    undo: '撤销',
    settings_saved: '设置已保存',
    no_chords: '记忆插槽中没有和弦',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    note_count: '{n}个音',
    default: '将鼠标悬停在任意控件上查看其功能',
    mode_scale: 'Scale 模式 \u2014 在64键打击垫网格上查看音阶音 [Tab]',
    mode_chord: 'Chord 模式 \u2014 逐步构建和弦：Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Input 模式 \u2014 自由点击打击垫，自动检测和弦 [Tab]',
    guitar: '切换吉他指板显示 [\u2318\u2325G]',
    bass: '切换贝斯指板显示 [\u2318\u2325B]',
    piano: '切换钢琴键盘显示 [\u2318\u2325P]',
    link_mode: 'Link 模式 \u2014 演奏的音符在所有乐器上实时同步 [\u2318\u2325L]',
    staff: '切换五线谱显示 [\u2318\u2325S]',
    circle: '五度圈 \u2014 主功能、下属功能、属功能以对应颜色显示 [\u2318\u2325F]',
    cof_major: '外圈 \u2014 选择大调',
    cof_minor: '内圈 \u2014 选择小调',
    cof_natural: '自然小调',
    cof_harmonic: '和声小调',
    cof_melodic: '旋律小调',
    sound: '切换音频控制面板 [\u2318\u2325A]',
    memory: '切换记忆插槽面板 \u2014 在16个插槽中保存/调用和弦 [\u2318\u2325M]',
    sect_key: '切换调显示',
    sect_input: '切换文本和弦输入 [\u2318\u2325T]',
    sect_quality: '切换Root/Quality/Tension选择器 [\u2318\u2325Q]',
    sect_voicing: '切换声位控制（Omit、Shell、Inversion、Drop）[\u2318\u2325V]',
    text_input: '直接输入和弦名称 \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: '显示当前和弦的可用音阶。非和弦音低音的分割和弦会从低音重新解释',
    sort_practical: '实用排序 \u2014 优先显示常用音阶。包含副属和弦音阶（如V7/ii的Mixolydian b13）',
    sort_diatonic: '理论排序 \u2014 按与当前调的理论距离排序',
    omit5: '从声位中省略5度 [O]',
    rootless: '省略根音 [R]',
    omit3: '从声位中省略3度',
    shell137: 'Shell voicing: Root-3rd-7th [S]',
    shell173: 'Shell voicing: Root-7th-3rd [S]',
    shell_off: '关闭Shell voicing [S]',
    shell_ext: '向Shell voicing添加音（+1或+2个和弦音）',
    inv_root: '原位 [\u2193]',
    inv: '转位 [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 按顶音排序的精致声位。支持 \u25B37、m7、7（HPS专属）[T]',
    tasty_nav: '循环切换变体 [Z / X]',
    stock: 'Stock Voicing \u2014 常用钢琴声位（HPS专属）[K]',
    stock_nav: '循环切换变体 [Z / X]',
    root_notation: '切换 \u266F 和 \u266D 记谱法',
    root_grid: '选择根音',
    quality_grid: '选择和弦类型（Maj, m, 7, dim, aug, sus...）',
    tension_grid: '向和弦添加延伸音（9, b9, #9, 11, #11, 13, b13）\u2014 可多选',
    diatonic: '当前音阶的自然和弦 \u2014 点击进入Chord模式 [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 对比和声小调与旋律小调的自然和弦 [\u2318\u2325N]',
    parallel_key: '同主音调 \u2014 显示相同根音的大/小调自然和弦。查看借用和弦的来源 [\u2318\u2325R]',
    secdom: '副属和弦 \u2014 显示解决到每个自然和弦的V7。点击自动显示Available Scale [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: '在 Input 模式下，将打击垫点击依次录入 Memory Slot [C]',
    capture_current: '将当前和弦 / TASTY / STOCK / Guitar voicing 保存到 Memory Slot [Shift+C]',
    capture_end: '结束录入并保存到当前插槽 [E]',
    save: '保存所有当前设置（调、音阶、音色、记忆、布局）',
    tutorial: '交互式教程 \u2014 逐步学习基础操作',
    help: '打开帮助窗口查看完整键盘快捷键参考 [?]',
    affiliate: '通过这些链接购买可支持开发...',
    lang: '切换显示语言',
    octave: '移动打击垫八度音域 \u2014 Push/Launchpad也可通过八度按钮控制',
    play: '播放当前和弦 [Space]',
    scale_select: '选择音阶',
    chord_key: '切换大调和小调',
    chord_key_picker: '打开调选择器，无需切换到Scale模式即可更改调',
    builder_clear: '清除当前和弦并重新开始 [X]',
    builder_back: '撤销和弦构建的上一步 [\u232B]',
    slash_chord: '分割和弦（On Chord）',
    guitar_diagram: '在构建器中选择和弦时自动反映常用吉他声位',
    guitar_label: '切换吉他指板上的音名显示',
    genre_preset: '切换吉他声位风格 \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: '循环切换吉他/贝斯声位位置 [, .]',
    to_pad: '将吉他/Stock声位映射到64键打击垫网格 [V]',
    inst_clear: '清除乐器图上输入的音符',
    inst_play: '播放乐器图上输入的音符',
    plain_clear: '清除Input模式中的所有音符 [X]',
    midi_export: '将所有记忆插槽导出为MIDI文件用于DAW',
    chs_export: '以CHS（Clover Chord Systems）格式导出所有记忆插槽',
    midi_import: '将MIDI文件导入记忆插槽',
    chs_import: '将CHS文件导入记忆插槽',
    midi_device: '选择MIDI输入',
    midi_panic: 'All Notes Off \u2014 停止所有卡住的MIDI音符',
    sound_mute: '声音 ON/OFF',
    sound_preset: '选择音色预设',
    volume: '主音量',
    sound_fx: '效果器 \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 每个音符触发滤波器开/关。LP/BP类型、2P/4P斜率',
    velocity: '力度曲线',
    mem_view: '记忆视图 \u2014 在16个插槽中保存和排列和弦 [M]',
    perform_view: 'Perform视图 \u2014 使用16个打击垫实时演奏保存的和弦 [P]',
    bank: '记忆库 \u2014 16个插槽 \u00D7 最多16个库。[ ] 切换',
    slot_save: '将当前和弦保存到所选插槽',
    play_slots: '按顺序播放所有保存的和弦',
    locut: 'Lo-cut \u2014 削减低频更清晰（复选框 ON/OFF，滑块 = 截止频率）',
    hicut: 'Hi-cut \u2014 削减高频音色更圆润（复选框 ON/OFF，滑块 = 截止频率）',
    drive: 'Drive \u2014 过载量，越大失真越强',
    tremolo: '颤音深度 \u2014 音量调制深度（Peterson 灯泡 + CdS 物理建模）',
    tremolo_speed: '颤音速度 \u2014 调制频率（Hz）',
    phaser: 'Phaser \u2014 相位偏移扫描，营造空间感',
    flanger: 'Flanger \u2014 极短延迟产生金属质感扫荡',
    af_on: '自动滤波器 ON/OFF',
    af_type: '滤波器类型 \u2014 LP=低通 / BP=带通',
    af_poles: '斜率 \u2014 2P=12dB/oct（缓）/ 4P=24dB/oct（陡）',
    af_depth: 'Depth \u2014 滤波器开合的范围',
    af_decay: 'Decay \u2014 滤波器关闭的速度（越小越快）',
    af_q: 'Q \u2014 共鸣（峰值锐度）',
    af_wet: 'WET \u2014 效果量（0=完全干声，10=完全湿声）',
    af_vol: 'VOL \u2014 输出音量（前级失真时请调低）',
    eq_bass: 'Baxandall Bass \u2014 低频搁架 EQ，中央=平直',
    eq_treble: 'Baxandall Treble \u2014 高频搁架 EQ，中央=平直',
    reverb_type: '混响类型 \u2014 Spring（弹簧，Twin 风格摇曳尾音）/ Plate（板式，金属密集尾音）',
    reverb_amount: '混响量 \u2014 湿信号混合',
    reverb_decay: '混响衰减 \u2014 尾音长度',
    reverb_stereo: '立体声 \u2014 ON 时左右扩展混响',
    reverb_dwell: 'Dwell \u2014 弹簧槽的输入驱动',
    vel_thresh: '力度阈值 \u2014 低于此值视为最小力度',
    vel_drive: '力度驱动 \u2014 感度曲线倾斜（正=强弱强调，负=平缓）',
    vel_compand: 'Compand \u2014 中位力度周围压缩/扩展',
    vel_range: 'Range \u2014 最大力度上限',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: '选择根音',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: '插槽 {slot}：空',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: '\u70B9\u51FB\u91CD\u547D\u540D',
    rename: '\u91CD\u547D\u540D',
    duplicate: '\u590D\u5236',
    delete: '\u5220\u9664',
    rename_prompt: '\u8F93\u5165Bank\u540D\u79F0:',
    confirm_delete: '\u5220\u9664 "{name}"\uFF1F',
    limit_reached: '\u6700\u591A16\u4E2ABanks',
    cannot_delete_last: '\u65E0\u6CD5\u5220\u9664\u6700\u540E\u4E00\u4E2ABank',
  },
  diatonic: {
    parallel: '同主音调',
    relative: '关系调',
    harm_mel: 'Harm/Mel',
    secdom: '副属和弦',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: '\u663E\u793A\u5168\u90E8',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 指南',
    tagline: '一款在64键打击垫网格上探索音阶、和弦和声位的浏览器工具。<br>无需音源 \u2014 只需Chrome。',
    cta: '打开应用',
    features: '功能特点',
    feat_sound: '<strong>无需音源</strong> \u2014 声音直接在Chrome中播放。内置4种管风琴 + 8种电钢琴预设。包含效果器（驱动、混响、移相器、镶边、颤音、Lo Cut、Hi Cut、自动滤波器）',
    feat_input: '<strong>无需打击垫技巧</strong> \u2014 3步构建和弦。显示延伸音。直接点击打击垫输入',
    feat_text_input: '<strong>文本和弦输入</strong> \u2014 按"/"直接输入Cm7, G7(b9,#11), Am7/G等。自动补全候选。支持dim, h(=m7\u266D5)等缩写',
    feat_detect: '<strong>和弦识别</strong> \u2014 根据点击的音符实时检测和弦名称。支持省略音、分割和弦和多个候选',
    feat_instruments: '<strong>吉他/贝斯/键盘显示</strong> \u2014 在吉他指板、贝斯和钢琴上显示和弦音。吉他指法输入自动反映到打击垫。和弦模式下按根音弦分组显示位置',
    feat_scales: '<strong>音阶显示</strong> \u2014 31种音阶 \u00D7 12个调。自然音阶、和声小调、旋律小调、五声音阶、Bebop等',
    feat_diatonic: '<strong>自然和弦显示</strong> \u2014 在条形图上显示所选音阶的自然和弦。点击或使用快捷键即时播放。支持三和弦/四和弦切换',
    feat_voicing: '<strong>声位操作</strong> \u2014 转位、Drop 2/3、Shell Voicing、Omit、Rootless。方向键控制转位，按钮切换多种指法',
    feat_memory: '<strong>和弦记忆</strong> \u2014 将喜欢的和弦保存到16个插槽。导出为MIDI文件用于DAW',
    feat_perform: '<strong>Perform模式</strong> \u2014 使用16个打击垫或电脑键盘实时演奏记忆和弦',
    feat_parent: '<strong>Available Scale反向查找</strong> \u2014 查找包含你的和弦的音阶。一目了然地查看Available Tensions。支持Practical/Diatonic排序切换',
    feat_pivot: '<strong>枢纽和弦思维</strong> \u2014 手动输入和弦后自然和弦条消失，显示该和弦可能属于的所有调。非常适合转调分析',
    feat_dimming: '<strong>Tension实用性显示</strong> \u2014 非属七和弦中，不常用的Tension（b9, #9, b13等）会以低透明度显示。仍可选择',
    feat_circle: '<strong>五度圈</strong> \u2014 显示五度圈。与调选择联动，显示自然和弦与功能（T/SD/D）。支持小调模式切换',
    feat_banks: '<strong>记忆库</strong> \u2014 16个插槽 \u00D7 最多16个库。切换、复制和重命名库。<kbd>[</kbd> <kbd>]</kbd> 键切换',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 包络滤波器（Auto-Wah）。3种类型：Cry Baby / Mu-Tron / Moog。可调节频率、共振、灵敏度和衰减',
    feat_drive: '<strong>Drive</strong> \u2014 模拟饱和。为声音增添温暖的过载',
    feat_clav: '<strong>Clavinet预设</strong> \u2014 E.PIANO中新增2种Clavinet预设（Clav Muted、Clav Bright）。非常适合放克',
    feat_midi_sens: '<strong>MIDI力度灵敏度</strong> \u2014 Push 3风格的4参数（Threshold、Drive、Compand、Range）力度曲线调节。实时曲线可视化。适用于所有MIDI控制器',
    feat_push_oct: '<strong>Push 3八度同步</strong> \u2014 Push 3八度 \u25B2\u25BC 按钮与应用的八度移位自动同步',
    feat_i18n: '<strong>多语言</strong> \u2014 9种语言（EN / JA / ZH / ES / FR / PT / DE / KO / IT）',
    screenshots: '截图',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: '选择调和音阶，在64键打击垫网格上以颜色编码显示音阶音。从自然和弦条中选择和弦。',
    ss_scale_alt: 'Scale Mode \u2014 C Major (Ionian) 音阶显示',
    ss_scale_caption: 'C Major (Ionian) \u2014 根音（橙色）、音阶音（蓝色）、特征音（黄色）',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: '3步构建和弦：Root \u2192 Quality \u2192 Tension。使用转位、Drop、Shell和Omit调整声位。使用Parent Scale面板反向查找音阶。',
    ss_chord_alt: 'Chord Mode \u2014 Dm7和弦显示及延伸音网格',
    ss_chord_caption: 'Dm7 \u2014 和弦音、3rd（粉色）、7th（绿色）。在Voicing Box中查看布局选项',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: '自由点击打击垫进行实时和弦检测。即使不了解理论也能理解和弦。',
    ss_input_alt: 'Input Mode \u2014 C7实时和弦检测',
    ss_input_caption: 'C7 \u2014 点击打击垫自动检测和弦名称。显示多个候选',
    ss_perform: 'Perform Mode',
    ss_perform_desc: '将保存的和弦放置在16个打击垫上，使用键盘或MIDI打击垫进行实时演奏。',
    ss_perform_alt: 'Perform Mode \u2014 16个插槽含和弦',
    ss_perform_caption: 'Perform Mode \u2014 C7、Fm7、G7、Am7已保存到插槽。使用4\u00D74键盘网格演奏',
    ss_parent: 'Available Scale + 枢纽和弦',
    ss_parent_desc: '反向查找包含你的和弦的音阶。可在Practical（实用性排序）和Diatonic（理论排序）之间切换。手动输入和弦时自然和弦条消失，可作为枢纽和弦进行分析。',
    ss_parent_alt: 'Parent Scale面板和吉他指板显示',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian)、C Mel.Min (Dorian b2)、F Major (Aeolian)等。显示Available Tensions',
    ss_parent_note: '\u203B 五声音阶/布鲁斯音阶属于调式（横向方法），与和弦-音阶理论（纵向对应）是不同的体系，因此不在Available Scale中涉及。在实际演奏中，五声音阶往往是首选。',
    ss_velocity: 'MIDI力度灵敏度',
    ss_velocity_desc: '使用Push 3风格的4个参数调节MIDI控制器的力度灵敏度。在Sound面板的VELOCITY SENSITIVITY区域配置。实时曲线可视化。',
    ss_push_oct: 'Push 3八度按钮同步',
    ss_push_oct_desc: 'Push 3八度 \u25B2\u25BC 按钮（CC#55/CC#54）与应用的八度移位自动同步。在Push 3上按八度按钮，显示八度会自动更新。',
    // HPS Voicing Features
    ss_hps_voicing_title: 'HPS专属Voicing功能',
    ss_hps_voicing_intro: "HPS会员可使用3种Voicing工具。在构建器中选择 TASTY / STOCK / Guitar 后，所选 voicing 会自动显示在64打击垫上。",
    ss_tasty: 'TASTY Voicing \u2014 按顶音分类',
    ss_tasty_desc: '129种精致声位以度数数组显示。选择和弦后按 <kbd>T</kbd> 启动，再次按下可切换其他声位。自动选择使所有音符适配打击垫的最佳位置。',
    ss_tasty_target: '适用: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: '信息区显示度数堆叠顺序（例如 <code>m9 (b3-b7-9-5-1)</code>）。这是声位结构\u2014\u2014表示从下到上音符的堆叠顺序。',
    ss_tasty_labels_title: '标签含义',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 省略根音（1度）。在爵士/R&B/Neo-Soul中，贝斯手负责根音，因此键盘或打击垫通常只演奏上层结构。',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 省略5度。5度的音色个性较弱，用延伸音替代可使声音更丰富。',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 省略3度。趋向sus或Quartal音响。',
    ss_tasty_ops_title: '操作',
    ss_stock: 'STOCK Voicing \u2014 钢琴Voicing合集',
    ss_stock_desc: "来自教材的154种钢琴声位，以度数记谱法显示。涵盖 Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread 全部和弦类型。所选 voicing 会自动显示在64打击垫上。",
    ss_stock_ops_title: '操作',
    ss_guitar_pos: 'Guitar Position \u2014 吉他Voicing',
    ss_guitar_pos_desc: "自动计算吉他指板上的和弦把位。左侧 Guitar 视图是乐器区域；构建器中的 Guitar 是用于64打击垫的 voicing 引擎。",
    usecases: '使用场景',
    uc1_q: '"我想找到这个和弦在打击垫上的声位"',
    uc1_a: '\u2192 在<span class="mode-badge chord">Chord</span>模式中选择Root、Quality和Tension \u2192 在Voicing Box中查看布局',
    uc2_q: '"我想在打击垫上查看课程中的音阶"',
    uc2_a: '\u2192 在<span class="mode-badge scale">Scale</span>模式中选择调和音阶。提供31种音阶',
    uc3_q: '"我想为DAW创建和弦进行"',
    uc3_a: '\u2192 将和弦保存到记忆插槽 \u2192 MIDI Export导入DAW',
    uc4_q: '"这个和弦属于哪个调？"',
    uc4_a: '\u2192 在Available Scale面板中反向查找。可切换Practical/Diatonic排序按实用性排列',
    uc7_q: '"我想找到转调的枢纽和弦"',
    uc7_a: '\u2192 在<span class="mode-badge chord">Chord</span>模式中手动输入和弦。自然和弦条消失，Available Scale显示该和弦可能属于的所有调',
    uc5_q: '"我想通过弹奏来确认和弦进行"',
    uc5_a: '\u2192 将和弦保存到记忆槽，然后用MIDI控制器或PC键盘弹奏试试',
    uc6_q: '"我想在打击垫上确认吉他和弦"',
    uc6_a: '\u2192 点击吉他指板输入 \u2192 自动显示在打击垫上 \u2192 检测和弦名称',
    uc8_q: '\u201C我想学习专业的Voicing\u201D',
    uc8_a: '\u2192 在<span class="mode-badge chord">Chord</span>模式下构建和弦，然后按 <kbd>T</kbd> 启动TASTY（顶音分类）或 <kbd>K</kbd> 启动STOCK（钢琴声位）。以度数记谱法查看，使用"映射到打击垫"转换为打击垫布局，保存到记忆槽并导出到DAW',
    quickstart: '快速入门',
    qs_modes: '3种模式',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> 显示音阶和自然和弦<br><span class="mode-badge chord">Chord</span> 3步构建和弦。可进行声位操作<br><span class="mode-badge input">Input</span> 自由点击打击垫 \u2192 自动检测和弦名称',
    qs_first: '开始使用',
    qs_step1: '选择一个调（例如C）',
    qs_step2: '选择一个音阶（例如Major）\u2192 音阶音出现在打击垫上',
    qs_step3: '点击自然和弦条上的和弦（例如Dm7）\u2192 显示和弦音',
    qs_step4: '点击打击垫播放声音。在Voicing Box中更改布局',
    qs_step5: '使用<kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>保存喜欢的和弦',
    qs_shortcuts: '键盘快捷键',
    qs_shortcuts_desc: '按<kbd>?</kbd>查看完整快捷键列表。<br><kbd>Space</kbd>播放和弦。<kbd>1</kbd>\u2013<kbd>7</kbd>选择自然和弦，<kbd>\u2191</kbd><kbd>\u2193</kbd>切换转位，<kbd>\u2190</kbd><kbd>\u2192</kbd>半音移动。<br>在Perform模式中，使用<kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd>作为4\u00D74网格。',
    footer_open: '打开64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: '在博客上了解更多 \u2192',
    // 标题图标
    header_icons: '标题图标',
    header_icons_desc: '右上角有三个图标按钮。',
    icon_save: '<strong>\uD83D\uDCBE 保存</strong> \u2014 将当前设置（音色、效果器、显示选项等）保存到浏览器。下次访问时自动恢复',
    icon_tutorial: '<strong>\uD83D\uDCD6 教程</strong> \u2014 浏览11个互动教程。逐步体验各功能的使用方法',
    icon_help: '<strong>? 帮助</strong> \u2014 查看快捷键列表、版本历史和各模式说明。也可按<kbd>?</kbd>键打开',
    // 声音面板
    sound_panel: '声音面板',
    sound_panel_desc: '选择音色和调整效果器。点击\u25B6按钮展开面板。',
    sound_presets: '音色预设',
    sound_presets_desc: 'Rhodes物理建模音源（Clean DI）为默认音色。无需下载采样即可立即演奏。使用VOICING旋钮调整拾音器音色。',
    sound_effects: '效果器',
    sound_effects_desc: '拖动旋钮调整各项参数。',
    fx_drive: '模拟饱和。温暖的过载',
    fx_locut: '低切滤波器。消除浑浊低音',
    fx_hicut: '高切滤波器。抑制刺耳高音',
    fx_reverb: '混响。增加空间感',
    fx_phaser: '移相器。波浪般的调制',
    fx_flanger: '镶边。喷气式调制',
    fx_tremolo: '颤音。周期性音量变化',
    sound_autofilter: '自动滤波器（Auto-Wah）',
    sound_autofilter_desc: '包络滤波器。可调整FREQ、RESO、SENS和DECAY。',
    version_history: '\u7248\u672C\u5386\u53F2',
    vh_540: '<b>V5.4</b> \u2014 物理建模升级。新增滤波器参数（WET / VOL）与 HPS 会员专属预设（Pad Sensei MK1 AMP Vintage Envelope Filter）',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 前级建模改进',
    vh_510: '<b>V5.1</b> \u2014 新增 C 大调固定音阶模式',
    vh_500: '<b>V5.0</b> \u2014 \u81EA\u5305\u542B\u97F3\u6E90 + \u6548\u679C\u5668\u67B6\u6784\u3002Spring Reverb\uFF08\u7269\u7406\u5EFA\u6A21\uFF09+ Plate Reverb\u3002Suitcase\u653E\u5927\u5668\u6A21\u578B\u6539\u8FDB\u3002Reverb Type\u5207\u6362\uFF08Spring/Plate\uFF09\u3002Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 \u6253\u5F00\u5373\u53EF\u6F14\u594F\uFF08\u65E0\u9700\u4E0B\u8F7D\u91C7\u6837\uFF09\u3002\u5FEB\u6377\u952E\u63D0\u793A\u5207\u6362\u3002NM/HM/MM\u5E73\u884C\u8C03\u81EA\u7136\u97F3\u9636\u548C\u5F26\u3002E.PIANO MIXER\u65B0\u589E PU LEVEL \u548C MECHANICAL\u3002\u548C\u5F26\u68C0\u6D4B\u663E\u793A\u6539\u8FDB',
    vh_490: '<b>V4.9</b> \u2014 搭载 Pad Sensei MK1 物理建模音源',
    vh_497: '<b>V4.9.7</b> \u2014 颤音现在采用物理建模。HPS 会员可使用 Pad Sensei MK1 Suitcase（物理建模放大器链）',
    vh_3377: '<b>V3.37.7</b> \u2014 用户评审：关系小调修正、标题大小写标签、无衬线打击垫字体、色觉友好切换（绿\u2192蓝）、Sound面板默认展开、布局偏移修正、教程聚光灯叠加层、Launchpad八度支持 + 所有MIDI控制器自动八度跟踪',
    vh_340: '<b>V3.40</b> \u2014 TASTY/Stock紧凑布局：和弦音自动最优排列在64键盘上。移除"映射到键盘"按钮。TASTY/Stock模式下隐藏和弦框',
    vh_336: '<b>V3.36</b> \u2014 吉他和弦引擎v2：风格预设（Jazz/Bossa/Funk）、参考指法库（120种\u00D712调）、自动指法分配（横按检测）',
    vh_335: '<b>V3.35</b> \u2014 教程UX改善（初学者评审）。所有工具提示翻译为9种语言。指南：新增音色面板和标题栏图标章节',
    vh_333: '<b>V3.33</b> \u2014 交互式教程。11个主题\u00D79种语言。首次功能交互时显示上下文提示',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154种钢琴声位（MIDI专用键盘显示+\u201C映射到打击垫\u201D）。指南新增HPS Voicing功能章节',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing。129种精致声位，按最高音排序。度数数组显示+自动八度优化。仅限HPS会员',
    vh_325: '<b>V3.25.0</b> \u2014 吉他声位\u2192打击垫映射（<kbd>V</kbd>键）。吉他式（每行1音）/ 紧凑式布局切换。吉他把位"全部"筛选器置顶',
    vh_324: '<b>V3.24</b> \u2014 新增Clavinet音色（E.PIANO中2种）。新增自动滤波器（包络滤波器/Auto-Wah）效果',
    vh_323: '<b>V3.23</b> \u2014 文本和弦输入。自动补全候选，按"/"聚焦，支持dim、h=m7\u266D5等缩写，按延伸音数量排序',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 自然和弦三和弦/四和弦切换。吉他/贝斯位置按根音弦分组',
    vh_37: '<b>V3.7</b> \u2014 \u58F0\u4F4D\u4FDD\u6301\uFF08\u534A\u97F3\u79FB\u52A8\u65F6\u81EA\u52A8\u7EF4\u6301\u6307\u6CD5\u5F62\u72B6\uFF09\u3002\u64AD\u653E\u65F6\u7684\u6253\u51FB\u5757\u7F51\u683C\u3001\u4E94\u7EBF\u8C31\u4E0E\u548C\u5F26\u68C0\u6D4B\u3002 <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">\u89C6\u9891</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI\u6587\u4EF6\u64AD\u653E \u2192 \u6253\u51FB\u5757\u706F\u5149\uFF08\u65F6\u95F4\u8F74\u64AD\u653E\u3001\u548C\u5F26\u540D\u663E\u793A\u3001Play/Pause/Stop/Seek\uFF09',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO\u91C7\u6837\u5668\uFF08Rhodes Mark I\uFF09\u30027\u79CD EP \u9884\u8BBE\u3002\u97F3\u6548 ON/OFF \u5F00\u5173\u3002\u652F\u6301 iPad',
    vh_31: '<b>V3.1</b> \u2014 \u529B\u5EA6\u7075\u654F\u5EA6\uFF084\u4E2A\u53C2\u6570 + \u66F2\u7EBF\u53EF\u89C6\u5316\uFF09\u3002\u652F\u6301 Push 3 \u5C45\u684C\u952E\u3002 <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">\u89C6\u9891</a>',
    vh_250: '<b>V2.50</b> \u2014 \u591A\u4E2A\u5185\u5B58\u9762\u677F\uFF0816 \u63D2\u69FD \u00D7 \u6700\u591A 16 \u4E2A\u9762\u677F\uFF0C\u5207\u6362/\u590D\u5236/\u91CD\u547D\u540D\uFF09',
    vh_218: '<b>V2.18</b> \u2014 \u81EA\u52A8\u4FDD\u5B58/\u6062\u590D\u6240\u6709\u8BBE\u7F6E\uFF08\u8C03/\u97F3\u9636/\u97F3\u6548/MIDI/\u5185\u5B58\uFF09',
    vh_213: '<b>V2.13</b> \u2014 \u4E50\u5668\u97F3\u9636\u53E0\u52A0\uFF08\u5409\u4ED6/\u8D1D\u65AF/\u9992\u7434\u663E\u793A Available Scale\uFF09\u3002\u6253\u51FB\u5757\u97F3\u7EA7\u6807\u7B7E\u3002\u5C45\u683C\u8054\u52A8\u64AD\u653E',
    vh_27: '<b>V2.7</b> \u2014 Tension \u6DFB\u52A0\u6A21\u5F0F\uFF08\u6253\u51FB\u5757/\u5409\u4ED6/\u8D1D\u65AF/\u952E\u76D8\u548C\u5F26\u5408\u6210 \u2192 Available Scale \u8FC7\u6EE4\uFF09',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay\uFF08Available Tensions\uFF0C\u6253\u51FB\u5757\u97F3\u9636\u53E0\u52A0\uFF09',
    vh_19: '<b>V1.9</b> \u2014 9\u79CD\u8BED\u8A00',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode\u300116\u4E2A\u5185\u5B58\u63D2\u69FD\u3001Undo\u3001D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain Mode\uFF0CMIDI/CHS \u5BFC\u51FA',
    vh_10: '<b>V1.0</b> \u2014 \u521D\u59CB\u53D1\u5E03\uFF08Scale/Chord/Voicing/Sound/MIDI\uFF09',
  },
  pos: {
    root_6: '6弦R',
    root_5: '5弦R',
    root_4: '4弦R',
    root_3: '3弦R',
    root_2: '2弦R',
    open: '开放弦',
    no_open: '无开放弦',
    all: '全部',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: '映射到Pad',
    genre_default: '标准',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    '按 C 键将当前和弦保存到 Memory',
    'Opt+1~V 直接保存到插槽（16键: 1234 QWER ASDF ZXCV）',
    'Shift+点击 Memory 插槽可删除',
    'Opt+拖拽可复制插槽',
    '按 S 切换 Shell 声位（1-3-7 / 1-7-3）',
    'Shift+D 切换 Drop 2 / Drop 3 声位',
    'Shift+G 显示吉他指板',
    '\u2318\u2325F 显示五度圈',
    'Tab 切换 Scale / Chord / Input 模式',
    'Space 播放当前音阶或和弦',
    '从 Memory 面板导出 MIDI 文件',
    '连接 MIDI 控制器直接演奏',
    '方向键 ↓↑ 改变和弦转位（Root / 1st / 2nd / 3rd）',
    '按 R 启用无根音声位',
    '按 O 省略五度音',
    'Shift+S 显示五线谱',
    '保存图标可跨会话保留设置',
    '[ ] 键切换 Memory 库 — 管理多首歌曲',
    'Perform 模式：用电脑键盘（1234 / QWER / ASDF / ZXCV）或 MIDI 触发和弦',
    '在 Chord 模式按 / 直接输入和弦名（如 Cm7, G7(b9,#11)）',
  ],
  tips_off: '不再显示提示',
  whats_new: '新功能',
  whats_new_497: '颤音现在采用物理建模！HPS 会员可使用 Pad Sensei MK1 Suitcase。',
  whats_new_61: '现在可以从指南访问在线手册。正在制作中。',
  whats_new_123: '现在可以从指南访问在线手册。正在制作中。',
  whats_new_51: '新增C大调固定模式！在帮助(?)菜单切换。Push/Launchpad将始终显示C大调。',
  whats_new_50: '弹簧混响 + 板式混响登场！Baxandall Bass/Treble EQ，Suitcase 音箱模型改进。',
  whats_new_32427: '吉他声位\u2192打击垫映射（V键）。吉他式 / 紧凑式布局切换',
  whats_new_33000: '教程系统！点击标题栏的书本图标，学习Scale模式、Chord模式等功能。',
  whats_new_640: 'V6.4.0 已更新：支持三个张力音判定、UST 分析、Note/Degree 显示，以及根据调性选择 # / b 记谱。',
  whats_new_650: 'V6.5.0 已更新：HPS 的 TASTY / STOCK / Guitar voicing 已整理到 Chord Builder 内。6 系和弦显示为 C6(9) / C6(9,#11)，并改进了吉他 voicing 筛选、显示平衡和播放音域。',
  whats_new_660: 'V6.6.0 已更新：HPS 会员专属——TASTY 新增四度叠置（So What）模式 voicing，适用于小调、大调和属和弦，带来 Miles Davis / McCoy Tyner 的声音。Chord Builder 的和弦种类排列也已整理。',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: '音色预设',
    sound_msg: '选择一个音色预设，点击打击垫试听。\nORGAN和E.PIANO — 每种都有多个预设。',
    sound_done: '听起来不错！按下"下一步"继续。',
    midi_title: 'MIDI控制器',
    midi_msg: '已检测到MIDI控制器。从下拉菜单中选择你的设备。\n力度灵敏度可在Sound面板中调节。',
    midi_no_device: '未检测到MIDI控制器 — 没关系。\n你可以使用打击垫点击、吉他/贝斯/钢琴输入或文本和弦输入。',
    input_title: '三种模式',
    input_msg: 'Scale — 在64键打击垫网格上查看音阶音\nChord — 使用声位、转位和延伸音构建和弦\nInput — 自由点击打击垫识别和弦名称\n\n使用Tab键或上方的模式按钮切换。',
    instruments_title: '乐器输入',
    instruments_msg: '吉他、贝斯、钢琴 — 分别开关显示并直接点击输入音符。\n吉他指板点击 \u2192 和弦识别 \u2192 "映射到Pad"(V) 转换为打击垫布局。\n文本输入：在Chord模式下按 / 直接输入和弦名（如 Cm7, G7(b9,#11)）。',
    done_title: '准备就绪！',
    done_msg: '一切准备好了。自由探索吧 — 按 ? 查看完整快捷键列表。\n指南中有截图、视频和使用场景。',
    next: '下一步',
    skip_step: '下一步',
    skip_all: '跳过教程',
    open_guide: '打开指南',
    close: '开始',
    reset: '重新开始教程',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: '教程',
    cat_getting_started: '入门',
    cat_features: '功能',
    cat_advanced: '高级',
    steps_label: '步',
    reset_all: '重置所有进度',
    close_selector: '关闭',
    hint_available: '有教程可用',
    hint_try: '试试看',
    btn_label: '教程',
    // Shared action labels
    next: '下一步',
    skip_step: '下一步',
    skip_all: '跳过教程',
    open_guide: '打开指南',
    close: '完成',
    onboarding_ask_title: '教程',
    onboarding_ask_msg: '第一次来？想快速浏览一下应用吗？',
    onboarding_yes: '下一步',
    onboarding_no: '跳过',
    // Onboarding
    onboarding_title: '初步体验',
    onboarding_desc: '学习 64 Pad Explorer 的基础操作',
    onboarding: {
      sound_title: '音色预设',
      sound_msg: '选择一个音色预设，点击打击垫试听。\nORGAN和E.PIANO — 每种都有多个预设。',
      sound_done: '听起来不错！按下一步继续。',
      midi_title: 'MIDI 控制器',
      midi_msg: '已检测到 MIDI 控制器。Push 3 和 Launchpad 开箱即用，无需设置。\n力度灵敏度可在 Sound 面板中调节。',
      midi_no_device: '未检测到 MIDI 控制器 — 没关系。\n你可以使用打击垫点击、吉他/贝斯/钢琴输入或文本和弦输入。',
      input_title: '三种模式',
      input_msg: 'Scale — 在64键打击垫网格上查看音阶音\nChord — 使用声位、转位和延伸音构建和弦\nInput — 自由点击打击垫识别和弦名称\n\n使用 Tab 键或上方的模式按钮切换。',
      instruments_title: '乐器输入',
      instruments_msg: '吉他、贝斯、钢琴 — 分别开关显示并直接点击输入音符。\n吉他指板点击 → 和弦识别 → "映射到Pad"(V) 转换为打击垫布局。\n文本输入：在 Chord 模式下按 / 直接输入和弦名（如 Cm7, G7(b9,#11)）。',
      done_title: '准备就绪！',
      done_msg: '一切准备好了。自由探索吧 — 按 ? 查看完整快捷键列表。\n指南中有截图、视频和使用场景。',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Scale 模式',
    scale_mode_desc: '在64键打击垫网格上探索音阶',
    scale_mode: {
      step1_title: '切换到 Scale 模式',
      step1_msg: 'Scale 模式在打击垫网格上点亮音阶音。\n点击任意亮起的打击垫可听到该音。',
      step2_title: '选择调',
      step2_msg: '选择一个根音调。打击垫网格会即时更新。\n试试在 C、G、F 之间切换 — 感受颜色图案的变化。',
      step3_title: '选择音阶',
      step3_msg: 'Major、Minor、Dorian、Mixolydian、Pentatonic……\n共31种音阶可选。打击垫实时更新。',
      step4_title: 'Diatonic Bar',
      step4_msg: '所选音阶的自然和弦显示在这里。\n点击任意和弦即可跳转到 Chord 模式并加载该声位。',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Chord 模式',
    chord_mode_desc: '逐步构建和弦',
    chord_mode: {
      step1_title: '切换到 Chord 模式',
      step1_msg: 'Chord 模式提供两种选择和弦的方式。\n① 从 Diatonic Bar 一键选择\n② 自建：Root → Quality → Tension',
      step_key_title: '调选择',
      step_key_msg: '设置音阶的调。设置调后，Diatonic Bar显示和弦，延伸音的可用性会根据音阶过滤。\n也可以不使用调，直接从Root自由构建和弦。',
      step_diatonic_title: 'Diatonic Bar',
      step_diatonic_msg: '所选调的自然和弦。\n点击即可立即设置和弦，并根据音阶过滤延伸音。',
      step2_title: '第1步：Root',
      step2_msg: '选择一个根音。C、D、E……全部12个音。\n显示屏展示你当前的和弦。',
      step3_title: '第2步：Quality',
      step3_msg: '选择和弦类型：Maj、min、7、m7、dim、aug……\n打击垫网格会点亮和弦音。',
      step4_title: '第3步：Tensions',
      step4_msg: '先选择 Quality — Tension 按钮会自动出现。\n9、b9、#9、11、#11、13、b13。可多选。',
      step5_title: '文本输入',
      step5_msg: '按 / 直接输入和弦名称。\n分数和弦和复杂声位都可以快速输入。',
      step6_title: '寻找副属音阶',
      step6_msg: '直接输入非 Diatonic 和弦。\n示例：输入 G7 → Available Scale 显示"Mixolydian"、"Mixolydian b13"等。\n切换到 Practical 排序可优先显示最常用的音阶。\n这就是找到副属和弦对应音阶的方法。',
      step7_title: 'Slash Chords',
      step7_msg: '在 Chord Builder 中点击 / 输入低音以构建 Slash Chord。\n也可在文本输入中输入 C/D 或 F△7/G。\nAvailable Scale 会自动更新以匹配 Slash Chord。',
    },
    // Input Mode tutorial
    input_mode_title: 'Input 模式',
    input_mode_desc: '通过MIDI控制器、打击垫、指板或键盘输入和弦',
    input_mode: {
      step1_title: '切换到 Input 模式',
      step1_msg: '通过MIDI控制器、点击打击垫、指板或键盘输入和弦的模式。\n和弦识别功能在所有模式下均可使用。',
      step2_title: '点击一些打击垫',
      step2_msg: '点击网格上的任意打击垫。\n每次点击切换一个音的开/关。',
      step3_title: '和弦识别',
      step3_msg: '检测到的和弦名称显示在网格上方。\n每个打击垫上显示音程标签（R、3、5、b7…）。',
      step4_title: '用 Capture 保存',
      step4_msg: '按 <strong>C</strong> 将当前和弦保存到下一个记忆插槽。\n逐个构建和弦进行。',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Diatonic Bar',
    diatonic_desc: '一键访问自然和弦',
    diatonic: {
      step1_title: 'Diatonic Bar',
      step1_msg: '每个音阶都有自己的自然和弦组。\n它们显示在这里 — 随时可以演奏。',
      step2_title: '三和弦 / 四和弦',
      step2_msg: '在3音三和弦和4音七和弦之间切换。\n和弦条即时更新。',
      step3_title: '点击和弦',
      step3_msg: '点击和弦条上的任意和弦。\n可以在 Chord Builder 中使用 Tension 等进行变换。',
      step4_title: '对比3种小调音阶（Harm/Mel）',
      step4_msg: '选择小调后，打开"Harm/Mel"(\u2318\u2325N)。\n和声小调与旋律小调的自然和弦出现在下方。\n与自然小调（上方条）对比 \u2014 注意V和弦从m7变为7。',
      step5_title: '副属和弦',
      step5_msg: '打开"Secondary Dominant"(\u2318\u2325D)。\n解决到每个自然和弦的V7和弦会显示出来。\n点击任一和弦，Available Scale自动显示。\n解决到大调 \u2192 Mixolydian。解决到小调 \u2192 HMP5\u2193/Altered。',
      step6_title: '键盘快捷键',
      step6_msg: '按 1\u20137 选择自然和弦。\n\u2318\u2325N（Harm/Mel）、\u2318\u2325D（SecDom）、\u2318\u2325R（同主音调）用于扩展条。',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: '保存和弦并实时演奏',
    memory: {
      step1_title: '保存和弦',
      step1_msg: '保存你喜欢的和弦。\n保存中意的声位，有助于编曲和练习。',
      step2_title: '16个记忆插槽',
      step2_msg: '与 PUSH、Launchpad、MPC、Maschine 上的16键 Drumrack 布局相同 — 直观易用。',
      step3_title: '记忆库',
      step3_msg: '在 PUSH 和 Launchpad 上，Drumrack 布局使操作直观易用。',
      step4_title: 'Perform 模式',
      step4_msg: 'PC 键盘按键也对应16个打击垫。',
      step5_title: 'MIDI 导出',
      step5_msg: '将所有记忆和弦导出为MIDI文件。\n拖入DAW即可开始制作。',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: '塑造你的和弦声位',
    voicing: {
      step1_title: 'Voicing 控制',
      step1_msg: '在 Chord Builder 模式下，可以从基本形式进行各种变换。\nOmit、Shell、Inversion、Drop — 全部在这里。',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> 用于 Shell voicing。在打击垫上流畅地学习 R37 和 R73 声位。',
      step3_title: 'Omit & Rootless',
      step3_msg: '快捷键通常采用助记符。\n<strong>O</strong>mit = 省略5度。<strong>R</strong>ootless = 无根音声位。',
      step4_title: '转位',
      step4_msg: '与大多数软件不同，你可以极快地创建转位。\n也有助于理解分数和弦。',
      step5_title: 'Drop Voicing',
      step5_msg: '当你想突出最高音时 —\nDrop voicing 也受支持。',
      step6_title: 'Voicing Box',
      step6_msg: '打击垫可以有多个位置选项。Voicing Box 负责处理这一点。\n点击打击垫上的 a、b、c、d 等，或输入字母，查看多种声位可能性。',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: '预设、效果和音量',
    sound: {
      step1_title: '音色预设',
      step1_msg: 'ORGAN（4种）和E.PIANO（8种）。\n点击打击垫或使用 MIDI 控制器。',
      step2_title: '详细面板',
      step2_msg: '点击 ▼ 展开音色详细面板。\n效果、音量和滤波器控制在这里。',
      step3_title: '效果器',
      step3_msg: 'Reverb、Phaser、Flanger、Tremolo、Auto-Filter、Drive。\n在详细面板中调节它们。',
      step4_title: '声音 ON/OFF',
      step4_msg: '扬声器图标可切换声音开/关。\n关闭后在使用 DAW 时更方便。',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: '按顶音分类的魅力声位。HPS会员专用功能',
    tasty: {
      step1_title: '激活 TASTY',
      step1_msg: '挑选简单逻辑无法产生的时髦声位。\n从最高音思考，对弦乐和管乐编配很有用。\n（仅限 HPS 会员）',
      step2_title: '循环配方',
      step2_msg: '用 Z / X 键向前/向后浏览声位。\n计数器显示当前位置。',
      step3_title: '音程标记',
      step3_msg: '信息区显示音程堆叠 — 如 m9 (b3-b7-9-5-1)。\n这是从下到上的声位结构。',
      step4_title: '映射到Pad',
      step4_msg: '普通软件做不到的打击垫优化。\n在打击垫上也能畅享时髦声位。',
      fb_step1_title: 'TASTY Voicing 是什么？',
      fb_step1_msg: '129种按顶音分类的精致声位。\n支持 Maj7 / Dom7 / Min7。以音程标记法显示。\n仅限 HPS 会员。',
      fb_step2_title: '如何访问 TASTY',
      fb_step2_msg: '加入 HPS（Hardcore Pad Style）后可用。\n在 Chord 模式下按 T 激活。Z/X 键浏览声位。\n详情请查看指南。',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: '钢琴常用的经典声位。HPS会员专用功能',
    stock: {
      step1_title: '激活 STOCK',
      step1_msg: '了解钢琴专用声位，帮助你摆脱只用基本形式的演奏。\n154种钢琴声位以音级标记法呈现。\n（仅限 HPS 会员）',
      step2_title: '循环声位',
      step2_msg: '用 Z / X 键向前/向后浏览声位。',
      step3_title: '键盘视图',
      step3_msg: '打开钢琴显示查看实际键位。\n声位在键盘上栩栩如生。',
      step4_title: '映射到Pad',
      step4_msg: '点击"映射到Pad"将声位转换为打击垫布局。\n保存到记忆并导出到你的DAW。',
      fb_step1_title: 'STOCK Voicing 是什么？',
      fb_step1_msg: '收录了常用的钢琴声位。\n以音程标记法展示声位结构。\n仅限 HPS 会员。',
      fb_step2_title: '如何访问 STOCK',
      fb_step2_msg: '加入 HPS（Hardcore Pad Style）后可用。\n在 Chord 模式下按 K 激活。\n详情请查看指南。',
    },
    // Circle of Fifths tutorial
    circle_title: '五度圈',
    circle_desc: '一目了然的调性关系',
    circle: {
      step1_title: '打开五度圈',
      step1_msg: '按 ⌘⌥F 或点击五度圈按钮。\n五度圈显示在下方。',
      step2_title: '调性联动',
      step2_msg: '快速查看对演奏和作曲很重要的代理和弦和自然和弦。',
      step3_title: '自然和弦功能',
      step3_msg: '与普通五度圈不同，64 Pad Explorer 允许你在选择小调时选择3种小调（Natural/Harmonic/Melodic）。\n更容易掌握复杂的小调。',
      step4_title: '选择小调',
      step4_msg: '五度圈内圈显示小调。\n点击内圈的调号可选择小调。\n自然和弦显示会相应变化。',
      step5_title: '3种小调音阶',
      step5_msg: '选择小调后，中央会出现 Nat / Harm / Mel 按钮。\nNat = Natural Minor（标准形式）\nHarm = Harmonic Minor（V7出现）\nMel = Melodic Minor（VI、VII级变化）',
      step6_title: '试着切换',
      step6_msg: '点击 Nat → Harm → Mel，观察自然和弦的变化。\n注意 Harmonic Minor 中 V7 的出现。',
    },
    // Guitar tutorial
    guitar_title: '吉他指板',
    guitar_desc: '从吉他输入和弦并映射到打击垫',
    guitar: {
      step1_title: '显示吉他指板',
      step1_msg: '按 ⌘⌥G 或点击 Guitar 按钮。\n和弦音会显示在指板上。',
      step2_title: '查看和弦位置',
      step2_msg: '在 Chord 模式下选择和弦，指板会自动显示对应位置。\n使用逗号（,）和句点（.）键循环切换位置。',
      step3_title: '从吉他输入',
      step3_msg: '切换到 Input 模式后，尝试点击指板上的品格输入音符。\n和弦名称会从你的输入中实时识别。',
      step4_title: '映射到打击垫',
      step4_msg: '"映射到Pad" 将吉他声位映射到打击垫网格上。',
    },
    // Shortcuts tutorial
    shortcuts_title: '键盘快捷键',
    shortcuts_desc: '高效操作的必备按键',
    shortcuts: {
      step1_title: '模式切换',
      step1_msg: 'Tab — 切换模式（Scale → Chord → Input）\nShift+Tab — 反向切换\n\n快速在各模式间移动。',
      step2_title: '自然和弦 & 导航',
      step2_msg: '1–7 — 选择自然和弦\n↑↓ — 循环转位\n←→ — 按半音移调根音（保持和弦形态）\n\n无需鼠标操作和弦。',
      step3_title: '声位操作',
      step3_msg: 'S — Shell 循环（关 → 1-3-7 → 1-7-3）\nO — Omit 5 切换\nR — Rootless 切换\nShift+D — Drop 循环（关 → Drop2 → Drop3）\nT — TASTY 开/关，K — STOCK 开/关\nZ / X — TASTY/STOCK 声位前/后\n←→ — 按半音移调声位（TASTY/STOCK 激活时）\nV — 映射到打击垫 / 布局切换\n/ — 文本和弦输入',
      step4_title: '记忆 & 库',
      step4_msg: 'Option+1234/qwer/asdf/zxcv — 保存到插槽\n[ ] — 切换库\nM — 记忆视图切换\nP — Perform 模式切换\nSpace — 播放\nShift+Space — 全部播放（顺序）',
      step5_title: '更多',
      step5_msg: '? — 帮助（完整快捷键列表）\n⌘⌥+G/B/P/F/S — 乐器/五度圈/五线谱切换\n⌘⌥+A/M/T/Q/V/K/H — 分区切换\nCmd/Ctrl+Z — 撤销（最多30次）\nEsc — 取消选择 / 关闭模态框',
    },
    // Link Mode tutorial
    link_title: 'Link 模式',
    link_desc: '在所有乐器上同步演奏的音符',
    link: {
      step1_title: 'Link 按钮',
      step1_msg: 'Link 按钮位于 Guitar / Bass / Piano 旁边。\n打开它可以在所有乐器上实时查看演奏的音符。',
      step2_title: 'Link 模式 ON',
      step2_msg: 'Link 激活后，乐器显示会变暗。\n演奏打击垫或 MIDI \u2014 只有演奏的音符会亮起。',
      step3_title: '演奏打击垫',
      step3_msg: '按下一个打击垫，观察相同的音符在吉他、贝斯和钢琴上亮起。\n查看每种乐器上哪个位置产生相同的音高。\n松开即清除。',
      step4_title: '快捷键',
      step4_msg: '\u2318\u2325+L 切换 Link 模式的开/关。\n非常适合学习音符在各乐器间的映射关系。',
    },
    // Minor Scales tutorial
    minor_scales_title: '对比3种小调音阶',
    minor_scales_desc: '自然小调、和声小调与旋律小调并列对比',
    minor_scales: {
      step1_title: '设置小调',
      step1_msg: 'Am（自然小调）已选择。\nDiatonic Bar 显示自然小调的和弦。',
      step2_title: '打开 Harm/Mel',
      step2_msg: '点击 "Harm/Mel"(\u2318\u2325N)。\n和声小调与旋律小调的自然和弦出现在下方。',
      step3_title: '对比',
      step3_msg: '观察与自然小调（上方条）的差异。\n在和声小调中，V和弦从 Em7 变为 E7 \u2014 实现了属功能进行。\n在旋律小调中，IV和弦也从 Dm7 变为 D7。\n点击任意和弦在打击垫上查看。',
      step4_title: '同主音调',
      step4_msg: '打开 "Parallel Key"(\u2318\u2325R) 查看相同根音的大调自然和弦。\n这揭示了借用和弦（调式互换）的来源。',
    },
    // Secondary Dominant tutorial
    secdom_title: '副属和弦',
    secdom_desc: '体验转调的入口',
    secdom: {
      step1_title: '从C大调开始',
      step1_msg: 'C大调已设置。\nDiatonic Bar 显示 C\u25B37、Dm7、Em7、F\u25B37、G7、Am7、Bm7(b5)。',
      step2_title: '打开副属和弦',
      step2_msg: '点击 "Secondary Dominant"(\u2318\u2325D)。\n解决到每个自然和弦的V7和弦出现。\n在C大调中：C7、D7、E7、A7、B7（共5个）。',
      step3_title: '解决到大调',
      step3_msg: '点击 C7(\u2192F\u25B37) 或 D7(\u2192G7)。\nAvailable Scale 显示 Mixolydian 为首选。\n因为解决目标是大调和弦。',
      step4_title: '解决到小调',
      step4_msg: '点击 A7(\u2192Dm7) 或 E7(\u2192Am7)。\nAvailable Scale 显示 HMP5\u2193（Phrygian Dominant）和 Altered 为首选。\n因为解决目标是小调和弦。',
      step5_title: '规则：只有2种类型',
      step5_msg: '副属和弦的音阶选择很简单：\n\u2022 解决到大调 \u2192 Mixolydian\n\u2022 解决到小调 \u2192 HMP5\u2193 或 Altered\n只需记住这些。',
    },
    // Settings tutorial
    settings_title: '显示与设置',
    settings_desc: '自定义你的工作空间',
    settings: {
      step1_title: '乐器面板',
      step1_msg: '在 Chord Builder 中选择和弦时，吉他会显示常用声位。\n在 Input 模式下，也可以从吉他、贝斯和键盘输入。',
      step2_title: '音名 / 音级',
      step2_msg: '在音名（C、D、E）和音级（R、2、3）之间切换。\n应用于打击垫和吉他显示。',
      step3_title: '八度移动',
      step3_msg: '使用 ▲▼ 将打击垫音域上移或下移一个八度。\nPush 3 和 Launchpad 的八度按钮自动同步。',
      step4_title: '分区折叠',
      step4_msg: '⌘⌥+Q（Quality/Tension）/ V（Voicing）/ K（Key）/ M（Memory）/ T（Text）折叠各分区。\n只显示你需要的内容。',
      step5_title: '布局顺序',
      step5_msg: '在 ? 帮助中，使用"Layout"下拉菜单重新排列3个面板。\n6种预设：Chord、Pad、Circle 的任意组合。\n在移动端，滑动顺序也会改变。',
      step6_title: '保存所有设置',
      step6_msg: '点击保存图标保存所有设置。\n调、音阶、音色、记忆、声位 — 全部保留。',
    },
  },
});
