// Italiano
I18N.addLang('it', {
  help: {
    title: '64 Pad Explorer',
    description: 'Uno strumento per esplorare scale, accordi e voicings su una griglia di 64 pad.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Scegliere tra 12 tonalità',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonica, minore armonica, minore melodica, pentatonica, Bebop e altro \u2014 31 tipi',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Mostra gli accordi diatonici della scala selezionata. Clicca per entrare in modalità Chord',
    chord_mode: 'Chord Mode (3 passaggi)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selezionare la fondamentale sulla tastiera del pianoforte',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Scegliere il tipo di accordo (Maj, m, aug, dim, sus, ecc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Aggiungere tensioni (9, b9, #9, 11, #11, 13, b13, ecc.). Selezione multipla consentita',
    chord_text: '<strong>Input testuale</strong> \u2014 Premi "/" per attivare. Digita Cm7, G7(b9,#11), Am7/G ecc. direttamente. Suggerimenti automatici',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usare il pulsante "/" per accordi con basso diverso (accordo / nota di basso)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omettere note',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 per aggiungere note)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Rivolti (Root, 1st, 2nd, 3rd)',
    inv_1: '1° rivolto',
    inv_2: '2° rivolto',
    inv_3: '3° rivolto',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tocca per scorrere le disposizioni sui pad (badge pulsante = disposizioni alternative disponibili)',
    display: 'Visualizzazione',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Attivare/disattivare tastiera di chitarra, basso, pianoforte e pentagramma indipendentemente. Nota: Le posizioni chitarra/basso mostrano diteggiature suonabili sullo strumento, non corrispondono alla disposizione del pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Mostra il circolo delle quinte. Collegato alla selezione della tonalità, mostrando accordi diatonici e funzioni (T/SD/D). Cambio di modo minore supportato',
    display_label: '<strong>Nome / Grado</strong> \u2014 Alternare tra nomi delle note (C, D, E) e gradi (R, 2, 3) su chitarra e pad',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Spostare l\'estensione dei pad di un\'ottava',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Attiva/disattiva il suono con l\'icona dell\'altoparlante',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Modellazione fisica Rhodes. I membri HPS possono selezionare il preset Suitcase (catena ampli modellata fisicamente). \u25BC apre il pannello dettagli',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Modellazione fisica Peterson Vactrol (stereo). Usa TREM/T.SPD per profondità e velocità',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 preset (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 preset (Rhodes, FM, Clavinet, ecc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro inviluppo (Auto-Wah). 3 tipi: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturazione analogica. Aggiunge un caldo overdrive al suono',
    sound_fx: '<strong>Effetti</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Clicca su un pad o una voicing box per riprodurre il suono',
    midi: 'MIDI',
    midi_detect: 'Rilevamento automatico dei dispositivi compatibili WebMIDI',
    midi_push: 'Supporto per l\'uscita MIDI seriale di Ableton Push',
    midi_chord: 'Identificazione automatica degli accordi dalle note suonate',
    midi_sustain: '<strong>Pedale sustain</strong> \u2014 Supporto MIDI CC64 (Hold Pedal)',
    color_title: 'Legenda colori',
    color_root: '<strong>Root</strong> \u2014 Nota fondamentale',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Note della scala / Note dell\'accordo',
    color_char: '<strong>Caratteristica</strong> \u2014 Note che definiscono la scala/l\'accordo',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (terza)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (settima)',
    color_tension: '<strong>Tension</strong> \u2014 Note di tensione',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota della scala un semitono sopra una nota dell\'accordo (in modalità Chord)',
    color_palette: 'Palette colori: Okabe-Ito (accessibile per daltonici)',
    input_title: 'Ingresso Guitar / Piano',
    input_desc1: 'Clicca sulla tastiera della chitarra o del pianoforte per inserire le note',
    input_desc2: 'Gli accordi vengono identificati automaticamente dall\'input e riflessi sul pad',
    input_desc3: '<strong>Clear</strong> \u2014 Cancella input, <strong>Play \u25B6</strong> \u2014 Riproduci le note inserite',
    input_title: 'Input Mode',
    input_desc1: 'Clicca liberamente sui pad per selezionare le note \u2192 Identificazione accordi in tempo reale',
    input_desc2: 'Senza filtro teorico. Esplora \u2192 scopri \u2192 impara la teoria dopo',
    input_desc3: 'Quando viene rilevato un accordo, etichette di grado (R, 3, 5, b7, ecc.) appaiono sui pad. Chitarra, basso, pianoforte e pentagramma si aggiornano automaticamente',
    input_memory: '<strong>Memory</strong> \u2014 Salva e richiama accordi in 16 slot',
    input_banks: '<strong>Banks</strong> \u2014 16 slot \u00D7 fino a 16 banchi. Cambia con <kbd>[</kbd> <kbd>]</kbd>. Duplicazione e rinomina supportate',
    input_export: '<strong>MIDI Export</strong> \u2014 Esporta gli accordi in memoria come file MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> pulsante o tasto <kbd>p</kbd> per cambiare',
    perform_desc1: 'Suona gli accordi dei Memory Slot in tempo reale con un layout a 16 pad',
    perform_desc2: 'Attiva tramite tastiera (griglia 4\u00D74) o pad MIDI',
    perform_desc3: 'Trascina e rilascia gli Slot per riordinare',
    shortcut_title: 'Scorciatoie da tastiera',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Selezionare accordo diatonico (scale a 7 note)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Selezionare voicing box (scorrere le alternative)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Scorrere i rivolti (modalità Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica della fondamentale',
    sc_omit: '<kbd>o</kbd> \u2014 Attivare/disattivare Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Attivare/disattivare Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclare Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclare Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: "<kbd>v</kbd> — Motore Guitar ON/OFF (mostra il voicing chitarra selezionato sulla griglia a 64 pad)",
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Ciclare posizione chitarra (precedente / successivo)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Cambiare posizione del basso (precedente / successivo)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Cancella accordo (modalità Chord)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clic per attivare/disattivare nota \u2014 il costruttore si aggiorna automaticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Avviare Capture / salvare nello slot successivo',
    sp_end: '<kbd>e</kbd> \u2014 Terminare Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Richiamare slot di memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Trasposizione cromatica (tutte le note \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Rivolto (più bassa \u21911ott / più alta \u21931ott)',
    sp_clear: '<kbd>x</kbd> \u2014 Cancella tutto',
    sp_transfer: '<b>Chord switch</b> \u2014 Trasferire l\'accordo rilevato in modalità Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Griglia 4\u00D74 attiva Slot 1\u201316',
    pf_midi: 'I pad MIDI (note 36\u201354) attivano anche gli Slot',
    shortcut_common: 'Comune (tutte le modalit\u00E0)',
    sc_perform: '<kbd>p</kbd> \u2014 Attivare/disattivare la vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Annulla Memory Slot (fino a 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Salvare accordo / voicing attuale in un Memory Slot',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Salvare accordo / voicing attuale in un Memory Slot',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 Salvare direttamente in un Memory Slot',
    sc_space: '<kbd>Space</kbd> \u2014 Riprodurre accordo attuale',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselezionare voicing box / chiudere la guida',
    sc_help: '<kbd>?</kbd> \u2014 Mostrare/nascondere la guida',
    sc_slash: '<kbd>/</kbd> \u2014 Attiva input testuale accordo',
    sc_tasty_nav: "<kbd>z</kbd> / <kbd>x</kbd> — Voicing TASTY/STOCK/Guitar prec/succ",
    shortcut_display: 'Toggle visualizzazione (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitar',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Bass',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Circle of Fifths',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Staff',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Input testuale',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Tonalità',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 Intestazione / Barra info',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: 'Mostra suggerimenti all\'avvio',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Blocca in Do maggiore',
    color_coding_toggle: 'Colora le note caratteristiche',
    c_fixed_tip: 'Il pad mostra sempre la scala di Do maggiore, indipendentemente da Key/Scale/Chord.',
    push_voicing_toggle: 'Voicing overview',
    layout: 'Disposizione',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Caratteristica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
  },
  ui: {
    close: 'Chiudi',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Salva impostazioni',
    sound_hint: 'Seleziona un preset audio per attivare il suono',
    tap_to_start: 'Tocca per attivare il suono',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: 'Tocca un pad per suonare!',
    load_vst: 'Carica plugin VST/AU...',
    affiliate_label: '',
    staff: 'Spartito',
    circle: 'Circolo',
    help: 'Guida',
    view_settings: 'Impostazioni vista',
    view_focus: 'Vista',
    view_layout: 'Layout',
    view_all: 'Tutti i pannelli',
    view_pad: 'Solo pad',
    view_chord: 'Solo chord builder',
    view_info: 'Solo info / memoria',
    layout_abc: 'Pad → Accordo → Circolo',
    layout_acb: 'Pad → Circolo → Accordo',
    layout_bac: 'Accordo → Pad → Circolo',
    layout_bca: 'Accordo → Circolo → Pad',
    layout_cab: 'Circolo → Pad → Accordo',
    layout_cba: 'Circolo → Accordo → Pad',
    view_setup_note: 'Nella versione Desktop, Push 3 Setup apre anche questa schermata. Jog Wheel sinistra/destra seleziona vista o layout, ruotando cambia il valore, e premendo Jog Wheel o Setup si chiude.',
    oct_down: 'Abbassa di un\'ottava',
    oct_up: 'Alza di un\'ottava',
    toggle_guitar: 'Mostra/nascondi tastiera chitarra (⌘⌥G)',
    toggle_bass: 'Mostra/nascondi tastiera basso (⌘⌥B)',
    toggle_piano: 'Mostra/nascondi tastiera pianoforte (⌘⌥P)',
    mode_scale: 'Modalit\u00E0 Scale \u2014 visualizza le note della scala sui pad (Tab per cambiare)',
    mode_chord: 'Modalit\u00E0 Chord \u2014 costruisci accordi con voicing (Tab per cambiare)',
    mode_input: 'Modalit\u00E0 Input \u2014 tocca i pad liberamente per rilevare accordi (Tab per cambiare)',
    play_chord: 'Riproduci accordo corrente (Space)',
    toggle_staff: 'Mostra/nascondi pentagramma (⌘⌥S)',
    toggle_circle: 'Mostra/nascondi circolo delle quinte (\u2318\u2325F)',
    toggle_sound: 'Mostra/nascondi controlli del suono',
    sound_mute: 'Suono ON/OFF',
    sound_expand: 'Mostra/nascondi impostazioni audio dettagliate',
    input_keys_disabled: 'La selezione della tonalit\u00E0 non \u00E8 usata in modalit\u00E0 Input',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
    chord_input: 'Inserisci accordo',
    chord_hint: 'Tensioni tra ( ): C7(b9,#11) | dim, h=m7♭5 supportati',
    key_hint: 'Configurabile anche dal modo Scale o dal Circolo delle Quinte',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Il mio Blog',
    guide: 'Guida',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Premi Capture per iniziare a costruire accordi',
    status_capturing: 'Cattura: Slot {slot}/16 \u2014 Clicca sui pad, poi Capture per salvare',
    status_editing: 'Modifica: Slot {slot} \u2014 Clicca sui pad per modificare',
    notes_label: 'Note: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    memory_full: 'Memory Slot pieni',
    no_current_chord: 'Nessun accordo attuale da salvare',
    slot_selected: 'Slot {slot} selezionato',
    slot_cleared: 'Slot {slot} cancellato',
    undo: 'Annulla',
    settings_saved: 'Impostazioni salvate',
    no_chords: 'Nessun accordo negli slot di memoria',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    note_count: '{n} note',
    default: 'Passa il mouse su un controllo per vedere cosa fa',
    mode_scale: 'Scale Mode \u2014 Visualizza le note della scala sulla griglia di 64 pad [Tab]',
    mode_chord: 'Chord Mode \u2014 Costruisci accordi passo passo: Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Input Mode \u2014 Tocca i pad liberamente, gli accordi vengono rilevati automaticamente [Tab]',
    guitar: 'Attiva/disattiva tastiera chitarra [\u2318\u2325G]',
    bass: 'Attiva/disattiva tastiera basso [\u2318\u2325B]',
    piano: 'Attiva/disattiva tastiera pianoforte [\u2318\u2325P]',
    link_mode: 'Link Mode \u2014 le note suonate si sincronizzano su tutti gli strumenti in tempo reale [\u2318\u2325L]',
    staff: 'Attiva/disattiva pentagramma [\u2318\u2325S]',
    circle: 'Circle of Fifths \u2014 Tonica, Sottodominante, Dominante mostrate con colori corrispondenti [\u2318\u2325F]',
    cof_major: 'Anello esterno \u2014 seleziona tonalità maggiore',
    cof_minor: 'Anello interno \u2014 seleziona tonalità minore',
    cof_natural: 'Minore naturale',
    cof_harmonic: 'Minore armonica',
    cof_melodic: 'Minore melodica',
    sound: 'Attiva/disattiva pannello controlli audio [\u2318\u2325A]',
    memory: 'Attiva/disattiva pannello Memory Slot \u2014 salva/richiama accordi in 16 slot [\u2318\u2325M]',
    sect_key: 'Attiva/disattiva visualizzazione tonalità',
    sect_input: 'Attiva/disattiva input testuale accordo [\u2318\u2325T]',
    sect_quality: 'Attiva/disattiva selettori Root/Quality/Tension [\u2318\u2325Q]',
    sect_voicing: 'Attiva/disattiva controlli voicing (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Digita il nome dell\'accordo direttamente \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Mostra le scale disponibili per l\'accordo corrente. Gli slash chords con basso non appartenente all\'accordo vengono reinterpretati dalla nota di basso',
    sort_practical: 'Ordinamento pratico \u2014 dà priorità alle scale più usate. Include scale per dominanti secondarie (es. Mixolydian b13 per V7/ii)',
    sort_diatonic: 'Ordinamento diatonico \u2014 ordina per distanza teorica dalla tonalità corrente',
    omit5: 'Rimuovi la 5\u00AA dal voicing [O]',
    rootless: 'Rimuovi la fondamentale [R]',
    omit3: 'Rimuovi la 3\u00AA dal voicing',
    shell137: 'Shell voicing: Root-3rd-7th [S]',
    shell173: 'Shell voicing: Root-7th-3rd [S]',
    shell_off: 'Disattiva shell voicing [S]',
    shell_ext: 'Aggiungi note allo shell voicing (+1 o +2 note dell\'accordo)',
    inv_root: 'Posizione fondamentale [\u2193]',
    inv: 'Rivolto [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 voicing raffinati ordinati per nota superiore. Funziona con \u25B37, m7, 7 (esclusiva HPS) [T]',
    tasty_nav: 'Cicla variazioni [Z / X]',
    stock: 'Stock Voicing \u2014 voicing pianistici comuni (esclusiva HPS) [K]',
    stock_nav: 'Cicla variazioni [Z / X]',
    root_notation: 'Alterna tra notazione \u266F e \u266D',
    root_grid: 'Seleziona nota fondamentale',
    quality_grid: 'Seleziona qualità dell\'accordo (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Aggiungi tensioni all\'accordo (9, b9, #9, 11, #11, 13, b13) \u2014 selezione multipla',
    diatonic: 'Accordi diatonici della scala corrente \u2014 clicca per entrare in Chord mode [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Confronta gli accordi diatonici di minore armonica e melodica affiancati [\u2318\u2325N]',
    parallel_key: 'Tonalità parallela \u2014 Mostra diatonici maggiore/minore per la stessa fondamentale. Vedi l\'origine degli accordi presi in prestito [\u2318\u2325R]',
    secdom: 'Dominante secondaria \u2014 Mostra V7 che risolvono su ogni accordo diatonico. Clicca per visualizzazione automatica Available Scale [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: 'In modalità Input, cattura i tocchi sui pad nei Memory Slot in sequenza [C]',
    capture_current: 'Salva accordo / voicing TASTY / STOCK / Guitar attuale in un Memory Slot [Shift+C]',
    capture_end: 'Termina la cattura e salva nello slot corrente [E]',
    save: 'Salva tutte le impostazioni correnti (tonalità, scala, suono, memoria, layout)',
    tutorial: 'Tutorial interattivi \u2014 impara le basi passo dopo passo',
    help: 'Apri la finestra di aiuto con riferimento completo delle scorciatoie [?]',
    affiliate: 'Acquistando tramite questi link supporti lo sviluppo\u2026',
    lang: 'Cambia lingua di visualizzazione',
    octave: 'Sposta l\'estensione di ottava dei pad \u2014 Push/Launchpad possono controllare anche tramite pulsanti ottava',
    play: 'Riproduci l\'accordo corrente [Space]',
    scale_select: 'Seleziona una scala',
    chord_key: 'Alterna tra tonalità maggiore e minore',
    chord_key_picker: 'Apri selettore tonalità per cambiare tonalità senza passare a Scale mode',
    builder_clear: 'Cancella l\'accordo corrente e ricomincia [X]',
    builder_back: 'Annulla l\'ultimo passaggio nella costruzione dell\'accordo [\u232B]',
    slash_chord: 'Slash chord (on chord)',
    guitar_diagram: 'Voicing chitarra comuni riflessi quando un accordo è selezionato nel costruttore',
    guitar_label: 'Attiva/disattiva nomi note sulla tastiera chitarra',
    genre_preset: 'Cambia genere voicing chitarra \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: 'Cicla posizioni voicing chitarra/basso [, .]',
    to_pad: 'Rifletti il voicing chitarra/stock sulla griglia di 64 pad [V]',
    inst_clear: 'Cancella le note inserite sul diagramma strumentale',
    inst_play: 'Riproduci le note inserite sul diagramma strumentale',
    plain_clear: 'Cancella tutte le note in Input mode [X]',
    midi_export: 'Esporta tutti gli slot di memoria come file MIDI per il tuo DAW',
    chs_export: 'Esporta tutti gli slot di memoria in formato CHS (Clover Chord Systems)',
    midi_import: 'Importa un file MIDI negli slot di memoria',
    chs_import: 'Importa un file CHS negli slot di memoria',
    midi_device: 'Seleziona ingresso MIDI',
    midi_panic: 'All Notes Off \u2014 ferma qualsiasi nota MIDI bloccata',
    sound_mute: 'Suono ON/OFF',
    sound_preset: 'Seleziona preset audio',
    volume: 'Volume master',
    sound_fx: 'Effetti \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 il filtro si apre/chiude su ogni nota. Tipo LP/BP, pendenza 2P/4P',
    velocity: 'Curva di velocità',
    mem_view: 'Vista memoria \u2014 salva e organizza accordi in 16 slot [M]',
    perform_view: 'Vista Perform \u2014 suona gli accordi salvati in tempo reale con 16 pad [P]',
    bank: 'Banchi di memoria \u2014 16 slot \u00D7 fino a 16 banchi. [ ] per cambiare',
    slot_save: 'Salva l\'accordo corrente nello slot selezionato',
    play_slots: 'Riproduci tutti gli accordi salvati in sequenza',
    locut: 'Lo-cut \u2014 Rimuove le basse per chiarezza (casella ON/OFF, slider = frequenza di taglio)',
    hicut: 'Hi-cut \u2014 Rimuove le alte per un tono pi\u00F9 rotondo (casella ON/OFF, slider = frequenza)',
    drive: 'Drive \u2014 Quantit\u00E0 di overdrive. Pi\u00F9 alto = pi\u00F9 distorsione',
    tremolo: 'Profondit\u00E0 di tremolo \u2014 Profondit\u00E0 di modulazione d\'ampiezza (modellazione fisica Peterson + CdS)',
    tremolo_speed: 'Velocit\u00E0 di tremolo \u2014 Frequenza di modulazione (Hz)',
    phaser: 'Phaser \u2014 Sweep con sfasamento',
    flanger: 'Flanger \u2014 Delay molto breve, sweep metallico',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Tipo filtro \u2014 LP=Passa-basso / BP=Passa-banda',
    af_poles: 'Pendenza \u2014 2P=12dB/oct (dolce) / 4P=24dB/oct (ripida)',
    af_depth: 'Depth \u2014 Ampiezza di apertura/chiusura del filtro',
    af_decay: 'Decay \u2014 Velocit\u00E0 di chiusura del filtro (minore = pi\u00F9 veloce)',
    af_q: 'Q \u2014 Risonanza (nitidezza del picco)',
    af_wet: 'WET \u2014 Quantit\u00E0 dell\'effetto (0 = totalmente dry, 10 = totalmente wet)',
    af_vol: 'VOL \u2014 Trim di uscita (abbassa se l\'ampli distorce)',
    eq_bass: 'Baxandall Bass \u2014 EQ shelving bassi. Centro = piatto',
    eq_treble: 'Baxandall Treble \u2014 EQ shelving alti. Centro = piatto',
    reverb_type: 'Tipo di reverb \u2014 Spring (coda ondulata stile Twin) / Plate (coda densa metallica)',
    reverb_amount: 'Quantit\u00E0 reverb \u2014 Mix segnale wet',
    reverb_decay: 'Decay reverb \u2014 Lunghezza della coda',
    reverb_stereo: 'Stereo \u2014 ON distribuisce reverb su L/R',
    reverb_dwell: 'Dwell \u2014 Drive d\'ingresso al serbatoio a molla',
    vel_thresh: 'Soglia di velocity \u2014 Colpi pi\u00F9 deboli trattati come velocity minima',
    vel_drive: 'Velocity Drive \u2014 Inclinazione della curva (positivo = accentua, negativo = appiattisce)',
    vel_compand: 'Compand \u2014 Comprime/espande attorno alla velocity media',
    vel_range: 'Range \u2014 Limite massimo di velocity',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Seleziona la fondamentale',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'Tutti i dispositivi',
  },
  memory: {
    slot_empty: 'Slot {slot}: Vuoto',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Clicca per rinominare',
    rename: 'Rinomina',
    duplicate: 'Duplica',
    delete: 'Elimina',
    rename_prompt: 'Nome del banco:',
    confirm_delete: 'Eliminare "{name}"?',
    limit_reached: 'Massimo 16 banchi',
    cannot_delete_last: 'Impossibile eliminare l\'ultimo banco',
  },
  diatonic: {
    parallel: 'Tonalità parallela',
    relative: 'Relativa',
    harm_mel: 'Harm/Mel',
    secdom: 'Dominante secondaria',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostra tutto',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guida',
    tagline: 'Uno strumento nel browser per esplorare scale, accordi e voicings su una griglia di 64 pad.<br>Non serve alcuna sorgente sonora \u2014 basta Chrome.',
    cta: 'Apri App',
    features: 'Funzionalit\u00E0',
    feat_sound: '<strong>Nessuna sorgente sonora necessaria</strong> \u2014 Il suono viene riprodotto direttamente in Chrome. 4 preset organo + 8 preset pianoforte elettrico integrati. Effetti (drive, reverb, phaser, flanger, tremolo, lo cut, hi cut, auto filter) inclusi',
    feat_input: '<strong>Nessuna abilit\u00E0 sui pad richiesta</strong> \u2014 Costruisci accordi in 3 passaggi. Tensioni visualizzate. Clicca sui pad per inserire direttamente',
    feat_text_input: '<strong>Input testuale accordi</strong> \u2014 Premi "/" per digitare Cm7, G7(b9,#11), Am7/G ecc. direttamente. Autocompletamento. Abbreviazioni come dim, h(=m7\u266D5)',
    feat_detect: '<strong>Rilevamento accordi</strong> \u2014 Rilevamento del nome dell\'accordo in tempo reale dalle note cliccate. Supporta omit, accordi con basso diverso e candidati multipli',
    feat_instruments: '<strong>Visualizzazione Guitar / Bass / Keyboard</strong> \u2014 Mostra le note dell\'accordo sulla tastiera della chitarra, del basso e del pianoforte. L\'input dalla diteggiatura della chitarra si riflette automaticamente sui pad. In modalit\u00E0 Chord, le posizioni sono raggruppate per corda fondamentale',
    feat_scales: '<strong>Visualizzazione scale</strong> \u2014 31 scale \u00D7 12 tonalit\u00E0. Diatonica, minore armonica, minore melodica, pentatonica, Bebop e altro',
    feat_diatonic: '<strong>Visualizzazione accordi diatonici</strong> \u2014 Gli accordi diatonici della scala selezionata sono mostrati su una barra. Clicca o usa le scorciatoie per suonare subito. Alterna tra triadi e tetradi',
    feat_voicing: '<strong>Operazioni di voicing</strong> \u2014 Inversion, Drop 2/3, Shell Voicing, Omit, Rootless. Tasti freccia per i rivolti, pulsanti per diteggiature multiple',
    feat_memory: '<strong>Memoria accordi</strong> \u2014 Salva i tuoi accordi preferiti in 16 slot. Esporta come file MIDI per il tuo DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Suona gli accordi in memoria in tempo reale usando 16 pad o la tastiera del PC',
    feat_parent: '<strong>Ricerca inversa Available Scale</strong> \u2014 Trova le scale che contengono il tuo accordo. Vedi le Available Tensions a colpo d\'occhio. Alternanza Practical/Diatonic',
    feat_pivot: '<strong>Pensiero accordo pivot</strong> \u2014 Inserisci un accordo manualmente e la barra diatonica scompare, mostrando tutte le tonalit\u00E0 a cui il tuo accordo potrebbe appartenere. Ideale per l\'analisi della modulazione',
    feat_dimming: '<strong>Visualizzazione pratica delle Tensions</strong> \u2014 Per gli accordi di 7\u00AA non dominante, le tensioni poco comuni (b9, #9, b13, ecc.) sono attenuate. Ancora selezionabili',
    feat_circle: '<strong>Circle of Fifths</strong> \u2014 Mostra il circolo delle quinte. Collegato alla selezione della tonalità, mostrando accordi diatonici e funzioni (T/SD/D). Cambio di modo minore supportato',
    feat_banks: '<strong>Banchi di memoria</strong> \u2014 16 slot \u00D7 fino a 16 banchi. Cambia, duplica e rinomina i banchi. Tasti <kbd>[</kbd> <kbd>]</kbd> per cambiare',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro inviluppo (Auto-Wah). 3 tipi: Cry Baby / Mu-Tron / Moog. Regola frequenza, risonanza, sensibilità e decadimento',
    feat_drive: '<strong>Drive</strong> \u2014 Saturazione analogica. Aggiunge un caldo overdrive al suono',
    feat_clav: '<strong>Preset Clavinet</strong> \u2014 2 preset clavinet aggiunti a E.PIANO (Clav Muted, Clav Bright). Perfetti per il funk',
    feat_midi_sens: '<strong>Sensibilità velocity MIDI</strong> \u2014 Regolazione della curva di velocità a 4 parametri stile Push 3 (Threshold, Drive, Compand, Range). Visualizzazione curva in tempo reale. Funziona con tutti i controller MIDI',
    feat_push_oct: '<strong>Sincronizzazione ottava Push 3</strong> \u2014 I pulsanti ottava \u25B2\u25BC di Push 3 si sincronizzano automaticamente con lo spostamento di ottava dell\'app',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 lingue (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshot',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Seleziona una tonalit\u00E0 e una scala per vedere le note della scala colorate sulla griglia di 64 pad. Scegli gli accordi dalla barra diatonica.',
    ss_scale_alt: 'Scale Mode \u2014 Visualizzazione della scala di C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (arancione), note della scala (blu), note caratteristiche (giallo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Costruisci accordi in 3 passaggi: Root \u2192 Quality \u2192 Tension. Regola i voicing con Inversion, Drop, Shell e Omit. Usa il pannello Parent Scale per la ricerca inversa delle scale.',
    ss_chord_alt: 'Chord Mode \u2014 Visualizzazione dell\'accordo Dm7 con griglia delle tensioni',
    ss_chord_caption: 'Dm7 \u2014 Note dell\'accordo, 3rd (rosa), 7th (verde). Controlla le opzioni di disposizione nei voicing box',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Clicca liberamente sui pad per il rilevamento degli accordi in tempo reale. Comprendi gli accordi anche senza conoscere la teoria.',
    ss_input_alt: 'Input Mode \u2014 Rilevamento in tempo reale di C7',
    ss_input_caption: 'C7 \u2014 Clicca sui pad per rilevare automaticamente i nomi degli accordi. Candidati multipli mostrati',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Posiziona gli accordi salvati su 16 pad per suonare in tempo reale usando la tastiera o i pad MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 slot con accordi',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 salvati negli slot. Suona usando la griglia 4\u00D74 della tastiera',
    ss_parent: 'Available Scale + Accordo Pivot',
    ss_parent_desc: 'Ricerca inversa delle scale che contengono il tuo accordo. Alterna tra ordinamento Practical (per usabilit\u00E0) e Diatonic (per teoria). L\'inserimento manuale di accordi nasconde la barra diatonica per l\'analisi degli accordi pivot.',
    ss_parent_alt: 'Pannello Parent Scale e visualizzazione tastiera chitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), ecc. Available Tensions visualizzate',
    ss_parent_note: '\u203B Le scale pentatoniche/blues sono modali (approccio orizzontale) e appartengono a un sistema diverso dalla teoria delle scale per accordo (mappatura verticale), quindi non sono incluse in Available Scale. Nella pratica, la pentatonica \u00E8 spesso la prima scelta.',
    ss_velocity: 'Sensibilità velocity MIDI',
    ss_velocity_desc: 'Regola la sensibilità della velocità del controller MIDI con 4 parametri stile Push 3. Configura nella sezione VELOCITY SENSITIVITY nel pannello Sound. Visualizzazione curva in tempo reale.',
    ss_push_oct: 'Sincronizzazione pulsante ottava Push 3',
    ss_push_oct_desc: 'I pulsanti ottava \u25B2\u25BC di Push 3 (CC#55/CC#54) si sincronizzano automaticamente con lo spostamento di ottava dell\'app. Premi i pulsanti ottava su Push 3 e l\'ottava del display si aggiorna automaticamente.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Funzioni di Voicing esclusive HPS',
    ss_hps_voicing_intro: "I membri HPS hanno accesso a 3 strumenti di voicing. Scegli TASTY / STOCK / Guitar dentro il builder per mostrare automaticamente quel voicing sulla griglia a 64 pad.",
    ss_tasty: 'TASTY Voicing \u2014 Classificato per nota superiore',
    ss_tasty_desc: '129 voicing sofisticati visualizzati come array di gradi. Seleziona un accordo, premi <kbd>T</kbd> per attivare e premi di nuovo per scorrere i voicing. Selezione automatica della posizione ottimale sui pad.',
    ss_tasty_target: 'Obiettivo: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'L\'area info mostra l\'ordine di impilamento dei gradi (es.: <code>m9 (b3-b7-9-5-1)</code>). Questa \u00E8 la struttura del voicing \u2014 quali note sono impilate dal basso verso l\'alto.',
    ss_tasty_labels_title: 'Significato delle etichette',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Fondamentale (1\u00B0 grado) omessa. Comune nel jazz/R&B/neo-soul dove il bassista copre la fondamentale.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5\u00AA omessa. La 5\u00AA ha poco carattere tonale, quindi viene sostituita con una tensione per un suono pi\u00F9 ricco.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3\u00AA omessa. Si avvicina a un suono sus o Quartal.',
    ss_tasty_ops_title: 'Comandi',
    ss_stock: 'STOCK Voicing \u2014 Raccolta di Voicing per pianoforte',
    ss_stock_desc: "154 voicing per pianoforte da materiali didattici, visualizzati in notazione di gradi. Copre Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. I voicing selezionati appaiono automaticamente sulla griglia a 64 pad.",
    ss_stock_ops_title: 'Comandi',
    ss_guitar_pos: 'Guitar Position \u2014 Voicing per chitarra',
    ss_guitar_pos_desc: "Calcolo automatico delle posizioni degli accordi sulla tastiera della chitarra. La vista Guitar a sinistra è l’area strumento; Guitar dentro il builder è il motore di voicing per la griglia a 64 pad.",
    usecases: 'Casi d\'uso',
    uc1_q: '"Voglio trovare come disporre questo accordo sui pad"',
    uc1_a: '\u2192 Seleziona Root, Quality e Tension in modalit\u00E0 <span class="mode-badge chord">Chord</span> \u2192 Controlla le disposizioni nei voicing box',
    uc2_q: '"Voglio vedere una scala della mia lezione sui pad"',
    uc2_a: '\u2192 Seleziona tonalit\u00E0 e scala in modalit\u00E0 <span class="mode-badge scale">Scale</span>. 31 scale disponibili',
    uc3_q: '"Voglio creare una progressione di accordi per il mio DAW"',
    uc3_a: '\u2192 Salva gli accordi negli slot di memoria \u2192 MIDI Export per importare nel tuo DAW',
    uc4_q: '"A quale tonalit\u00E0 appartiene questo accordo?"',
    uc4_a: '\u2192 Ricerca inversa nel pannello Available Scale. Alterna tra ordinamento Practical/Diatonic',
    uc7_q: '"Voglio trovare accordi pivot per la modulazione"',
    uc7_a: '\u2192 Inserisci un accordo manualmente in modalit\u00E0 <span class="mode-badge chord">Chord</span>. La barra diatonica scompare e Available Scale mostra tutte le tonalit\u00E0 possibili',
    uc5_q: '"Voglio controllare le progressioni di accordi suonandole"',
    uc5_a: '\u2192 Salva gli accordi negli slot di memoria, poi suonali con un controller MIDI o la tastiera del PC',
    uc6_q: '"Voglio verificare un accordo di chitarra sui pad"',
    uc6_a: '\u2192 Clicca sulla tastiera della chitarra per inserire \u2192 Visualizzazione automatica sui pad \u2192 Nome dell\'accordo rilevato',
    uc8_q: '"Voglio imparare voicing professionali"',
    uc8_a: '\u2192 Costruisci un accordo in modalit\u00E0 <span class="mode-badge chord">Chord</span>, poi premi <kbd>T</kbd> per TASTY (classificazione per nota superiore) o <kbd>K</kbd> per STOCK (voicing pianoforte). Visualizza con notazione di gradi, salva in memoria ed esporta nel DAW',
    quickstart: 'Guida rapida',
    qs_modes: '3 modalit\u00E0',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Visualizza scale e accordi diatonici<br><span class="mode-badge chord">Chord</span> Costruisci accordi in 3 passaggi. Operazioni di voicing disponibili<br><span class="mode-badge input">Input</span> Clicca liberamente sui pad \u2192 Rileva automaticamente i nomi degli accordi',
    qs_first: 'Per iniziare',
    qs_step1: 'Scegli una tonalit\u00E0 (es. C)',
    qs_step2: 'Scegli una scala (es. Major) \u2192 Le note della scala appaiono sui pad',
    qs_step3: 'Clicca un accordo sulla barra diatonica (es. Dm7) \u2192 Note dell\'accordo visualizzate',
    qs_step4: 'Clicca sui pad per riprodurre i suoni. Cambia disposizione nei voicing box',
    qs_step5: 'Salva gli accordi preferiti con <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Scorciatoie da tastiera',
    qs_shortcuts_desc: 'Premi <kbd>?</kbd> per l\'elenco completo delle scorciatoie.<br><kbd>Space</kbd> per riprodurre accordo. <kbd>1</kbd>\u2013<kbd>7</kbd> per accordi diatonici, <kbd>\u2191</kbd><kbd>\u2193</kbd> per rivolti, <kbd>\u2190</kbd><kbd>\u2192</kbd> per movimento cromatico.<br>In Perform mode, usa <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> come griglia 4\u00D74.',
    footer_open: 'Apri 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Scopri di pi\u00F9 sul blog \u2192',
    header_icons: 'Icone dell\u2019intestazione',
    header_icons_desc: 'Tre pulsanti icona nell\u2019angolo in alto a destra.',
    icon_save: '<strong>\uD83D\uDCBE Salva</strong> \u2014 Salva le impostazioni correnti (suono, effetti, opzioni di visualizzazione, ecc.) nel browser. Ripristino automatico alla prossima visita',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Esplora 11 tutorial interattivi. Impara ogni funzione passo dopo passo',
    icon_help: '<strong>? Aiuto</strong> \u2014 Mostra scorciatoie da tastiera, cronologia versioni e descrizione dei modi. Si apre anche con il tasto <kbd>?</kbd>',
    sound_panel: 'Pannello audio',
    sound_panel_desc: 'Seleziona i preset audio e regola gli effetti. Clicca il pulsante \u25B6 per espandere il pannello.',
    sound_presets: 'Preset audio',
    sound_presets_desc: 'Il motore di modellazione fisica Rhodes (Clean DI) è il suono predefinito. Suona subito senza scaricare campioni. Usa la manopola VOICING per regolare il tono del pickup.',
    sound_effects: 'Effetti',
    sound_effects_desc: 'Trascina ogni manopola per regolare i valori.',
    fx_drive: 'Saturazione analogica. Distorsione calda',
    fx_locut: 'Filtro taglia-bassi. Rimuove bassi fangosi',
    fx_hicut: 'Filtro taglia-alti. Attenua alti aspri',
    fx_reverb: 'Riverbero. Aggiunge profondità spaziale',
    fx_phaser: 'Phaser. Modulazione avvolgente',
    fx_flanger: 'Flanger. Modulazione tipo jet',
    fx_tremolo: 'Tremolo. Modulazione periodica del volume',
    sound_autofilter: 'Auto-Filtro (Auto-Wah)',
    sound_autofilter_desc: 'Filtro a inviluppo. Regola FREQ, RESO, SENS e DECAY.',
    version_history: 'Cronologia delle versioni',
    vh_540: '<b>V5.4</b> \u2014 Physical modeling aggiornato. Aggiunti parametri del filtro (WET / VOL) e un preset esclusivo HPS (Pad Sensei MK1 AMP Vintage Envelope Filter)',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Modeling del preamp migliorato',
    vh_510: '<b>V5.1</b> \u2014 Aggiunto modo scala fissa Do maggiore',
    vh_500: '<b>V5.0</b> \u2014 Motore sonoro ed effetti autonomi. Spring Reverb (modellazione fisica) + Plate Reverb. Modello amplificatore Suitcase migliorato. Selettore tipo Reverb (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Suona istantaneamente all\'apertura (nessun download di campioni). Attiva/disattiva suggerimenti scorciatoie. Accordi diatonici NM/HM/MM per tonalit\u00E0 minori parallele. PU LEVEL e MECHANICAL aggiunti all\'E.PIANO MIXER. Miglioramenti nella visualizzazione del rilevamento accordi',
    vh_490: '<b>V4.9</b> \u2014 Motore di modellazione fisica Pad Sensei MK1',
    vh_497: '<b>V4.9.7</b> \u2014 Il tremolo ora \u00E8 modellato fisicamente. I membri HPS ottengono Pad Sensei MK1 Suitcase (catena amplificatore modellata fisicamente)',
    vh_3377: '<b>V3.37.7</b> \u2014 Revisione utente: correzione tonalità minore relativa, badge in Title Case, font sans-serif sui pad, toggle accessibili per daltonici (verde\u2192blu), pannello Sound aperto di default, correzione layout shift, overlay spotlight tutorial, supporto ottava Launchpad + tracciamento automatico ottava per tutti i controller MIDI',
    vh_340: '<b>V3.40</b> \u2014 Posizionamento compatto TASTY/Stock: layout ottimale automatico sulla griglia 64 pad. Pulsante "To Pad" rimosso. Box voicing nascosti durante modalit\u00E0 TASTY/Stock',
    vh_336: '<b>V3.36</b> \u2014 Motore voicing chitarra v2: preset di genere (Jazz/Bossa/Funk), tabella di riferimento (120 tipi \u00D7 12 tonalit\u00E0), assegnazione automatica delle dita con rilevamento del barr\u00E9',
    vh_335: '<b>V3.35</b> \u2014 Miglioramenti UX dei tutorial (revisione per principianti). Tutti i tooltip tradotti in 9 lingue. Guida: sezioni pannello audio e icone intestazione aggiunte',
    vh_333: '<b>V3.33</b> \u2014 Tutorial interattivi. 11 argomenti \u00D7 9 lingue. Suggerimenti contestuali alla prima interazione con ogni funzionalit\u00E0',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 voicing per pianoforte con tastiera specifica MIDI. Guida aggiornata con sezione funzioni di voicing HPS',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 voicing sofisticati ordinati per nota pi\u00F9 alta. Visualizzazione array di gradi + ottimizzazione automatica dell\u2019ottava. Solo membri HPS',
    vh_325: '<b>V3.25.0</b> \u2014 Voicing chitarra \u2192 riflesso su pad (tasto <kbd>V</kbd>). Cambio layout stile chitarra (1 nota per riga) / compatto. Filtro "Tutti" posizioni chitarra in primo piano',
    vh_324: '<b>V3.24</b> \u2014 Preset Clavinet aggiunti (2 in E.PIANO). Effetto Auto Filter (filtro inviluppo / auto-wah) aggiunto',
    vh_323: '<b>V3.23</b> \u2014 Input testuale accordi con autocompletamento. "/" per attivare, abbreviazioni (dim, h=m7\u266D5), ordinamento per tensioni',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Alternanza triade/tetrade diatonica. Posizioni chitarra/basso raggruppate per corda fondamentale',
    vh_37: '<b>V3.7</b> \u2014 Preservazione della posizione di voicing (mantenimento automatico della forma della diteggiatura nei movimenti cromatici). Griglia pad, pentagramma e rilevamento accordi durante la riproduzione. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 Riproduzione file MIDI \u2192 illuminazione pad (riproduzione timeline, visualizzazione nome accordo, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 preset EP. Interruttore Sound ON/OFF. Supporto iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilit\u00E0 velocit\u00E0 (4 parametri + visualizzazione curva). Supporto tasto ottava Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Pi\u00F9 banchi di memoria (16 slot \u00D7 fino a 16 banchi, cambiare/duplicare/rinominare)',
    vh_218: '<b>V2.18</b> \u2014 Salvataggio/ripristino automatico di tutte le impostazioni (tonalit\u00E0/scala/suono/MIDI/memoria)',
    vh_213: '<b>V2.13</b> \u2014 Sovrapposizione scala strumento (chitarra/basso/piano mostrano Available Scale). Etichette di grado sui pad. Riproduzione collegata all\u0027ottava',
    vh_27: '<b>V2.7</b> \u2014 Modalit\u00E0 aggiunta tensioni (sintesi accordi pad/chitarra/basso/tastiera \u2192 filtraggio Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, sovrapposizione scala sui pad)',
    vh_19: '<b>V1.9</b> \u2014 9 lingue',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 slot di memoria, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Modalit\u00E0 Plain, export MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Versione iniziale (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6ªR',
    root_5: '5ªR',
    root_4: '4ªR',
    root_3: '3ªR',
    root_2: '2ªR',
    open: 'Aperta',
    no_open: 'Senza aperte',
    all: 'Tutte',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'Su Pad',
    genre_default: 'Standard',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    'Premi C per salvare l\'accordo attuale in Memory',
    'Opt+1~V salva direttamente in uno slot (16 tasti: 1234 QWER ASDF ZXCV)',
    'Shift+Clic su uno slot Memory per eliminarlo',
    'Opt+Trascina per copiare uno slot',
    'Premi S per alternare Shell voicing (1-3-7 / 1-7-3)',
    'Shift+D alterna Drop 2 / Drop 3',
    'Shift+G mostra la tastiera della chitarra',
    '\u2318\u2325F mostra il Circolo delle Quinte',
    'Tab alterna i modi Scale / Chord / Input',
    'Spazio riproduce la scala o l\'accordo corrente',
    'Esporta tutti gli slot Memory come file MIDI',
    'Collega un controller MIDI per suonare i pad',
    'Frecce ↓↑ cambiano il rivolto dell\'accordo',
    'Premi R per voicing senza fondamentale',
    'Premi O per omettere la 5ª',
    'Shift+S mostra lo spartito',
    'L\'icona di salvataggio preserva le impostazioni tra sessioni',
    '[ ] cambia banchi Memory — gestisci più brani',
    'Modalità Perform: Attiva accordi con tastiera (1234 / QWER / ASDF / ZXCV) o pad MIDI',
    'Premi / in modalità Chord per digitare nomi di accordi (es: Cm7, G7(b9,#11))',
  ],
  tips_off: 'Non mostrare suggerimenti',
  whats_new: 'Novità',
  whats_new_497: 'Il tremolo ora \u00E8 modellato fisicamente! I membri HPS ottengono Pad Sensei MK1 Suitcase.',
  whats_new_61: 'Il manuale online è ora accessibile dalla Guida. Attualmente in costruzione.',
  whats_new_123: 'Il manuale online è ora accessibile dalla Guida. Attualmente in costruzione.',
  whats_new_51: 'Aggiunta modalità Do maggiore bloccata! Attivala da Aiuto (?). Push/Launchpad mostrerà sempre Do maggiore.',
  whats_new_50: 'Riverberi spring e plate aggiunti! Baxandall Bass/Treble EQ, amp Suitcase migliorato.',
  whats_new_32427: 'Voicing chitarra \u2192 riflesso su pad (tasto V). Cambio layout stile chitarra / compatto',
  whats_new_33000: 'Sistema tutorial! Clicca l\'icona del libro nell\'intestazione per imparare Scale mode, Chord mode e altro.',
  whats_new_640: 'V6.4.0 è disponibile: rilevamento di tre tensioni, analisi UST, visualizzazione Note/Degree e scrittura # / b in base alla tonalità.',
  whats_new_650: 'V6.5.0 è disponibile: i voicing HPS TASTY / STOCK / Guitar ora sono dentro il Chord Builder. La famiglia di sesta usa C6(9) / C6(9,#11), con filtri chitarra, bilanciamento visivo e intervallo di playback migliorati.',
  whats_new_660: 'V6.6.0 è disponibile: i membri HPS ottengono voicing modali per quarte (So What) in TASTY — il suono di Miles Davis / McCoy Tyner — per accordi minori, maggiori e dominanti. È stato riordinato anche il layout dei tipi di accordo nel Chord Builder.',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Preset audio',
    sound_msg: 'Scegli un preset audio e tocca un pad per ascoltarlo.\nORGAN e E.PIANO \u2014 ognuno ha diversi preset.',
    sound_done: 'Suona bene! Premi Avanti per continuare.',
    midi_title: 'Controller MIDI',
    midi_msg: '\u00C8 stato rilevato un controller MIDI. Seleziona il tuo dispositivo dal menu a tendina.\nLa sensibilit\u00E0 della velocit\u00E0 pu\u00F2 essere regolata nel pannello Sound.',
    midi_no_device: 'Nessun controller MIDI rilevato \u2014 nessun problema.\nPuoi usare i clic sui pad, l\u0027input chitarra/basso/piano o l\u0027input testuale di accordi.',
    input_title: 'Tre modalit\u00E0',
    input_msg: 'Scale \u2014 visualizza le note della scala sulla griglia di 64 pad\nChord \u2014 costruisci accordi con voicing, rivolti e tensioni\nInput \u2014 tocca i pad liberamente per rilevare i nomi degli accordi\n\nCambia con Tab o i pulsanti di modalit\u00E0 sopra.',
    instruments_title: 'Input strumentale',
    instruments_msg: 'Chitarra, Basso, Piano \u2014 attiva ogni visualizzazione e clicca per inserire note direttamente.\nClic sulla tastiera \u2192 rilevamento accordo \u2192 "Su Pad" (V) per convertire nel layout dei pad.\nInput testuale: premi / in modalit\u00E0 Chord per digitare nomi di accordi (es. Cm7, G7(b9,#11)).',
    done_title: 'Pronto!',
    done_msg: 'Tutto pronto. Esplora liberamente \u2014 premi ? per l\u0027elenco completo delle scorciatoie.\nLa Guida contiene screenshot, video e casi d\u0027uso.',
    next: 'Avanti',
    skip_step: 'Avanti',
    skip_all: 'Salta tutorial',
    open_guide: 'Apri Guida',
    close: 'Inizia',
    reset: 'Riavvia tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    btn_label: 'Tutorial',
    // Selector UI
    selector_title: 'Tutorial',
    cat_getting_started: 'Per iniziare',
    cat_features: 'Funzionalità',
    cat_advanced: 'Avanzato',
    steps_label: 'passaggi',
    reset_all: 'Reimposta tutti i progressi',
    close_selector: 'Chiudi',
    hint_available: 'Tutorial disponibile',
    hint_try: 'Provalo',
    // Shared action labels
    next: 'Avanti',
    skip_step: 'Avanti',
    skip_all: 'Salta tutorial',
    open_guide: 'Apri Guida',
    close: 'Fine',
    // Onboarding
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: 'Prima volta qui? Vuoi un tour rapido dell\u0027app?',
    onboarding_yes: 'Avanti',
    onboarding_no: 'Salta',
    onboarding_title: 'Primi passi',
    onboarding_desc: 'Impara le basi di 64 Pad Explorer',
    onboarding: {
      sound_title: 'Preset audio',
      sound_msg: 'Scegli un preset audio e tocca un pad per ascoltarlo.\nORGAN e E.PIANO — ognuno ha diversi preset.',
      sound_done: 'Suona bene! Premi Avanti per continuare.',
      midi_title: 'Controller MIDI',
      midi_msg: 'È stato rilevato un controller MIDI. Push 3 e Launchpad funzionano subito — nessuna configurazione necessaria.\nLa sensibilità della velocità può essere regolata nel pannello Sound.',
      midi_no_device: 'Nessun controller MIDI rilevato — nessun problema.\nPuoi usare i clic sui pad, l\'input chitarra/basso/piano o l\'input testuale di accordi.',
      input_title: 'Tre modalità',
      input_msg: 'Scale — visualizza le note della scala sulla griglia di 64 pad\nChord — costruisci accordi con voicing, rivolti e tensioni\nInput — tocca i pad liberamente per rilevare i nomi degli accordi\n\nCambia con Tab o i pulsanti di modalità sopra.',
      instruments_title: 'Input strumentale',
      instruments_msg: 'Chitarra, Basso, Piano — attiva ogni visualizzazione e clicca per inserire note direttamente.\nClic sulla tastiera → rilevamento accordo → "Su Pad" (V) per convertire nel layout dei pad.\nInput testuale: premi / in modalità Chord per digitare nomi di accordi (es. Cm7, G7(b9,#11)).',
      done_title: 'Pronto!',
      done_msg: 'Tutto pronto. Esplora liberamente — premi ? per l\'elenco completo delle scorciatoie.\nLa Guida contiene screenshot, video e casi d\'uso.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Scale Mode',
    scale_mode_desc: 'Esplora le scale sulla griglia di 64 pad',
    scale_mode: {
      step1_title: 'Passa a Scale Mode',
      step1_msg: 'Scale mode mostra le note della scala illuminate sulla griglia dei pad.\nTocca un pad illuminato per ascoltare la nota.',
      step2_title: 'Scegli una tonalità',
      step2_msg: 'Seleziona una tonalità fondamentale. La griglia si aggiorna istantaneamente.\nProva a passare tra C, G, F — ascolta come cambia il pattern dei colori.',
      step3_title: 'Scegli una scala',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 scale disponibili. I pad si aggiornano in tempo reale.',
      step4_title: 'Diatonic Bar',
      step4_msg: 'Gli accordi diatonici della scala scelta appaiono qui.\nClicca qualsiasi accordo per passare a Chord mode con quel voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Chord Mode',
    chord_mode_desc: 'Costruisci accordi passo dopo passo',
    chord_mode: {
      step1_title: 'Passa a Chord Mode',
      step1_msg: 'Chord mode offre due modi per selezionare accordi.\n① Scegli dalla barra diatonica con un clic\n② Costruisci il tuo: Root → Quality → Tension',
      step_key_title: 'Selezione tonalità',
      step_key_msg: 'Imposta la tonalità della scala. Quando una tonalità è impostata, la barra diatonica mostra gli accordi e la disponibilità delle tensioni viene filtrata.\nPuoi anche costruire accordi liberamente dalla Root senza usare una tonalità.',
      step_diatonic_title: 'Diatonic Bar',
      step_diatonic_msg: 'Accordi diatonici della tonalità selezionata.\nClicca per impostare istantaneamente un accordo con filtraggio delle tensioni basato sulla scala.',
      step2_title: 'Step 1: Root',
      step2_msg: 'Scegli una nota fondamentale. C, D, E... tutte le 12 tonalità.\nIl display mostra il tuo accordo corrente.',
      step3_title: 'Step 2: Quality',
      step3_msg: 'Scegli il tipo di accordo: Maj, min, 7, m7, dim, aug...\nLa griglia illumina le note dell\'accordo.',
      step4_title: 'Step 3: Tensions',
      step4_msg: 'Scegli prima una Quality \u2014 i pulsanti Tension appaiono automaticamente.\n9, b9, #9, 11, #11, 13, b13. Si possono selezionare pi\u00F9 tensioni.',
      step5_title: 'Input testuale',
      step5_msg: 'Digita i nomi degli accordi direttamente con il tasto /.\nSlash chords e voicing complessi possono essere inseriti rapidamente.',
      step6_title: 'Trovare le scale per la dominante secondaria',
      step6_msg: 'Inserisci direttamente un accordo non diatonico.\nEsempio: Input G7 → Available Scale mostra "Mixolydian", "Mixolydian b13", ecc.\nPassate a Practical sort per le scale più utili prima.\nCosì trovi la scala giusta per le dominanti secondarie.',
      step7_title: 'Slash Chords',
      step7_msg: 'Clicca / nel costruttore di accordi per inserire una nota di basso per Slash Chords.\nPuoi anche digitare C/D o F△7/G nell\'input testuale.\nAvailable Scale si aggiorna per corrispondere allo Slash Chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Input Mode',
    input_mode_desc: 'Inserisci accordi da controller MIDI, pad, manico o tastiera',
    input_mode: {
      step1_title: 'Passa a Input Mode',
      step1_msg: 'Inserisci accordi tramite controller MIDI, cliccando sui pad, dal manico o dalla tastiera.\nIl rilevamento degli accordi funziona in tutte le modalità.',
      step2_title: 'Tocca alcuni pad',
      step2_msg: 'Clicca qualsiasi pad sulla griglia.\nOgni tocco attiva o disattiva una nota.',
      step3_title: 'Rilevamento accordi',
      step3_msg: 'Il nome dell\'accordo rilevato appare sopra la griglia.\nEtichette di grado (R, 3, 5, b7...) appaiono su ogni pad.',
      step4_title: 'Salva con Capture',
      step4_msg: 'Il tasto <strong>C</strong> salva l\u0027accordo corrente nel prossimo slot di memoria.\nCostruisci progressioni di accordi una alla volta.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Diatonic Bar',
    diatonic_desc: 'Accesso con un clic agli accordi diatonici',
    diatonic: {
      step1_title: 'La Diatonic Bar',
      step1_msg: 'Ogni scala ha il suo set di accordi diatonici.\nAppaiono qui — pronti da suonare.',
      step2_title: 'Triade / Tetrade',
      step2_msg: 'Alterna tra triadi a 3 note e accordi di settima a 4 note.\nLa barra si aggiorna istantaneamente.',
      step3_title: 'Clicca un accordo',
      step3_msg: 'Clicca un accordo sulla barra.\nPuoi trasformarlo con tensioni e altro nel Chord Builder.',
      step4_title: 'Scorciatoia da tastiera',
      step4_msg: 'Premi 1–7 per selezionare accordi diatonici istantaneamente.\nNiente mouse necessario.',
      step5_title: 'Dominante secondaria',
      step5_msg: 'Attiva "Secondary Dominant" (\u2318\u2325D).\nVengono mostrati gli accordi V7 che risolvono su ogni accordo diatonico.\nClicca uno e Available Scale si visualizza automaticamente.\nRisoluzione maggiore \u2192 Mixolydian. Risoluzione minore \u2192 HMP5\u2193/Altered.',
      step6_title: 'Scorciatoie da tastiera',
      step6_msg: 'Premi 1\u20137 per accordi diatonici.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Tonalità parallela) per barre di estensione.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Salva accordi e suonali dal vivo',
    memory: {
      step1_title: 'Salva un accordo',
      step1_msg: 'Salva i tuoi accordi preferiti.\nSalvare i voicing che ti piacciono aiuta nel beat-making e nella pratica.',
      step2_title: '16 slot di memoria',
      step2_msg: 'Funziona come un layout Drumrack a 16 pad su PUSH, Launchpad, MPC e Maschine \u2014 intuitivo da usare.',
      step3_title: 'Banchi di memoria',
      step3_msg: 'Su PUSH e Launchpad, il layout Drumrack rende l\u0027uso intuitivo.',
      step4_title: 'Perform Mode',
      step4_msg: 'Anche i tasti della tastiera del PC corrispondono ai 16 pad.',
      step5_title: 'MIDI Export',
      step5_msg: 'Esporta tutti gli accordi in memoria come file MIDI.\nTrascinali nel tuo DAW e inizia a produrre.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Modella i voicing dei tuoi accordi',
    voicing: {
      step1_title: 'Controlli Voicing',
      step1_msg: 'In modalit\u00E0 Chord Builder, sono possibili diverse trasformazioni dalla forma base.\nOmit, Shell, Inversion, Drop \u2014 tutto qui.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> \u00E8 per Shell voicing. Impara i voicing R37 e R73 in modo fluido sul pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'I tasti scorciatoia sono spesso impostati come mnemonici.\n<strong>O</strong>mit = ometti la 5\u00AA. <strong>R</strong>ootless = voicing senza fondamentale.',
      step4_title: 'Rivolti',
      step4_msg: 'A differenza della maggior parte dei software, puoi creare rivolti in modo ultra-rapido.\nAiuta anche a capire gli slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Per quando vuoi mettere in evidenza la nota superiore \u2014\nAnche i Drop voicing sono supportati.',
      step6_title: 'Voicing Box',
      step6_msg: 'I pad possono avere pi\u00F9 opzioni di posizione. La Voicing Box gestisce questo.\nClicca a, b, c, d ecc. sul pad, o digita la lettera, per vedere pi\u00F9 possibilit\u00E0 di voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Preset, effetti e volume',
    sound: {
      step1_title: 'Preset audio',
      step1_msg: 'ORGAN (4 tipi) e E.PIANO (8 tipi).\nClicca un pad o usa il tuo controller MIDI.',
      step2_title: 'Pannello dettagli',
      step2_msg: 'Clicca ▼ per espandere il pannello dettagli del suono.\nEffetti, volume e controlli filtro sono qui.',
      step3_title: 'Effetti',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nRegolali nel pannello dettagli.',
      step4_title: 'Sound ON/OFF',
      step4_msg: 'Attiva e disattiva il suono con l\u0027icona dell\u0027altoparlante.\nDisattivarlo pu\u00F2 essere comodo quando usi una DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicing classificati per nota superiore. Solo membri HPS',
    tasty: {
      step1_title: 'Attiva TASTY',
      step1_msg: 'Seleziona voicing ricercati che la logica semplice da sola non pu\u00F2 produrre.\nPensare dalla nota superiore \u00E8 utile per arrangiamenti di archi e fiati.\n(Solo membri HPS)',
      step2_title: 'Sfoglia le ricette',
      step2_msg: 'Tasti Z / X per sfogliare i voicing avanti/indietro.\nIl contatore mostra la posizione.',
      step3_title: 'Notazione di gradi',
      step3_msg: 'L\'area info mostra la pila dei gradi — es. m9 (b3-b7-9-5-1).\nQuesta è la struttura del voicing dal basso verso l\'alto.',
      step4_title: 'To Pad',
      step4_msg: 'Ottimizzazione dei pad che il software convenzionale non pu\u00F2 fare.\nGoditi il piacere di suonare voicing eleganti anche sui pad.',
      fb_step1_title: 'Cos\u0027\u00E8 TASTY Voicing?',
      fb_step1_msg: '129 voicing ricercati ordinati per nota superiore.\nSupporta Maj7 / Dom7 / Min7. Visualizzati in notazione di gradi.\nSolo membri HPS.',
      fb_step2_title: 'Come accedere a TASTY',
      fb_step2_msg: 'Disponibile quando ti unisci a HPS (Hardcore Pad Style).\nPremi T in Chord mode per attivare. Tasti Z/X per sfogliare i voicing.\nVedi la Guida per i dettagli.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicing idiomatici classici del pianoforte. Solo membri HPS',
    stock: {
      step1_title: 'Attiva STOCK',
      step1_msg: 'Conoscere i voicing specifici del pianoforte ti aiuta a liberarti dal suonare solo in forma base.\n154 voicing per pianoforte in notazione di gradi.\n(Solo membri HPS)',
      step2_title: 'Sfoglia i voicing',
      step2_msg: 'Tasti Z / X per sfogliare i voicing avanti/indietro.',
      step3_title: 'Vista tastiera',
      step3_msg: 'Attiva la visualizzazione Piano per vedere le posizioni reali dei tasti.\nIl voicing prende vita sulla tastiera.',
      step4_title: 'To Pad',
      step4_msg: 'Clicca "To Pad" per mappare il voicing nel layout dei pad.\nSalva in memoria ed esporta nel tuo DAW.',
      fb_step1_title: 'Cos\u0027\u00E8 STOCK Voicing?',
      fb_step1_msg: 'Presenta i voicing pianistici comunemente usati.\nLa notazione di gradi mostra la struttura.\nSolo membri HPS.',
      fb_step2_title: 'Come accedere a STOCK',
      fb_step2_msg: 'Disponibile quando ti unisci a HPS (Hardcore Pad Style).\nPremi K in Chord mode per attivare.\nVedi la Guida per i dettagli.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Circolo delle Quinte',
    circle_desc: 'Relazioni tra tonalità a colpo d\'occhio',
    circle: {
      step1_title: 'Apri il Circolo',
      step1_msg: 'Premi ⌘⌥F o clicca il pulsante Circle.\nIl circolo delle quinte appare sotto.',
      step2_title: 'Collegamento tonalit\u00E0',
      step2_msg: 'Controlla rapidamente accordi sostitutivi e diatonici importanti per la performance e la composizione.',
      step3_title: 'Funzioni diatoniche',
      step3_msg: 'A differenza del tipico circolo delle quinte, 64 Pad Explorer permette di selezionare 3 tipi di minore (Natural/Harmonic/Melodic) quando scegli una tonalit\u00E0 minore.\nRende pi\u00F9 facile padroneggiare le tonalit\u00E0 minori pi\u00F9 complesse.',
      step4_title: 'Selezionare una tonalità minore',
      step4_msg: 'L\'anello interno del circolo mostra le tonalità minori.\nClicca una tonalità nell\'anello interno per selezionare una tonalità minore.\nLa visualizzazione degli accordi diatonici cambierà.',
      step5_title: '3 tipi di scala minore',
      step5_msg: 'Quando è selezionata una tonalità minore, i pulsanti Nat / Harm / Mel appaiono al centro.\nNat = Natural Minor (forma standard)\nHarm = Harmonic Minor (V7 appare)\nMel = Melodic Minor (i gradi VI, VII cambiano)',
      step6_title: 'Prova a cambiare',
      step6_msg: 'Clicca Nat \u2192 Harm \u2192 Mel e osserva come cambiano gli accordi diatonici.\nNota come V7 appare in Harmonic Minor.',
    },
    // Guitar tutorial
    guitar_title: 'Diagramma chitarra',
    guitar_desc: 'Inserisci accordi dalla chitarra e riflettili sui pad',
    guitar: {
      step1_title: 'Mostra il manico della chitarra',
      step1_msg: 'Premi \u2318\u2325G o clicca il pulsante Guitar.\nLe note dell\'accordo appaiono sul manico.',
      step2_title: 'Visualizza posizioni accordo',
      step2_msg: 'Seleziona un accordo in Chord mode e il manico mostra automaticamente le posizioni corrispondenti.\nUsa virgola (,) e punto (.) per scorrere le posizioni.',
      step3_title: 'Inserisci dalla chitarra',
      step3_msg: 'Passa alla modalit\u00E0 Input. Prova a cliccare i tasti sul manico per inserire note.\nI nomi degli accordi vengono rilevati in tempo reale.',
      step4_title: 'Rifletti sul pad',
      step4_msg: '"Rifletti sul pad" mappa il voicing della chitarra sulla griglia dei pad.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Scorciatoie da tastiera',
    shortcuts_desc: 'Tasti essenziali per un\'operazione efficiente',
    shortcuts: {
      step1_title: 'Cambio modalit\u00E0',
      step1_msg: 'Tab \u2014 Cambia modalit\u00E0 (Scale \u2192 Chord \u2192 Input)\nShift+Tab \u2014 Direzione inversa\n\nCambia rapidamente tra le modalit\u00E0.',
      step2_title: 'Diatonica & navigazione',
      step2_msg: '1\u20137 \u2014 Seleziona accordo diatonico\n\u2191\u2193 \u2014 Cicla rivolti\n\u2190\u2192 \u2014 Trasporta la fondamentale di un semitono (mantiene la forma)\n\nOpera gli accordi senza mouse.',
      step3_title: 'Operazioni voicing',
      step3_msg: 'S \u2014 Ciclo Shell (off \u2192 1-3-7 \u2192 1-7-3)\nO \u2014 Toggle Omit 5\nR \u2014 Toggle Rootless\nShift+D \u2014 Ciclo Drop (off \u2192 Drop2 \u2192 Drop3)\nT \u2014 TASTY ON/OFF, K \u2014 STOCK ON/OFF\nZ / X \u2014 voicing TASTY/STOCK prec/succ\n\u2190\u2192 \u2014 Trasporta voicing di un semitono (durante TASTY/STOCK)\nV \u2014 Rifletti sul pad / cambio layout\n/ \u2014 Testo input accordo',
      step4_title: 'Memoria & banchi',
      step4_msg: 'Option+1234/qwer/asdf/zxcv \u2014 Salva nello slot\n[ ] \u2014 Cambia banco\nM \u2014 Attiva/disattiva vista memoria\nP \u2014 Attiva/disattiva Perform mode\nSpace \u2014 Suona\nShift+Space \u2014 Suona tutto (sequenziale)',
      step5_title: 'Altro',
      step5_msg: '? \u2014 Aiuto (lista completa scorciatoie)\n\u2318\u2325+G/B/P/F/S \u2014 Toggle strumenti/circolo/pentagramma\n\u2318\u2325+A/M/T/Q/V/K/H \u2014 Toggle sezioni\nCmd/Ctrl+Z \u2014 Annulla (fino a 30 volte)\nEsc \u2014 Deseleziona / Chiudi finestre',
    },
    // Link Mode tutorial
    link_title: 'Link Mode',
    link_desc: 'Sincronizza le note suonate su tutti gli strumenti',
    link: {
      step1_title: 'Pulsante Link',
      step1_msg: 'Il pulsante Link è accanto a Guitar / Bass / Piano.\nAttivalo per vedere le note suonate su tutti gli strumenti in tempo reale.',
      step2_title: 'Link Mode ON',
      step2_msg: 'Quando Link è attivo, le visualizzazioni degli strumenti si attenuano.\nSuona i pad o il MIDI \u2014 solo le note suonate si illuminano.',
      step3_title: 'Suona i pad',
      step3_msg: 'Premi un pad e guarda la stessa nota illuminarsi su chitarra, basso e pianoforte.\nVedi quali posizioni su ogni strumento producono lo stesso pitch.\nRilascia per cancellare.',
      step4_title: 'Scorciatoia',
      step4_msg: '\u2318\u2325+L attiva/disattiva il Link mode.\nPerfetto per imparare come le note si mappano tra gli strumenti.',
    },
    // Minor Scales tutorial
    minor_scales_title: 'Confronta 3 scale minori',
    minor_scales_desc: 'Naturale, armonica e melodica affiancate',
    minor_scales: {
      step1_title: 'Imposta una tonalità minore',
      step1_msg: 'Am (minore naturale) è selezionato.\nLa barra diatonica mostra gli accordi della minore naturale.',
      step2_title: 'Attiva Harm/Mel',
      step2_msg: 'Clicca "Harm/Mel" (\u2318\u2325N).\nGli accordi diatonici della minore armonica e melodica appaiono sotto.',
      step3_title: 'Confronta',
      step3_msg: 'Osserva le differenze dalla minore naturale (barra superiore).\nNella armonica, il V cambia da Em7 a E7 \u2014 abilitando il moto dominante.\nNella melodica, anche il IV cambia da Dm7 a D7.\nClicca qualsiasi accordo per vederlo sui pad.',
      step4_title: 'Tonalità parallela',
      step4_msg: 'Attiva "Parallel Key" (\u2318\u2325R) per vedere gli accordi diatonici maggiori per la stessa fondamentale.\nQuesto rivela l\'origine degli accordi presi in prestito (interscambio modale).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Dominante secondaria',
    secdom_desc: 'Sperimenta la porta verso la modulazione',
    secdom: {
      step1_title: 'Inizia in C maggiore',
      step1_msg: 'C maggiore è impostato.\nLa barra diatonica mostra C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Attiva la dominante secondaria',
      step2_msg: 'Clicca "Secondary Dominant" (\u2318\u2325D).\nAppaiono gli accordi V7 che risolvono su ogni accordo diatonico.\nIn C maggiore: C7, D7, E7, A7, B7 (5 in totale).',
      step3_title: 'Risoluzione verso il maggiore',
      step3_msg: 'Clicca C7 (\u2192F\u25B37) o D7 (\u2192G7).\nAvailable Scale mostra Mixolydian come prima scelta.\nPerché l\'obiettivo della risoluzione è un accordo maggiore.',
      step4_title: 'Risoluzione verso il minore',
      step4_msg: 'Clicca A7 (\u2192Dm7) o E7 (\u2192Am7).\nAvailable Scale mostra HMP5\u2193 (Phrygian Dominant) e Altered come prime scelte.\nPerché l\'obiettivo della risoluzione è un accordo minore.',
      step5_title: 'La regola: solo 2 tipi',
      step5_msg: 'La scelta della scala per le dominanti secondarie è semplice:\n\u2022 Risoluzione maggiore \u2192 Mixolydian\n\u2022 Risoluzione minore \u2192 HMP5\u2193 o Altered\nÈ tutto quello che devi ricordare.',
    },
    // Settings tutorial
    settings_title: 'Visualizzazione & Impostazioni',
    settings_desc: 'Personalizza il tuo spazio di lavoro',
    settings: {
      step1_title: 'Pannelli strumenti',
      step1_msg: 'La visualizzazione Guitar mostra voicing comunemente usati quando selezioni un accordo nel Chord Builder.\nIn modalit\u00E0 Input, puoi anche inserire da chitarra, basso e tastiera.',
      step2_title: 'Nomi note / Gradi',
      step2_msg: 'Alterna tra nomi delle note (C, D, E) e gradi (R, 2, 3).\nSi applica a pad e visualizzazione chitarra.',
      step3_title: 'Spostamento ottava',
      step3_msg: 'Usa ▲▼ per spostare l\'estensione dei pad su o gi\u00F9 di un\'ottava.\nI pulsanti ottava di Push 3 e Launchpad si sincronizzano automaticamente.',
      step4_title: 'Toggle sezioni',
      step4_msg: '\u2318\u2325+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) per comprimere le sezioni.\nMostra solo ci\u00F2 di cui hai bisogno.',
      step5_title: 'Ordine del layout',
      step5_msg: 'In ? Help, usa il menu "Layout" per riordinare i 3 pannelli.\n6 preset: Chord, Pad, Circle in qualsiasi ordine.\nSu mobile, cambia anche l\'ordine di scorrimento.',
      step6_title: 'Salva tutto',
      step6_msg: 'Clicca l\'icona di salvataggio per preservare tutte le impostazioni.\nTonalit\u00E0, scala, suono, memoria, voicing — tutto viene mantenuto.',
    },
  },
});
