// Português
I18N.addLang('pt', {
  help: {
    title: '64 Pad Explorer',
    description: 'Uma ferramenta para explorar escalas, acordes e voicings numa grelha de 64 pads.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Escolher entre 12 tonalidades',
    scale_scale: '<strong>Scale</strong> \u2014 Diatónica, menor harmónica, menor melódica, pentatónica, Bebop e mais \u2014 31 tipos',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Mostra os acordes diatónicos da escala selecionada. Clique para entrar no modo Chord',
    chord_mode: 'Chord Mode (3 passos)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selecionar a fundamental no teclado de piano',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Escolher o tipo de acorde (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Adicionar tensões (9, b9, #9, 11, #11, 13, b13, etc.). Seleção múltipla permitida',
    chord_text: '<strong>Entrada de texto</strong> \u2014 Pressione "/" para focar. Digite Cm7, G7(b9,#11), Am7/G etc. diretamente. Sugestões automáticas',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usar o botão "/" para acordes invertidos (acorde sobre nota de baixo)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omitir notas',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 para adicionar notas)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversões (Root, 1st, 2nd, 3rd)',
    inv_1: '1.ª inversão',
    inv_2: '2.ª inversão',
    inv_3: '3.ª inversão',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Toque para percorrer as opções de disposição no pad (um contador como A1/3 = disposições alternativas disponíveis)',
    display: 'Visualização',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Ativar/desativar braço da guitarra, baixo, teclado e pauta musical independentemente. Nota: As posições de guitarra/baixo mostram digitações tocáveis no instrumento, não correspondem à disposição do pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Exibe o círculo de quintas. Vinculado à seleção de tonalidade, mostrando acordes diatónicos e funções (T/SD/D). Suporte para alternância de modo menor',
    display_label: '<strong>Nome / Grau</strong> \u2014 Alternar entre nomes de notas (C, D, E) e graus (R, 2, 3) na guitarra e nos pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Deslocar a extensão dos pads por oitava',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Ativar/desativar som com o \u00EDcone do altifalante',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Modelagem física de EP Soul/Funk/Jazz-Funk. Os membros HPS podem selecionar o preset AMP (cadeia de amplificação com modelagem física). \u25BC abre o painel de detalhes',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Modelagem física opto-style (estéreo). Use TREM/T.SPD para profundidade e velocidade',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Soul/Funk/Jazz-Funk EP, FM, clav-style, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro envelope (Auto-Wah). 3 tipos: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturação analógica. Adiciona overdrive quente ao som',
    sound_fx: '<strong>Efeitos</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Clique num pad ou voicing box para reproduzir o som',
    midi: 'MIDI',
    midi_detect: 'Deteção automática de dispositivos compatíveis com WebMIDI',
    midi_push: 'Suporte para saída MIDI série do Ableton Push',
    midi_chord: 'Identificação automática de acordes a partir das notas tocadas',
    midi_sustain: '<strong>Pedal de sustain</strong> \u2014 Compatível com MIDI CC64 (Hold Pedal)',
    color_title: 'Legenda de cores',
    color_root: '<strong>Root</strong> \u2014 Nota fundamental',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notas da escala / Notas do acorde',
    color_char: '<strong>Característica</strong> \u2014 Notas que definem a escala/acorde',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (terça)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (sétima)',
    color_tension: '<strong>Tension</strong> \u2014 Notas de tensão',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota da escala um semitom acima de uma nota do acorde (no modo Chord)',
    color_palette: 'Paleta de cores: Okabe-Ito (acessível para daltónicos)',
    input_title: 'Entrada Guitar / Piano',
    input_desc1: 'Clique no braço da guitarra ou no teclado do piano para inserir notas',
    input_desc2: 'Os acordes são identificados automaticamente a partir da entrada e refletidos no pad',
    input_desc3: '<strong>Clear</strong> \u2014 Limpar entrada, <strong>Play \u25B6</strong> \u2014 Reproduzir notas inseridas',
    input_title: 'Input Mode',
    input_desc1: 'Clique livremente nos pads para selecionar notas \u2192 Identificação de acordes em tempo real',
    input_desc2: 'Sem filtro te\u00F3rico. Explorar \u2192 descobrir \u2192 aprender teoria depois',
    input_desc3: 'Quando um acorde \u00E9 detetado, r\u00F3tulos de grau (R, 3, 5, b7, etc.) aparecem nos pads. Guitarra, baixo, piano e pauta atualizam-se automaticamente',
    input_memory: '<strong>Memory</strong> \u2014 Guardar e recuperar acordes em 16 slots',
    input_banks: '<strong>Banks</strong> \u2014 16 slots \u00D7 até 16 bancos. Alternar com <kbd>[</kbd> <kbd>]</kbd>. Duplicar e renomear suportados',
    input_export: '<strong>MIDI Export</strong> \u2014 Exportar acordes da mem\u00F3ria como ficheiro MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> bot\u00E3o ou tecla <kbd>p</kbd> para alternar',
    perform_desc1: 'Toque os acordes dos Memory Slots em tempo real com um layout de 16 pads',
    perform_desc2: 'Acione via teclado (grelha 4\u00D74) ou pads MIDI',
    perform_desc3: 'Arraste e solte Slots para reordenar',
    shortcut_title: 'Atalhos de teclado',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Selecionar acorde diatónico (escalas de 7 notas)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Selecionar voicing box (percorrer alternativas)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Percorrer inversões (modo Chord)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposição cromática da fundamental',
    sc_omit: '<kbd>o</kbd> \u2014 Ativar/desativar Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Ativar/desativar Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclar Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclar Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: "<kbd>v</kbd> — Motor Guitar ON/OFF (mostra o voicing de guitarra selecionado na grade de 64 pads)",
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Ciclar posição de guitarra (anterior / próximo)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Alternar posição do baixo (anterior / próximo)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Limpar acorde (modo Chord)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clique para ativar/desativar nota \u2014 construtor atualizado automaticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Iniciar Capture / guardar no slot seguinte',
    sp_end: '<kbd>e</kbd> \u2014 Terminar Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recuperar slot de memória (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transposição cromática (todas as notas \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversão (mais grave \u21911oit / mais aguda \u21931oit)',
    sp_clear: '<kbd>x</kbd> \u2014 Limpar tudo',
    sp_transfer: '<b>Chord switch</b> \u2014 Transferir acorde detetado para o modo Chord',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Grelha 4\u00D74 aciona Slots 1\u201316',
    pf_midi: 'Pads MIDI (notas 36\u201354) tamb\u00E9m acionam Slots',
    shortcut_common: 'Comum (todos os modos)',
    sc_perform: '<kbd>p</kbd> \u2014 Alternar vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Desfazer Memory Slots (at\u00E9 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Guardar o acorde / voicing atual num Memory Slot',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Guardar o acorde / voicing atual num Memory Slot',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 Guardar diretamente num Memory Slot',
    sc_space: '<kbd>Space</kbd> \u2014 Tocar acorde atual',
    sc_esc: '<kbd>Esc</kbd> \u2014 Desselecionar voicing box / fechar ajuda',
    sc_help: '<kbd>?</kbd> \u2014 Mostrar/ocultar ajuda',
    sc_slash: '<kbd>/</kbd> \u2014 Focar entrada de texto de acorde',
    sc_tasty_nav: "<kbd>z</kbd> / <kbd>x</kbd> — Voicing TASTY/STOCK/Guitar anterior/próximo",
    shortcut_display: 'Alternar visualiza\u00E7\u00E3o (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitar',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Bass',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Circle of Fifths',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Staff',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Text Input',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Key Display',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 Header / Info Bar',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: 'Mostrar dicas na inicialização',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Fixar em Dó maior',
    perform_same_notes: 'Mostrar apenas as notas tocadas no Perform',
    perform_same_notes_tip: 'Ligado mostra apenas as alturas exatas gravadas no Perform. Desligado compacta o voicing tocado em uma única posição educativa.',
    color_coding_toggle: 'Colorir notas características e de acorde',
    c_fixed_tip: 'O pad sempre mostra a escala de Dó maior, independentemente de Key/Scale/Chord.',
    layout: 'Layout',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Característica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
    scale_root: 'Raiz da escala',
  },
  ui: {
    close: 'Fechar',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Salvar configurações',
    sound_hint: 'Selecione um preset de som para ativar o áudio',
    tap_to_start: 'Toque para ativar o som',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: 'Toque em qualquer pad para tocar!',
    load_vst: 'Carregar plugin VST/AU...',
    affiliate_label: '',
    staff: 'Partitura',
    circle: 'Ciclo',
    help: 'Ajuda',
    view_settings: 'Definições de vista',
    show_all_positions: 'Todas as posições',
    view_focus: 'Vista',
    view_layout: 'Layout',
    view_all: 'Todos os painéis',
    view_pad: 'Só pads',
    view_chord: 'Só construtor de acordes',
    view_info: 'Só info / memória',
    layout_abc: 'Pad → Acorde → Círculo',
    layout_acb: 'Pad → Círculo → Acorde',
    layout_bac: 'Acorde → Pad → Círculo',
    layout_bca: 'Acorde → Círculo → Pad',
    layout_cab: 'Círculo → Pad → Acorde',
    layout_cba: 'Círculo → Acorde → Pad',
    view_setup_note: 'Na versão Desktop, Push 3 Setup também abre este ecrã. Jog Wheel esquerda/direita escolhe vista ou layout, rodar altera o valor, e premir Jog Wheel ou Setup fecha.',
    oct_down: 'Descer oitava',
    oct_up: 'Subir oitava',
    toggle_guitar: 'Mostrar/ocultar bra\u00E7o da guitarra (⌘⌥G)',
    toggle_bass: 'Mostrar/ocultar bra\u00E7o do baixo (⌘⌥B)',
    toggle_piano: 'Mostrar/ocultar teclado de piano (⌘⌥P)',
    mode_scale: 'Modo Scale \u2014 ver notas da escala nos pads (Tab para alternar)',
    mode_chord: 'Modo Chord \u2014 construir acordes com voicings (Tab para alternar)',
    mode_input: 'Modo Input \u2014 clicar pads livremente para detetar acordes (Tab para alternar)',
    play_chord: 'Tocar acorde atual (Space)',
    toggle_staff: 'Mostrar/ocultar pauta musical (⌘⌥S)',
    toggle_circle: 'Mostrar/ocultar c\u00EDrculo de quintas (\u2318\u2325F)',
    toggle_sound: 'Mostrar/ocultar controlos de som',
    sound_mute: 'Som ON/OFF',
    sound_expand: 'Mostrar/ocultar defini\u00E7\u00F5es detalhadas de som',
    input_keys_disabled: 'A sele\u00E7\u00E3o de tonalidade n\u00E3o \u00E9 usada no modo Input',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grau',
    chord_input: 'Inserir acorde',
    chord_hint: 'Tensões em ( ): C7(b9,#11) | dim, h=m7♭5 suportados',
    key_hint: 'Também configurável pelo modo Scale ou Círculo de quintas',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Meu Blog',
    guide: 'Guia',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Prima Capture para começar a construir acordes',
    status_capturing: 'A capturar: Slot {slot}/16 \u2014 Clique nos pads, depois Capture para guardar',
    status_editing: 'A editar: Slot {slot} \u2014 Clique nos pads para modificar',
    notes_label: 'Notas: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    memory_full: 'Memory Slots cheios',
    no_current_chord: 'Não há acorde atual para guardar',
    slot_selected: 'Slot {slot} selecionado',
    slot_cleared: 'Slot {slot} limpo',
    undo: 'Desfazer',
    settings_saved: 'Configurações salvas',
    no_chords: 'Sem acordes nos slots de memória',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    note_count: '{n} notas',
    default: 'Passe o cursor sobre qualquer controlo para ver o que faz',
    mode_scale: 'Modo Scale \u2014 Ver notas da escala na grelha de 64 pads [Tab]',
    mode_chord: 'Modo Chord \u2014 Construir acordes passo a passo: Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Modo Input \u2014 Toque livremente nos pads, os acordes s\u00E3o detetados automaticamente [Tab]',
    guitar: 'Alternar exibi\u00E7\u00E3o do bra\u00E7o de guitarra [\u2318\u2325G]',
    bass: 'Alternar exibi\u00E7\u00E3o do bra\u00E7o de baixo [\u2318\u2325B]',
    piano: 'Alternar exibi\u00E7\u00E3o do teclado de piano [\u2318\u2325P]',
    link_mode: 'Modo Link \u2014 notas tocadas sincronizam em todos os instrumentos em tempo real [\u2318\u2325L]',
    staff: 'Alternar pauta musical [\u2318\u2325S]',
    circle: 'Circle of Fifths \u2014 T\u00F3nica, Subdominante, Dominante mostradas em cores correspondentes [\u2318\u2325F]',
    cof_major: 'Anel exterior \u2014 selecionar tonalidade maior',
    cof_minor: 'Anel interior \u2014 selecionar tonalidade menor',
    cof_natural: 'Menor natural',
    cof_harmonic: 'Menor harm\u00F3nica',
    cof_melodic: 'Menor mel\u00F3dica',
    sound: 'Alternar painel de controlos de \u00E1udio [\u2318\u2325A]',
    memory: 'Alternar painel Memory Slot \u2014 guardar/recuperar acordes em 16 slots [\u2318\u2325M]',
    sect_key: 'Alternar exibi\u00E7\u00E3o de Key',
    sect_input: 'Alternar entrada de texto de acorde [\u2318\u2325T]',
    sect_quality: 'Alternar seletores Root/Quality/Tension [\u2318\u2325Q]',
    sect_voicing: 'Alternar controlos de voicing (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Digite o nome do acorde diretamente \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Mostrar escalas dispon\u00EDveis para o acorde atual. Slash chords com baixo n\u00E3o pertencente ao acorde s\u00E3o reinterpretados a partir da nota de baixo',
    sort_practical: 'Ordena\u00E7\u00E3o pr\u00E1tica \u2014 prioriza escalas frequentemente usadas. Inclui escalas de dominante secund\u00E1ria (ex.: Mixolydian b13 para V7/ii)',
    sort_diatonic: 'Ordena\u00E7\u00E3o diat\u00F3nica \u2014 ordena pela dist\u00E2ncia te\u00F3rica da tonalidade atual',
    omit5: 'Remover a 5\u00AA do voicing [O]',
    rootless: 'Remover a fundamental [R]',
    omit3: 'Remover a 3\u00AA do voicing',
    shell137: 'Shell voicing: Root-3rd-7th [S]',
    shell173: 'Shell voicing: Root-7th-3rd [S]',
    shell_off: 'Desativar shell voicing [S]',
    shell_ext: 'Adicionar notas ao shell voicing (+1 ou +2 notas do acorde)',
    inv_root: 'Posi\u00E7\u00E3o fundamental [\u2193]',
    inv: 'Invers\u00E3o [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 voicings refinados ordenados por nota superior. Funciona com \u25B37, m7, 7 (exclusivo HPS) [T]',
    tasty_nav: 'Percorrer varia\u00E7\u00F5es [Z / X]',
    stock: 'Stock Voicing \u2014 voicings comuns de piano (exclusivo HPS) [K]',
    stock_nav: 'Percorrer varia\u00E7\u00F5es [Z / X]',
    root_notation: 'Alternar entre nota\u00E7\u00E3o \u266F e \u266D',
    root_grid: 'Selecionar nota fundamental',
    quality_grid: 'Selecionar qualidade do acorde (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Adicionar tens\u00F5es ao acorde (9, b9, #9, 11, #11, 13, b13) \u2014 m\u00FAltiplas OK',
    diatonic: 'Acordes diat\u00F3nicos da escala atual \u2014 clique para entrar no modo Chord [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Comparar acordes diat\u00F3nicos de menor harm\u00F3nica e mel\u00F3dica lado a lado [\u2318\u2325N]',
    parallel_key: 'Tonalidade paralela \u2014 Mostrar diat\u00F3nica maior/menor para a mesma fundamental. Veja de onde v\u00EAm os acordes emprestados [\u2318\u2325R]',
    secdom: 'Dominante secund\u00E1ria \u2014 Mostrar V7 que resolve para cada acorde diat\u00F3nico. Clique para exibi\u00E7\u00E3o autom\u00E1tica de Available Scale [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: 'No modo Input, capturar toques nos pads em Memory Slots em sequência [C]',
    capture_current: 'Guardar o acorde / voicing TASTY / STOCK / Guitar atual num Memory Slot [Shift+C]',
    capture_end: 'Terminar captura e guardar no slot atual [E]',
    save: 'Guardar todas as defini\u00E7\u00F5es atuais (tonalidade, escala, som, mem\u00F3ria, layout)',
    tutorial: 'Tutoriais interativos \u2014 aprenda os fundamentos passo a passo',
    help: 'Abrir modal de ajuda com refer\u00EAncia completa de atalhos [?]',
    affiliate: 'Comprar atrav\u00E9s destes links apoia o desenvolvimento\u2026',
    lang: 'Mudar idioma de exibi\u00E7\u00E3o',
    octave: 'Deslocar a faixa de oitava dos pads \u2014 Push/Launchpad tamb\u00E9m pode controlar via bot\u00F5es de oitava',
    show_all_positions: 'Quando ativado, mostra todas as posições do acorde na grade e as caixas de voicing. Quando desativado, mostra apenas uma forma básica.',
    play: 'Tocar o acorde atual [Space]',
    scale_select: 'Selecionar uma escala',
    chord_key: 'Alternar entre tonalidade maior e menor',
    chord_key_picker: 'Abrir seletor de tonalidade para mudar a tonalidade sem mudar para o modo Scale',
    builder_clear: 'Limpar o acorde atual e come\u00E7ar de novo [X]',
    builder_back: 'Desfazer o \u00FAltimo passo na constru\u00E7\u00E3o do acorde [\u232B]',
    slash_chord: 'Slash chord (on chord)',
    guitar_diagram: 'Voicings comuns de guitarra refletidos quando um acorde \u00E9 selecionado no construtor',
    guitar_label: 'Alternar nomes de notas no bra\u00E7o de guitarra',
    genre_preset: 'Mudar g\u00E9nero de voicing de guitarra \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: 'Percorrer posi\u00E7\u00F5es de voicing de guitarra/baixo [, .]',
    to_pad: 'Refletir o voicing de guitarra/stock na grelha de 64 pads [V]',
    inst_clear: 'Limpar notas inseridas no diagrama de instrumento',
    inst_play: 'Tocar notas inseridas no diagrama de instrumento',
    plain_clear: 'Limpar todas as notas no modo Input [X]',
    midi_export: 'Exportar todos os slots de mem\u00F3ria como ficheiro MIDI para o seu DAW',
    chs_export: 'Exportar todos os slots de mem\u00F3ria em formato CHS (Clover Chord Systems)',
    midi_import: 'Importar um ficheiro MIDI para os slots de mem\u00F3ria',
    chs_import: 'Importar um ficheiro CHS para os slots de mem\u00F3ria',
    midi_device: 'Selecionar entrada MIDI',
    midi_panic: 'All Notes Off \u2014 parar quaisquer notas MIDI presas',
    sound_mute: 'Som ON/OFF',
    sound_preset: 'Selecionar preset de som',
    volume: 'Volume principal',
    sound_fx: 'Efeitos \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 filtro abre/fecha em cada nota. Tipo LP/BP, inclina\u00E7\u00E3o 2P/4P',
    velocity: 'Curva de velocidade',
    mem_view: 'Vista Memory \u2014 guardar e organizar acordes em 16 slots [M]',
    perform_view: 'Vista Perform \u2014 tocar acordes guardados em tempo real com 16 pads [P]',
    bank: 'Bancos de mem\u00F3ria \u2014 16 slots \u00D7 at\u00E9 16 bancos. [ ] para trocar',
    slot_save: 'Guardar o acorde atual no slot selecionado',
    play_slots: 'Tocar todos os acordes guardados em sequ\u00EAncia',
    locut: 'Lo-cut \u2014 Remove graves para clareza (checkbox ON/OFF, slider = frequ\u00EAncia de corte)',
    hicut: 'Hi-cut \u2014 Remove agudos para um tom mais redondo (checkbox ON/OFF, slider = frequ\u00EAncia)',
    drive: 'Drive \u2014 Quantidade de overdrive. Mais alto = mais distor\u00E7\u00E3o',
    tremolo: 'Profundidade de tr\u00EAmolo \u2014 Profundidade de modula\u00E7\u00E3o de amplitude (modelagem f\u00EDsica opto + CdS)',
    tremolo_speed: 'Velocidade de tr\u00EAmolo \u2014 Taxa de modula\u00E7\u00E3o (Hz)',
    phaser: 'Phaser \u2014 Varredura com deslocamento de fase',
    flanger: 'Flanger \u2014 Delay muito curto, varredura met\u00E1lica',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Tipo de filtro \u2014 LP=Passa-baixa / BP=Passa-banda',
    af_poles: 'Declive \u2014 2P=12dB/oct (suave) / 4P=24dB/oct (acentuado)',
    af_depth: 'Depth \u2014 Amplitude de abertura/fechamento do filtro',
    af_decay: 'Decay \u2014 Velocidade de fechamento do filtro (menor = mais r\u00E1pido)',
    af_q: 'Q \u2014 Resson\u00E2ncia (agudez do pico)',
    af_wet: 'WET \u2014 Quantidade do efeito (0 = totalmente dry, 10 = totalmente wet)',
    af_vol: 'VOL \u2014 Trim de sa\u00EDda (baixe se o ampli distorcer)',
    eq_bass: 'Baxandall Bass \u2014 EQ shelving de graves. Centro = plano',
    eq_treble: 'Baxandall Treble \u2014 EQ shelving de agudos. Centro = plano',
    reverb_type: 'Tipo de reverb \u2014 Spring (cauda ondulante estilo Twin) / Plate (cauda densa met\u00E1lica)',
    reverb_amount: 'Quantidade de reverb \u2014 Mistura de sinal wet',
    reverb_decay: 'Decay de reverb \u2014 Dura\u00E7\u00E3o da cauda',
    reverb_stereo: 'Est\u00E9reo \u2014 ON espalha reverb por L/R',
    reverb_dwell: 'Dwell \u2014 Entrada no tanque de molas',
    vel_thresh: 'Limite de velocidade \u2014 Batidas mais suaves tratadas como velocidade m\u00EDnima',
    vel_drive: 'Velocity Drive \u2014 Inclina\u00E7\u00E3o da curva (positivo = acentua, negativo = aplaina)',
    vel_compand: 'Compand \u2014 Comprime/expande em torno da velocidade m\u00E9dia',
    vel_range: 'Range \u2014 Limite m\u00E1ximo de velocidade',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Selecionar fundamental',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'Todos os dispositivos',
  },
  memory: {
    slot_empty: 'Slot {slot}: Vazio',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    recall: 'Recuperar',
    play: 'Reproduzir',
    duplicate: 'Duplicar',
    delete: 'Excluir',
    save_here: 'Salvar aqui',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Clique para renomear',
    rename: 'Renomear',
    duplicate: 'Duplicar',
    delete: 'Excluir',
    rename_prompt: 'Nome do banco:',
    confirm_delete: 'Excluir "{name}"?',
    limit_reached: 'M\u00E1ximo 16 bancos',
    cannot_delete_last: 'N\u00E3o \u00E9 poss\u00EDvel excluir o \u00FAltimo banco',
  },
  diatonic: {
    parallel: 'Tonalidade paralela',
    relative: 'Relativa',
    harm_mel: 'Harm/Mel',
    secdom: 'Dominante secund\u00E1ria',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostrar tudo',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guia',
    tagline: 'Uma ferramenta de navegador para explorar escalas, acordes e voicings numa grelha de 64 pads.<br>Sem necessidade de fonte sonora \u2014 apenas Chrome.',
    cta: 'Abrir App',
    features: 'Funcionalidades',
    feat_sound: '<strong>Sem necessidade de fonte sonora</strong> \u2014 O som toca diretamente no Chrome. 4 presets de \u00F3rg\u00E3o + 8 presets de piano el\u00E9trico integrados. Efeitos (drive, reverb, phaser, flanger, tremolo, lo cut, hi cut, auto filter) inclu\u00EDdos',
    feat_input: '<strong>Sem habilidade de pad necess\u00E1ria</strong> \u2014 Construa acordes em 3 passos. Tens\u00F5es exibidas. Clique nos pads para inserir diretamente',
    feat_text_input: '<strong>Entrada de texto de acordes</strong> \u2014 Pressione "/" para digitar Cm7, G7(b9,#11), Am7/G etc. diretamente. Autocompletar. Abreviações como dim, h(=m7\u266D5)',
    feat_detect: '<strong>Dete\u00E7\u00E3o de acordes</strong> \u2014 Dete\u00E7\u00E3o em tempo real do nome do acorde a partir das notas clicadas. Suporta omit, acordes invertidos e m\u00FAltiplos candidatos',
    feat_instruments: '<strong>Exibi\u00E7\u00E3o Guitar / Bass / Keyboard</strong> \u2014 Mostra notas do acorde no bra\u00E7o da guitarra, baixo e piano. A entrada pelo bra\u00E7o da guitarra reflete-se automaticamente nos pads. No modo Chord, as posi\u00E7\u00F5es s\u00E3o agrupadas por corda raiz',
    feat_scales: '<strong>Exibi\u00E7\u00E3o de escalas</strong> \u2014 31 escalas \u00D7 12 tonalidades. Diat\u00F3nica, menor harm\u00F3nica, menor mel\u00F3dica, pentat\u00F3nica, Bebop e mais',
    feat_diatonic: '<strong>Exibi\u00E7\u00E3o de acordes diat\u00F3nicos</strong> \u2014 Os acordes diat\u00F3nicos s\u00E3o mostrados numa barra para a escala selecionada. Clique ou use atalhos para tocar instantaneamente. Alterna entre tr\u00EDades e t\u00E9trades',
    feat_voicing: '<strong>Opera\u00E7\u00F5es de voicing</strong> \u2014 Invers\u00F5es, Drop 2/3, Shell Voicing, Omit, Rootless. Setas para invers\u00F5es, bot\u00F5es para m\u00FAltiplas digita\u00E7\u00F5es',
    feat_memory: '<strong>Mem\u00F3ria de acordes</strong> \u2014 Guarde os seus acordes favoritos em 16 slots. Exporte como ficheiros MIDI para o seu DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Toque os acordes em mem\u00F3ria em tempo real com 16 pads ou o seu teclado de PC',
    feat_parent: '<strong>Pesquisa inversa Available Scale</strong> \u2014 Encontre escalas que cont\u00EAm o seu acorde. Veja as Available Tensions de relance. Altern\u00E2ncia Practical/Diatonic',
    feat_pivot: '<strong>Pensamento de acorde pivot</strong> \u2014 Insira um acorde manualmente e a barra diat\u00F3nica desaparece, mostrando todas as tonalidades \u00E0s quais o seu acorde poderia pertencer. Ideal para an\u00E1lise de modula\u00E7\u00E3o',
    feat_dimming: '<strong>Exibi\u00E7\u00E3o pr\u00E1tica de Tensions</strong> \u2014 Para acordes de 7\u00AA n\u00E3o dominante, as tens\u00F5es pouco comuns (b9, #9, b13, etc.) s\u00E3o atenuadas. Ainda selecion\u00E1veis',
    feat_circle: '<strong>Circle of Fifths</strong> \u2014 Exibe o c\u00EDrculo de quintas. Vinculado \u00E0 sele\u00E7\u00E3o de tonalidade, mostrando acordes diat\u00F3nicos e fun\u00E7\u00F5es (T/SD/D). Suporte para altern\u00E2ncia de modo menor',
    feat_banks: '<strong>Bancos de mem\u00F3ria</strong> \u2014 16 slots \u00D7 at\u00E9 16 bancos. Trocar, duplicar e renomear bancos. Teclas <kbd>[</kbd> <kbd>]</kbd> para trocar',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro envelope (Auto-Wah). 3 tipos: Cry Baby / Mu-Tron / Moog. Ajuste frequ\u00EAncia, resson\u00E2ncia, sensibilidade e decaimento',
    feat_drive: '<strong>Drive</strong> \u2014 Satura\u00E7\u00E3o anal\u00F3gica. Adiciona overdrive quente ao som',
    feat_clav: '<strong>Presets de clav-style</strong> \u2014 2 presets de clav-style adicionados ao E.PIANO (Clav Muted, Clav Bright). Perfeito para funk',
    feat_midi_sens: '<strong>Sensibilidade de velocidade MIDI</strong> \u2014 Ajuste de curva de velocidade com 4 par\u00E2metros estilo Push 3 (Threshold, Drive, Compand, Range). Visualiza\u00E7\u00E3o da curva em tempo real. Funciona com todos os controladores MIDI',
    feat_push_oct: '<strong>Sincroniza\u00E7\u00E3o de oitava Push 3</strong> \u2014 Os bot\u00F5es de oitava \u25B2\u25BC do Push 3 sincronizam automaticamente com o deslocamento de oitava da app',
    feat_i18n: '<strong>Multilingue</strong> \u2014 9 l\u00EDnguas (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Capturas de ecr\u00E3',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Selecione uma tonalidade e uma escala para ver as notas da escala coloridas na grelha de 64 pads. Escolha acordes na barra diat\u00F3nica.',
    ss_scale_alt: 'Scale Mode \u2014 Exibi\u00E7\u00E3o da escala de C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (laranja), notas da escala (azul), notas caracter\u00EDsticas (amarelo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construa acordes em 3 passos: Root \u2192 Quality \u2192 Tension. Ajuste voicings com invers\u00F5es, Drop, Shell e Omit. Use o painel Parent Scale para pesquisa inversa.',
    ss_chord_alt: 'Chord Mode \u2014 Exibi\u00E7\u00E3o do acorde Dm7 com grelha de tens\u00F5es',
    ss_chord_caption: 'Dm7 \u2014 Notas do acorde, 3rd (rosa), 7th (verde). Verifique as disposi\u00E7\u00F5es nas voicing boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Clique livremente nos pads para dete\u00E7\u00E3o de acordes em tempo real. Entenda os acordes mesmo sem conhecer a teoria.',
    ss_input_alt: 'Input Mode \u2014 Dete\u00E7\u00E3o em tempo real de C7',
    ss_input_caption: 'C7 \u2014 Clique nos pads para detetar automaticamente nomes de acordes. M\u00FAltiplos candidatos mostrados',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Coloque os acordes guardados em 16 pads para performance em tempo real via teclado ou pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 slots com acordes',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 guardados nos slots. Toque usando a grelha de teclado 4\u00D74',
    ss_parent: 'Available Scale + Acorde Pivot',
    ss_parent_desc: 'Pesquisa inversa de escalas que cont\u00EAm o seu acorde. Alterne entre ordena\u00E7\u00E3o Practical (por usabilidade) e Diatonic (por teoria). A entrada manual de acordes oculta a barra diat\u00F3nica para an\u00E1lise de acordes pivot.',
    ss_parent_alt: 'Painel Parent Scale e exibi\u00E7\u00E3o do bra\u00E7o da guitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions exibidas',
    ss_parent_note: '\u203B As escalas pentat\u00F3nicas/blues s\u00E3o modais (abordagem horizontal) e pertencem a um sistema diferente da teoria de escalas por acorde (mapeamento vertical), por isso n\u00E3o est\u00E3o inclu\u00EDdas no Available Scale. Na pr\u00E1tica, a pentat\u00F3nica \u00E9 frequentemente a primeira escolha.',
    ss_velocity: 'Sensibilidade de velocidade MIDI',
    ss_velocity_desc: 'Ajuste a sensibilidade de velocidade do controlador MIDI com 4 par\u00E2metros estilo Push 3. Configure na sec\u00E7\u00E3o VELOCITY SENSITIVITY dentro do painel Sound. Visualiza\u00E7\u00E3o da curva em tempo real.',
    ss_push_oct: 'Sincroniza\u00E7\u00E3o do bot\u00E3o de oitava Push 3',
    ss_push_oct_desc: 'Os bot\u00F5es de oitava \u25B2\u25BC do Push 3 (CC#55/CC#54) sincronizam automaticamente com o deslocamento de oitava da app. Prima os bot\u00F5es de oitava no Push 3 e a oitava do display atualiza-se automaticamente.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Fun\u00E7\u00F5es de Voicing exclusivas do HPS',
    ss_hps_voicing_intro: "Membros HPS têm acesso a 3 ferramentas de voicing. Escolha TASTY / STOCK / Guitar dentro do builder para mostrar esse voicing automaticamente na grade de 64 pads.",
    ss_tasty: 'TASTY Voicing \u2014 Classificado pela nota superior',
    ss_tasty_desc: '129 voicings sofisticados exibidos como arrays de graus. Selecione um acorde, pressione <kbd>T</kbd> para ativar e pressione novamente para percorrer os voicings. Sele\u00E7\u00E3o autom\u00E1tica da posi\u00E7\u00E3o ideal nos pads.',
    ss_tasty_target: 'Alvo: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'A \u00E1rea de informa\u00E7\u00F5es mostra a ordem de empilhamento dos graus (ex.: <code>m9 (b3-b7-9-5-1)</code>). Esta \u00E9 a estrutura do voicing \u2014 quais notas s\u00E3o empilhadas de baixo para cima.',
    ss_tasty_labels_title: 'Significado dos r\u00F3tulos',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Fundamental (1\u00BA grau) omitida. Comum em jazz/R&B/neo-soul onde o baixista cobre a fundamental.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5\u00AA omitida. A 5\u00AA tem pouco car\u00E1ter tonal, por isso \u00E9 substitu\u00EDda por uma tens\u00E3o para um som mais rico.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3\u00AA omitida. Aproxima-se de um som sus ou Quartal.',
    ss_tasty_ops_title: 'Controlos',
    ss_stock: 'STOCK Voicing \u2014 Cole\u00E7\u00E3o de Voicings de piano',
    ss_stock_desc: "154 voicings de piano de materiais didáticos, exibidos em notação de graus. Abrange Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Os voicings selecionados aparecem automaticamente na grade de 64 pads.",
    ss_stock_ops_title: 'Controlos',
    ss_guitar_pos: 'Guitar Position \u2014 Voicings de guitarra',
    ss_guitar_pos_desc: "Calcula automaticamente posições de acordes no braço da guitarra. A visualização Guitar à esquerda é a área de instrumento; Guitar dentro do builder é o motor de voicing para a grade de 64 pads.",
    usecases: 'Casos de uso',
    uc1_q: '\u00AB Quero encontrar como voicer este acorde nos pads \u00BB',
    uc1_a: '\u2192 Selecione Root, Quality e Tension no modo <span class="mode-badge chord">Chord</span> \u2192 Verifique as disposi\u00E7\u00F5es nas voicing boxes',
    uc2_q: '\u00AB Quero ver uma escala da minha aula nos pads \u00BB',
    uc2_a: '\u2192 Selecione tonalidade e escala no modo <span class="mode-badge scale">Scale</span>. 31 escalas dispon\u00EDveis',
    uc3_q: '\u00AB Quero criar uma progress\u00E3o de acordes para o meu DAW \u00BB',
    uc3_a: '\u2192 Guarde os acordes nos slots de mem\u00F3ria \u2192 MIDI Export para importar no seu DAW',
    uc4_q: '\u00AB A que tonalidade pertence este acorde? \u00BB',
    uc4_a: '\u2192 Pesquisa inversa no painel Available Scale. Alterne entre ordena\u00E7\u00E3o Practical/Diatonic',
    uc7_q: '\u00AB Quero encontrar acordes pivot para modula\u00E7\u00E3o \u00BB',
    uc7_a: '\u2192 Insira um acorde manualmente no modo <span class="mode-badge chord">Chord</span>. A barra diat\u00F3nica desaparece e Available Scale mostra todas as tonalidades poss\u00EDveis',
    uc5_q: '\u00AB Quero conferir progress\u00F5es de acordes tocando-os \u00BB',
    uc5_a: '\u2192 Salve os acordes nos slots de mem\u00F3ria e toque-os com um controlador MIDI ou teclado do PC',
    uc6_q: '\u00AB Quero conferir acordes de guitarra nos pads \u00BB',
    uc6_a: '\u2192 Clique no bra\u00E7o da guitarra para inserir \u2192 Exibi\u00E7\u00E3o autom\u00E1tica nos pads \u2192 Nome do acorde detetado',
    uc8_q: '\u00AB Quero aprender voicings profissionais \u00BB',
    uc8_a: '\u2192 Construa um acorde no modo <span class="mode-badge chord">Chord</span>, depois pressione <kbd>T</kbd> para TASTY (classifica\u00E7\u00E3o por nota superior) ou <kbd>K</kbd> para STOCK (voicings de piano). Visualize com nota\u00E7\u00E3o de graus, guarde na mem\u00F3ria e exporte para o DAW',
    quickstart: 'In\u00EDcio r\u00E1pido',
    qs_modes: '3 modos',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Mostrar escalas e acordes diat\u00F3nicos<br><span class="mode-badge chord">Chord</span> Construir acordes em 3 passos. Opera\u00E7\u00F5es de voicing dispon\u00EDveis<br><span class="mode-badge input">Input</span> Clicar livremente nos pads \u2192 Dete\u00E7\u00E3o autom\u00E1tica dos nomes de acordes',
    qs_first: 'Para come\u00E7ar',
    qs_step1: 'Escolha uma tonalidade (ex: C)',
    qs_step2: 'Escolha uma escala (ex: Major) \u2192 As notas da escala aparecem nos pads',
    qs_step3: 'Clique num acorde na barra diat\u00F3nica (ex: Dm7) \u2192 Notas do acorde exibidas',
    qs_step4: 'Clique nos pads para tocar sons. Mude as disposi\u00E7\u00F5es nas voicing boxes',
    qs_step5: 'Guarde os seus acordes favoritos com <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Atalhos de teclado',
    qs_shortcuts_desc: 'Prima <kbd>?</kbd> para a lista completa de atalhos.<br><kbd>Space</kbd> para tocar acorde. <kbd>1</kbd>\u2013<kbd>7</kbd> para acordes diat\u00F3nicos, <kbd>\u2191</kbd><kbd>\u2193</kbd> para invers\u00F5es, <kbd>\u2190</kbd><kbd>\u2192</kbd> para movimento crom\u00E1tico.<br>No Perform mode, use <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> como grelha 4\u00D74.',
    footer_open: 'Abrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Saiba mais no blog \u2192',
    header_icons: 'Ícones do cabeçalho',
    header_icons_desc: 'Três botões de ícone no canto superior direito.',
    icon_save: '<strong>\uD83D\uDCBE Salvar</strong> \u2014 Salva as configurações atuais (som, efeitos, opções de exibição, etc.) no navegador. Restauração automática na próxima visita',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Explore 11 tutoriais interativos. Aprenda cada função passo a passo',
    icon_help: '<strong>? Ajuda</strong> \u2014 Mostra atalhos de teclado, histórico de versões e descrição dos modos. Também abre com a tecla <kbd>?</kbd>',
    sound_panel: 'Painel de som',
    sound_panel_desc: 'Selecione presets de som e ajuste os efeitos. Clique no botão \u25B6 para expandir o painel.',
    sound_presets: 'Presets de som',
    sound_presets_desc: 'O motor de modelagem física Soul/Funk/Jazz-Funk EP (Clean DI) é o padrão. Toque instantaneamente sem download de samples. Use o knob VOICING para ajustar o timbre do pickup.',
    sound_effects: 'Efeitos',
    sound_effects_desc: 'Arraste cada knob para ajustar os valores.',
    fx_drive: 'Saturação analógica. Distorção quente',
    fx_locut: 'Filtro corta-graves. Remove graves embolados',
    fx_hicut: 'Filtro corta-agudos. Atenua agudos ásperos',
    fx_reverb: 'Reverb. Adiciona profundidade espacial',
    fx_phaser: 'Phaser. Modulação envolvente',
    fx_flanger: 'Flanger. Modulação tipo jato',
    fx_tremolo: 'Tremolo. Modulação periódica de volume',
    sound_autofilter: 'Auto-Filtro (Auto-Wah)',
    sound_autofilter_desc: 'Filtro envelope. Ajuste FREQ, RESO, SENS e DECAY.',
    version_history: 'Hist\u00F3rico de vers\u00F5es',
    vh_540: '<b>V5.4</b> \u2014 Modelagem f\u00EDsica atualizada. Adicionados par\u00E2metros de filtro (WET / VOL) e um preset exclusivo HPS (Pad Sensei MK1 AMP Vintage Envelope Filter)',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Modelagem do preamp melhorada',
    vh_510: '<b>V5.1</b> \u2014 Modo de escala fixa em D\u00F3 maior adicionado',
    vh_500: '<b>V5.0</b> \u2014 Motor de som e efeitos aut\u00F3nomos. Spring Reverb (modelagem f\u00EDsica) + Plate Reverb. Modelo de amplificador AMP melhorado. Seletor de tipo de Reverb (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Toque instantaneamente ao abrir (sem download de samples). Alternar dicas de atalhos. Acordes diat\u00F4nicos NM/HM/MM para tonalidades menores paralelas. PU LEVEL e MECHANICAL adicionados ao E.PIANO MIXER. Melhorias na exibi\u00E7\u00E3o de detec\u00E7\u00E3o de acordes',
    vh_490: '<b>V4.9</b> \u2014 Motor de modelagem f\u00EDsica Pad Sensei MK1',
    vh_497: '<b>V4.9.7</b> \u2014 O tremolo agora \u00E9 fisicamente modelado. Membros HPS obt\u00EAm Pad Sensei MK1 AMP (cadeia de amplifica\u00E7\u00E3o fisicamente modelada)',
    vh_3377: '<b>V3.37.7</b> \u2014 Revis\u00E3o de utilizador: corre\u00E7\u00E3o de tonalidade relativa menor, badges em mai\u00FAsculas, fonte sans-serif nos pads, alternadores acess\u00EDveis para dalt\u00F3nicos (verde\u2192azul), painel Sound aberto por padr\u00E3o, corre\u00E7\u00E3o de deslocamento de layout, overlay spotlight de tutorial, suporte de oitava Launchpad + rastreamento autom\u00E1tico de oitava para todos os controladores MIDI',
    vh_340: '<b>V3.40</b> \u2014 Posicionamento compacto TASTY/Stock: layout \u00F3timo autom\u00E1tico na grade de 64 pads. Bot\u00E3o "To Pad" removido. Caixas de voicing ocultas durante modo TASTY/Stock',
    vh_336: '<b>V3.36</b> \u2014 Motor de voicing guitarra v2: presets de g\u00EAnero (Jazz/Bossa/Funk), tabela de refer\u00EAncia (120 tipos \u00D7 12 tons), atribui\u00E7\u00E3o autom\u00E1tica de dedos com detec\u00E7\u00E3o de pestana',
    vh_335: '<b>V3.35</b> \u2014 Melhorias UX de tutoriais (revis\u00E3o para iniciantes). Todos os tooltips traduzidos para 9 idiomas. Guia: se\u00E7\u00F5es de painel de som e \u00EDcones de cabe\u00E7alho adicionadas',
    vh_333: '<b>V3.33</b> \u2014 Tutoriais interativos. 11 t\u00F3picos \u00D7 9 idiomas. Dicas contextuais na primeira intera\u00E7\u00E3o com cada funcionalidade',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 voicings de piano com teclado espec\u00EDfico MIDI. Guia atualizado com sec\u00E7\u00E3o de fun\u00E7\u00F5es de voicing HPS',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 voicings sofisticados ordenados por nota superior. Exibi\u00E7\u00E3o de array de graus + otimiza\u00E7\u00E3o autom\u00E1tica de oitava. Apenas membros HPS',
    vh_325: '<b>V3.25.0</b> \u2014 Voicing de guitarra \u2192 refletir no pad (tecla <kbd>V</kbd>). Altern\u00E2ncia layout estilo guitarra (1 nota por linha) / compacto. Filtro "Todos" de posi\u00E7\u00E3o de guitarra em primeiro',
    vh_324: '<b>V3.24</b> \u2014 Presets de clav-style adicionados (2 em E.PIANO). Efeito Auto Filter (filtro envelope / auto-wah) adicionado',
    vh_323: '<b>V3.23</b> \u2014 Entrada de texto de acordes com autocompletar. "/" para focar, abrevia\u00E7\u00F5es (dim, h=m7\u266D5), ordena\u00E7\u00E3o por tens\u00F5es',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Altern\u00E2ncia tr\u00EDade/t\u00E9trade diat\u00F3nica. Posi\u00E7\u00F5es de guitarra/baixo agrupadas por corda raiz',
    vh_37: '<b>V3.7</b> \u2014 Preserva\u00E7\u00E3o da posi\u00E7\u00E3o de voicing (manuten\u00E7\u00E3o autom\u00E1tica da forma da digita\u00E7\u00E3o no movimento crom\u00E1tico). Grelha de pads, pauta e dete\u00E7\u00E3o de acordes durante a reprodu\u00E7\u00E3o. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">V\u00EDdeo</a>',
    vh_35: '<b>V3.5</b> \u2014 Reprodu\u00E7\u00E3o de ficheiro MIDI \u2192 ilumina\u00E7\u00E3o de pads (reprodu\u00E7\u00E3o por timeline, visualiza\u00E7\u00E3o do nome do acorde, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Soul/Funk/Jazz-Funk EP). 7 presets EP. Interruptor Sound ON/OFF. Suporte iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilidade de velocidade (4 par\u00E2metros + visualiza\u00E7\u00E3o de curva). Suporte para bot\u00E3o de oitava Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">V\u00EDdeo</a>',
    vh_250: '<b>V2.50</b> \u2014 M\u00FAltiplos bancos de mem\u00F3ria (16 slots \u00D7 at\u00E9 16 bancos, trocar/duplicar/renomear)',
    vh_218: '<b>V2.18</b> \u2014 Guardado/restauro autom\u00E1tico de todas as defini\u00E7\u00F5es (tonalidade/escala/som/MIDI/mem\u00F3ria)',
    vh_213: '<b>V2.13</b> \u2014 Sobreposi\u00E7\u00E3o de escala de instrumento (guitarra/baixo/piano mostram Available Scale). R\u00F3tulos de grau nos pads. Reprodu\u00E7\u00E3o ligada \u00E0 oitava',
    vh_27: '<b>V2.7</b> \u2014 Modo de adi\u00E7\u00E3o de tens\u00F5es (s\u00EDntese de acordes pad/guitarra/baixo/teclado \u2192 filtragem Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, sobreposi\u00E7\u00E3o de escala nos pads)',
    vh_19: '<b>V1.9</b> \u2014 9 l\u00EDnguas',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 slots de mem\u00F3ria, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Modo Plain, export MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Lan\u00E7amento inicial (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6ªR',
    root_5: '5ªR',
    root_4: '4ªR',
    root_3: '3ªR',
    root_2: '2ªR',
    open: 'Aberta',
    no_open: 'Sem abertas',
    all: 'Todas',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'Para Pad',
    genre_default: 'Padrão',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    'Pressione C para salvar o acorde atual no Memory',
    'Opt+1~V salva diretamente no slot (16 teclas: 1234 QWER ASDF ZXCV)',
    'Shift+Clique num slot de Memory para apagar',
    'Opt+Arrastar para copiar um slot',
    'Pressione S para alternar Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D alterna Drop 2 / Drop 3',
    'Shift+G mostra o braço da guitarra',
    '\u2318\u2325F mostra o Círculo de Quintas',
    'Tab alterna entre modos Scale / Chord / Input',
    'Espaço toca a escala ou acorde atual',
    'Exporte todos os slots de Memory como arquivo MIDI',
    'Conecte um controlador MIDI para tocar os pads',
    'Setas ↓↑ mudam a inversão do acorde',
    'Pressione R para voicing sem fundamental',
    'Pressione O para omitir a 5ª',
    'Shift+S mostra a partitura',
    'O ícone de salvar preserva suas configurações entre sessões',
    '[ ] muda bancos de Memory — gerencie várias músicas',
    'Modo Perform: Dispare acordes com teclado (1234 / QWER / ASDF / ZXCV) ou pads MIDI',
    'Pressione / no modo Chord para digitar nomes de acordes (ex: Cm7, G7(b9,#11))',
  ],
  tips_off: 'Não mostrar dicas',
  whats_new: 'Novidades',
  whats_new_497: 'O tremolo agora \u00E9 fisicamente modelado! Membros HPS obt\u00EAm Pad Sensei MK1 AMP.',
  whats_new_61: 'O manual online já está acessível pelo Guia. Atualmente em construção.',
  whats_new_123: 'O manual online já está acessível pelo Guia. Atualmente em construção.',
  whats_new_51: 'Modo fixo em Dó maior adicionado! Ative pelo menu Ajuda (?). Push/Launchpad mostrará sempre Dó maior.',
  whats_new_50: 'Reverbs spring e plate adicionados! Baxandall Bass/Treble EQ, amp AMP melhorado.',
  whats_new_32427: 'Voicing de guitarra \u2192 refletir no pad (tecla V). Alternância layout estilo guitarra / compacto',
  whats_new_33000: 'Sistema de tutoriais! Clique no \u00EDcone do livro no cabe\u00E7alho para aprender o modo Scale, modo Chord e mais.',
  whats_new_640: 'V6.4.0 já está disponível: deteção de três tensões, análise UST, visualização Note/Degree e escrita # / b conforme a tonalidade.',
  whats_new_650: 'V6.5.0 já está disponível: os voicings HPS TASTY / STOCK / Guitar agora ficam dentro do Chord Builder. A família de sexta usa C6(9) / C6(9,#11), com filtros de guitarra, equilíbrio visual e alcance de reprodução melhorados.',
  whats_new_660: 'V6.6.0 já está disponível: membros HPS agora têm voicings modais por quartas (So What) no TASTY — o som de Miles Davis / McCoy Tyner — para acordes menores, maiores e dominantes. A organização dos tipos no Chord Builder também foi refinada.',
  whats_new_6716: 'V6.7.16 já está disponível: o modo Scale inclui Double Stop para harmonias de duas notas 3rd / 4th / 6th. A deteção UST está mais clara e mostra os graus das notas dentro da estrutura superior.',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Preset de som',
    sound_msg: 'Escolha um preset de som e toque num pad para ouvir.\nORGAN e E.PIANO \u2014 cada um tem m\u00FAltiplos presets.',
    sound_done: 'Soa bem! Prima Seguinte para continuar.',
    midi_title: 'Controlador MIDI',
    midi_msg: 'Foi detetado um controlador MIDI. Selecione o seu dispositivo no menu suspenso.\nA sensibilidade de velocidade pode ser ajustada no painel Sound.',
    midi_no_device: 'Nenhum controlador MIDI detetado \u2014 sem problema.\nPode usar cliques nos pads, entrada de guitarra/baixo/piano ou entrada de texto de acordes.',
    input_title: 'Tr\u00EAs modos',
    input_msg: 'Scale \u2014 ver notas da escala na grelha de 64 pads\nChord \u2014 construir acordes com voicings, invers\u00F5es e tens\u00F5es\nInput \u2014 clicar livremente nos pads para detetar nomes de acordes\n\nMude com Tab ou os bot\u00F5es de modo acima.',
    instruments_title: 'Entrada de instrumentos',
    instruments_msg: 'Guitarra, Baixo, Piano \u2014 ative cada visualiza\u00E7\u00E3o e clique para inserir notas diretamente.\nClique no bra\u00E7o \u2192 dete\u00E7\u00E3o de acorde \u2192 "Para Pad" (V) para converter em layout de pads.\nEntrada de texto: prima / no modo Chord para digitar nomes de acordes (ex. Cm7, G7(b9,#11)).',
    done_title: 'Pronto!',
    done_msg: 'Tudo preparado. Explore livremente \u2014 prima ? para a lista completa de atalhos.\nO manual online tem guias detalhados de cada funcionalidade.',
    next: 'Seguinte',
    skip_step: 'Seguinte',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Manual Online',
    close: 'Come\u00E7ar',
    reset: 'Reiniciar tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    btn_label: 'Tutoriais',
    // Selector UI
    selector_title: 'Tutoriais',
    cat_getting_started: 'Primeiros passos',
    cat_features: 'Funcionalidades',
    cat_advanced: 'Avan\u00E7ado',
    steps_label: 'passos',
    reset_all: 'Reiniciar todo o progresso',
    close_selector: 'Fechar',
    hint_available: 'Tutorial disponível',
    hint_try: 'Experimentar',
    // Shared action labels
    next: 'Seguinte',
    skip_step: 'Seguinte',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Manual Online',
    close: 'Conclu\u00EDdo',
    // Onboarding
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: 'Primeira vez aqui? Quer um tour r\u00E1pido pela app?',
    onboarding_yes: 'Próximo',
    onboarding_no: 'Saltar',
    onboarding_title: 'Primeiros passos',
    onboarding_desc: 'Aprenda os fundamentos do 64 Pad Explorer',
    onboarding: {
      app_version_title: 'Sobre a App Desktop',
      app_version_msg: 'Esta \u00E9 a 64Pad Explorer Desktop (Standalone / VST3 / AU).\n\nVers\u00E3o browser: o motor de \u00E1udio integrado (ORGAN / E.PIANO) reproduz diretamente.\nVers\u00E3o Desktop: sem \u00E1udio integrado. Os pads enviam MIDI \u2014 o som vem de um plugin VST/AU externo (ex. Pad Sensei MK1) na sua DAW ou como plugin carregado. A integra\u00E7\u00E3o com Push 3 est\u00E1 dispon\u00EDvel no modo Standalone.\n\nO tutorial foca na sa\u00EDda MIDI e nas fun\u00E7\u00F5es de visualiza\u00E7\u00E3o.',
      sound_title: 'Preset de som',
      sound_title_desktop: 'Saída de som',
      sound_msg: 'Escolha um preset de som e toque num pad para ouvir.\nORGAN e E.PIANO \u2014 cada um tem m\u00FAltiplos presets.',
      sound_msg_desktop: 'O painel Sound cont\u00E9m defini\u00E7\u00F5es de sa\u00EDda MIDI.\nO \u00E1udio \u00E9 produzido pela sua DAW ou por um plugin VST/AU externo. A sensibilidade de velocidade pode ser ajustada aqui.',
      sound_done: 'Soa bem! Prima Seguinte para continuar.',
      midi_title: 'Controlador MIDI',
      midi_msg: 'Foi detetado um controlador MIDI. Push 3 e Launchpad funcionam imediatamente — sem configuração necessária.\nA sensibilidade de velocidade pode ser ajustada no painel Sound.',
      midi_no_device: 'Nenhum controlador MIDI detetado \u2014 sem problema.\nPode usar cliques nos pads, entrada de guitarra/baixo/piano ou entrada de texto de acordes.',
      input_title: 'Tr\u00EAs modos',
      input_msg: 'Scale \u2014 ver notas da escala na grelha de 64 pads\nChord \u2014 construir acordes com voicings, invers\u00F5es e tens\u00F5es\nInput \u2014 clicar livremente nos pads para detetar nomes de acordes\n\nMude com Tab ou os bot\u00F5es de modo acima.',
      instruments_title: 'Entrada de instrumentos',
      instruments_msg: 'Guitarra, Baixo, Piano \u2014 ative cada visualiza\u00E7\u00E3o e clique para inserir notas diretamente.\nClique no bra\u00E7o \u2192 dete\u00E7\u00E3o de acorde \u2192 "Para Pad" (V) para converter em layout de pads.\nEntrada de texto: prima / no modo Chord para digitar nomes de acordes (ex. Cm7, G7(b9,#11)).',
      done_title: 'Pronto!',
      done_msg: 'Tudo preparado. Explore livremente \u2014 prima ? para a lista completa de atalhos.\nO manual online tem guias detalhados de cada funcionalidade.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Modo Scale',
    scale_mode_desc: 'Explore escalas na grelha de 64 pads',
    scale_mode: {
      step1_title: 'Mudar para o modo Scale',
      step1_msg: 'O modo Scale ilumina as notas da escala na grelha.\nToque em qualquer pad iluminado para ouvir a nota.',
      step2_title: 'Escolha uma tonalidade',
      step2_msg: 'Escolha uma tonalidade raiz. A grelha atualiza-se instantaneamente.\nExperimente alternar entre C, G, F \u2014 ou\u00E7a como o padr\u00E3o de cores muda.',
      step3_title: 'Escolha uma escala',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 escalas dispon\u00EDveis. Os pads atualizam-se em tempo real.',
      step4_title: 'Barra diat\u00F3nica',
      step4_msg: 'Os acordes diat\u00F3nicos da sua escala aparecem aqui.\nClique em qualquer acorde para ir ao modo Chord com esse voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Modo Chord',
    chord_mode_desc: 'Construa acordes passo a passo',
    chord_mode: {
      step1_title: 'Mudar para o modo Chord',
      step1_msg: 'O modo Chord oferece duas formas de selecionar acordes.\n① Escolha na barra diatónica com um clique\n② Construa o seu: Root → Quality → Tension',
      step_key_title: 'Sele\u00E7\u00E3o de tonalidade',
      step_key_msg: 'Defina a tonalidade da escala. Quando uma Key est\u00E1 definida, a barra diat\u00F3nica mostra acordes e a disponibilidade de tens\u00F5es \u00E9 filtrada.\nTamb\u00E9m pode construir acordes livremente a partir da Root sem usar Key.',
      step_diatonic_title: 'Barra diat\u00F3nica',
      step_diatonic_msg: 'Acordes diat\u00F3nicos da Key selecionada.\nClique para definir instantaneamente um acorde com filtragem de tens\u00F5es baseada na escala.',
      step2_title: 'Passo 1: Root',
      step2_msg: 'Escolha uma nota fundamental. C, D, E... todas as 12 notas.\nO visor mostra o seu acorde atual.',
      step3_title: 'Passo 2: Quality',
      step3_msg: 'Escolha o tipo de acorde: Maj, min, 7, m7, dim, aug...\nA grelha ilumina as notas do acorde.',
      step4_title: 'Passo 3: Tensions',
      step4_msg: 'Escolha primeiro uma Quality \u2014 os bot\u00F5es de tens\u00E3o aparecem automaticamente.\n9, b9, #9, 11, #11, 13, b13. V\u00E1rias tens\u00F5es podem ser selecionadas.',
      step5_title: 'Entrada de texto',
      step5_msg: 'Digite nomes de acordes diretamente com a tecla /.\nSlash chords e voicings complexos podem ser inseridos rapidamente.',
      step6_title: 'Encontrar escalas de dominante secundária',
      step6_msg: 'Insira diretamente um acorde não diatónico.\nExemplo: Input G7 → Available Scale mostra "Mixolydian", "Mixolydian b13", etc.\nMude para Practical sort para ver primeiro as escalas mais úteis.\nAssim encontra a escala certa para as dominantes secundárias.',
      step7_title: 'Slash Chords',
      step7_msg: 'Clique em / no construtor de acordes para inserir uma nota de baixo para Slash Chords.\nTambém pode digitar C/D ou F△7/G na entrada de texto.\nAvailable Scale atualiza-se para corresponder ao Slash Chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Modo Input',
    input_mode_desc: 'Insira acordes via controlador MIDI, pads, braço ou teclado',
    input_mode: {
      step1_title: 'Mudar para o modo Input',
      step1_msg: 'Insira acordes via controlador MIDI, clicando nos pads, braço ou teclado.\nA deteção de acordes funciona em todos os modos.',
      step2_title: 'Toque em alguns pads',
      step2_msg: 'Clique em quaisquer pads na grelha.\nCada toque ativa ou desativa uma nota.',
      step3_title: 'Dete\u00E7\u00E3o de acordes',
      step3_msg: 'O nome do acorde detetado aparece acima da grelha.\nR\u00F3tulos de grau (R, 3, 5, b7...) aparecem em cada pad.',
      step4_title: 'Guardar com Capture',
      step4_msg: 'A tecla <strong>C</strong> guarda o acorde atual no pr\u00F3ximo slot de mem\u00F3ria.\nConstrua progress\u00F5es de acordes uma a uma.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Barra diat\u00F3nica',
    diatonic_desc: 'Acesso com um clique aos acordes diat\u00F3nicos',
    diatonic: {
      step1_title: 'A barra diat\u00F3nica',
      step1_msg: 'Cada escala tem o seu pr\u00F3prio conjunto de acordes diat\u00F3nicos.\nEles aparecem aqui \u2014 prontos para tocar.',
      step2_title: 'Tr\u00EDade / T\u00E9trade',
      step2_msg: 'Alterne entre tr\u00EDades de 3 notas e acordes de s\u00E9tima de 4 notas.\nA barra atualiza-se instantaneamente.',
      step3_title: 'Clique num acorde',
      step3_msg: 'Clique num acorde na barra.\nPode transform\u00E1-lo com tens\u00F5es e mais no Chord Builder.',
      step4_title: 'Atalho de teclado',
      step4_msg: 'Prima 1\u20137 para selecionar acordes diat\u00F3nicos instantaneamente.\nSem necessidade de rato.',
      step5_title: 'Dominante secund\u00E1ria',
      step5_msg: 'Ative "Secondary Dominant" (\u2318\u2325D).\nOs acordes V7 que resolvem para cada acorde diat\u00F3nico s\u00E3o mostrados.\nClique num e Available Scale exibe-se automaticamente.\nResolu\u00E7\u00E3o para maior \u2192 Mixolydian. Resolu\u00E7\u00E3o para menor \u2192 HMP5\u2193/Altered.',
      step6_title: 'Atalhos de teclado',
      step6_msg: 'Prima 1\u20137 para acordes diat\u00F3nicos.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Tonalidade paralela) para barras de extens\u00E3o.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Guarde acordes e toque-os ao vivo',
    memory: {
      step1_title: 'Guardar um acorde',
      step1_msg: 'Guarde os seus acordes favoritos.\nGuardar voicings que gosta ajuda no beat-making e na pr\u00E1tica.',
      step2_title: '16 slots de mem\u00F3ria',
      step2_msg: 'Funciona como um layout Drumrack de 16 pads no PUSH, Launchpad, MPC e Maschine \u2014 intuitivo de usar.',
      step3_title: 'Bancos de mem\u00F3ria',
      step3_msg: 'No PUSH e Launchpad, o layout Drumrack torna o uso intuitivo.',
      step4_title: 'Modo Perform',
      step4_msg: 'As teclas do teclado do PC tamb\u00E9m correspondem aos 16 pads.',
      step5_title: 'Exporta\u00E7\u00E3o MIDI',
      step5_msg: 'Exporte todos os acordes em mem\u00F3ria como ficheiro MIDI.\nArraste para o seu DAW e comece a produzir.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Molde os seus voicings de acordes',
    voicing: {
      step1_title: 'Controlos de voicing',
      step1_msg: 'No modo Chord Builder, v\u00E1rias transforma\u00E7\u00F5es s\u00E3o poss\u00EDveis a partir da forma b\u00E1sica.\nOmit, Shell, Inversion, Drop \u2014 tudo aqui.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> \u00E9 para Shell voicing. Aprenda voicings R37 e R73 de forma fluida no pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'As teclas de atalho s\u00E3o frequentemente definidas como mnem\u00F3nicas.\n<strong>O</strong>mit = omitir a 5\u00AA. <strong>R</strong>ootless = voicing sem fundamental.',
      step4_title: 'Invers\u00F5es',
      step4_msg: 'Ao contr\u00E1rio da maioria dos softwares, pode criar invers\u00F5es ultra-rapidamente.\nTamb\u00E9m ajuda a entender slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Para quando quer destacar a nota superior \u2014\nDrop voicings tamb\u00E9m s\u00E3o suportados.',
      step6_title: 'Voicing Box',
      step6_msg: 'Os pads podem ter v\u00E1rias op\u00E7\u00F5es de posi\u00E7\u00E3o. A Voicing Box trata disso.\nClique em a, b, c, d etc. no pad, ou digite a letra, para ver v\u00E1rias possibilidades de voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, efeitos e volume',
    sound: {
      step1_title: 'Presets de som',
      step1_title_desktop: 'Saída MIDI',
      step1_msg: 'ORGAN (4 tipos) e E.PIANO (8 tipos).\nClique num pad ou use o seu controlador MIDI.',
      step1_msg_desktop: 'A vers\u00E3o Desktop n\u00E3o tem \u00E1udio integrado.\nClicar num pad envia notas MIDI. Carregue um plugin VST/AU (ex. Pad Sensei MK1) na sua DAW ou como plugin alojado para produzir som.\nA sensibilidade de velocidade pode ser ajustada aqui.',
      step2_title: 'Painel de detalhes',
      step2_msg: 'Clique em \u25BC para expandir o painel de detalhes de som.\nEfeitos, volume e controlos de filtro est\u00E3o aqui.',
      step3_title: 'Efeitos',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nAjuste-os no painel de detalhes.',
      step4_title: 'Som ON/OFF',
      step4_msg: 'Ative e desative o som com o \u00EDcone do altifalante.\nDesligar pode ser conveniente ao usar uma DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings classificados por nota superior. Apenas membros HPS',
    tasty: {
      step1_title: 'Ativar TASTY',
      step1_msg: 'Selecione voicings sofisticados que a l\u00F3gica simples n\u00E3o consegue produzir.\nPensar a partir da nota superior \u00E9 \u00FAtil para arranjos de cordas e metais.\n(Apenas membros HPS)',
      step2_title: 'Ciclar receitas',
      step2_msg: 'Teclas Z / X para explorar voicings para a frente/trás.\nO contador mostra a sua posição.',
      step3_title: 'Nota\u00E7\u00E3o de graus',
      step3_msg: 'A \u00E1rea de info mostra o empilhamento de graus \u2014 ex. m9 (b3-b7-9-5-1).\nEsta \u00E9 a estrutura do voicing de baixo para cima.',
      step4_title: 'Para Pad',
      step4_msg: 'Otimiza\u00E7\u00E3o de pad que software convencional n\u00E3o consegue.\nDesfrute de tocar voicings elegantes nos pads tamb\u00E9m.',
      fb_step1_title: 'O que é TASTY Voicing?',
      fb_step1_msg: '129 voicings sofisticados ordenados por nota superior.\nSuporta Maj7 / Dom7 / Min7. Apresentado em notação de graus.\nApenas membros HPS.',
      fb_step2_title: 'Como aceder ao TASTY',
      fb_step2_msg: 'Disponível ao aderir ao HPS (Hardcore Pad Style).\nPrima T no modo Chord para ativar. Teclas Z/X para explorar voicings.\nVer o Guia para mais detalhes.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicings idiom\u00E1ticos cl\u00E1ssicos de piano. Apenas membros HPS',
    stock: {
      step1_title: 'Ativar STOCK',
      step1_msg: 'Conhecer voicings espec\u00EDficos do piano ajuda a libertar-se de tocar apenas na forma b\u00E1sica.\n154 voicings de piano em nota\u00E7\u00E3o de graus.\n(Apenas membros HPS)',
      step2_title: 'Ciclar voicings',
      step2_msg: 'Teclas Z / X para explorar voicings para a frente/trás.',
      step3_title: 'Vista de teclado',
      step3_msg: 'Ative a visualiza\u00E7\u00E3o de Piano para ver as posi\u00E7\u00F5es reais.\nO voicing ganha vida no teclado.',
      step4_title: 'Para Pad',
      step4_msg: 'Clique em "Para Pad" para mapear o voicing no layout dos pads.\nGuarde na mem\u00F3ria e exporte para o seu DAW.',
      fb_step1_title: 'O que é STOCK Voicing?',
      fb_step1_msg: 'Apresenta voicings de piano comummente usados.\nA notação de graus mostra-lhe a estrutura.\nApenas membros HPS.',
      fb_step2_title: 'Como aceder ao STOCK',
      fb_step2_msg: 'Disponível ao aderir ao HPS (Hardcore Pad Style).\nPrima K no modo Chord para ativar.\nVer o Guia para mais detalhes.',
    },
    // Circle of Fifths tutorial
    circle_title: 'C\u00EDrculo de quintas',
    circle_desc: 'Rela\u00E7\u00F5es entre tonalidades num relance',
    circle: {
      step1_title: 'Abrir o c\u00EDrculo',
      step1_msg: 'Prima ⌘⌥F ou clique no botão Circle.\nO círculo de quintas aparece em baixo.',
      step2_title: 'Liga\u00E7\u00E3o de tonalidade',
      step2_msg: 'Verifique rapidamente acordes de substitui\u00E7\u00E3o e diat\u00F3nicos importantes para performance e composi\u00E7\u00E3o.',
      step3_title: 'Fun\u00E7\u00F5es diat\u00F3nicas',
      step3_msg: 'Ao contr\u00E1rio do c\u00EDrculo de quintas t\u00EDpico, o 64 Pad Explorer permite selecionar 3 tipos de menor (Natural/Harmonic/Melodic) ao escolher uma tonalidade menor.\nFacilita o dom\u00EDnio das tonalidades menores mais complexas.',
      step4_title: 'Selecionar uma tonalidade menor',
      step4_msg: 'O anel interior do círculo mostra tonalidades menores.\nClique numa tonalidade do anel interior para selecionar uma tonalidade menor.\nA visualização de acordes diatónicos irá mudar.',
      step5_title: '3 tipos de escala menor',
      step5_msg: 'Quando uma tonalidade menor está selecionada, os botões Nat / Harm / Mel aparecem no centro.\nNat = Natural Minor (forma padrão)\nHarm = Harmonic Minor (V7 aparece)\nMel = Melodic Minor (os graus VI, VII mudam)',
      step6_title: 'Experimente mudar',
      step6_msg: 'Clique em Nat \u2192 Harm \u2192 Mel e observe como os acordes diat\u00F3nicos mudam.\nNote como V7 aparece em Harmonic Minor.',
    },
    // Guitar tutorial
    guitar_title: 'Diagrama de guitarra',
    guitar_desc: 'Insira acordes a partir da guitarra e reflita nos pads',
    guitar: {
      step1_title: 'Mostrar bra\u00E7o de guitarra',
      step1_msg: 'Prima \u2318\u2325G ou clique no bot\u00E3o Guitar.\nAs notas do acorde aparecem no bra\u00E7o.',
      step2_title: 'Ver posi\u00E7\u00F5es de acorde',
      step2_msg: 'Selecione um acorde no modo Chord e o bra\u00E7o mostra automaticamente as posi\u00E7\u00F5es correspondentes.\nUse v\u00EDrgula (,) e ponto (.) para percorrer as posi\u00E7\u00F5es.',
      step3_title: 'Inserir a partir de guitarra',
      step3_msg: 'Mude para o modo Input. Tente clicar nos trastes do bra\u00E7o para inserir notas.\nOs nomes dos acordes s\u00E3o detetados em tempo real.',
      step4_title: 'Refletir no pad',
      step4_msg: '"Refletir no pad" mapeia o voicing de guitarra para a grelha de pads.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Atalhos de teclado',
    shortcuts_desc: 'Teclas essenciais para opera\u00E7\u00E3o eficiente',
    shortcuts: {
      step1_title: 'Mudar modo',
      step1_msg: 'Tab \u2014 Mudar modo (Scale \u2192 Chord \u2192 Input)\nShift+Tab \u2014 Dire\u00E7\u00E3o inversa\n\nMude rapidamente entre modos.',
      step2_title: 'Diat\u00F3nica & navega\u00E7\u00E3o',
      step2_msg: '1\u20137 \u2014 Selecionar acorde diat\u00F3nico\n\u2191\u2193 \u2014 Percorrer invers\u00F5es\n\u2190\u2192 \u2014 Transpor fundamental por semitom (mant\u00E9m a forma)\n\nOpere acordes sem rato.',
      step3_title: 'Opera\u00E7\u00F5es de voicing',
      step3_msg: 'S \u2014 Ciclo Shell (off \u2192 1-3-7 \u2192 1-7-3)\nO \u2014 Alternar Omit 5\nR \u2014 Alternar Rootless\nShift+D \u2014 Ciclo Drop (off \u2192 Drop2 \u2192 Drop3)\nT \u2014 TASTY ON/OFF, K \u2014 STOCK ON/OFF\nZ / X \u2014 voicing TASTY/STOCK anterior/seguinte\n\u2190\u2192 \u2014 Transpor voicing por semitom (durante TASTY/STOCK)\nV \u2014 Refletir no pad / alternar layout\n/ \u2014 Entrada de texto de acorde',
      step4_title: 'Mem\u00F3ria & bancos',
      step4_msg: 'Option+1234/qwer/asdf/zxcv \u2014 Guardar no slot\n[ ] \u2014 Mudar banco\nM \u2014 Alternar vista mem\u00F3ria\nP \u2014 Alternar modo Perform\nSpace \u2014 Reproduzir\nShift+Space \u2014 Reproduzir tudo (sequencial)',
      step5_title: 'Mais',
      step5_msg: '? \u2014 Ajuda (lista completa de atalhos)\n\u2318\u2325+G/B/P/F/S \u2014 Alternares Instrumento/C\u00EDrculo/Pauta\n\u2318\u2325+A/M/T/Q/V/K/H \u2014 Alternares de sec\u00E7\u00F5es\nCmd/Ctrl+Z \u2014 Desfazer (at\u00E9 30 vezes)\nEsc \u2014 Desselecionar / Fechar modais',
    },
    // Settings tutorial
    settings_title: 'Visualiza\u00E7\u00E3o & Defini\u00E7\u00F5es',
    settings_desc: 'Personalize o seu espa\u00E7o de trabalho',
    settings: {
      step1_title: 'Pain\u00E9is de instrumentos',
      step1_msg: 'A visualiza\u00E7\u00E3o Guitar exibe voicings comuns quando seleciona um acorde no Chord Builder.\nNo modo Input, tamb\u00E9m pode inserir a partir de guitarra, baixo e teclado.',
      step2_title: 'Nomes / Graus',
      step2_msg: 'Alterne entre nomes de notas (C, D, E) e graus (R, 2, 3).\nAplica-se aos pads e \u00E0 visualiza\u00E7\u00E3o de guitarra.',
      step3_title: 'Deslocamento de oitava',
      step3_msg: 'Use ▲▼ para deslocar a extensão dos pads uma oitava acima ou abaixo.\nOs botões de oitava do Push 3 e Launchpad sincronizam-se automaticamente.',
      step4_title: 'Alternar secções',
      step4_msg: '⌘⌥+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) para recolher secções.\nMostre apenas o que precisa.',
      step5_title: 'Ordem de layout',
      step5_msg: 'Em ? Ajuda, use o menu suspenso "Layout" para reordenar os 3 painéis.\n6 presets: Chord, Pad, Circle em qualquer ordem.\nNo mobile, a ordem de deslizamento também muda.',
      step6_title: 'Guardar tudo',
      step6_msg: 'Clique no ícone de guardar para preservar todas as definições.\nTonalidade, escala, som, memória, voicing — tudo é preservado.',
    },
    // Link Mode tutorial
    link_title: 'Modo Link',
    link_desc: 'Sincronizar notas tocadas em todos os instrumentos',
    link: {
      step1_title: 'Bot\u00E3o Link',
      step1_msg: 'O bot\u00E3o Link est\u00E1 ao lado de Guitar / Bass / Piano.\nAtive-o para ver as notas tocadas em todos os instrumentos em tempo real.',
      step2_title: 'Modo Link ON',
      step2_msg: 'Quando o Link est\u00E1 ativo, os instrumentos ficam atenuados.\nToque pads ou MIDI \u2014 apenas as notas tocadas acendem.',
      step3_title: 'Toque nos pads',
      step3_msg: 'Prima um pad e observe a mesma nota acender na guitarra, baixo e piano.\nVeja quais posi\u00E7\u00F5es em cada instrumento produzem o mesmo tom.\nSolte para limpar.',
      step4_title: 'Atalho',
      step4_msg: '\u2318\u2325+L alterna o modo Link ON/OFF.\nPerfeito para aprender como as notas se mapeiam entre instrumentos.',
    },
    // Minor 3 Scales tutorial
    minor_scales_title: 'Comparar 3 escalas menores',
    minor_scales_desc: 'Natural, harm\u00F3nica e mel\u00F3dica lado a lado',
    minor_scales: {
      step1_title: 'Definir uma tonalidade menor',
      step1_msg: 'Am (menor natural) est\u00E1 selecionada.\nA barra diat\u00F3nica mostra os acordes de menor natural.',
      step2_title: 'Ativar Harm/Mel',
      step2_msg: 'Clique em "Harm/Mel" (\u2318\u2325N).\nOs acordes diat\u00F3nicos de menor harm\u00F3nica e mel\u00F3dica aparecem abaixo.',
      step3_title: 'Comparar',
      step3_msg: 'Observe as diferen\u00E7as em rela\u00E7\u00E3o \u00E0 menor natural (barra superior).\nNa HM, o acorde V muda de Em7 para E7 \u2014 permitindo movimento dominante.\nNa MM, o acorde IV tamb\u00E9m muda de Dm7 para D7.\nClique em qualquer acorde para v\u00EA-lo nos pads.',
      step4_title: 'Tonalidade paralela',
      step4_msg: 'Ative "Parallel Key" (\u2318\u2325R) para ver a diat\u00F3nica maior da mesma fundamental.\nIsto revela a origem dos acordes emprestados (interc\u00E2mbio modal).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Dominante secund\u00E1ria',
    secdom_desc: 'Experimente a porta de entrada para a modula\u00E7\u00E3o',
    secdom: {
      step1_title: 'Come\u00E7ar em C maior',
      step1_msg: 'C Major est\u00E1 definido.\nA barra diat\u00F3nica mostra C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Ativar dominante secund\u00E1ria',
      step2_msg: 'Clique em "Secondary Dominant" (\u2318\u2325D).\nOs acordes V7 que resolvem para cada acorde diat\u00F3nico aparecem.\nEm C Major: C7, D7, E7, A7, B7 (5 no total).',
      step3_title: 'Resolu\u00E7\u00E3o para maior',
      step3_msg: 'Clique em C7 (\u2192F\u25B37) ou D7 (\u2192G7).\nAvailable Scale mostra Mixolydian como primeira op\u00E7\u00E3o.\nPorque o alvo de resolu\u00E7\u00E3o \u00E9 um acorde maior.',
      step4_title: 'Resolu\u00E7\u00E3o para menor',
      step4_msg: 'Clique em A7 (\u2192Dm7) ou E7 (\u2192Am7).\nAvailable Scale mostra HMP5\u2193 (Phrygian Dominant) e Altered como primeiras op\u00E7\u00F5es.\nPorque o alvo de resolu\u00E7\u00E3o \u00E9 um acorde menor.',
      step5_title: 'A regra: apenas 2 tipos',
      step5_msg: 'A sele\u00E7\u00E3o de escala para dominantes secund\u00E1rias \u00E9 simples:\n\u2022 Resolu\u00E7\u00E3o para maior \u2192 Mixolydian\n\u2022 Resolu\u00E7\u00E3o para menor \u2192 HMP5\u2193 ou Altered\n\u00C9 tudo o que precisa de lembrar.',
    },
  },
});
