// English (fallback)
I18N.addLang('en', {
  help: {
    title: '64 Pad Explorer',
    description: 'A tool for exploring scales, chords, and voicings on a 64-pad grid.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Choose from 12 keys',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more \u2014 31 types',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Shows diatonic chords for the selected scale. Click to enter Chord mode',
    chord_mode: 'Chord Mode (3 Steps)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Select root on the piano keyboard',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Choose chord type (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Add tensions (9, b9, #9, 11, #11, 13, b13, etc.). Multiple selections OK',
    chord_text: '<strong>Text Input</strong> \u2014 Press "/" to focus. Type Cm7, G7(b9,#11), Am7/G etc. directly. Autocomplete suggestions appear',
    chord_onchord: '<strong>On Chord</strong> \u2014 Use the "/" button for slash chords (chord over bass note)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omit notes',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 to add notes)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversions (Root, 1st, 2nd, 3rd)',
    inv_1: '1st Inversion',
    inv_2: '2nd Inversion',
    inv_3: '3rd Inversion',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Tap to cycle through pad layout options (a count like A1/3 means alternative layouts exist)',
    display: 'Display',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Toggle guitar fretboard, bass, piano keyboard, and staff notation independently',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Displays the circle of fifths. Linked to key selection, showing diatonic chords and functions (T/SD/D). Minor mode switching supported',
    display_label: '<strong>Note Name / Degree</strong> \u2014 Switch between note names (C, D, E) and degrees (R, 2, 3) on guitar and pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Shift pad range by octave',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Toggle sound on/off with the speaker icon',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Rhodes physical modeling. HPS members can select the Suitcase preset (physically modeled amp chain). \u25BC opens the detail panel',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Peterson Vactrol physical modeling (stereo). Use TREM/T.SPD for depth and rate',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 Pad Sensei MK1 (Physical Modeling) + Sampler',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Envelope filter (Auto-Wah). 3 types: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Analog saturation. Adds warm overdrive to the sound',
    sound_fx: '<strong>Effects</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Click a pad or voicing box to play sound',
    midi: 'MIDI',
    midi_detect: 'Auto-detects WebMIDI-compatible devices',
    midi_push: 'Supports Ableton Push serial MIDI output',
    midi_chord: 'Auto-identifies chords from input notes',
    midi_sustain: '<strong>Sustain pedal</strong> \u2014 MIDI CC64 (Hold Pedal) supported',
    color_title: 'Color Legend',
    color_root: '<strong>Root</strong> \u2014 Root note',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Scale notes / Chord tones',
    color_char: '<strong>Characteristic</strong> \u2014 Notes that define the scale/chord',
    color_3rd: '<strong>3rd</strong> \u2014 Guide tone (3rd)',
    color_7th: '<strong>7th</strong> \u2014 Guide tone (7th)',
    color_tension: '<strong>Tension</strong> \u2014 Tension notes',
    color_avoid: '<strong>Avoid</strong> \u2014 Scale note a half step above a chord tone (in Chord mode)',
    color_palette: 'Color palette: Okabe-Ito (color vision accessible)',
    input_title: 'Guitar / Piano Input',
    input_desc1: 'Click the guitar fretboard or piano keyboard to input notes',
    input_desc2: 'Chords are auto-identified from input and reflected on the pad',
    input_desc3: '<strong>Clear</strong> \u2014 Clear input, <strong>Play \u25B6</strong> \u2014 Play input notes',
    input_title: 'Input Mode',
    input_desc1: 'Click pads freely to select notes \u2192 Real-time chord identification',
    input_desc2: 'No theory filter. Explore \u2192 discover \u2192 learn theory afterward',
    input_desc3: 'When a chord is detected, degree labels (R, 3, 5, b7, etc.) appear on pads. Guitar, bass, piano, and staff update automatically',
    input_memory: '<strong>Memory</strong> \u2014 Save and recall chords in 16 slots',
    input_banks: '<strong>Banks</strong> \u2014 16 slots \u00D7 up to 16 banks. Switch with <kbd>[</kbd> <kbd>]</kbd>. Duplicate and rename supported',
    input_export: '<strong>MIDI Export</strong> \u2014 Export memory chords as a MIDI file',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> button or <kbd>p</kbd> key to switch',
    perform_desc1: 'Play memory slot chords in real-time with a 16-pad layout',
    perform_desc2: 'Trigger via keyboard (4\u00D74 grid) or MIDI pads',
    perform_desc3: 'Drag & drop slots to reorder',
    shortcut_title: 'Keyboard Shortcuts',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Select diatonic chord (7-note scales)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Select voicing box (cycles alternatives)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Cycle inversions (Chord mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic root transpose',
    sc_omit: '<kbd>o</kbd> \u2014 Toggle Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Toggle Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Cycle Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Cycle Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: '<kbd>Shift</kbd>+<kbd>g</kbd> / <kbd>v</kbd> \u2014 Guitar engine ON/OFF (show selected guitar voicing on the 64-pad grid)',
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Cycle guitar position (prev / next)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Cycle bass position (prev / next)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Clear chord (Chord mode)',
    sc_pad_explore: '<b>Pad (Chord mode)</b> \u2014 Click pad to toggle note \u2014 builder updates automatically',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Start Capture / save to next slot',
    sp_end: '<kbd>e</kbd> \u2014 End Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recall memory slot (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatic transpose (all notes \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversion (lowest \u21911oct / highest \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Clear all',
    sp_transfer: '<b>Chord switch</b> \u2014 Transfer detected chord to Chord mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74 grid triggers slots 1\u201316',
    pf_midi: 'MIDI pads (notes 36\u201354) also trigger slots',
    shortcut_common: 'Common (All Modes)',
    sc_perform: '<kbd>p</kbd> \u2014 Toggle Perform view',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Undo memory slots (up to 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Save the current chord / voicing to a Memory Slot',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Save the current chord / voicing to a Memory Slot',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 Save directly to a Memory Slot (16 slots)',
    sc_space: '<kbd>Space</kbd> \u2014 Play current chord',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deselect voicing box / close Help',
    sc_help: '<kbd>?</kbd> \u2014 Toggle Help',
    sc_slash: '<kbd>/</kbd> \u2014 Focus text chord input',
    sc_tasty_nav: '<kbd>z</kbd> / <kbd>x</kbd> \u2014 TASTY/STOCK/Guitar voicing prev/next',
    shortcut_display: 'Display Toggle (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitar',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Bass',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Circle of Fifths',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Staff',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Text Input',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Key Display',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 Header / Info Bar',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    sc_cmd_harmonic: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>J</kbd> \u2014 T/SD/D',
    tips_toggle: 'Show startup tips',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Lock to C Major',
    perform_same_notes: 'Show only played notes in Perform',
    perform_same_notes_tip: 'On shows only the exact recorded pitches in Perform. Off collapses the playing voicing to one educational position.',
    color_coding_toggle: 'Color characteristic & chord tones',
    c_fixed_tip: 'Pad always displays C Major scale regardless of Key/Scale/Chord selection. Pad layout stays physical — key is cognitive (like piano). This is the instrument-correct behavior.',
    layout: 'Layout',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Characteristic',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
    scale_root: 'Scale root',
  },
  ui: {
    close: 'Close',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Save Settings',
    sound_hint: 'Select a sound preset to enable audio',
    tap_to_start: 'Tap to start playing',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: 'Tap any pad to play!',
    input_keys_disabled: 'Key selection is not used in Input mode',
    load_vst: 'Load VST/AU Plugin...',
    affiliate_label: '',
    staff: 'Staff',
    circle: 'Circle',
    help: 'Help',
    view_settings: 'View Settings',
    show_all_positions: 'All Positions',
    view_focus: 'Focus',
    view_layout: 'Layout',
    view_all: 'All panes',
    view_pad: 'Pad only',
    view_chord: 'Chord builder only',
    view_info: 'Info / Memory only',
    layout_abc: 'Pad → Chord → Circle',
    layout_acb: 'Pad → Circle → Chord',
    layout_bac: 'Chord → Pad → Circle',
    layout_bca: 'Chord → Circle → Pad',
    layout_cab: 'Circle → Pad → Chord',
    layout_cba: 'Circle → Chord → Pad',
    view_setup_note: 'In the Desktop version, Push 3 Setup also opens this screen. Jog Wheel left/right selects Focus or Layout, turn changes the value, and Jog Wheel press or Setup closes it.',
    oct_down: 'Shift octave down',
    oct_up: 'Shift octave up',
    toggle_guitar: 'Show/hide guitar fretboard (⌘⌥G)',
    toggle_bass: 'Show/hide bass fretboard (⌘⌥B)',
    toggle_piano: 'Show/hide piano keyboard (⌘⌥P)',
    mode_scale: 'Scale mode \u2014 view scale notes on the pad (Tab to cycle)',
    mode_chord: 'Chord mode \u2014 build chords with voicings (Tab to cycle)',
    mode_input: 'Input mode \u2014 tap pads freely to detect chords (Tab to cycle)',
    play_chord: 'Play current chord (Space)',
    toggle_staff: 'Show/hide staff notation (⌘⌥S)',
    toggle_circle: 'Show/hide circle of fifths (⌘⌥F)',
    toggle_sound: 'Show/hide sound controls',
    sound_mute: 'Sound ON/OFF',
    sound_expand: 'Show/hide detailed sound settings',
  },
  label: {
    note_name: 'Note',
    degree: 'Degree',
    chord_input: 'Enter a chord',
    chord_hint: 'Tensions in ( ): C7(b9,#11) | dim, h=m7♭5 supported',
    key_hint: 'Also settable via Scale mode or Circle of Fifths',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'My Blog',
    guide: 'Guide',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Press Capture to start building chords',
    status_capturing: 'Capturing: Slot {slot}/16 \u2014 Click pads, then Capture to save',
    status_editing: 'Editing: Slot {slot} \u2014 Click pads to modify',
    notes_label: 'Notes: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    memory_full: 'Memory slots are full',
    no_current_chord: 'No current chord to save',
    slot_selected: 'Slot {slot} selected',
    slot_cleared: 'Slot {slot} cleared',
    undo: 'Undo',
    settings_saved: 'Settings saved',
    no_chords: 'No chords in memory slots',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    note_count: '{n} notes',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Select root',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Slot {slot}: Empty',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    recall: 'Recall',
    play: 'Play',
    duplicate: 'Duplicate',
    delete: 'Delete',
    save_here: 'Save here',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Click to rename bank',
    rename: 'Rename',
    duplicate: 'Duplicate',
    delete: 'Delete',
    rename_prompt: 'Enter bank name:',
    confirm_delete: 'Delete "{name}"?',
    limit_reached: 'Maximum 16 banks',
    cannot_delete_last: 'Cannot delete the last bank',
  },
  diatonic: {
    parallel: 'Parallel Key',
    relative: 'Relative',
    harm_mel: 'Harm/Mel',
    secdom: 'Secondary Dominant',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Show all',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Guide',
    tagline: 'A browser tool for exploring scales, chords, and voicings on a 64-pad grid.<br>No sound source needed \u2014 just Chrome.',
    cta: 'Open App',
    features: 'Features',
    feat_sound: '<strong>No sound source needed</strong> \u2014 Sound plays right in Chrome. 4 organ + 8 electric piano presets built in. Effects (drive, reverb, phaser, flanger, tremolo, lo cut, hi cut, auto filter) included',
    feat_input: '<strong>No pad skills required</strong> \u2014 Build chords in 3 steps. Tensions displayed. Click pads to input directly',
    feat_text_input: '<strong>Text Chord Input</strong> \u2014 Press "/" to type Cm7, G7(b9,#11), Am7/G etc. directly. Autocomplete suggestions. Abbreviations like dim, h(=m7\u266D5) supported',
    feat_detect: '<strong>Chord detection</strong> \u2014 Real-time chord name detection from clicked notes. Supports omit, slash chords, and multiple candidates',
    feat_instruments: '<strong>Guitar / Bass / Keyboard display</strong> \u2014 Shows chord tones on guitar fretboard, bass, and piano. Guitar fingering input auto-reflects on pads. In Chord mode, positions are grouped by root string',
    feat_scales: '<strong>Scale display</strong> \u2014 31 scales \u00D7 12 keys. Diatonic, Harmonic Minor, Melodic Minor, Pentatonic, Bebop, and more',
    feat_diatonic: '<strong>Diatonic chord display</strong> \u2014 Diatonic chords shown on a bar for the selected scale. Click or use shortcuts to play instantly. Triad/tetrad toggle supported',
    feat_voicing: '<strong>Voicing operations</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Arrow keys for inversions, buttons for multiple fingerings',
    feat_memory: '<strong>Chord memory</strong> \u2014 Save favorite chords to 16 slots. Export as MIDI files for your DAW',
    feat_perform: '<strong>Perform mode</strong> \u2014 Play memory chords in real-time using 16 pads or your PC keyboard',
    feat_parent: '<strong>Available Scale reverse lookup</strong> \u2014 Find scales that contain your chord. See available tensions at a glance. Practical/Diatonic sort toggle',
    feat_pivot: '<strong>Pivot chord thinking</strong> \u2014 Manually input a chord and the diatonic bar disappears, showing all keys your chord could belong to. Perfect for modulation analysis',
    feat_dimming: '<strong>Tension practical display</strong> \u2014 For non-dominant 7th chords, uncommon tensions (b9, #9, b13, etc.) are dimmed. Still selectable',
    feat_circle: '<strong>Circle of Fifths</strong> \u2014 Displays the circle of fifths. Linked to key selection, showing diatonic chords and functions (T/SD/D). Minor mode switching supported',
    feat_banks: '<strong>Memory banks</strong> \u2014 16 slots \u00D7 up to 16 banks. Switch, duplicate, and rename banks. <kbd>[</kbd> <kbd>]</kbd> keys to switch',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Envelope filter (Auto-Wah). 3 types: Cry Baby / Mu-Tron / Moog. Adjust frequency, resonance, sensitivity, and decay',
    feat_drive: '<strong>Drive</strong> \u2014 Analog saturation. Adds warm overdrive to the sound',
    feat_clav: '<strong>Clavinet presets</strong> \u2014 2 clavinet presets added to E.PIANO (Clav Muted, Clav Bright). Perfect for funk',
    feat_midi_sens: '<strong>MIDI velocity sensitivity</strong> \u2014 Push 3-style 4-parameter (Threshold, Drive, Compand, Range) velocity curve adjustment. Real-time curve visualization. Works with all MIDI controllers',
    feat_push_oct: '<strong>Push 3 octave sync</strong> \u2014 Push 3 octave \u25B2\u25BC buttons auto-sync with the app\u2019s octave shift',
    feat_i18n: '<strong>Multilingual</strong> \u2014 9 languages (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshots',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Select a key and scale to see scale notes color-coded on the 64-pad grid. Choose chords from the diatonic bar.',
    ss_scale_alt: 'Scale Mode \u2014 C Major (Ionian) scale display',
    ss_scale_caption: 'C Major (Ionian) \u2014 Root (orange), scale notes (blue), characteristic notes (yellow)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Build chords in 3 steps: Root \u2192 Quality \u2192 Tension. Adjust voicings with inversions, Drop, Shell, and Omit. Use the Parent Scale panel to reverse-lookup scales.',
    ss_chord_alt: 'Chord Mode \u2014 Dm7 chord display with tension grid',
    ss_chord_caption: 'Dm7 \u2014 Chord tones in grey over the scale background. Use Space to cycle display candidates when available',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Input notes from pads, MIDI controllers, fretboard, or keyboard to detect chord names. Pad presses in Chord mode stay in practice view and do not jump into Input detection.',
    ss_input_alt: 'Input Mode \u2014 C7 real-time chord detection',
    ss_input_caption: 'C7 \u2014 Click pads to auto-detect chord names. Multiple candidates shown',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Place saved chords on 16 pads for real-time performance using keyboard or MIDI pads.',
    ss_perform_alt: 'Perform Mode \u2014 16 slots with chords',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 saved to slots. Play using 4\u00D74 keyboard grid',
    ss_parent: 'Available Scale + Pivot Chord',
    ss_parent_desc: 'Reverse-lookup scales that contain your chord. Toggle between Practical (by usability) and Diatonic (by theory) sorting. Manual chord input hides the diatonic bar for pivot chord analysis.',
    ss_parent_alt: 'Parent Scale panel and guitar fretboard display',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Available Tensions displayed',
    ss_parent_note: '\u203B Pentatonic/Blues scales are modal (horizontal approach) and belong to a different system from chord-scale theory (vertical mapping), so they are not included in Available Scale. In practice, pentatonic is often the first choice.',
    ss_velocity: 'MIDI Velocity Sensitivity',
    ss_velocity_desc: 'Adjust MIDI controller velocity sensitivity with Push 3-style 4 parameters. Configure in the VELOCITY SENSITIVITY section within the Sound panel. Real-time curve visualization.',
    ss_push_oct: 'Push 3 Octave Button Sync',
    ss_push_oct_desc: 'Push 3 octave \u25B2\u25BC buttons (CC#55/CC#54) automatically sync with the app\u2019s octave shift. Press the octave buttons on Push 3 and the display octave updates automatically.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'HPS-Exclusive Voicing Features',
    ss_hps_voicing_intro: 'HPS members get 3 voicing tools. Choose TASTY / STOCK / Guitar inside the builder to show that voicing on the 64-pad grid automatically.',
    ss_tasty: 'TASTY Voicing \u2014 Classified by Top Note',
    ss_tasty_desc: '129 sophisticated voicings displayed as degree arrays. Select a chord, press <kbd>T</kbd> to activate, and press again to cycle through voicings. Auto-selects the optimal pad position.',
    ss_tasty_target: 'Target: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'The info area shows degree stacking order (e.g., <code>m9 (b3-b7-9-5-1)</code>). This is the voicing structure \u2014 which notes are stacked from bottom to top.',
    ss_tasty_labels_title: 'Label meanings',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Root (1st degree) omitted. Common in jazz/R&B/neo-soul where the bassist covers the root.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5th omitted. The 5th has little tonal character, so it\'s replaced with a tension for richer sound.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3rd omitted. Approaches a sus or quartal sound.',
    ss_tasty_ops_title: 'Controls',
    ss_stock: 'STOCK Voicing \u2014 Piano Voicing Collection',
    ss_stock_desc: '154 piano voicings from educational materials, displayed in degree notation. Covers Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Selected voicings appear on the 64-pad grid automatically.',
    ss_stock_ops_title: 'Controls',
    ss_guitar_pos: 'Guitar Position \u2014 Guitar Voicings',
    ss_guitar_pos_desc: 'Auto-calculates chord positions on the guitar fretboard. The left Guitar view is the instrument area; Guitar inside the builder is the voicing engine for the 64-pad grid.',
    usecases: 'Use Cases',
    uc1_q: '"I want to find how to voice this chord on pads"',
    uc1_a: '\u2192 Select Root, Quality, and Tension in <span class="mode-badge chord">Chord</span> mode \u2192 Check layouts in voicing boxes',
    uc2_q: '"I want to see a scale from my lesson on the pads"',
    uc2_a: '\u2192 Select key and scale in <span class="mode-badge scale">Scale</span> mode. 31 scales available',
    uc3_q: '"I want to create a chord progression for my DAW"',
    uc3_a: '\u2192 Save chords to memory slots \u2192 MIDI Export to import into your DAW',
    uc4_q: '"Which key does this chord belong to?"',
    uc4_a: '\u2192 Reverse-lookup in the Available Scale panel. Switch between Practical/Diatonic sort for usability ordering',
    uc7_q: '"I want to find pivot chords for modulation"',
    uc7_a: '\u2192 Manually input a chord in <span class="mode-badge chord">Chord</span> mode. The diatonic bar disappears and Available Scale shows all keys your chord could belong to',
    uc5_q: '"I want to check chord progressions by playing them"',
    uc5_a: '\u2192 Save chords to memory slots, then play them with a MIDI controller or PC keyboard',
    uc6_q: '"I want to check guitar chords on the pads"',
    uc6_a: '\u2192 Click guitar fretboard to input \u2192 Auto-displayed on pads \u2192 Chord name detected',
    uc8_q: '"I want to learn professional voicings"',
    uc8_a: '\u2192 Build a chord in <span class="mode-badge chord">Chord</span> mode, then press <kbd>T</kbd> for TASTY (top-note classification) or <kbd>K</kbd> for STOCK (piano voicings). View with degree notation, save to memory, and export to DAW',
    quickstart: 'Quick Start',
    qs_modes: '3 Modes',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Display scales and diatonic chords<br><span class="mode-badge chord">Chord</span> Build chords in 3 steps. Voicing operations available<br><span class="mode-badge input">Input</span> Click pads freely \u2192 Auto-detect chord names',
    qs_first: 'Getting Started',
    qs_step1: 'Choose a key (e.g., C)',
    qs_step2: 'Choose a scale (e.g., Major) \u2192 Scale notes appear on pads',
    qs_step3: 'Click a chord on the diatonic bar (e.g., Dm7) \u2192 Chord tones displayed',
    qs_step4: 'Click pads to play sounds. Change layouts in voicing boxes',
    qs_step5: 'Save favorite chords with <kbd>Option</kbd>+<kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> (16 slots)',
    qs_shortcuts: 'Keyboard Shortcuts',
    qs_shortcuts_desc: 'Press <kbd>?</kbd> for the full shortcut list.<br><kbd>Space</kbd> to play chord. <kbd>1</kbd>\u2013<kbd>7</kbd> for diatonic chords, <kbd>\u2191</kbd><kbd>\u2193</kbd> for inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> for chromatic movement.<br>In Perform mode, use <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> as a 4\u00D74 grid.',
    footer_open: 'Open 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Learn more on the blog \u2192',
    // Header Icons
    header_icons: 'Header Icons',
    header_icons_desc: 'Three icon buttons in the top-right corner.',
    icon_save: '<strong>\uD83D\uDCBE Save</strong> \u2014 Save current settings (sound, effects, display options, etc.) to the browser. Auto-restored on next visit',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Browse 12 interactive tutorials. Learn each feature step by step',
    icon_help: '<strong>? Help</strong> \u2014 View shortcut keys, version history, and mode descriptions. Also opens with <kbd>?</kbd> key',
    // Sound Panel
    sound_panel: 'Sound Panel',
    sound_panel_desc: 'Select sound presets and adjust effects. Click the \u25B6 button to expand the panel.',
    sound_presets: 'Sound Presets',
    sound_presets_desc: 'Pad Sensei MK1 (physical modeling) is the default. Play instantly with no sample downloads. Use the VOICING knob to adjust pickup tone.',
    sound_effects: 'Effects',
    sound_effects_desc: 'Drag each knob to adjust values.',
    fx_drive: 'Analog saturation. Adds warm overdrive',
    fx_locut: 'Low-cut filter. Removes muddy bass',
    fx_hicut: 'High-cut filter. Tames harsh highs',
    fx_reverb: 'Reverb. Adds spatial depth',
    fx_phaser: 'Phaser. Sweeping modulation',
    fx_flanger: 'Flanger. Jet-like modulation',
    fx_tremolo: 'Tremolo. Periodic volume modulation',
    sound_autofilter: 'Auto-Filter (Auto-Wah)',
    sound_autofilter_desc: 'Envelope filter. Adjust FREQ, RESO, SENS, and DECAY.',
    version_history: 'Version History',
    vh_540: '<b>V5.4</b> \u2014 Physical modeling upgraded. Added filter parameters (WET / VOL) and an HPS-only preset (Pad Sensei MK1 AMP Vintage Envelope Filter)',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Preamp modeling improved',
    vh_510: '<b>V5.1</b> \u2014 C major fixed-scale mode added',
    vh_500: '<b>V5.0</b> \u2014 Self-contained sound engine + effects. Spring Reverb (physical modeling) + Plate Reverb. Suitcase amp model improved. Reverb Type selector (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Play instantly from the moment you open (no sample download). Shortcut key hint toggle. NM/HM/MM diatonic chords for parallel minor keys. PU LEVEL and MECHANICAL added to E.PIANO MIXER. Chord detection display improvements',
    vh_490: '<b>V4.9</b> \u2014 Pad Sensei MK1 physical modeling sound source',
    vh_497: '<b>V4.9.7</b> \u2014 Tremolo is now physically modeled. HPS members get Pad Sensei MK1 Suitcase (physically modeled amp chain)',
    vh_3377: '<b>V3.37.7</b> \u2014 User review: relative minor key fix, title case badges, sans-serif pad font, color-blind friendly toggles (green\u2192blue), Sound panel open by default, layout shift fix, tutorial spotlight overlay, Launchpad octave support + auto-octave tracking for all MIDI controllers',
    vh_340: '<b>V3.40</b> \u2014 3-pane layout switching, TASTY/STOCK transpose (\u2190\u2192), Z/X voicing navigation, Cmd+Option display toggles (Ableton-style), section collapse, mobile UX improvements, Info Bar (hover descriptions), full shortcut reference update',
    vh_336: '<b>V3.36</b> \u2014 Guitar voicing engine v2: genre presets (Jazz/Bossa/Funk), reference table (120 types \u00D7 12 keys), auto finger assignment with barre detection',
    vh_335: '<b>V3.35</b> \u2014 Tutorial UX improvements (beginner review). All tooltips translated to 9 languages. Guide: sound panel & header icon sections added',
    vh_333: '<b>V3.33</b> \u2014 Interactive tutorials. 11 topics \u00D7 9 languages. Context hints on first feature interaction',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 piano voicings with MIDI-specific keyboard display. Guide updated with HPS voicing features section',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 sophisticated voicings sorted by top note. Degree array display + auto octave optimization. HPS members only',
    vh_325: '<b>V3.25.0</b> \u2014 Guitar voicing \u2192 Pad reflect (<kbd>V</kbd> key). Guitar-like (1 note per row) / Compact layout switch. Guitar position "All" filter first',
    vh_324: '<b>V3.24</b> \u2014 Clavinet presets added (2 in E.PIANO). Auto Filter (envelope filter / auto-wah) effect added',
    vh_323: '<b>V3.23</b> \u2014 Text chord input with autocomplete. Press "/" to focus, supports abbreviations (dim, h=m7\u266D5), tension-count sorting',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Diatonic triad/tetrad toggle. Guitar/bass positions grouped by root string',
    vh_37: '<b>V3.7</b> \u2014 Voicing position preservation (auto-maintain fingering shape on chromatic movement). Pad grid, staff, and chord detection during playback. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI file playback \u2192 pad lighting (timeline playback, chord name display, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO sampler (Rhodes Mark I). 7 EP presets. Sound ON/OFF toggle. iPad support',
    vh_31: '<b>V3.1</b> \u2014 Velocity sensitivity (4 parameters + curve visualization). Push 3 octave button support. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Multiple memory banks (16 slots \u00D7 up to 16 banks, switch/duplicate/rename)',
    vh_218: '<b>V2.18</b> \u2014 Auto save/restore all settings (key/scale/sound/MIDI/memory)',
    vh_213: '<b>V2.13</b> \u2014 Instrument scale overlay (guitar/bass/piano show Available Scale). Pad degree labels. Octave-linked playback',
    vh_27: '<b>V2.7</b> \u2014 Tension addition mode (pad/guitar/bass/keyboard chord synthesis \u2192 Available Scale filtering)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, scale overlay on pads)',
    vh_19: '<b>V1.9</b> \u2014 9 languages',
    vh_18: '<b>V1.8</b> \u2014 Perform mode, 16 memory slots, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain mode, MIDI/CHS export',
    vh_10: '<b>V1.0</b> \u2014 Initial release (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6th R',
    root_5: '5th R',
    root_4: '4th R',
    root_3: '3rd R',
    root_2: '2nd R',
    open: 'Open',
    no_open: 'No open',
    all: 'All',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'To Pad',
    genre_default: 'Standard',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    'Press C to save the current chord to Memory',
    'Opt+1~V saves directly to a Memory slot (16 keys: 1234 QWER ASDF ZXCV)',
    'Shift+Click on a Memory slot to delete it',
    'Opt+Drag to copy a Memory slot to another',
    'Press S to cycle Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D cycles Drop 2 / Drop 3 voicings',
    '⌘⌥G shows Guitar fretboard view',
    '⌘⌥F shows Circle of Fifths',
    'Tab cycles Scale / Chord / Input modes',
    'Space plays the current chord',
    'Export all Memory slots as a MIDI file from the Memory panel',
    'Connect a MIDI controller to play pads directly',
    'Arrow keys change chord inversion (Root / 1st / 2nd / 3rd)',
    'Press R for rootless voicing',
    'Press O to omit the 5th',
    '⌘⌥S shows staff notation',
    'The save icon preserves all your settings across sessions',
    '[ ] keys switch Memory banks — manage multiple songs',
    'Perform mode: Trigger saved chords with PC keyboard (1234 / QWER / ASDF / ZXCV) or MIDI pads',
    'Press / in Chord mode to type chord names directly (e.g. Cm7, G7(b9,#11))',
  ],
  tips_off: "Don't show tips",
  whats_new: "What's New",
  whats_new_497: 'Tremolo is now physically modeled! HPS members get Pad Sensei MK1 Suitcase.',
  whats_new_61: 'Online manual is now live. Find the link in the Help modal.',
  whats_new_123: 'Online manual is now live. Find the link in the Help modal.',
  whats_new_51: 'Lock to C Major mode added! Toggle from Help (?). When on, Push/Launchpad always display C Major — instrument-correct behavior. Chord/TASTY/Stock overlays now stay in the browser UI, not the pad.',
  whats_new_50: 'Spring & Plate reverb added! Baxandall Bass/Treble EQ, Suitcase amp improved.',
  whats_new_32427: 'Guitar voicing \u2192 Pad reflect (V key). Guitar-like / Compact layout switch.',
  whats_new_33000: 'Tutorial system! Click the book icon in the header to learn Scale mode, Chord mode, and more.',
  whats_new_640: 'V6.4.0 is live: chord detection now recognizes three tensions, UST analysis, note/degree display, and key-aware sharp/flat spelling.',
  whats_new_650: 'V6.5.0 is live: HPS TASTY / STOCK / Guitar voicings now live inside the Chord Builder. Sixth-family names use C6(9) / C6(9,#11), and guitar voicing filters, display balance, and playback range are improved.',
  whats_new_660: 'V6.6.0 is live: a stronger chord-detection engine, expanded TASTY voicings (including quartal / So What), and sus chords added to the Chord Builder.',
  whats_new_670: 'V6.7.0 is live: a redesigned Chord mode. Selecting a chord now shows one easy basic form first, with a "Show all positions" button (lower left) to see every voicing. Pads are single-colour by default — switch to degree colours in Display settings. Right-click a pad for Capture / All positions / Clear.',
  whats_new_6716: 'V6.7.16 is live: HPS member access and the Desktop version now include Double Stop display in Scale mode for 3rd / 4th / 6th two-note harmonies. UST detection is clearer, with degree labels for the notes inside the upper structure. A Double Stop tutorial video is now available from Tutorials.',
  whats_new_6717: 'V6.7.17 is live: Available Scale notation is clearer for pivot-chord reading, and cases where the Available Scale display did not update correctly have been fixed.',

  // Legacy tutorial keys (backward compat for old lang files)
  tutorial: {
    sound_title: 'Sound Preset',
    sound_msg: 'Change the preset and tap a pad to hear it.\nORGAN and E.PIANO — each has multiple presets.',
    sound_done: 'Sounds good! Press Next to continue.',
    midi_title: 'MIDI Controller',
    midi_msg: 'A MIDI controller has been detected. Select your device from the dropdown.\nVelocity sensitivity can be adjusted in the Sound panel.',
    midi_no_device: 'No MIDI controller detected — that\'s OK.\nYou can use pad clicks, guitar/bass/piano input, or text chord input.',
    input_title: 'Three Modes',
    input_msg: 'Scale — view scale notes on the 64-pad grid\nChord — build chords with voicings, inversions, and tensions\nInput — tap pads freely to detect chord names\n\nSwitch with Tab or the mode buttons above.',
    instruments_title: 'Instruments & Link',
    instruments_msg: 'Guitar, Bass, Piano — toggle each display and click to input notes directly.\nLink — played notes sync across all instruments in real-time. Learn how notes map between instruments.\nText input: press / in Chord mode to type chord names (e.g. Cm7, G7(b9,#11)).',
    done_title: 'Ready!',
    done_msg: 'You\'re all set. Explore freely — press ? for the full shortcut list.\nThe online manual has detailed guides for every feature.',
    next: 'Next',
    skip_step: 'Next',
    skip_all: 'Skip tutorial',
    open_guide: 'Open Online Manual',
    close: 'Start',
    reset: 'Restart tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutorials',
    cat_getting_started: 'Getting Started',
    cat_features: 'Features',
    cat_advanced: 'Advanced',
    steps_label: 'steps',
    reset_all: 'Reset all progress',
    close_selector: 'Close',
    hint_available: 'Tutorial available',
    hint_try: 'Try it',
    // Button label
    btn_label: 'Tutorials',
    // Shared action labels
    next: 'Next',
    skip_step: 'Next',
    skip_all: 'Skip tutorial',
    open_guide: 'Open Online Manual',
    close: 'Done',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: 'First time here? Want a quick tour of the app?',
    onboarding_yes: 'Next',
    onboarding_no: 'Skip',
    // Onboarding
    onboarding_title: 'First Steps',
    onboarding_desc: 'Learn the basics of 64 Pad Explorer',
    onboarding: {
      app_version_title: 'About the Desktop App',
      app_version_msg: 'This is 64Pad Explorer Desktop (Standalone / VST3 / AU).\n\nBrowser version: the built-in audio engine (ORGAN / E.PIANO) plays sound directly.\nDesktop version: there is no built-in audio. Pads output MIDI — sound comes from an external VST/AU plug-in (e.g. Pad Sensei MK1) loaded in your DAW or as a hosted plug-in. Push 3 integration is available in Standalone mode.\n\nThe tutorial focuses on MIDI output and visualization features.',
      sound_title: 'Sound Preset',
      sound_title_desktop: 'Sound Output',
      sound_msg: 'Change the preset and tap a pad to hear it.\nORGAN and E.PIANO — each has multiple presets.',
      sound_msg_desktop: 'The Sound panel contains MIDI output settings.\nAudio is produced by your DAW or an external VST/AU plug-in. Velocity sensitivity can be adjusted here.',
      sound_done: 'Sounds good! Press Next to continue.',
      midi_title: 'MIDI Controller',
      midi_msg: 'A MIDI controller has been detected. Push 3 and Launchpad work out of the box — no setup needed.\nVelocity sensitivity can be adjusted in the Sound panel.',
      midi_no_device: 'No MIDI controller detected — that\'s OK.\nYou can use pad clicks, guitar/bass/piano input, or text chord input.',
      input_title: 'Three Modes',
      input_msg: 'Scale — view scale notes on the 64-pad grid\nChord — build chords with voicings, inversions, and tensions\nInput — tap pads freely to detect chord names\n\nSwitch with Tab or the mode buttons above.',
      instruments_title: 'Instrument Input',
      instruments_msg: 'Guitar, Bass, Piano — toggle each display and click to input notes directly.\nWith HPS enabled, Guitar inside the builder shows guitar voicings on the 64-pad grid.\nText input: press / in Chord mode to type chord names (e.g. Cm7, G7(b9,#11)).',
      done_title: 'Ready!',
      done_msg: 'You\'re all set. Explore freely — press ? for the full shortcut list.\nThe online manual has detailed guides for every feature.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Scale Mode',
    scale_mode_desc: 'Explore scales on the 64-pad grid',
    scale_mode: {
      step1_title: 'Switch to Scale Mode',
      step1_msg: 'Scale mode shows scale notes lit up across the pad grid.\nTap any lit pad to hear the note.',
      step2_title: 'Choose a Key',
      step2_msg: 'Pick a key from Major and Minor rows (Cycle of 4ths order).\nYou can also set the key from the Circle of Fifths. Outer ring = major keys, inner ring = minor keys. Minor keys support 3 types of minor scales.\nTry switching between C, G, F.',
      step3_title: 'Choose a Scale',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 scales available. The pads update in real time.',
      step4_title: 'Diatonic Bar',
      step4_msg: 'The diatonic chords for your chosen scale appear here.\nPress 3 for triads, 4 for tetrads (7th chords).\nClick any chord to jump into Chord mode with that voicing.',
    },
    // Double Stop tutorial
    double_stop_title: 'Double Stop',
    double_stop_desc: 'Explore two-note harmonies inside a scale',
    double_stop: {
      step1_title: 'Turn on Double Stop',
      step1_msg: 'In Scale mode, Double Stop overlays a two-note harmony on top of the normal scale display.\nIt is for moving from single-note scale practice into melodic harmony.',
      step2_title: 'Scale Set',
      step2_msg: 'Choose the scale set used for Double Stop.\nMajor / Ionian, Mixolydian, Dorian, and Melodic Minor focus on practical seven-note scale vocabulary.',
      step3_title: '3rd / 4th / 6th',
      step3_msg: '3rd / 4th / 6th are scale-degree intervals, not fixed semitone counts.\nIn C Major, 3rd means C-E, D-F, E-G, and so on.',
      step4_title: 'Move the Starting Note',
      step4_msg: 'Use Up / Down, or the Push 3 Jog Wheel / D-pad left-right, to move the starting note.\nEach move updates the display and plays the current Double Stop so you can learn it by eye and ear.',
      step5_title: 'Cycle Positions',
      step5_msg: 'When the same two notes have multiple pad positions, use Space, Push 3 Jog Wheel press, or D-pad center to cycle them.\nThe goal is to find positions that are playable with one hand.',
      fb_step1_title: 'What is Double Stop?',
      fb_step1_msg: 'Double Stop means playing a two-note harmony.\n64Pad Explorer overlays 3rd / 4th / 6th shapes in Scale mode. It is available with HPS member access or in the Desktop version.',
      fb_step2_title: 'Video Walkthrough',
      fb_step2_msg: 'You can also watch the Double Stop workflow in this tutorial video.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Chord Mode',
    chord_mode_desc: 'Build chords step by step',
    chord_mode: {
      step1_title: 'Switch to Chord Mode',
      step1_msg: 'Chord mode gives you two ways to select chords.\n① Pick from the diatonic bar in one click\n② Build your own: Root → Quality → Tension',
      step_key_title: 'Key Selection',
      step_key_msg: 'Set the scale key. When a Key is set, the diatonic bar shows chords and tension availability is filtered.\nYou can also build chords freely from Root without using Key.',
      step_diatonic_title: 'Diatonic Bar',
      step_diatonic_msg: 'Diatonic chords for the selected Key.\nClick to instantly set a chord with scale-aware tension filtering.',
      step2_title: 'Root',
      step2_msg: 'Pick the chord root note. All 12 notes.\nIndependent from Key — build non-diatonic chords freely.',
      step3_title: 'Chord Quality',
      step3_msg: 'Choose the chord type: Maj, min, 7, m7, dim, aug...\nThe pad grid shows chord tones over the scale background. Pressing pads in Chord mode stays in practice view and does not jump into Input detection.',
      step4_title: 'Tensions',
      step4_msg: 'Choose Quality first — tension buttons appear automatically.\nWhen using the diatonic bar, available tensions are highlighted based on the scale.',
      step5_title: 'Text Input',
      step5_msg: 'Type chord names directly with / key.\nSlash chords and complex voicings can be entered quickly.\nIf TASTY / STOCK / Guitar is active, confirming text input exits that engine and returns to the basic chord display.',
      step6_title: 'Secondary Dominant',
      step6_msg: 'Turn on the "Secondary Dominant" button below the diatonic bar (⌘⌥D).\nIt shows the V7 that resolves to each diatonic chord.\nClick one and Available Scale auto-shows the right scale — Mixolydian for major targets, HMP5↓/Altered for minor targets.',
      step7_title: 'Slash Chords',
      step7_msg: 'Click / in the chord builder to enter a bass note for slash chords.\nYou can also type C/D or F△7/G in text input.\nAvailable Scale updates to match the slash chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Input Mode',
    input_mode_desc: 'Input chords via MIDI controller, pads, fretboard, or keyboard',
    input_mode: {
      step1_title: 'Switch to Input Mode',
      step1_msg: 'Input chords via MIDI controller, clicking pads, fretboard, or keyboard.\nUse Input when you want chord-name detection from played notes. Leaving Input clears the working notes unless you explicitly hand the chord off to Chord mode.',
      step2_title: 'Tap Some Pads',
      step2_msg: 'Click any pads on the grid.\nEach tap toggles a note on or off.',
      step3_title: 'Chord Detection',
      step3_msg: 'The detected chord name appears above the grid.\nDegree labels (R, 3, 5, b7...) show on each pad.',
      step4_title: 'Save with Capture',
      step4_msg: '<strong>C</strong> starts Input Capture.\n<strong>Shift+C</strong> instantly saves the current chord / TASTY / STOCK / Guitar voicing to Memory Slot.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Diatonic Bar',
    diatonic_desc: 'One-click access to diatonic chords',
    diatonic: {
      step1_title: 'The Diatonic Bar',
      step1_msg: 'Every scale has its own set of diatonic chords.\nThey appear here — ready to play.',
      step2_title: 'Triad / Tetrad',
      step2_msg: 'Toggle between 3-note triads and 4-note seventh chords.\nThe bar updates instantly.',
      step3_title: 'Click a Chord',
      step3_msg: 'Click a chord on the bar.\nYou can transform it with tensions and more in the Chord Builder.',
      step4_title: 'Compare 3 Minor Scales (Harm/Mel)',
      step4_msg: 'With a minor key selected, turn on "Harm/Mel" (\u2318\u2325N).\nHarmonic and Melodic Minor diatonic chords appear below.\nCompare with Natural Minor — notice how the V chord changes from m7 to 7.',
      step5_title: 'Secondary Dominant',
      step5_msg: 'Turn on "Secondary Dominant" (\u2318\u2325D).\nV7 chords resolving to each diatonic chord are shown.\nClick one and Available Scale auto-displays.\nMajor resolution \u2192 Mixolydian. Minor resolution \u2192 HMP5\u2193/Altered.',
      step6_title: 'Keyboard Shortcuts',
      step6_msg: 'Press 1\u20137 for diatonic chords.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Parallel Key) for extension bars.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Save chords and play them live',
    memory: {
      step1_title: 'Save a Chord',
      step1_msg: 'Save your favorite chords.\nSaving voicings you like helps with beat-making and practice. The current TASTY / STOCK / Guitar voicing can also be saved with Shift+C.',
      step2_title: '16 Memory Slots',
      step2_msg: 'Works like a 16-pad Drumrack layout on PUSH, Launchpad, MPC, and Maschine.\nIn Memory view, clicking a saved slot selects and plays it. Editing the selected slot auto-saves it.',
      step3_title: 'Memory Banks',
      step3_msg: 'Banks page the 16 slots. Use [ ] on the computer keyboard, or Page Left / Right on Push 3.',
      step4_title: 'Perform Mode',
      step4_msg: 'Perform plays saved chords from the computer keyboard or Push 3 pads.\nThe display now follows Scale / Chord colors: scale in the background, chord tones in grey, playback pitch preserved exactly as saved.',
      step5_title: 'MIDI Export',
      step5_msg: 'Export all memory chords as a MIDI file.\nDrag into your DAW and start producing.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Shape your chord voicings',
    voicing: {
      step1_title: 'Voicing Controls',
      step1_msg: 'In Chord Builder mode, various transformations are possible from the basic form.\nOmit, Shell, Inversion, Drop — all here.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> is for Shell voicing. Learn R37 and R73 voicings\nsmoothly on the pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Shortcut keys are often set to mnemonics.\n<strong>O</strong>mit = omit 5th. <strong>R</strong>ootless = rootless voicing.',
      step4_title: 'Inversions',
      step4_msg: 'Unlike most software, you can create inversions ultra-fast.\nAlso helps understand slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'For when you want to feature the top note —\nDrop voicings are also supported.',
      step6_title: 'Voicing Box',
      step6_msg: 'Pads can have multiple position options. The Voicing Box handles this.\nClick a, b, c, d etc. on the pad, or type the letter, to see multiple voicing possibilities.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, effects, and volume',
    sound: {
      step1_title: 'Sound Presets',
      step1_title_desktop: 'MIDI Output',
      step1_msg: 'ORGAN (4 types) and E.PIANO (8 types).\nClick a pad or use your MIDI controller.',
      step1_msg_desktop: 'The Desktop version has no built-in audio.\nClicking a pad outputs MIDI notes. Load a VST/AU plug-in (e.g. Pad Sensei MK1) in your DAW or as a hosted plug-in to produce sound.\nVelocity sensitivity can be adjusted here.',
      step2_title: 'Detail Panel',
      step2_msg: 'Click ▼ to expand the sound detail panel.\nEffects, volume, and filter controls live here.',
      step3_title: 'Effects',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nTweak them in the detail panel.',
      step4_title: 'Sound ON/OFF',
      step4_msg: 'Toggle sound ON/OFF with the speaker icon.\nTurning it off can be convenient when using a DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings classified by top note. HPS members only',
    tasty: {
      step1_title: 'Activate TASTY',
      step1_msg: 'Select hip voicings that simple logic alone can\'t produce.\nThinking from the top note is useful for string and horn arrangements.\n(HPS members only)',
      step2_title: 'Browse Recipes',
      step2_msg: 'Z / X keys to browse voicings forward/backward.\nThe counter shows your position.',
      step3_title: 'Degree Notation',
      step3_msg: 'The info area shows the degree stack — e.g. m9 (b3-b7-9-5-1).\nThis is the voicing structure from bottom to top.',
      step4_title: 'Pad Display',
      step4_msg: 'TASTY automatically displays the selected voicing on the pad grid.\nEnjoy playing stylish voicings on pads too.',
      fb_step1_title: 'What is TASTY Voicing?',
      fb_step1_msg: '129 sophisticated voicings sorted by top note.\nSupports Maj7 / Dom7 / Min7. Displayed in degree notation.\nHPS members only.',
      fb_step2_title: 'How to Access TASTY',
      fb_step2_msg: 'Available when you join HPS (Hardcore Pad Style).\nPress T in Chord mode to activate. Z/X keys to browse voicings.\nSee the Guide for details.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Classic piano voicing idioms. HPS members only',
    stock: {
      step1_title: 'Activate STOCK',
      step1_msg: 'Knowing piano-specific voicings helps you break free from basic-form-only playing.\n154 piano voicings in degree notation.\n(HPS members only)',
      step2_title: 'Browse Voicings',
      step2_msg: 'Z / X keys to browse voicings forward/backward.',
      step3_title: 'Keyboard View',
      step3_msg: 'Turn on Piano display to see the actual key positions.\nThe voicing comes alive on the keyboard.',
      step4_title: 'Pad Display',
      step4_msg: 'STOCK automatically displays the selected voicing on the pad grid.\nSave to memory and export to your DAW.',
      fb_step1_title: 'What is STOCK Voicing?',
      fb_step1_msg: 'Presents commonly used piano voicings.\nDegree notation shows you the structure.\nHPS members only.',
      fb_step2_title: 'How to Access STOCK',
      fb_step2_msg: 'Available when you join HPS (Hardcore Pad Style).\nPress K in Chord mode to activate.\nSee the Guide for details.',
    },
    // Minor 3 Scales tutorial
    minor_scales_title: 'Compare 3 Minor Scales',
    minor_scales_desc: 'Natural, Harmonic & Melodic side by side',
    minor_scales: {
      step1_title: 'Set a Minor Key',
      step1_msg: 'Am (Natural Minor) is selected.\nThe diatonic bar shows Natural Minor chords.',
      step2_title: 'Turn On Harm/Mel',
      step2_msg: 'Click "Harm/Mel" (\u2318\u2325N).\nHarmonic and Melodic Minor diatonic chords appear below.',
      step3_title: 'Compare',
      step3_msg: 'Look at the differences from Natural Minor (top bar).\nIn HM, the V chord changes from Em7 to E7 \u2014 enabling dominant motion.\nIn MM, the IV chord also changes from Dm7 to D7.\nClick any chord to see it on the pads.',
      step4_title: 'Parallel Key',
      step4_msg: 'Turn on "Parallel Key" (\u2318\u2325R) to see the major key diatonic for the same root.\nThis reveals the source of borrowed chords (modal interchange).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Secondary Dominant',
    secdom_desc: 'Experience the gateway to modulation',
    secdom: {
      step1_title: 'Start in C Major',
      step1_msg: 'C Major is set.\nThe diatonic bar shows C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Turn On Secondary Dominant',
      step2_msg: 'Click "Secondary Dominant" (\u2318\u2325D).\nV7 chords resolving to each diatonic chord appear.\nIn C Major: C7, D7, E7, A7, B7 (5 total).',
      step3_title: 'Resolving to Major',
      step3_msg: 'Click C7 (\u2192F\u25B37) or D7 (\u2192G7).\nAvailable Scale shows Mixolydian as the top choice.\nBecause the resolution target is a major chord.',
      step4_title: 'Resolving to Minor',
      step4_msg: 'Click A7 (\u2192Dm7) or E7 (\u2192Am7).\nAvailable Scale shows HMP5\u2193 (Phrygian Dominant) and Altered as top choices.\nBecause the resolution target is a minor chord.',
      step5_title: 'The Rule: Just 2 Types',
      step5_msg: 'Scale selection for secondary dominants is simple:\n\u2022 Major resolution \u2192 Mixolydian\n\u2022 Minor resolution \u2192 HMP5\u2193 or Altered\nThat\u2019s all you need to remember.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Circle of Fifths',
    circle_desc: 'Key relationships at a glance',
    circle: {
      step1_title: 'Open the Circle',
      step1_msg: 'Press ⌘⌥F or click the Circle button.\nThe circle of fifths appears below.',
      step2_title: 'Key Linking',
      step2_msg: 'Quickly check proxy chords and diatonics that are important for performance and composition.',
      step3_title: 'Diatonic Functions',
      step3_msg: 'The circle shows proxy chords in the same color (T/SD/D).\nTonic, Subdominant, and Dominant relationships are visible at a glance.',
      step4_title: 'Select a Minor Key',
      step4_msg: 'The inner ring shows minor keys.\nClick one to select a minor key.\nThe circle always shows Natural Minor diatonic chords.',
      step5_title: 'Scale Switching',
      step5_msg: 'With a minor key selected, use the Scale Selector to switch between Natural/Harmonic/Melodic.\nPads and the diatonic bar update accordingly.\nUse the "Harm/Mel" button (\u2318\u2325N) below the diatonic bar to compare all 3 minor scales.',
      step6_title: 'Parallel Key & Secondary Dominant',
      step6_msg: 'Below the diatonic bar, find "Parallel Key" and "Secondary Dominant" buttons.\nParallel Key shows borrowed chord sources. Secondary Dominant shows V7 chords with auto Available Scale display.',
    },
    // Guitar tutorial
    guitar_title: 'Guitar Diagram',
    guitar_desc: 'Check and input guitar chord positions',
    guitar: {
      step1_title: 'Show Guitar Fretboard',
      step1_msg: 'Press ⌘⌥G or click the Guitar button.\nChord tones appear on the fretboard.',
      step2_title: 'View Chord Positions',
      step2_msg: 'Select a chord in Chord mode and one playable position in the real guitar register appears on the fretboard.\nIf there are multiple candidates, browse them with comma (,), period (.), or Space.',
      step3_title: 'Input from Guitar',
      step3_msg: 'Switched to Input mode. Try clicking frets on the fretboard to input notes.\nChord names are detected in real-time from your input.',
      step4_title: 'Guitar Engine',
      step4_msg: 'With HPS enabled, press Guitar inside the builder to show the selected guitar voicing on the 64-pad grid.\nThe 64 pads and Push 3 show one playable guitar-register position at a time.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Keyboard Shortcuts',
    shortcuts_desc: 'Essential keys for efficient operation',
    shortcuts: {
      step1_title: 'Mode Switching',
      step1_msg: 'Tab — Switch modes (Scale → Chord → Input)\nShift+Tab — Reverse direction\n\nQuickly move between modes.',
      step2_title: 'Diatonic & Navigation',
      step2_msg: '1–7 — Select diatonic chord\n↑↓ — Cycle inversions\n←→ — Transpose root by semitone (keeps chord shape)\n\nOperate chords without a mouse.',
      step3_title: 'Voicing Operations',
      step3_msg: 'S — Shell cycle (off → 1-3-7 → 1-7-3)\nO — Omit 5 toggle\nR — Rootless toggle\nShift+D — Drop cycle (off → Drop2 → Drop3)\nT — TASTY ON/OFF, K — STOCK ON/OFF, Shift+G / V — Guitar engine ON/OFF\nZ / X — TASTY/STOCK/Guitar voicing prev/next\n←→ — Transpose voicing by semitone (during TASTY/STOCK)\n/ — Text chord input',
      step4_title: 'Memory & Banks',
      step4_msg: 'Option+1234/qwer/asdf/zxcv — Save to slot\nShift+C — Save current chord/voicing\n[ ] — Switch banks\nP — Toggle Perform\nSpace — Play, or cycle display candidates when available\nShift+Space — Play All (sequential)',
      step5_title: 'More',
      step5_msg: '? — Help (full shortcut list)\n⌘⌥+G/B/P/F/S — Instrument/Circle/Staff toggles\n⌘⌥+A/M/T/Q/V/K/H — Section toggles\n⌘⌥+I — Toggle shortcut key indicators on buttons\nCmd/Ctrl+Z — Undo (up to 30 times)\nEsc — Deselect / Close modals',
    },
    // Settings tutorial
    link_title: 'Link Mode',
    link_desc: 'Sync played notes across all instruments',
    link: {
      step1_title: 'Link Button',
      step1_msg: 'The Link button is next to Guitar / Bass / Piano.\nTurn it ON to see played notes on all instruments in real-time.',
      step2_title: 'Link Mode ON',
      step2_msg: 'When Link is active, instrument displays dim.\nPlay pads or MIDI — only the played notes light up.',
      step3_title: 'Play the Pads',
      step3_msg: 'Press a pad and watch the same note light up on guitar, bass, and piano.\nSee which positions on each instrument produce the same pitch.\nRelease to clear.',
      step4_title: 'Shortcut',
      step4_msg: '\u2318\u2325+L toggles Link mode ON/OFF.\nPerfect for learning how notes map across instruments.',
    },
    settings_title: 'Display & Settings',
    settings_desc: 'Customize your workspace',
    settings: {
      step1_title: 'Instrument Panels',
      step1_msg: 'Guitar displays commonly used voicings when you select a chord in the Chord Builder.\nIn Input mode, you can also input from guitar, bass, and keyboard.',
      step2_title: 'Note Names / Degrees',
      step2_msg: 'Switch between note names (C, D, E) and degrees (R, 2, 3).\nApplies to pads and guitar display.',
      step3_title: 'Octave Shift',
      step3_msg: 'Use ▲▼ to shift the pad range up or down an octave.\nPush 3 and Launchpad octave buttons sync automatically.',
      step4_title: 'Section Toggles',
      step4_msg: '⌘⌥+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) to collapse sections.\nShow only what you need.',
      step5_title: 'Layout Order',
      step5_msg: 'In ? Help, use the "Layout" dropdown to reorder the 3 panes.\n6 presets: Chord, Pad, Circle in any order.\nOn mobile, swipe order changes too.',
      step6_title: 'Save Everything',
      step6_msg: 'Click the save icon to preserve all settings.\nKey, scale, sound, memory, voicing — everything persists.',
    },
  },
  info: {
    default: 'Hover over any control to see what it does',
    mode_scale: 'Scale Mode \u2014 View scale notes on the 64 pad grid [Tab]',
    mode_chord: 'Chord Mode \u2014 Build chords step by step: Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Input Mode \u2014 Tap pads freely, chords are auto-detected [Tab]',
    guitar: 'Toggle guitar fretboard display [\u2318\u2325G]',
    bass: 'Toggle bass fretboard display [\u2318\u2325B]',
    piano: 'Toggle piano keyboard display [\u2318\u2325P]',
    link_mode: 'Link Mode \u2014 played notes sync across all instruments in real-time [\u2318\u2325L]',
    staff: 'Toggle staff notation [\u2318\u2325S]',
    circle: 'Circle of Fifths \u2014 Tonic, Subdominant, Dominant shown in matching colors [\u2318\u2325F]',
    cof_major: 'Outer ring \u2014 select Major key',
    cof_minor: 'Inner ring \u2014 select Minor key',
    cof_natural: 'Natural Minor',
    cof_harmonic: 'Harmonic Minor',
    cof_melodic: 'Melodic Minor',
    sound: 'Toggle audio controls panel [\u2318\u2325A]',
    memory: 'Toggle Memory Slot panel \u2014 save/recall chords in 16 slots [\u2318\u2325M]',
    sect_key: 'Toggle Key display',
    sect_input: 'Toggle text chord input [\u2318\u2325T]',
    sect_quality: 'Toggle Root/Quality/Tension selectors [\u2318\u2325Q]',
    sect_voicing: 'Toggle voicing controls (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Type chord name directly \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Show available scales for the current chord. Slash chords with non-chord-tone bass are reinterpreted from the bass note',
    sort_practical: 'Practical sort \u2014 prioritizes commonly used scales. Includes secondary dominant scales (e.g., Mixolydian b13 for V7/ii)',
    sort_diatonic: 'Diatonic sort \u2014 sorts by theoretical distance from the current key',
    omit5: 'Remove the 5th from the voicing [O]',
    rootless: 'Remove the root [R]',
    omit3: 'Remove the 3rd from the voicing',
    shell137: 'Shell voicing: Root-3rd-7th [S]',
    shell173: 'Shell voicing: Root-7th-3rd [S]',
    shell_off: 'Disable shell voicing [S]',
    shell_ext: 'Add notes to shell voicing (+1 or +2 chord tones)',
    inv_root: 'Root position [\u2193]',
    inv: 'Inversion [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 refined voicings sorted by top note. Works with \u25B37, m7, 7 (HPS exclusive) [T]',
    tasty_nav: 'Cycle variations [Z / X]',
    stock: 'Stock Voicing \u2014 common piano voicings (HPS exclusive) [K]',
    stock_nav: 'Cycle variations [Z / X]',
    root_notation: 'Switch between \u266F and \u266D notation',
    root_grid: 'Select root note',
    quality_grid: 'Select chord quality (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Add tensions to the chord (9, b9, #9, 11, #11, 13, b13) \u2014 multiple OK',
    diatonic: 'Diatonic chords for the current scale \u2014 click to enter Chord mode [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Compare Harmonic & Melodic Minor diatonic chords side by side [\u2318\u2325N]',
    parallel_key: 'Parallel Key \u2014 Show major/minor diatonic for the same root. See where borrowed chords come from [\u2318\u2325R]',
    secdom: 'Secondary Dominant \u2014 Show V7 resolving to each diatonic chord. Click for Available Scale auto-display [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325J]',
    capture: 'In Input mode, capture pad taps into Memory Slots in sequence [C]',
    capture_current: 'Save the current chord / TASTY / STOCK / Guitar voicing to a Memory Slot [Shift+C]',
    save: 'Save all current settings (key, scale, sound, memory, layout)',
    tutorial: 'Interactive tutorials \u2014 learn the basics step by step',
    help: 'Open help modal with full keyboard shortcut reference [?]',
    affiliate: 'Purchasing through these links supports development…',
    lang: 'Switch display language',
    octave: 'Shift pad octave range \u2014 Push/Launchpad can also control via octave buttons',
    show_all_positions: 'When on, shows every grid position of the chord plus the voicing boxes. When off, shows just one basic form.',
    play: 'Play the current chord [Space]',
    scale_select: 'Select a scale',
    chord_key: 'Switch between Major and Minor key',
    chord_key_picker: 'Open key picker to change key without switching to Scale mode',
    builder_clear: 'Clear the current chord and start over [X]',
    builder_back: 'Undo the last step in chord building [\u232B]',
    slash_chord: 'Slash chord (on chord)',
    guitar_diagram: 'Common guitar voicings reflected when chord is selected in the builder',
    guitar_label: 'Toggle note names on guitar fretboard',
    genre_preset: 'Switch guitar voicing genre \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: 'Cycle through guitar/bass voicing positions [, .]',
    to_pad: 'Use the builder Guitar engine to show guitar voicings on the 64-pad grid [Shift+G / V]',
    inst_clear: 'Clear notes entered on the instrument diagram',
    inst_play: 'Play notes entered on the instrument diagram',
    capture_end: 'End capturing and save to the current slot [E]',
    plain_clear: 'Clear all notes in Input mode [X]',
    midi_export: 'Export all memory slots as a MIDI file for your DAW',
    chs_export: 'Export all memory slots in CHS (Clover Chord Systems) format',
    midi_import: 'Import a MIDI file into memory slots',
    chs_import: 'Import a CHS file into memory slots',
    midi_device: 'Select MIDI input',
    midi_panic: 'All Notes Off \u2014 stop any stuck MIDI notes',
    sound_mute: 'Sound ON/OFF',
    sound_preset: 'Select sound preset',
    volume: 'Master volume',
    sound_fx: 'Effects \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 filter opens/closes on each note. LP/BP type, 2P/4P slope',
    ep_rhodes: 'PU Level \u2014 Pickup signal level. Turn down to hear Mechanical layer only',
    ep_voicing: 'Voicing \u2014 Pickup angle (bell character). 0=bark (on-axis, H2 dominant), 1=clean (off-axis)',
    ep_mechanical: 'Mechanical \u2014 Acoustic body noise (attack thud + release + tine radiation). Adds realism',
    velocity: 'Velocity curve',
    mem_view: 'Memory view \u2014 save and arrange chords in 16 slots [M]',
    perform_view: 'Perform view \u2014 play saved chords in real-time with 16 pads [P]',
    bank: 'Memory banks \u2014 16 slots \u00D7 up to 16 banks. [ ] to switch',
    slot_save: 'Save the current chord to the selected slot',
    play_slots: 'Play all saved chords in sequence',
    locut: 'Lo-cut \u2014 Remove lows for clarity (checkbox ON/OFF, slider = cutoff freq)',
    hicut: 'Hi-cut \u2014 Remove highs for a rounder tone (checkbox ON/OFF, slider = cutoff freq)',
    drive: 'Drive \u2014 Overdrive amount. Higher = more distortion',
    tremolo: 'Tremolo depth \u2014 Amplitude modulation depth (Peterson bulb + CdS physical model)',
    tremolo_speed: 'Tremolo speed \u2014 Modulation rate (Hz)',
    phaser: 'Phaser \u2014 Phase-shifted sweep for spacious movement',
    flanger: 'Flanger \u2014 Very short delay for metallic sweep',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Filter type \u2014 LP=Lowpass / BP=Bandpass',
    af_poles: 'Slope \u2014 2P=12dB/oct (gentle) / 4P=24dB/oct (steep)',
    af_depth: 'Depth \u2014 Range the filter opens and closes',
    af_decay: 'Decay \u2014 How fast the filter closes (smaller = faster)',
    af_q: 'Q \u2014 Resonance (sharpness of the peak)',
    af_wet: 'WET \u2014 Effect amount (0 = fully dry, 10 = fully wet)',
    af_vol: 'VOL \u2014 Output trim (turn down to avoid amp clipping)',
    eq_bass: 'Baxandall Bass \u2014 Low-shelf EQ. Center = flat',
    eq_treble: 'Baxandall Treble \u2014 High-shelf EQ. Center = flat',
    reverb_type: 'Reverb type \u2014 Spring (Twin-style swirling tail) / Plate (dense metallic tail)',
    reverb_amount: 'Reverb amount \u2014 Wet signal mix',
    reverb_decay: 'Reverb decay \u2014 Length of the tail',
    reverb_stereo: 'Stereo \u2014 ON spreads reverb across L/R',
    reverb_dwell: 'Dwell \u2014 Input drive into the spring tank',
    vel_thresh: 'Velocity threshold \u2014 Hits softer than this are treated as minimum velocity',
    vel_drive: 'Velocity drive \u2014 Tilt of the sensitivity curve (positive = accentuate, negative = flatten)',
    vel_compand: 'Compand \u2014 Compress/expand around mid velocity',
    vel_range: 'Range \u2014 Maximum velocity cap',
    midi_import: 'Import a MIDI file into memory slots',
    chs_import: 'Import a CHS file into memory slots',
  },
});
