// Deutsch
I18N.addLang('de', {
  help: {
    title: '64 Pad Explorer',
    description: 'Ein Werkzeug zum Erkunden von Skalen, Akkorden und Voicings auf einem 64-Pad-Raster.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Aus 12 Tonarten wählen',
    scale_scale: '<strong>Scale</strong> \u2014 Diatonisch, harmonisch Moll, melodisch Moll, Pentatonik, Bebop und mehr \u2014 31 Typen',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Zeigt die diatonischen Akkorde der gewählten Skala. Klicken, um in den Chord-Modus zu wechseln',
    chord_mode: 'Chord Mode (3 Schritte)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Grundton auf der Klaviertastatur auswählen',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Akkordtyp wählen (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Tensions hinzufügen (9, b9, #9, 11, #11, 13, b13, etc.). Mehrfachauswahl möglich',
    chord_text: '<strong>Texteingabe</strong> \u2014 "/" drücken zum Fokussieren. Cm7, G7(b9,#11), Am7/G etc. direkt eingeben. Vorschläge erscheinen automatisch',
    chord_onchord: '<strong>On Chord</strong> \u2014 Die "/"-Taste für Slash-Akkorde verwenden (Akkord über Basston)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Töne weglassen',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell Voicing (+1, +2 um Töne hinzuzufügen)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Umkehrungen (Root, 1st, 2nd, 3rd)',
    inv_1: '1. Umkehrung',
    inv_2: '2. Umkehrung',
    inv_3: '3. Umkehrung',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop Voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Antippen, um Pad-Anordnungen durchzuschalten (eine Zahl wie A1/3 = alternative Anordnungen verfügbar)',
    display: 'Anzeige',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Gitarrengriffbrett, Bass, Klaviertastatur und Notenzeile unabhängig ein-/ausschalten. Hinweis: Gitarren-/Basspositionen zeigen spielbare Griffmuster des Instruments, sie entsprechen nicht der Pad-Anordnung',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Zeigt den Quintenzirkel an. Mit der Tonartwahl verknüpft, zeigt diatonische Akkorde und Funktionen (T/SD/D). Moll-Modus-Umschaltung unterstützt',
    display_label: '<strong>Notenname / Stufe</strong> \u2014 Zwischen Notennamen (C, D, E) und Stufen (R, 2, 3) auf Gitarre und Pads umschalten',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Pad-Tonumfang um eine Oktave verschieben',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A AN/AUS</strong> \u2014 Sound mit dem Lautsprecher-Symbol ein-/ausschalten',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Rhodes Physical Modeling. HPS-Mitglieder können das Suitcase-Preset (physikalisch modellierte Amp-Chain) wählen. \u25BC öffnet das Detail-Panel',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Peterson Vactrol Physical Modeling (Stereo). TREM/T.SPD für Tiefe und Rate',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 Presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 Presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Hüllkurvenfilter (Auto-Wah). 3 Typen: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Analoge Sättigung. Fügt dem Sound eine warme Verzerrung hinzu',
    sound_fx: '<strong>Effekte</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Pad oder Voicing Box anklicken, um den Klang abzuspielen',
    midi: 'MIDI',
    midi_detect: 'Automatische Erkennung WebMIDI-kompatibler Geräte',
    midi_push: 'Unterstützung für serielle MIDI-Ausgabe von Ableton Push',
    midi_chord: 'Automatische Akkorderkennung aus eingegebenen Noten',
    midi_sustain: '<strong>Sustain-Pedal</strong> \u2014 MIDI CC64 (Hold Pedal) unterstützt',
    color_title: 'Farblegende',
    color_root: '<strong>Root</strong> \u2014 Grundton',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Skalentöne / Akkordtöne',
    color_char: '<strong>Charakteristisch</strong> \u2014 Töne, die die Skala/den Akkord definieren',
    color_3rd: '<strong>3rd</strong> \u2014 Guide Tone (Terz)',
    color_7th: '<strong>7th</strong> \u2014 Guide Tone (Septime)',
    color_tension: '<strong>Tension</strong> \u2014 Spannungstöne',
    color_avoid: '<strong>Avoid</strong> \u2014 Skalenton einen Halbton über einem Akkordton (im Chord-Modus)',
    color_palette: 'Farbpalette: Okabe-Ito (farbfehlsichtigkeitsfreundlich)',
    input_title: 'Guitar / Piano Eingabe',
    input_desc1: 'Gitarrengriffbrett oder Klaviertastatur anklicken, um Noten einzugeben',
    input_desc2: 'Akkorde werden automatisch aus der Eingabe erkannt und auf dem Pad dargestellt',
    input_desc3: '<strong>Clear</strong> \u2014 Eingabe löschen, <strong>Play \u25B6</strong> \u2014 Eingegebene Noten abspielen',
    input_title: 'Input Mode',
    input_desc1: 'Pads frei anklicken, um Noten auszuwählen \u2192 Echtzeit-Akkorderkennung',
    input_desc2: 'Ohne Theoriefilter. Erkunden \u2192 entdecken \u2192 Theorie danach lernen',
    input_desc3: 'Bei Akkorderkennung werden Stufenlabels (R, 3, 5, b7 usw.) auf den Pads angezeigt. Gitarre, Bass, Klavier und Notensystem aktualisieren sich automatisch',
    input_memory: '<strong>Memory</strong> \u2014 Akkorde in 16 Slots speichern und abrufen',
    input_banks: '<strong>Banks</strong> \u2014 16 Slots \u00D7 bis zu 16 Bänke. Mit <kbd>[</kbd> <kbd>]</kbd> wechseln. Duplizieren und Umbenennen unterstützt',
    input_export: '<strong>MIDI Export</strong> \u2014 Gespeicherte Akkorde als MIDI-Datei exportieren',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> Button oder <kbd>p</kbd> Taste zum Umschalten',
    perform_desc1: 'Memory Slot-Akkorde in Echtzeit mit einem 16-Pad-Layout spielen',
    perform_desc2: '\u00DCber Tastatur (4\u00D74-Raster) oder MIDI-Pads ausl\u00F6sen',
    perform_desc3: 'Slots per Drag & Drop neu anordnen',
    shortcut_title: 'Tastenkürzel',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Diatonischen Akkord auswählen (7-Ton-Skalen)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Voicing Box auswählen (Alternativen durchschalten)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrungen durchschalten (Chord-Modus)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition des Grundtons',
    sc_omit: '<kbd>o</kbd> \u2014 Omit 5 umschalten',
    sc_rootless: '<kbd>r</kbd> \u2014 Rootless umschalten',
    sc_shell: '<kbd>s</kbd> \u2014 Shell durchschalten (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Drop durchschalten (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: "<kbd>v</kbd> — Guitar-Engine ON/OFF (ausgewähltes Gitarren-Voicing auf dem 64-Pad-Raster anzeigen)",
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Gitarrenposition wechseln (zurück / vor)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Bass-Position wechseln (zurück / vor)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Akkord löschen (Chord-Modus)',
    sc_pad_explore: '<b>Pad (Chord-Modus)</b> \u2014 Klicken zum Ein-/Ausschalten \u2014 Builder wird automatisch aktualisiert',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Capture starten / im nächsten Slot speichern',
    sp_end: '<kbd>e</kbd> \u2014 Capture beenden',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Speicherslot abrufen (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Chromatische Transposition (alle Noten \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Umkehrung (tiefste \u21911 Okt. / höchste \u21931 Okt.)',
    sp_clear: '<kbd>x</kbd> \u2014 Alles löschen',
    sp_transfer: '<b>Chord switch</b> \u2014 Erkannten Akkord in den Chord-Modus übertragen',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 4\u00D74-Raster l\u00F6st Slots 1\u201316 aus',
    pf_midi: 'MIDI-Pads (Noten 36\u201354) l\u00F6sen ebenfalls Slots aus',
    shortcut_common: 'Allgemein (alle Modi)',
    sc_perform: '<kbd>p</kbd> \u2014 Perform-Ansicht umschalten',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Memory Slots r\u00FCckg\u00E4ngig machen (bis zu 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Aktuellen Akkord / Voicing in einen Memory Slot speichern',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Aktuellen Akkord / Voicing in einen Memory Slot speichern',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 Direkt in einen Memory Slot speichern',
    sc_space: '<kbd>Space</kbd> \u2014 Aktuellen Akkord abspielen',
    sc_esc: '<kbd>Esc</kbd> \u2014 Voicing Box abwählen / Hilfe schließen',
    sc_help: '<kbd>?</kbd> \u2014 Hilfe ein-/ausblenden',
    sc_slash: '<kbd>/</kbd> \u2014 Text-Akkordeingabe fokussieren',
    sc_tasty_nav: "<kbd>z</kbd> / <kbd>x</kbd> — TASTY/STOCK/Guitar Voicing vor/zurück",
    shortcut_display: 'Anzeige umschalten (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitar',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Bass',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Quintenzirkel',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Notenzeile',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Texteingabe',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Tonartanzeige',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 Header / Info-Leiste',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: 'Tipps beim Start anzeigen',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Auf C-Dur sperren',
    color_coding_toggle: 'Charakteristische Töne färben',
    show_all_positions_toggle: 'Alle Akkordpositionen anzeigen',
    c_fixed_tip: 'Das Pad zeigt immer die C-Dur-Tonleiter an, unabhängig von Key/Scale/Chord.',
    push_voicing_toggle: 'Voicing overview',
    layout: 'Layout',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Charakteristisch',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
    scale_root: 'Skalengrundton',
  },
  ui: {
    close: 'Schließen',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Einstellungen speichern',
    sound_hint: 'Wähle ein Sound-Preset, um Audio zu aktivieren',
    tap_to_start: 'Tippen zum Aktivieren',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: 'Tippe auf ein Pad zum Spielen!',
    input_keys_disabled: 'Tonartauswahl wird im Input-Modus nicht verwendet',
    load_vst: 'VST/AU-Plugin laden...',
    affiliate_label: '',
    staff: 'Noten',
    circle: 'Quintenzirkel',
    help: 'Hilfe',
    view_settings: 'Anzeigeeinstellungen',
    show_all_positions: 'Alle Positionen',
    view_focus: 'Ansicht',
    view_layout: 'Layout',
    view_all: 'Alle Bereiche',
    view_pad: 'Nur Pads',
    view_chord: 'Nur Chord Builder',
    view_info: 'Nur Info / Memory',
    layout_abc: 'Pad → Chord → Circle',
    layout_acb: 'Pad → Circle → Chord',
    layout_bac: 'Chord → Pad → Circle',
    layout_bca: 'Chord → Circle → Pad',
    layout_cab: 'Circle → Pad → Chord',
    layout_cba: 'Circle → Chord → Pad',
    view_setup_note: 'In der Desktop-Version öffnet Push 3 Setup ebenfalls diesen Bildschirm. Jog Wheel links/rechts wählt Ansicht oder Layout, Drehen ändert den Wert, Jog Wheel drücken oder Setup schließt ihn.',
    oct_down: 'Oktave nach unten',
    oct_up: 'Oktave nach oben',
    toggle_guitar: 'Gitarrengriffbrett ein-/ausblenden (⌘⌥G)',
    toggle_bass: 'Bassgriffbrett ein-/ausblenden (⌘⌥B)',
    toggle_piano: 'Klaviertastatur ein-/ausblenden (⌘⌥P)',
    mode_scale: 'Scale-Modus \u2014 Skalent\u00F6ne auf den Pads anzeigen (Tab zum Wechseln)',
    mode_chord: 'Chord-Modus \u2014 Akkorde mit Voicings bauen (Tab zum Wechseln)',
    mode_input: 'Input-Modus \u2014 Pads frei antippen um Akkorde zu erkennen (Tab zum Wechseln)',
    play_chord: 'Aktuellen Akkord abspielen (Space)',
    toggle_staff: 'Notenzeile ein-/ausblenden (⌘⌥S)',
    toggle_circle: 'Quintenzirkel ein-/ausblenden (⌘⌥F)',
    toggle_sound: 'Sound-Steuerung ein-/ausblenden',
    sound_mute: 'Sound AN/AUS',
    sound_expand: 'Detaillierte Sound-Einstellungen ein-/ausblenden',
  },
  label: {
    note_name: 'Note',
    degree: 'Stufe',
    chord_input: 'Akkord eingeben',
    chord_hint: 'Tensions in ( ): C7(b9,#11) | dim, h=m7\u266D5 unterstützt',
    key_hint: 'Auch im Scale-Modus oder Quintenzirkel einstellbar',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mein Blog',
    guide: 'Anleitung',
    wishlist: 'Wunschliste',
  },
  input: {
    status_idle: 'Capture drücken, um Akkorde zu erstellen',
    status_capturing: 'Aufnahme: Slot {slot}/16 \u2014 Pads anklicken, dann Capture zum Speichern',
    status_editing: 'Bearbeitung: Slot {slot} \u2014 Pads anklicken zum Ändern',
    notes_label: 'Noten: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    memory_full: 'Memory Slots sind voll',
    no_current_chord: 'Kein aktueller Akkord zum Speichern',
    slot_selected: 'Slot {slot} ausgewählt',
    slot_cleared: 'Slot {slot} gelöscht',
    undo: 'Rückgängig',
    settings_saved: 'Einstellungen gespeichert',
    no_chords: 'Keine Akkorde in den Speicherslots',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    default: 'Über ein Steuerelement fahren, um seine Funktion zu sehen',
    mode_scale: 'Scale Mode \u2014 Skalentöne auf dem 64-Pad-Raster anzeigen [Tab]',
    mode_chord: 'Chord Mode \u2014 Akkorde Schritt für Schritt bauen: Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Input Mode \u2014 Pads frei antippen, Akkorde werden automatisch erkannt [Tab]',
    guitar: 'Gitarrengriffbrett ein-/ausblenden [\u2318\u2325G]',
    bass: 'Bassgriffbrett ein-/ausblenden [\u2318\u2325B]',
    piano: 'Klaviertastatur ein-/ausblenden [\u2318\u2325P]',
    link_mode: 'Link Mode \u2014 gespielte Noten werden in Echtzeit auf allen Instrumenten synchronisiert [\u2318\u2325L]',
    staff: 'Notenzeile ein-/ausblenden [\u2318\u2325S]',
    circle: 'Quintenzirkel \u2014 Tonika, Subdominante, Dominante in passenden Farben [\u2318\u2325F]',
    cof_major: 'Äußerer Ring \u2014 Dur-Tonart auswählen',
    cof_minor: 'Innerer Ring \u2014 Moll-Tonart auswählen',
    cof_natural: 'Natürliches Moll',
    cof_harmonic: 'Harmonisch Moll',
    cof_melodic: 'Melodisch Moll',
    sound: 'Audio-Steuerungsfeld ein-/ausblenden [\u2318\u2325A]',
    memory: 'Memory Slot-Panel ein-/ausblenden \u2014 Akkorde in 16 Slots speichern/abrufen [\u2318\u2325M]',
    sect_key: 'Tonartanzeige ein-/ausblenden',
    sect_input: 'Text-Akkordeingabe ein-/ausblenden [\u2318\u2325T]',
    sect_quality: 'Root/Quality/Tension-Auswahl ein-/ausblenden [\u2318\u2325Q]',
    sect_voicing: 'Voicing-Steuerung ein-/ausblenden (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Akkordnamen direkt eingeben \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Verfügbare Skalen für den aktuellen Akkord anzeigen. Slash-Akkorde mit akkord-fremdem Basston werden vom Basston aus interpretiert',
    sort_practical: 'Praktische Sortierung \u2014 bevorzugt häufig verwendete Skalen. Einschließlich Sekundärdominant-Skalen (z.B. Mixolydisch b13 für V7/ii)',
    sort_diatonic: 'Diatonische Sortierung \u2014 sortiert nach theoretischem Abstand zur aktuellen Tonart',
    omit5: 'Quinte aus dem Voicing entfernen [O]',
    rootless: 'Grundton entfernen [R]',
    omit3: 'Terz aus dem Voicing entfernen',
    shell137: 'Shell Voicing: Root-3rd-7th [S]',
    shell173: 'Shell Voicing: Root-7th-3rd [S]',
    shell_off: 'Shell Voicing deaktivieren [S]',
    shell_ext: 'Töne zum Shell Voicing hinzufügen (+1 oder +2 Akkordtöne)',
    inv_root: 'Grundstellung [\u2193]',
    inv: 'Umkehrung [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 raffinierte Voicings nach Topnote sortiert. Für \u25B37, m7, 7 (HPS-exklusiv) [T]',
    tasty_nav: 'Variationen durchschalten [Z / X]',
    stock: 'Stock Voicing \u2014 gängige Klavier-Voicings (HPS-exklusiv) [K]',
    stock_nav: 'Variationen durchschalten [Z / X]',
    root_notation: 'Zwischen \u266F und \u266D Notation wechseln',
    root_grid: 'Grundton auswählen',
    quality_grid: 'Akkord-Quality auswählen (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Tensions zum Akkord hinzufügen (9, b9, #9, 11, #11, 13, b13) \u2014 Mehrfachauswahl möglich',
    diatonic: 'Diatonische Akkorde der aktuellen Skala \u2014 klicken zum Wechseln in den Chord-Modus [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Harmonisch und melodisch Moll-Diatonik nebeneinander vergleichen [\u2318\u2325N]',
    parallel_key: 'Parallel Key \u2014 Dur-/Moll-Diatonik für denselben Grundton anzeigen. Herkunft von Borrowed Chords sichtbar [\u2318\u2325R]',
    secdom: 'Sekundärdominante \u2014 V7 zeigen, der zu jedem diatonischen Akkord auflöst. Klicken für automatische Available Scale-Anzeige [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: 'Pad-Eingaben im Input-Modus der Reihe nach in Memory Slots aufnehmen [C]',
    capture_current: 'Aktuellen Akkord / TASTY / STOCK / Guitar-Voicing in einen Memory Slot speichern [Shift+C]',
    capture_end: 'Aufnahme beenden und im aktuellen Slot speichern [E]',
    save: 'Alle aktuellen Einstellungen speichern (Tonart, Skala, Sound, Memory, Layout)',
    tutorial: 'Interaktive Tutorials \u2014 Grundlagen Schritt für Schritt lernen',
    help: 'Hilfe-Dialog mit vollständiger Tastenkürzel-Referenz öffnen [?]',
    affiliate: 'Über diese Links einkaufen unterstützt die Entwicklung\u2026',
    lang: 'Anzeigesprache wechseln',
    octave: 'Pad-Oktavbereich verschieben \u2014 Push/Launchpad kann auch über Oktavtasten steuern',
    show_all_positions: 'Eingeschaltet zeigt alle Rasterpositionen des Akkords sowie die Voicing-Boxen. Ausgeschaltet wird nur eine Grundform gezeigt.',
    play: 'Aktuellen Akkord abspielen [Space]',
    scale_select: 'Skala auswählen',
    chord_key: 'Zwischen Dur- und Moll-Tonart wechseln',
    chord_key_picker: 'Tonart-Auswahl öffnen, um die Tonart zu ändern ohne in den Scale-Modus zu wechseln',
    builder_clear: 'Aktuellen Akkord löschen und neu beginnen [X]',
    builder_back: 'Letzten Schritt im Akkordaufbau rückgängig machen [\u232B]',
    slash_chord: 'Slash Chord (On Chord)',
    guitar_diagram: 'Gängige Gitarren-Voicings werden angezeigt, wenn ein Akkord im Builder ausgewählt ist',
    guitar_label: 'Notennamen auf dem Gitarrengriffbrett ein-/ausblenden',
    genre_preset: 'Gitarren-Voicing-Genre wechseln \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: 'Gitarren-/Bass-Voicing-Positionen durchschalten [, .]',
    to_pad: 'Gitarren-/Stock-Voicing auf das 64-Pad-Raster übertragen [V]',
    inst_clear: 'Auf dem Instrumentendiagramm eingegebene Noten löschen',
    inst_play: 'Auf dem Instrumentendiagramm eingegebene Noten abspielen',
    plain_clear: 'Alle Noten im Input-Modus löschen [X]',
    midi_export: 'Alle Memory Slots als MIDI-Datei für die DAW exportieren',
    chs_export: 'Alle Memory Slots im CHS-Format (Clover Chord Systems) exportieren',
    midi_import: 'MIDI-Datei in Memory Slots importieren',
    chs_import: 'CHS-Datei in Memory Slots importieren',
    midi_device: 'MIDI-Eingang auswählen',
    midi_panic: 'All Notes Off \u2014 hängende MIDI-Noten stoppen',
    sound_mute: 'Sound AN/AUS',
    sound_preset: 'Sound-Preset auswählen',
    volume: 'Master-Lautstärke',
    sound_fx: 'Effekte \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 Filter öffnet/schließt bei jeder Note. LP/BP Typ, 2P/4P Flankensteilheit',
    velocity: 'Velocity-Kurve',
    mem_view: 'Memory-Ansicht \u2014 Akkorde in 16 Slots speichern und anordnen [M]',
    perform_view: 'Perform-Ansicht \u2014 gespeicherte Akkorde in Echtzeit mit 16 Pads spielen [P]',
    bank: 'Memory-Bänke \u2014 16 Slots \u00D7 bis zu 16 Bänke. [ ] zum Wechseln',
    slot_save: 'Aktuellen Akkord im ausgewählten Slot speichern',
    play_slots: 'Alle gespeicherten Akkorde nacheinander abspielen',
    locut: 'Lo-cut \u2014 Tiefen entfernen f\u00FCr Klarheit (Checkbox ON/OFF, Slider = Grenzfrequenz)',
    hicut: 'Hi-cut \u2014 H\u00F6hen entfernen f\u00FCr rundere Klangfarbe (Checkbox ON/OFF, Slider = Frequenz)',
    drive: 'Drive \u2014 Overdrive-Menge. H\u00F6her = mehr Verzerrung',
    tremolo: 'Tremolo-Tiefe \u2014 Amplitudenmodulationstiefe (Peterson + CdS physikalisches Modell)',
    tremolo_speed: 'Tremolo-Geschwindigkeit \u2014 Modulationsrate (Hz)',
    phaser: 'Phaser \u2014 Phasenverschobener Sweep',
    flanger: 'Flanger \u2014 Sehr kurzes Delay, metallischer Sweep',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Filtertyp \u2014 LP=Tiefpass / BP=Bandpass',
    af_poles: 'Flanke \u2014 2P=12dB/oct (sanft) / 4P=24dB/oct (steil)',
    af_depth: 'Depth \u2014 Bereich der Filter\u00F6ffnung/-schlie\u00DFung',
    af_decay: 'Decay \u2014 Geschwindigkeit, mit der der Filter schlie\u00DFt (kleiner = schneller)',
    af_q: 'Q \u2014 Resonanz (Sch\u00E4rfe des Peaks)',
    af_wet: 'WET \u2014 Effektanteil (0 = komplett dry, 10 = komplett wet)',
    af_vol: 'VOL \u2014 Output-Trim (bei Amp-Verzerrung absenken)',
    eq_bass: 'Baxandall Bass \u2014 Tiefen-Shelving-EQ. Mitte = flach',
    eq_treble: 'Baxandall Treble \u2014 H\u00F6hen-Shelving-EQ. Mitte = flach',
    reverb_type: 'Reverb-Typ \u2014 Spring (Twin-Stil schwingende Fahne) / Plate (metallische dichte Fahne)',
    reverb_amount: 'Reverb-Menge \u2014 Wet-Signal-Mix',
    reverb_decay: 'Reverb-Decay \u2014 L\u00E4nge der Fahne',
    reverb_stereo: 'Stereo \u2014 ON verteilt Reverb auf L/R',
    reverb_dwell: 'Dwell \u2014 Eingangspegel in den Federhall-Tank',
    vel_thresh: 'Velocity-Schwelle \u2014 Anschl\u00E4ge darunter werden als minimale Velocity behandelt',
    vel_drive: 'Velocity Drive \u2014 Neigung der Sensitivit\u00E4tskurve (positiv = betont, negativ = gl\u00E4ttet)',
    vel_compand: 'Compand \u2014 Komprimiert/expandiert um die mittlere Velocity',
    vel_range: 'Range \u2014 Maximale Velocity-Grenze',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Grundton auswählen',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'Alle Geräte',
  },
  memory: {
    slot_empty: 'Slot {slot}: Leer',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    recall: 'Abrufen',
    play: 'Abspielen',
    duplicate: 'Duplizieren',
    delete: 'Löschen',
    save_here: 'Hier speichern',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Klicken zum Umbenennen',
    rename: 'Umbenennen',
    duplicate: 'Duplizieren',
    delete: 'L\u00F6schen',
    rename_prompt: 'Bank-Name eingeben:',
    confirm_delete: '"{name}" l\u00F6schen?',
    limit_reached: 'Maximal 16 B\u00E4nke',
    cannot_delete_last: 'Letzte Bank kann nicht gel\u00F6scht werden',
  },
  diatonic: {
    parallel: 'Paralleltonart',
    relative: 'Relative Tonart',
    harm_mel: 'Harm/Mel',
    secdom: 'Sekundärdominante',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Alle anzeigen',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Anleitung',
    tagline: 'Ein Browser-Tool zum Erkunden von Skalen, Akkorden und Voicings auf einem 64-Pad-Raster.<br>Keine Klangquelle n\u00F6tig \u2014 nur Chrome.',
    cta: 'App \u00F6ffnen',
    features: 'Funktionen',
    feat_sound: '<strong>Keine Klangquelle n\u00F6tig</strong> \u2014 Sound wird direkt in Chrome abgespielt. 4 Orgel- + 8 E-Piano-Presets integriert. Effekte (Drive, Reverb, Phaser, Flanger, Tremolo, Lo Cut, Hi Cut, Auto Filter) inklusive',
    feat_input: '<strong>Keine Pad-Kenntnisse erforderlich</strong> \u2014 Akkorde in 3 Schritten aufbauen. Tensions werden angezeigt. Pads direkt anklicken zur Eingabe',
    feat_text_input: '<strong>Text-Akkordeingabe</strong> \u2014 "/" drücken um Cm7, G7(b9,#11), Am7/G etc. direkt einzugeben. Autovervollständigung. Abkürzungen wie dim, h(=m7\u266D5)',
    feat_detect: '<strong>Akkorderkennung</strong> \u2014 Echtzeit-Akkorderkennung aus angeklickten T\u00F6nen. Unterst\u00FCtzt Omit, Slash-Akkorde und mehrere Vorschl\u00E4ge',
    feat_instruments: '<strong>Guitar / Bass / Keyboard-Anzeige</strong> \u2014 Zeigt Akkordt\u00F6ne auf Gitarrengriffbrett, Bass und Klavier. Eingabe \u00FCber Gitarrengriffbrett wird automatisch auf Pads \u00FCbertragen. Im Chord-Modus werden Positionen nach Grundton-Saite gruppiert',
    feat_scales: '<strong>Scale-Anzeige</strong> \u2014 31 Skalen \u00D7 12 Tonarten. Diatonisch, harmonisch Moll, melodisch Moll, Pentatonik, Bebop und mehr',
    feat_diatonic: '<strong>Diatonische Akkorde</strong> \u2014 Diatonische Akkorde werden als Leiste f\u00FCr die gew\u00E4hlte Skala angezeigt. Per Klick oder Tastenk\u00FCrzel sofort abspielen. Dreiklang/Vierklang-Umschaltung',
    feat_voicing: '<strong>Voicing-Operationen</strong> \u2014 Inversions, Drop 2/3, Shell Voicing, Omit, Rootless. Pfeiltasten f\u00FCr Inversions, Buttons f\u00FCr verschiedene Fingerings',
    feat_memory: '<strong>Chord Memory</strong> \u2014 Lieblingsakkorde in 16 Slots speichern. Als MIDI-Dateien f\u00FCr die DAW exportieren',
    feat_perform: '<strong>Perform Mode</strong> \u2014 Memory-Akkorde in Echtzeit mit 16 Pads oder PC-Tastatur spielen',
    feat_parent: '<strong>Available Scale R\u00FCckw\u00E4rtssuche</strong> \u2014 Skalen finden, die den Akkord enthalten. Available Tensions auf einen Blick sehen. Practical/Diatonic-Sortierung umschaltbar',
    feat_pivot: '<strong>Pivot-Akkord-Denken</strong> \u2014 Akkord manuell eingeben und die diatonische Leiste verschwindet. Alle Tonarten, zu denen der Akkord geh\u00F6ren k\u00F6nnte, werden angezeigt. Ideal f\u00FCr Modulationsanalyse',
    feat_dimming: '<strong>Praktische Tension-Anzeige</strong> \u2014 Bei nicht-dominanten Septakkorden werden ungew\u00F6hnliche Tensions (b9, #9, b13 usw.) abgedimmt. Weiterhin ausw\u00E4hlbar',
    feat_circle: '<strong>Quintenzirkel</strong> \u2014 Zeigt den Quintenzirkel an. Mit der Tonartwahl verknüpft, zeigt diatonische Akkorde und Funktionen (T/SD/D). Moll-Modus-Umschaltung unterstützt',
    feat_banks: '<strong>Memory-Bänke</strong> \u2014 16 Slots \u00D7 bis zu 16 Bänke. Wechseln, duplizieren und umbenennen. <kbd>[</kbd> <kbd>]</kbd> Tasten zum Wechseln',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Hüllkurvenfilter (Auto-Wah). 3 Typen: Cry Baby / Mu-Tron / Moog. Frequenz, Resonanz, Empfindlichkeit und Decay einstellen',
    feat_drive: '<strong>Drive</strong> \u2014 Analoge Sättigung. Fügt dem Sound eine warme Verzerrung hinzu',
    feat_clav: '<strong>Clavinet-Presets</strong> \u2014 2 Clavinet-Presets zu E.PIANO hinzugefügt (Clav Muted, Clav Bright). Perfekt für Funk',
    feat_midi_sens: '<strong>MIDI-Anschlagempfindlichkeit</strong> \u2014 Push 3-artige 4-Parameter-Anpassung (Threshold, Drive, Compand, Range) der Velocity-Kurve. Echtzeit-Kurvenvisualisierung. Funktioniert mit allen MIDI-Controllern',
    feat_push_oct: '<strong>Push 3 Oktav-Synchronisation</strong> \u2014 Push 3 Oktav-Tasten \u25B2\u25BC synchronisieren automatisch mit der Oktavverschiebung der App',
    feat_i18n: '<strong>Mehrsprachig</strong> \u2014 9 Sprachen (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Screenshots',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Tonart und Skala w\u00E4hlen, um Skalent\u00F6ne farbcodiert auf dem 64-Pad-Raster zu sehen. Akkorde aus der diatonischen Leiste w\u00E4hlen.',
    ss_scale_alt: 'Scale Mode \u2014 C-Dur (Ionisch) Skala-Anzeige',
    ss_scale_caption: 'C-Dur (Ionisch) \u2014 Root (orange), Skalent\u00F6ne (blau), charakteristische T\u00F6ne (gelb)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Akkorde in 3 Schritten aufbauen: Root \u2192 Quality \u2192 Tension. Voicings mit Inversions, Drop, Shell und Omit anpassen. Im Parent Scale-Panel Skalen r\u00FCckw\u00E4rts suchen.',
    ss_chord_alt: 'Chord Mode \u2014 Dm7-Akkord mit Tension-Raster',
    ss_chord_caption: 'Dm7 \u2014 Akkordt\u00F6ne, 3rd (rosa), 7th (gr\u00FCn). Layout-Optionen in den Voicing Boxes pr\u00FCfen',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Pads frei anklicken f\u00FCr Echtzeit-Akkorderkennung. Verstehe Akkorde auch ohne Theoriekenntnisse.',
    ss_input_alt: 'Input Mode \u2014 C7 Echtzeit-Akkorderkennung',
    ss_input_caption: 'C7 \u2014 Pads anklicken f\u00FCr automatische Akkorderkennung. Mehrere Vorschl\u00E4ge werden angezeigt',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Gespeicherte Akkorde auf 16 Pads f\u00FCr Echtzeit-Performance per Tastatur oder MIDI-Pads platzieren.',
    ss_perform_alt: 'Perform Mode \u2014 16 Slots mit Akkorden',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 in Slots gespeichert. Abspielen \u00FCber 4\u00D74-Tastatur-Raster',
    ss_parent: 'Available Scale + Pivot-Akkord',
    ss_parent_desc: 'Skalen r\u00FCckw\u00E4rts suchen, die den Akkord enthalten. Zwischen Practical (nach Nutzbarkeit) und Diatonic (nach Theorie) Sortierung umschalten. Bei manueller Akkordeingabe verschwindet die diatonische Leiste f\u00FCr Pivot-Akkord-Analyse.',
    ss_parent_alt: 'Parent Scale-Panel und Gitarrengriffbrett-Anzeige',
    ss_parent_caption: 'Dm7 \u2192 C-Dur (Dorisch), C Mel.Min (Dorisch b2), F-Dur (\u00C4olisch) usw. Available Tensions angezeigt',
    ss_parent_note: '\u203B Pentatonische/Blues-Skalen sind modal (horizontaler Ansatz) und geh\u00F6ren zu einem anderen System als die Akkord-Skalen-Theorie (vertikale Zuordnung), daher sind sie nicht in Available Scale enthalten. In der Praxis ist die Pentatonik oft die erste Wahl.',
    ss_velocity: 'MIDI Velocity-Empfindlichkeit',
    ss_velocity_desc: 'MIDI-Controller Velocity-Empfindlichkeit mit Push 3-artigen 4 Parametern einstellen. Im Abschnitt VELOCITY SENSITIVITY im Sound-Panel konfigurieren. Echtzeit-Kurvenvisualisierung.',
    ss_push_oct: 'Push 3 Oktavtasten-Synchronisation',
    ss_push_oct_desc: 'Push 3 Oktav-Tasten \u25B2\u25BC (CC#55/CC#54) synchronisieren sich automatisch mit der Oktavverschiebung der App. Drücke die Oktavtasten auf Push 3 und die Anzeigeoktave aktualisiert sich automatisch.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'HPS-exklusive Voicing-Funktionen',
    ss_hps_voicing_intro: "HPS-Mitglieder erhalten 3 Voicing-Werkzeuge. Wählen Sie TASTY / STOCK / Guitar im Builder, um das jeweilige Voicing automatisch auf dem 64-Pad-Raster anzuzeigen.",
    ss_tasty: 'TASTY Voicing \u2014 Nach Topnote klassifiziert',
    ss_tasty_desc: '129 raffinierte Voicings als Stufen-Arrays dargestellt. W\u00E4hlen Sie einen Akkord, dr\u00FCcken Sie <kbd>T</kbd> zum Aktivieren und erneut zum Durchbl\u00E4ttern der Voicings. Automatische Auswahl der optimalen Pad-Position.',
    ss_tasty_target: 'Ziel: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'Der Info-Bereich zeigt die Stufen-Stapelreihenfolge (z.B. <code>m9 (b3-b7-9-5-1)</code>). Dies ist die Voicing-Struktur \u2014 welche T\u00F6ne von unten nach oben gestapelt werden.',
    ss_tasty_labels_title: 'Bedeutung der Labels',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Grundton (1. Stufe) weggelassen. \u00DCblich in Jazz/R&B/Neo-Soul, wo der Bassist den Grundton \u00FCbernimmt.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 5. Stufe weggelassen. Die Quinte hat wenig tonalen Charakter und wird durch eine Tension f\u00FCr einen reicheren Klang ersetzt.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 3. Stufe weggelassen. N\u00E4hert sich einem Sus- oder Quartal-Klang.',
    ss_tasty_ops_title: 'Bedienung',
    ss_stock: 'STOCK Voicing \u2014 Klavier-Voicing-Sammlung',
    ss_stock_desc: "154 Klavier-Voicings aus Lehrmaterialien in Stufennotation. Umfasst Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Ausgewählte Voicings erscheinen automatisch auf dem 64-Pad-Raster.",
    ss_stock_ops_title: 'Bedienung',
    ss_guitar_pos: 'Guitar Position \u2014 Gitarren-Voicings',
    ss_guitar_pos_desc: "Automatische Berechnung der Akkordpositionen auf dem Gitarrengriffbrett. Die linke Guitar-Ansicht ist der Instrumentenbereich; Guitar im Builder ist die Voicing-Engine für das 64-Pad-Raster.",
    usecases: 'Anwendungsf\u00E4lle',
    uc1_q: '\u201EIch m\u00F6chte herausfinden, wie ich diesen Akkord auf den Pads greifen kann\u201C',
    uc1_a: '\u2192 Root, Quality und Tension im <span class="mode-badge chord">Chord</span>-Modus w\u00E4hlen \u2192 Layouts in den Voicing Boxes pr\u00FCfen',
    uc2_q: '\u201EIch m\u00F6chte eine Skala aus meinem Unterricht auf den Pads sehen\u201C',
    uc2_a: '\u2192 Tonart und Skala im <span class="mode-badge scale">Scale</span>-Modus w\u00E4hlen. 31 Skalen verf\u00FCgbar',
    uc3_q: '\u201EIch m\u00F6chte eine Akkordfolge f\u00FCr meine DAW erstellen\u201C',
    uc3_a: '\u2192 Akkorde in Memory Slots speichern \u2192 MIDI Export zum Import in die DAW',
    uc4_q: '\u201EZu welcher Tonart geh\u00F6rt dieser Akkord?\u201C',
    uc4_a: '\u2192 R\u00FCckw\u00E4rtssuche im Available Scale-Panel. Zwischen Practical/Diatonic-Sortierung umschalten',
    uc7_q: '\u201EIch m\u00F6chte Pivot-Akkorde f\u00FCr die Modulation finden\u201C',
    uc7_a: '\u2192 Akkord manuell im <span class="mode-badge chord">Chord</span>-Modus eingeben. Die diatonische Leiste verschwindet und Available Scale zeigt alle m\u00F6glichen Tonarten',
    uc5_q: '\u201EIch m\u00F6chte Akkordfolgen durch Spielen \u00FCberpr\u00FCfen\u201C',
    uc5_a: '\u2192 Akkorde in Memory-Slots speichern, dann mit MIDI-Controller oder PC-Tastatur spielen',
    uc6_q: '\u201EIch m\u00F6chte Gitarrenakkorde auf den Pads \u00FCberpr\u00FCfen\u201C',
    uc6_a: '\u2192 Gitarrengriffbrett anklicken zur Eingabe \u2192 Automatisch auf Pads dargestellt \u2192 Akkordname erkannt',
    uc8_q: '\u201EIch m\u00F6chte professionelle Voicings lernen\u201C',
    uc8_a: '\u2192 Erstellen Sie einen Akkord im <span class="mode-badge chord">Chord</span>-Modus, dann dr\u00FCcken Sie <kbd>T</kbd> f\u00FCr TASTY (Topnote-Klassifikation) oder <kbd>K</kbd> f\u00FCr STOCK (Klavier-Voicings). Mit Stufennotation anzeigen, im Speicher sichern und in die DAW exportieren',
    quickstart: 'Schnellstart',
    qs_modes: '3 Modi',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Skalen und diatonische Akkorde anzeigen<br><span class="mode-badge chord">Chord</span> Akkorde in 3 Schritten aufbauen. Voicing-Operationen verf\u00FCgbar<br><span class="mode-badge input">Input</span> Pads frei anklicken \u2192 Akkordnamen automatisch erkennen',
    qs_first: 'Erste Schritte',
    qs_step1: 'Tonart w\u00E4hlen (z.B. C)',
    qs_step2: 'Skala w\u00E4hlen (z.B. Major) \u2192 Skalent\u00F6ne erscheinen auf den Pads',
    qs_step3: 'Einen Akkord auf der diatonischen Leiste anklicken (z.B. Dm7) \u2192 Akkordt\u00F6ne werden angezeigt',
    qs_step4: 'Pads anklicken, um T\u00F6ne zu h\u00F6ren. Layouts in den Voicing Boxes \u00E4ndern',
    qs_step5: 'Lieblingsakkorde mit <kbd>Option</kbd>+<kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> speichern (16 Slots)',
    qs_shortcuts: 'Tastenk\u00FCrzel',
    qs_shortcuts_desc: '<kbd>?</kbd> dr\u00FCcken f\u00FCr die vollst\u00E4ndige Tastenk\u00FCrzel-Liste.<br><kbd>Space</kbd> zum Akkord abspielen. <kbd>1</kbd>\u2013<kbd>7</kbd> f\u00FCr diatonische Akkorde, <kbd>\u2191</kbd><kbd>\u2193</kbd> f\u00FCr Inversions, <kbd>\u2190</kbd><kbd>\u2192</kbd> f\u00FCr chromatische Bewegung.<br>Im Perform Mode <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> als 4\u00D74-Raster verwenden.',
    footer_open: '64 Pad Explorer \u00F6ffnen',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'Mehr erfahren im Blog \u2192',
    header_icons: 'Header-Symbole',
    header_icons_desc: 'Drei Symbolschaltflächen in der oberen rechten Ecke.',
    icon_save: '<strong>\uD83D\uDCBE Speichern</strong> \u2014 Speichert aktuelle Einstellungen (Sound, Effekte, Anzeigeoptionen usw.) im Browser. Automatische Wiederherstellung beim nächsten Besuch',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 11 interaktive Tutorials durchstöbern. Jede Funktion Schritt für Schritt lernen',
    icon_help: '<strong>? Hilfe</strong> \u2014 Zeigt Tastenkürzel, Versionshistorie und Modusbeschreibungen. Öffnet auch mit <kbd>?</kbd>-Taste',
    sound_panel: 'Sound-Panel',
    sound_panel_desc: 'Sound-Presets auswählen und Effekte anpassen. Klicke auf \u25B6 um das Panel zu erweitern.',
    sound_presets: 'Sound-Presets',
    sound_presets_desc: 'Die Rhodes Physical-Modeling-Engine (Clean DI) ist der Standard. Sofort spielbar ohne Sample-Downloads. Verwende den VOICING-Regler, um den Pickup-Klang anzupassen.',
    sound_effects: 'Effekte',
    sound_effects_desc: 'Ziehe jeden Regler, um die Werte anzupassen.',
    fx_drive: 'Analoge Sättigung. Warme Verzerrung',
    fx_locut: 'Tiefpassfilter. Entfernt matschige Bässe',
    fx_hicut: 'Hochpassfilter. Dämpft scharfe Höhen',
    fx_reverb: 'Hall. Fügt räumliche Tiefe hinzu',
    fx_phaser: 'Phaser. Wellenförmige Modulation',
    fx_flanger: 'Flanger. Jet-artige Modulation',
    fx_tremolo: 'Tremolo. Periodische Lautstärkemodulation',
    sound_autofilter: 'Auto-Filter (Auto-Wah)',
    sound_autofilter_desc: 'Hüllkurvenfilter. Stelle FREQ, RESO, SENS und DECAY ein.',
    version_history: 'Versionshistorie',
    vh_540: '<b>V5.4</b> \u2014 Physikalisches Modeling aktualisiert. Filter-Parameter (WET / VOL) und ein HPS-exklusives Preset (Pad Sensei MK1 AMP Vintage Envelope Filter) erg\u00E4nzt',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Preamp-Modeling verbessert',
    vh_510: '<b>V5.1</b> \u2014 C-Dur-Festtonleiter-Modus hinzugef\u00FCgt',
    vh_500: '<b>V5.0</b> \u2014 Eigenst\u00E4ndige Sound-Engine + Effekte. Spring Reverb (physikalische Modellierung) + Plate Reverb. Suitcase-Verst\u00E4rkermodell verbessert. Reverb-Typ-Auswahl (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Sofort spielbereit beim \u00D6ffnen (kein Sample-Download). Tastenkombinations-Hinweise umschalten. NM/HM/MM diatonische Akkorde f\u00FCr parallele Moll-Tonarten. PU LEVEL und MECHANICAL zum E.PIANO MIXER hinzugef\u00FCgt. Verbesserungen der Akkorderkennung-Anzeige',
    vh_490: '<b>V4.9</b> \u2014 Pad Sensei MK1 Physical-Modeling-Sound-Engine',
    vh_497: '<b>V4.9.7</b> \u2014 Tremolo ist jetzt physikalisch modelliert. HPS-Mitglieder erhalten Pad Sensei MK1 Suitcase (physikalisch modellierte Amp-Kette)',
    vh_3377: '<b>V3.37.7</b> \u2014 Benutzer-Review: Relative Moll-Tonart-Fix, Title Case Badges, serifenlose Pad-Schrift, farbenblindfreundliche Umschalter (grün\u2192blau), Sound-Panel standardmäßig geöffnet, Layout-Shift-Fix, Tutorial-Spotlight-Overlay, Launchpad Oktav-Unterstützung + Auto-Oktav-Tracking für alle MIDI-Controller',
    vh_340: '<b>V3.40</b> \u2014 3-Bereiche-Layout-Umschaltung, TASTY/STOCK Transposition (\u2190\u2192), Z/X Voicing-Navigation, Cmd+Option Anzeige-Umschalter (Ableton-Stil), Abschnitts-Einklappen, Mobile UX-Verbesserungen, Info-Leiste (Hover-Beschreibungen), vollständige Tastenkürzel-Referenz aktualisiert',
    vh_336: '<b>V3.36</b> \u2014 Gitarren-Voicing-Engine v2: Genre-Presets (Jazz/Bossa/Funk), Referenztabelle (120 Typen \u00D7 12 Tonarten), automatische Fingerzuordnung mit Barr\u00E9-Erkennung',
    vh_335: '<b>V3.35</b> \u2014 Tutorial-UX-Verbesserungen (Anf\u00E4nger-Review). Alle Tooltips in 9 Sprachen \u00FCbersetzt. Anleitung: Abschnitte f\u00FCr Sound-Panel und Header-Icons hinzugef\u00FCgt',
    vh_333: '<b>V3.33</b> \u2014 Interaktive Tutorials. 11 Themen \u00D7 9 Sprachen. Kontexthinweise bei erster Funktionsinteraktion',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 Klavier-Voicings mit MIDI-spezifischer Tastaturanzeige. Anleitung um HPS-Voicing-Funktionen erg\u00E4nzt',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 raffinierte Voicings sortiert nach h\u00F6chster Note. Grad-Array-Anzeige + automatische Oktavoptimierung. Nur f\u00FCr HPS-Mitglieder',
    vh_325: '<b>V3.25.0</b> \u2014 Gitarren-Voicing \u2192 Pad-Spiegelung (<kbd>V</kbd>-Taste). Umschalten Gitarren-Stil (1 Note pro Reihe) / Kompakt-Layout. Gitarrenposition "Alle" Filter zuerst',
    vh_324: '<b>V3.24</b> \u2014 Clavinet-Presets hinzugef\u00FCgt (2 in E.PIANO). Auto Filter (H\u00FCllkurvenfilter / Auto-Wah) Effekt hinzugef\u00FCgt',
    vh_323: '<b>V3.23</b> \u2014 Text-Akkordeingabe mit Autovervollst\u00E4ndigung. "/" zum Fokussieren, Abk\u00FCrzungen (dim, h=m7\u266D5), Sortierung nach Tensions',
    vh_322: '<b>V3.22</b> \u2014 Quintenzirkel-Anzeige. Synchronisiert mit der Tonartwahl, zeigt diatonische Akkorde und harmonische Funktion, Moll-Skalenmodus-Umschaltung',
    vh_321: '<b>V3.21</b> \u2014 Diatonischer Dreiklang/Vierklang-Umschalter. Gitarren-/Bass-Positionen nach Grundton-Saite gruppiert',
    vh_37: '<b>V3.7</b> \u2014 Voicing-Position beibehalten (Fingersatz-Form bei chromatischer Bewegung automatisch beibehalten). Pad-Raster, Notenzeile und Akkorderkennung w\u00E4hrend der Wiedergabe. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 MIDI-Datei-Wiedergabe \u2192 Pad-Beleuchtung (Timeline-Wiedergabe, Akkordname-Anzeige, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 E.PIANO-Sampler (Rhodes Mark I). 7 EP-Presets. Sound AN/AUS-Schalter. iPad-Unterst\u00FCtzung',
    vh_31: '<b>V3.1</b> \u2014 Anschlagdynamik (4 Parameter + Kurvenvisualisierung). Push 3 Oktavtasten-Unterst\u00FCtzung. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 Mehrere Speicherb\u00E4nke (16 Slots \u00D7 bis zu 16 B\u00E4nke, Wechseln/Duplizieren/Umbenennen)',
    vh_218: '<b>V2.18</b> \u2014 Alle Einstellungen automatisch speichern/wiederherstellen (Tonart/Skala/Sound/MIDI/Speicher)',
    vh_213: '<b>V2.13</b> \u2014 Instrument-Skalen\u00FCberlagerung (Gitarre/Bass/Piano zeigen Available Scale). Pad-Stufenbezeichnungen. Oktavgekoppelte Wiedergabe',
    vh_27: '<b>V2.7</b> \u2014 Tension-Erg\u00E4nzungsmodus (Pad/Gitarre/Bass/Keyboard-Akkordaufbau \u2192 Available Scale-Filterung)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, Skalen-Overlay auf Pads)',
    vh_19: '<b>V1.9</b> \u2014 9 Sprachen',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 Speicherslots, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Plain Mode, MIDI/CHS-Export',
    vh_10: '<b>V1.0</b> \u2014 Erstver\u00F6ffentlichung (Skala/Akkord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6.S R',
    root_5: '5.S R',
    root_4: '4.S R',
    root_3: '3.S R',
    root_2: '2.S R',
    open: 'Offen',
    no_open: 'Ohne offen',
    all: 'Alle',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'Auf Pad',
    genre_default: 'Standard',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    'Drücke C um den aktuellen Akkord im Memory zu speichern',
    'Opt+1~V speichert direkt in einen Slot (16 Tasten: 1234 QWER ASDF ZXCV)',
    'Shift+Klick auf einen Memory-Slot zum Löschen',
    'Opt+Ziehen zum Kopieren eines Slots',
    'Drücke S für Shell Voicings (1-3-7 / 1-7-3)',
    'Shift+D wechselt Drop 2 / Drop 3',
    '⌘⌥G zeigt das Gitarrengriffbrett',
    '⌘⌥F zeigt den Quintenzirkel',
    'Tab wechselt zwischen Scale / Chord / Input',
    'Leertaste spielt die aktuelle Tonleiter oder den Akkord',
    'Exportiere alle Memory-Slots als MIDI-Datei',
    'Verbinde einen MIDI-Controller zum Spielen',
    'Pfeiltasten ↓↑ ändern die Akkordumkehrung',
    'Drücke R für Rootless Voicing',
    'Drücke O um die Quinte wegzulassen',
    '⌘⌥S zeigt die Notenzeile',
    'Das Speicher-Symbol bewahrt alle Einstellungen',
    '[ ] wechselt Memory-Bänke — verwalte mehrere Songs',
    'Perform-Modus: Akkorde mit Tastatur (1234 / QWER / ASDF / ZXCV) oder MIDI-Pads auslösen',
    'Drücke / im Chord-Modus um Akkordnamen einzugeben (z.B. Cm7, G7(b9,#11))',
  ],
  tips_off: 'Tipps ausblenden',
  whats_new: 'Neuheiten',
  whats_new_497: 'Tremolo ist jetzt physikalisch modelliert! HPS-Mitglieder erhalten Pad Sensei MK1 Suitcase.',
  whats_new_61: 'Das Online-Handbuch ist jetzt über den Guide zugänglich. Derzeit in Arbeit.',
  whats_new_123: 'Das Online-Handbuch ist jetzt über den Guide zugänglich. Derzeit in Arbeit.',
  whats_new_51: 'C-Dur-Sperrmodus hinzugefügt! Im Hilfe-Menü (?) umschaltbar. Push/Launchpad zeigt dann immer C-Dur.',
  whats_new_50: 'Spring- und Plate-Reverb hinzugef\u00FCgt! Baxandall Bass/Treble EQ, Suitcase-Amp verbessert.',
  whats_new_32427: 'Gitarren-Voicing \u2192 Pad-Spiegelung (V-Taste). Umschalten Gitarren-Stil / Kompakt-Layout',
  whats_new_33000: 'Tutorial-System! Klicke auf das Buch-Symbol in der Kopfzeile, um Scale-Modus, Chord-Modus und mehr zu lernen.',
  whats_new_640: 'V6.4.0 ist live: Erkennung von drei Tensions, UST-Analyse, Note/Degree-Anzeige und tonartbewusste # / b-Schreibweise.',
  whats_new_650: 'V6.5.0 ist live: HPS TASTY / STOCK / Guitar-Voicings sind jetzt im Chord Builder gebündelt. Die Sext-Familie verwendet C6(9) / C6(9,#11); Gitarrenfilter, Anzeige-Balance und Wiedergabebereich wurden verbessert.',
  whats_new_660: 'V6.6.0 ist live: HPS-Mitglieder erhalten Quarten-Voicings (So What) in TASTY — der Sound von Miles Davis / McCoy Tyner — für Moll-, Dur- und Dominantakkorde. Die Reihenfolge der Akkordtypen im Chord Builder wurde ebenfalls überarbeitet.',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Sound-Preset',
    sound_msg: 'W\u00E4hle ein Sound-Preset und tippe auf ein Pad zum Anh\u00F6ren.\nORGAN und E.PIANO \u2014 jedes hat mehrere Presets.',
    sound_done: 'Klingt gut! Dr\u00FCcke Weiter um fortzufahren.',
    midi_title: 'MIDI-Controller',
    midi_msg: 'Ein MIDI-Controller wurde erkannt. W\u00E4hle dein Ger\u00E4t aus dem Dropdown.\nDie Anschlagdynamik kann im Sound-Panel angepasst werden.',
    midi_no_device: 'Kein MIDI-Controller erkannt \u2014 kein Problem.\nDu kannst Pad-Klicks, Gitarren-/Bass-/Klaviereingabe oder Text-Akkordeingabe nutzen.',
    input_title: 'Drei Modi',
    input_msg: 'Scale \u2014 Skalent\u00F6ne auf dem 64-Pad-Raster anzeigen\nChord \u2014 Akkorde mit Voicings, Umkehrungen und Tensions bauen\nInput \u2014 Pads frei antippen um Akkordnamen zu erkennen\n\nWechsle mit Tab oder den Modus-Buttons oben.',
    instruments_title: 'Instrument-Eingabe',
    instruments_msg: 'Gitarre, Bass, Klavier \u2014 Anzeige jeweils umschalten und klicken um Noten direkt einzugeben.\nGriffbrett-Klick \u2192 Akkorderkennung \u2192 "Auf Pad" (V) um in Pad-Layout umzuwandeln.\nTexteingabe: / im Chord-Modus dr\u00FCcken um Akkordnamen einzugeben (z.B. Cm7, G7(b9,#11)).',
    done_title: 'Bereit!',
    done_msg: 'Alles eingerichtet. Erkunde frei \u2014 dr\u00FCcke ? f\u00FCr die vollst\u00E4ndige Tastenk\u00FCrzel-Liste.\nDie Anleitung enth\u00E4lt Screenshots, Videos und Anwendungsf\u00E4lle.',
    next: 'Weiter',
    skip_step: 'Weiter',
    skip_all: 'Tutorial \u00FCberspringen',
    open_guide: 'Anleitung \u00F6ffnen',
    close: 'Starten',
    reset: 'Tutorial neu starten',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    btn_label: 'Tutorials',
    // Selector UI
    selector_title: 'Tutorials',
    cat_getting_started: 'Erste Schritte',
    cat_features: 'Funktionen',
    cat_advanced: 'Fortgeschritten',
    steps_label: 'Schritte',
    reset_all: 'Gesamten Fortschritt zur\u00FCcksetzen',
    close_selector: 'Schlie\u00DFen',
    hint_available: 'Tutorial verfügbar',
    hint_try: 'Ausprobieren',
    // Shared action labels
    next: 'Weiter',
    skip_step: 'Weiter',
    skip_all: 'Tutorial \u00FCberspringen',
    open_guide: 'Anleitung \u00F6ffnen',
    close: 'Fertig',
    // Onboarding
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: 'Zum ersten Mal hier? M\u00F6chtest du eine kurze Tour durch die App?',
    onboarding_yes: 'Weiter',
    onboarding_no: '\u00DCberspringen',
    onboarding_title: 'Erste Schritte',
    onboarding_desc: 'Lerne die Grundlagen von 64 Pad Explorer',
    onboarding: {
      sound_title: 'Sound-Preset',
      sound_msg: 'W\u00E4hle ein Sound-Preset und tippe auf ein Pad zum Anh\u00F6ren.\nORGAN und E.PIANO \u2014 jedes hat mehrere Presets.',
      sound_done: 'Klingt gut! Dr\u00FCcke Weiter um fortzufahren.',
      midi_title: 'MIDI-Controller',
      midi_msg: 'Ein MIDI-Controller wurde erkannt. Push 3 und Launchpad funktionieren sofort — keine Einrichtung nötig.\nDie Anschlagdynamik kann im Sound-Panel angepasst werden.',
      midi_no_device: 'Kein MIDI-Controller erkannt \u2014 kein Problem.\nDu kannst Pad-Klicks, Gitarren-/Bass-/Klaviereingabe oder Text-Akkordeingabe nutzen.',
      input_title: 'Drei Modi',
      input_msg: 'Scale \u2014 Skalent\u00F6ne auf dem 64-Pad-Raster anzeigen\nChord \u2014 Akkorde mit Voicings, Umkehrungen und Tensions bauen\nInput \u2014 Pads frei antippen um Akkordnamen zu erkennen\n\nWechsle mit Tab oder den Modus-Buttons oben.',
      instruments_title: 'Instrument-Eingabe',
      instruments_msg: 'Gitarre, Bass, Klavier \u2014 Anzeige jeweils umschalten und klicken um Noten direkt einzugeben.\nGriffbrett-Klick \u2192 Akkorderkennung \u2192 "Auf Pad" (V) um in Pad-Layout umzuwandeln.\nTexteingabe: / im Chord-Modus dr\u00FCcken um Akkordnamen einzugeben (z.B. Cm7, G7(b9,#11)).',
      done_title: 'Bereit!',
      done_msg: 'Alles eingerichtet. Erkunde frei \u2014 dr\u00FCcke ? f\u00FCr die vollst\u00E4ndige Tastenk\u00FCrzel-Liste.\nDie Anleitung enth\u00E4lt Screenshots, Videos und Anwendungsf\u00E4lle.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Scale-Modus',
    scale_mode_desc: 'Erkunde Skalen auf dem 64-Pad-Raster',
    scale_mode: {
      step1_title: 'In den Scale-Modus wechseln',
      step1_msg: 'Der Scale-Modus zeigt Skalent\u00F6ne leuchtend auf dem Pad-Raster.\nTippe auf einen leuchtenden Pad um den Ton zu h\u00F6ren.',
      step2_title: 'Tonart w\u00E4hlen',
      step2_msg: 'W\u00E4hle eine Grundtonart. Das Pad-Raster aktualisiert sich sofort.\nVersuche zwischen C, G, F zu wechseln \u2014 h\u00F6re, wie sich das Farbmuster \u00E4ndert.',
      step3_title: 'Skala w\u00E4hlen',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 Skalen verf\u00FCgbar. Die Pads aktualisieren sich in Echtzeit.',
      step4_title: 'Diatonische Leiste',
      step4_msg: 'Die diatonischen Akkorde deiner Skala erscheinen hier.\nKlicke auf einen Akkord um in den Chord-Modus mit diesem Voicing zu wechseln.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Chord-Modus',
    chord_mode_desc: 'Baue Akkorde Schritt f\u00FCr Schritt',
    chord_mode: {
      step1_title: 'In den Chord-Modus wechseln',
      step1_msg: 'Der Chord-Modus bietet zwei Wege zur Akkordauswahl.\n\u2460 Aus der diatonischen Leiste mit einem Klick wählen\n\u2461 Eigenen bauen: Root \u2192 Quality \u2192 Tension',
      step_key_title: 'Tonart-Auswahl',
      step_key_msg: 'Die Skalentonart festlegen. Wenn eine Tonart gesetzt ist, zeigt die diatonische Leiste Akkorde und die Tension-Verfügbarkeit wird gefiltert.\nDu kannst auch frei von Root aus Akkorde bauen, ohne eine Tonart zu verwenden.',
      step_diatonic_title: 'Diatonische Leiste',
      step_diatonic_msg: 'Diatonische Akkorde für die gewählte Tonart.\nKlicken, um sofort einen Akkord mit skalen-bewusster Tension-Filterung zu setzen.',
      step2_title: 'Schritt 1: Root',
      step2_msg: 'W\u00E4hle einen Grundton. C, D, E... alle 12 T\u00F6ne.\nDie Anzeige zeigt deinen aktuellen Akkord.',
      step3_title: 'Schritt 2: Quality',
      step3_msg: 'W\u00E4hle den Akkordtyp: Maj, min, 7, m7, dim, aug...\nDas Pad-Raster leuchtet die Akkordt\u00F6ne auf.',
      step4_title: 'Schritt 3: Tensions',
      step4_msg: 'W\u00E4hle zuerst eine Quality \u2014 Tension-Buttons erscheinen automatisch.\n9, b9, #9, 11, #11, 13, b13. Mehrere Tensions k\u00F6nnen gew\u00E4hlt werden.',
      step5_title: 'Texteingabe',
      step5_msg: 'Gib Akkordnamen direkt mit der Taste / ein.\nSlash-Akkorde und komplexe Voicings k\u00F6nnen schnell eingegeben werden.',
      step6_title: 'Sekundärdominant-Tonleitern finden',
      step6_msg: 'Gib einen nicht-diatonischen Akkord direkt ein.\nBeispiel: Input G7 \u2192 Available Scale zeigt "Mixolydian", "Mixolydian b13" usw.\nWechsle zu Practical sort für die nützlichsten Tonleitern zuerst.\nSo findest du die richtige Tonleiter für Sekundärdominanten.',
      step7_title: 'Slash Chords',
      step7_msg: 'Klicke auf / im Akkord-Builder um eine Bassnote für Slash Chords einzugeben.\nDu kannst auch C/D oder F\u25B37/G in der Texteingabe eingeben.\nAvailable Scale aktualisiert sich entsprechend dem Slash Chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Input-Modus',
    input_mode_desc: 'Akkorde über MIDI-Controller, Pads, Griffbrett oder Tastatur eingeben',
    input_mode: {
      step1_title: 'In den Input-Modus wechseln',
      step1_msg: 'Gib Akkorde über MIDI-Controller, Pad-Klick, Griffbrett oder Tastatur ein.\nDie Akkorderkennung funktioniert in allen Modi.',
      step2_title: 'Tippe auf einige Pads',
      step2_msg: 'Klicke auf beliebige Pads im Raster.\nJeder Klick schaltet eine Note ein oder aus.',
      step3_title: 'Akkorderkennung',
      step3_msg: 'Der erkannte Akkordname erscheint \u00FCber dem Raster.\nStufenbezeichnungen (R, 3, 5, b7...) werden auf jedem Pad angezeigt.',
      step4_title: 'Mit Capture speichern',
      step4_msg: 'Die Taste <strong>C</strong> speichert den aktuellen Akkord im n\u00E4chsten Memory-Slot.\nBaue Akkordprogressionen Schritt f\u00FCr Schritt auf.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Diatonische Leiste',
    diatonic_desc: 'Ein-Klick-Zugriff auf diatonische Akkorde',
    diatonic: {
      step1_title: 'Die diatonische Leiste',
      step1_msg: 'Jede Skala hat ihr eigenes Set diatonischer Akkorde.\nSie erscheinen hier \u2014 spielbereit.',
      step2_title: 'Dreiklang / Vierklang',
      step2_msg: 'Wechsle zwischen 3-Ton-Dreikl\u00E4ngen und 4-Ton-Septakkorden.\nDie Leiste aktualisiert sich sofort.',
      step3_title: 'Klicke auf einen Akkord',
      step3_msg: 'Klicke auf einen Akkord in der Leiste.\nDu kannst ihn mit Tensions und mehr im Chord Builder transformieren.',
      step4_title: '3 Moll-Skalen vergleichen (Harm/Mel)',
      step4_msg: 'Mit einer Moll-Tonart ausgewählt, aktiviere "Harm/Mel" (\u2318\u2325N).\nHarmonisch und melodisch Moll-Diatonik erscheinen darunter.\nVergleiche mit natürlich Moll \u2014 beachte, wie sich der V-Akkord von m7 zu 7 ändert.',
      step5_title: 'Sekundärdominante',
      step5_msg: 'Aktiviere "Secondary Dominant" (\u2318\u2325D).\nV7-Akkorde, die zu jedem diatonischen Akkord auflösen, werden angezeigt.\nKlicke auf einen und Available Scale erscheint automatisch.\nDur-Auflösung \u2192 Mixolydisch. Moll-Auflösung \u2192 HMP5\u2193/Altered.',
      step6_title: 'Tastenkürzel',
      step6_msg: 'Drücke 1\u20137 für diatonische Akkorde.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Parallel Key) für Erweiterungsleisten.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Akkorde speichern und live spielen',
    memory: {
      step1_title: 'Akkord speichern',
      step1_msg: 'Speichere deine Lieblingsakkorde.\nVoicings speichern, die dir gefallen, hilft beim Beat-Making und \u00DCben.',
      step2_title: '16 Speicherslots',
      step2_msg: 'Funktioniert wie ein 16-Pad-Drumrack-Layout auf PUSH, Launchpad, MPC und Maschine \u2014 intuitiv zu bedienen.',
      step3_title: 'Speicherb\u00E4nke',
      step3_msg: 'Auf PUSH und Launchpad macht das Drumrack-Layout die Bedienung intuitiv.',
      step4_title: 'Perform-Modus',
      step4_msg: 'Auch die PC-Tastatur-Tasten entsprechen den 16 Pads.',
      step5_title: 'MIDI-Export',
      step5_msg: 'Exportiere alle Speicher-Akkorde als MIDI-Datei.\nZiehe sie in deine DAW und beginne zu produzieren.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Gestalte deine Akkord-Voicings',
    voicing: {
      step1_title: 'Voicing-Steuerung',
      step1_msg: 'Im Chord Builder-Modus sind verschiedene Transformationen aus der Grundform m\u00F6glich.\nOmit, Shell, Inversion, Drop \u2014 alles hier.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> steht f\u00FCr Shell Voicing. Lerne R37- und R73-Voicings fl\u00FCssig auf dem Pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Tastenk\u00FCrzel sind oft als Merkw\u00F6rter gesetzt.\n<strong>O</strong>mit = Quinte weglassen. <strong>R</strong>ootless = Voicing ohne Grundton.',
      step4_title: 'Umkehrungen',
      step4_msg: 'Anders als bei den meisten Programmen k\u00F6nnen Umkehrungen ultraschnell erstellt werden.\nHilft auch beim Verstehen von Slash-Akkorden.',
      step5_title: 'Drop Voicing',
      step5_msg: 'F\u00FCr den Fall, dass du die obere Stimme hervorheben willst \u2014\nDrop Voicings werden ebenfalls unterst\u00FCtzt.',
      step6_title: 'Voicing Box',
      step6_msg: 'Pads k\u00F6nnen mehrere Positionsoptionen haben. Die Voicing Box verwaltet das.\nKlicke a, b, c, d usw. auf dem Pad, oder tippe den Buchstaben, um verschiedene Voicing-M\u00F6glichkeiten zu sehen.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, Effekte und Lautst\u00E4rke',
    sound: {
      step1_title: 'Sound-Presets',
      step1_msg: 'ORGAN (4 Typen) und E.PIANO (8 Typen).\nKlicke auf ein Pad oder nutze deinen MIDI-Controller.',
      step2_title: 'Detail-Panel',
      step2_msg: 'Klicke auf \u25BC um das Sound-Detail-Panel aufzuklappen.\nEffekte, Lautst\u00E4rke und Filterregler sind hier.',
      step3_title: 'Effekte',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nStelle sie im Detail-Panel ein.',
      step4_title: 'Sound AN/AUS',
      step4_msg: 'Sound AN/AUS mit dem Lautsprecher-Symbol umschalten.\nAusschalten kann praktisch sein, wenn du eine DAW verwendest.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote-Voicings nach Topnote sortiert. Nur f\u00FCr HPS-Mitglieder',
    tasty: {
      step1_title: 'TASTY aktivieren',
      step1_msg: 'W\u00E4hle stilvolle Voicings aus, die einfache Logik allein nicht erzeugen kann.\nVom Topnote aus zu denken ist n\u00FCtzlich f\u00FCr Streicher- und Bl\u00E4ser-Arrangements.\n(Nur f\u00FCr HPS-Mitglieder)',
      step2_title: 'Rezepte durchbl\u00E4ttern',
      step2_msg: 'Tasten Z / X um Voicings vorwärts/rückwärts zu durchsuchen.\nDer Zähler zeigt deine Position.',
      step3_title: 'Stufen-Notation',
      step3_msg: 'Der Info-Bereich zeigt die Stufen-Stapelung \u2014 z.B. m9 (b3-b7-9-5-1).\nDas ist die Voicing-Struktur von unten nach oben.',
      step4_title: 'Auf Pad',
      step4_msg: 'Pad-Optimierung, die herk\u00F6mmliche Software nicht bietet.\nGenie\u00DFe es, stilvolle Voicings auch auf Pads zu spielen.',
      fb_step1_title: 'Was ist TASTY Voicing?',
      fb_step1_msg: '129 ausgefeilte Voicings nach Topnote sortiert.\nUnterstützt Maj7 / Dom7 / Min7. In Stufen-Notation angezeigt.\nNur für HPS-Mitglieder.',
      fb_step2_title: 'Wie auf TASTY zugreifen',
      fb_step2_msg: 'Verfügbar nach Beitritt zu HPS (Hardcore Pad Style).\nDrücke T im Chord-Modus zum Aktivieren. Tasten Z/X um Voicings zu durchsuchen.\nSiehe Anleitung für Details.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Klassische Klavier-Voicing-Idiome. Nur f\u00FCr HPS-Mitglieder',
    stock: {
      step1_title: 'STOCK aktivieren',
      step1_msg: 'Klavier-spezifische Voicings kennen hilft dir, \u00FCber das reine Grundform-Spiel hinauszukommen.\n154 Klavier-Voicings in Stufen-Notation.\n(Nur f\u00FCr HPS-Mitglieder)',
      step2_title: 'Voicings durchbl\u00E4ttern',
      step2_msg: 'Tasten Z / X um Voicings vorwärts/rückwärts zu durchsuchen.',
      step3_title: 'Tastatur-Ansicht',
      step3_msg: 'Aktiviere die Piano-Anzeige um die tats\u00E4chlichen Tastenpositionen zu sehen.\nDas Voicing wird auf der Tastatur lebendig.',
      step4_title: 'Auf Pad',
      step4_msg: 'Klicke auf "Auf Pad" um das Voicing auf das Pad-Layout zu \u00FCbertragen.\nSpeichere es und exportiere es in deine DAW.',
      fb_step1_title: 'Was ist STOCK Voicing?',
      fb_step1_msg: 'Zeigt häufig verwendete Klavier-Voicings.\nDie Stufen-Notation zeigt dir die Struktur.\nNur für HPS-Mitglieder.',
      fb_step2_title: 'Wie auf STOCK zugreifen',
      fb_step2_msg: 'Verfügbar nach Beitritt zu HPS (Hardcore Pad Style).\nDrücke K im Chord-Modus zum Aktivieren.\nSiehe Anleitung für Details.',
    },
    // Link Mode tutorial
    link_title: 'Link Mode',
    link_desc: 'Gespielte Noten über alle Instrumente synchronisieren',
    link: {
      step1_title: 'Link-Button',
      step1_msg: 'Der Link-Button befindet sich neben Guitar / Bass / Piano.\nAktivieren, um gespielte Noten auf allen Instrumenten in Echtzeit zu sehen.',
      step2_title: 'Link Mode AN',
      step2_msg: 'Wenn Link aktiv ist, werden die Instrumentenanzeigen gedimmt.\nSpiele Pads oder MIDI \u2014 nur die gespielten Noten leuchten auf.',
      step3_title: 'Pads spielen',
      step3_msg: 'Drücke ein Pad und beobachte, wie dieselbe Note auf Gitarre, Bass und Klavier aufleuchtet.\nSiehe, welche Positionen auf jedem Instrument denselben Ton erzeugen.\nLoslassen zum Löschen.',
      step4_title: 'Tastenkürzel',
      step4_msg: '\u2318\u2325+L schaltet den Link Mode AN/AUS.\nPerfekt um zu lernen, wie Noten über Instrumente hinweg zugeordnet sind.',
    },
    // Minor 3 Scales tutorial
    minor_scales_title: '3 Moll-Skalen vergleichen',
    minor_scales_desc: 'Natürlich, harmonisch und melodisch Moll nebeneinander',
    minor_scales: {
      step1_title: 'Moll-Tonart einstellen',
      step1_msg: 'Am (natürlich Moll) ist ausgewählt.\nDie diatonische Leiste zeigt natürlich Moll-Akkorde.',
      step2_title: 'Harm/Mel aktivieren',
      step2_msg: 'Klicke auf "Harm/Mel" (\u2318\u2325N).\nHarmonisch und melodisch Moll-Diatonik erscheinen darunter.',
      step3_title: 'Vergleichen',
      step3_msg: 'Schau dir die Unterschiede zu natürlich Moll (obere Leiste) an.\nBei HM ändert sich der V-Akkord von Em7 zu E7 \u2014 das ermöglicht Dominantbewegung.\nBei MM ändert sich auch der IV-Akkord von Dm7 zu D7.\nKlicke auf einen Akkord, um ihn auf den Pads zu sehen.',
      step4_title: 'Paralleltonart',
      step4_msg: 'Aktiviere "Parallel Key" (\u2318\u2325R), um die Dur-Diatonik für denselben Grundton zu sehen.\nDas zeigt die Herkunft von Borrowed Chords (modale Austausch).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Sekundärdominante',
    secdom_desc: 'Das Tor zur Modulation erleben',
    secdom: {
      step1_title: 'In C-Dur starten',
      step1_msg: 'C-Dur ist eingestellt.\nDie diatonische Leiste zeigt C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Sekundärdominante aktivieren',
      step2_msg: 'Klicke auf "Secondary Dominant" (\u2318\u2325D).\nV7-Akkorde, die zu jedem diatonischen Akkord auflösen, erscheinen.\nIn C-Dur: C7, D7, E7, A7, B7 (5 insgesamt).',
      step3_title: 'Auflösung nach Dur',
      step3_msg: 'Klicke auf C7 (\u2192F\u25B37) oder D7 (\u2192G7).\nAvailable Scale zeigt Mixolydisch als erste Wahl.\nWeil das Auflösungsziel ein Dur-Akkord ist.',
      step4_title: 'Auflösung nach Moll',
      step4_msg: 'Klicke auf A7 (\u2192Dm7) oder E7 (\u2192Am7).\nAvailable Scale zeigt HMP5\u2193 (Phrygisch Dominant) und Altered als erste Wahl.\nWeil das Auflösungsziel ein Moll-Akkord ist.',
      step5_title: 'Die Regel: Nur 2 Typen',
      step5_msg: 'Skalenwahl für Sekundärdominanten ist einfach:\n\u2022 Dur-Auflösung \u2192 Mixolydisch\n\u2022 Moll-Auflösung \u2192 HMP5\u2193 oder Altered\nDas ist alles, was du dir merken musst.',
    },
    // Circle of Fifths tutorial
    circle_title: 'Quintenzirkel',
    circle_desc: 'Tonart-Beziehungen auf einen Blick',
    circle: {
      step1_title: 'Den Zirkel \u00F6ffnen',
      step1_msg: 'Drücke \u2318\u2325F oder klicke auf den Quintenzirkel-Button.\nDer Quintenzirkel erscheint darunter.',
      step2_title: 'Tonart-Verkn\u00FCpfung',
      step2_msg: '\u00DCberpr\u00FCfe schnell Stellvertreterakkorde und diatonische Akkorde, die f\u00FCr Performance und Komposition wichtig sind.',
      step3_title: 'Diatonische Funktionen',
      step3_msg: 'Anders als beim typischen Quintenzirkel kannst du im 64 Pad Explorer 3 Moll-Arten (Natural/Harmonic/Melodic) w\u00E4hlen, wenn du eine Moll-Tonart w\u00E4hlst.\nDas erleichtert das Meistern der kniffligen Moll-Tonarten.',
      step4_title: 'Moll-Tonart auswählen',
      step4_msg: 'Der innere Ring des Zirkels zeigt Moll-Tonarten.\nKlicke auf eine Tonart im inneren Ring um eine Moll-Tonart zu wählen.\nDie diatonische Akkordanzeige ändert sich.',
      step5_title: '3 Moll-Tonleitertypen',
      step5_msg: 'Wenn eine Moll-Tonart ausgewählt ist, erscheinen Nat / Harm / Mel Buttons in der Mitte.\nNat = Natural Minor (Standardform)\nHarm = Harmonic Minor (V7 erscheint)\nMel = Melodic Minor (VI, VII Stufen ändern sich)',
      step6_title: 'Ausprobieren',
      step6_msg: 'Klicke auf Nat \u2192 Harm \u2192 Mel und beobachte die \u00C4nderungen in den diatonischen Akkorden.\nBeachte wie V7 in Harmonic Minor erscheint.',
    },
    // Guitar tutorial
    guitar_title: 'Gitarrendiagramm',
    guitar_desc: 'Akkorde von Gitarre eingeben und auf Pads \u00FCbertragen',
    guitar: {
      step1_title: 'Gitarrenhals anzeigen',
      step1_msg: 'Dr\u00FCcke \u2318\u2325G oder klicke auf den Guitar-Button.\nAkkordtöne erscheinen auf dem Griffbrett.',
      step2_title: 'Akkordpositionen ansehen',
      step2_msg: 'W\u00E4hle einen Akkord im Chord-Modus und das Griffbrett zeigt automatisch passende Positionen.\nBenutze Komma (,) und Punkt (.) zum Durchbl\u00E4ttern der Positionen.',
      step3_title: 'Von Gitarre eingeben',
      step3_msg: 'In den Input-Modus gewechselt. Versuche Bünde auf dem Griffbrett anzuklicken um Noten einzugeben.\nAkkordnamen werden in Echtzeit erkannt.',
      step4_title: 'Auf Pad \u00FCbertragen',
      step4_msg: '"Auf Pad \u00FCbertragen" mappt das Gitarren-Voicing auf das Pad-Raster.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Tastaturk\u00FCrzel',
    shortcuts_desc: 'Wesentliche Tasten f\u00FCr effizientes Arbeiten',
    shortcuts: {
      step1_title: 'Moduswechsel',
      step1_msg: 'Tab \u2014 Modus wechseln (Scale \u2192 Chord \u2192 Input)\nShift+Tab \u2014 Umgekehrte Richtung\n\nSchnell zwischen Modi wechseln.',
      step2_title: 'Diatonik & Navigation',
      step2_msg: '1\u20137 \u2014 Diatonischen Akkord w\u00E4hlen\n\u2191\u2193 \u2014 Umkehrungen durchbl\u00E4ttern\n\u2190\u2192 \u2014 Grundton um Halbton transponieren (h\u00E4lt Akkordform)\n\nAkkorde ohne Maus bedienen.',
      step3_title: 'Voicing-Operationen',
      step3_msg: 'S \u2014 Shell-Zyklus (aus \u2192 1-3-7 \u2192 1-7-3)\nO \u2014 Omit 5 umschalten\nR \u2014 Rootless umschalten\nShift+D \u2014 Drop-Zyklus (aus \u2192 Drop2 \u2192 Drop3)\nT \u2014 TASTY EIN/AUS, K \u2014 STOCK EIN/AUS\nZ / X \u2014 TASTY/STOCK Voicing vor/zur\u00FCck\n\u2190\u2192 \u2014 Voicing um Halbton transponieren (w\u00E4hrend TASTY/STOCK)\nV \u2014 Auf Pad \u00FCbertragen / Layout umschalten\n/ \u2014 Akkord-Texteingabe',
      step4_title: 'Speicher & B\u00E4nke',
      step4_msg: 'Option+1234/qwer/asdf/zxcv \u2014 In Slot speichern\n[ ] \u2014 B\u00E4nke wechseln\nM \u2014 Speicheransicht umschalten\nP \u2014 Perform-Modus umschalten\nSpace \u2014 Spielen\nShift+Space \u2014 Alles spielen (sequenziell)',
      step5_title: 'Mehr',
      step5_msg: '? \u2014 Hilfe (vollst\u00E4ndige Tastaturk\u00FCrzel-Liste)\n\u2318\u2325+G/B/P/F/S \u2014 Instrument/Zirkel/Notenblatt umschalten\n\u2318\u2325+A/M/T/Q/V/K/H \u2014 Abschnitte umschalten\nCmd/Ctrl+Z \u2014 R\u00FCckg\u00E4ngig (bis zu 30 Mal)\nEsc \u2014 Abw\u00E4hlen / Modale schlie\u00DFen',
    },
    // Settings tutorial
    settings_title: 'Anzeige & Einstellungen',
    settings_desc: 'Passe deinen Arbeitsbereich an',
    settings: {
      step1_title: 'Instrument-Panels',
      step1_msg: 'Die Gitarren-Anzeige zeigt g\u00E4ngige Voicings, wenn du einen Akkord im Chord Builder w\u00E4hlst.\nIm Input-Modus kannst du auch \u00FCber Gitarre, Bass und Keyboard eingeben.',
      step2_title: 'Notennamen / Stufen',
      step2_msg: 'Wechsle zwischen Notennamen (C, D, E) und Stufen (R, 2, 3).\nGilt f\u00FCr Pads und Gitarrenanzeige.',
      step3_title: 'Oktav-Verschiebung',
      step3_msg: 'Verwende \u25B2\u25BC um den Pad-Bereich um eine Oktave zu verschieben.\nPush 3 und Launchpad Oktav-Tasten synchronisieren sich automatisch.',
      step4_title: 'Abschnitte ein-/ausblenden',
      step4_msg: '\u2318\u2325+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) um Abschnitte einzuklappen.\nZeige nur was du brauchst.',
      step5_title: 'Layout-Reihenfolge',
      step5_msg: 'In ? Hilfe, nutze das "Layout"-Dropdown um die 3 Panels neu anzuordnen.\n6 Presets: Chord, Pad, Circle in beliebiger Reihenfolge.\nAuf Mobilgeräten ändert sich auch die Wischreihenfolge.',
      step6_title: 'Alles speichern',
      step6_msg: 'Klicke auf das Speicher-Symbol um alle Einstellungen zu bewahren.\nTonart, Skala, Sound, Speicher, Voicing \u2014 alles bleibt erhalten.',
    },
  },
});
