// Español
I18N.addLang('es', {
  help: {
    title: '64 Pad Explorer',
    description: 'Herramienta para explorar escalas, acordes y voicings en una cuadrícula de 64 pads.',
    manual_link: 'Manual →',
    update_history_link: 'Update History',
    download_desktop_link: 'Desktop Download',
    scale_mode: 'Scale Mode',
    scale_key: '<strong>Key</strong> \u2014 Elige entre 12 tonalidades',
    scale_scale: '<strong>Scale</strong> \u2014 Diatónica, Menor Armónica, Menor Melódica, Pentatónica, Bebop y más \u2014 31 tipos',
    scale_diatonic: '<strong>Diatonic Bar</strong> \u2014 Muestra los acordes diatónicos de la escala seleccionada. Haz clic para entrar en Chord Mode',
    chord_mode: 'Chord Mode (3 pasos)',
    chord_step1: '<strong>Step 1: Root</strong> \u2014 Selecciona la nota raíz en el teclado de piano',
    chord_step2: '<strong>Step 2: Quality</strong> \u2014 Elige el tipo de acorde (Maj, m, aug, dim, sus, etc.)',
    chord_step3: '<strong>Step 3: Tension</strong> \u2014 Añade tensiones (9, b9, #9, 11, #11, 13, b13, etc.). Selección múltiple OK',
    chord_text: '<strong>Entrada de texto</strong> \u2014 Pulsa "/" para enfocar. Escribe Cm7, G7(b9,#11), Am7/G etc. directamente. Aparecen sugerencias',
    chord_onchord: '<strong>On Chord</strong> \u2014 Usa el botón "/" para acordes con bajo alterno (acorde sobre nota de bajo)',
    voicing: 'Voicing',
    voicing_omit: '<strong>Omit 5 / Rootless / Omit 3</strong> \u2014 Omitir notas',
    voicing_shell: '<strong>Shell 1-3-7 / 1-7-3</strong> \u2014 Shell voicing (+1, +2 para añadir notas)',
    voicing_inv: '<strong>Inversion</strong> \u2014 Inversiones (Root, 1st, 2nd, 3rd)',
    inv_1: '1.ª inversión',
    inv_2: '2.ª inversión',
    inv_3: '3.ª inversión',
    voicing_drop: '<strong>Drop 2 / Drop 3</strong> \u2014 Drop voicings',
    voicing_box: '<strong>Voicing Box</strong> \u2014 Toca para recorrer las opciones de disposición en el pad (un contador como A1/3 = disposiciones alternativas disponibles)',
    display: 'Visualización',
    display_inst: '<strong>Guitar / Bass / Piano / Staff</strong> \u2014 Activa/desactiva el diapasón de guitarra, el bajo, el teclado de piano y la partitura de forma independiente. Nota: Las posiciones de guitarra/bajo muestran digitaciones tocables del instrumento, no corresponden a la disposición del pad',
    display_circle: '<strong>Circle of Fifths</strong> \u2014 Muestra el círculo de quintas. Vinculado a la selección de tonalidad, mostrando acordes diatónicos y funciones (T/SD/D). Compatible con cambio a modo menor',
    display_label: '<strong>Nombre de nota / Grado</strong> \u2014 Alterna entre nombres de notas (C, D, E) y grados (R, 2, 3) en la guitarra y los pads',
    display_oct: '<strong>Octave \u25B2\u25BC</strong> \u2014 Desplaza el rango de los pads por octava',
    sound: 'Sound',
    sound_onoff: '<strong>\uD83D\uDD0A ON/OFF</strong> \u2014 Activa/desactiva el sonido con el icono del altavoz',
    sound_select: '<strong>Pad Sensei MK1</strong> \u2014 Modelado físico Rhodes. Los miembros HPS pueden seleccionar el preset Suitcase (cadena de amplificación con modelado físico). \u25BC abre el panel de detalles',
    sound_tremolo: '<strong>Tremolo</strong> \u2014 Modelado físico Peterson Vactrol (estéreo). Usa TREM/T.SPD para profundidad y velocidad',
    sound_organ: '<strong>ORGAN</strong> \u2014 4 presets (Jazz, Perc, Full, Gospel)',
    sound_ep: '<strong>E.PIANO</strong> \u2014 8 presets (Rhodes, FM, Clavinet, etc.)',
    sound_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro envolvente (Auto-Wah). 3 tipos: Cry Baby / Mu-Tron / Moog',
    sound_drive: '<strong>Drive</strong> \u2014 Saturación analógica. Añade una cálida distorsión al sonido',
    sound_fx: '<strong>Efectos</strong> \u2014 Lo Cut, Hi Cut, Reverb, Phaser, Flanger, Volume',
    sound_play: 'Haz clic en un pad o en el Voicing Box para reproducir sonido',
    midi: 'MIDI',
    midi_detect: 'Detecta automáticamente dispositivos compatibles con WebMIDI',
    midi_push: 'Compatible con la salida MIDI serial de Ableton Push',
    midi_chord: 'Identifica acordes automáticamente a partir de las notas de entrada',
    midi_sustain: '<strong>Pedal de sustain</strong> \u2014 Compatible con MIDI CC64 (Hold Pedal)',
    color_title: 'Leyenda de colores',
    color_root: '<strong>Root</strong> \u2014 Nota raíz',
    color_scale: '<strong>Scale / Chord</strong> \u2014 Notas de la escala / Notas del acorde',
    color_char: '<strong>Nota característica</strong> \u2014 Notas que definen la escala/el acorde',
    color_3rd: '<strong>3rd</strong> \u2014 Nota guía (3.ª)',
    color_7th: '<strong>7th</strong> \u2014 Nota guía (7.ª)',
    color_tension: '<strong>Tension</strong> \u2014 Notas de tensión',
    color_avoid: '<strong>Avoid</strong> \u2014 Nota de la escala a un semitono por encima de una nota del acorde (en Chord Mode)',
    color_palette: 'Paleta de colores: Okabe-Ito (accesible para distintas visiones del color)',
    input_title: 'Input Mode',
    input_desc1: 'Haz clic en los pads libremente para seleccionar notas \u2192 Identificación de acordes en tiempo real',
    input_desc2: 'Sin filtro de teor\u00EDa. Explora \u2192 descubre \u2192 aprende la teor\u00EDa despu\u00E9s',
    input_desc3: 'Al detectar un acorde, se muestran etiquetas de grado (R, 3, 5, b7, etc.) en los pads. Guitarra, bajo, piano y pentagrama se actualizan autom\u00E1ticamente',
    input_memory: '<strong>Memory</strong> \u2014 Guarda y recupera acordes en 16 ranuras',
    input_banks: '<strong>Banks</strong> \u2014 16 ranuras \u00D7 hasta 16 bancos. Cambiar con <kbd>[</kbd> <kbd>]</kbd>. Duplicar y renombrar compatible',
    input_export: '<strong>MIDI Export</strong> \u2014 Exporta los acordes de memoria como archivo MIDI',
    perform_title: 'Perform Mode',
    perform_switch: '<strong>Memory / Perform</strong> botón o tecla <kbd>p</kbd> para cambiar',
    perform_desc1: 'Toca los acordes de los Memory Slots en tiempo real con un layout de 16 pads',
    perform_desc2: 'Activa mediante teclado (cuadr\u00EDcula 4\u00D74) o pads MIDI',
    perform_desc3: 'Arrastra y suelta Slots para reordenar',
    shortcut_title: 'Atajos de teclado',
    shortcut_scale_chord: 'Scale / Chord Mode',
    sc_diatonic: '<kbd>1</kbd>\u2013<kbd>7</kbd> \u2014 Seleccionar acorde diatónico (escalas de 7 notas)',
    sc_voicing: '<kbd>a</kbd>\u2013<kbd>i</kbd> \u2014 Seleccionar Voicing Box (recorre las alternativas)',
    sc_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Recorrer inversiones (Chord Mode)',
    sc_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático de la raíz',
    sc_omit: '<kbd>o</kbd> \u2014 Alternar Omit 5',
    sc_rootless: '<kbd>r</kbd> \u2014 Alternar Rootless',
    sc_shell: '<kbd>s</kbd> \u2014 Ciclar Shell (off \u2192 1-3-7 \u2192 1-7-3 \u2192 off)',
    sc_drop: '<kbd>d</kbd> \u2014 Ciclar Drop (off \u2192 Drop 2 \u2192 Drop 3 \u2192 off)',
    sc_voicing_reflect: "<kbd>v</kbd> — Motor Guitar ON/OFF (muestra el voicing de guitarra seleccionado en la cuadrícula de 64 pads)",
    sc_guitar_pos: '<kbd>,</kbd> / <kbd>.</kbd> \u2014 Ciclar posición de guitarra (anterior / siguiente)',
    sc_bass_pos: '<kbd>&lt;</kbd> / <kbd>&gt;</kbd> \u2014 Cambiar posición del bajo (anterior / siguiente)',
    sc_tasty: '<kbd>t</kbd> \u2014 TASTY ON/OFF',
    sc_stock: '<kbd>k</kbd> \u2014 STOCK ON/OFF',
    sc_clear: '<kbd>x</kbd> \u2014 Borrar acorde (Chord Mode)',
    sc_pad_explore: '<b>Pad (modo Chord)</b> \u2014 Clic para activar/desactivar nota \u2014 constructor actualizado automáticamente',
    shortcut_input: 'Input Mode',
    sp_capture: '<kbd>c</kbd> \u2014 Iniciar Capture / guardar en la siguiente ranura',
    sp_end: '<kbd>e</kbd> \u2014 Finalizar Capture',
    sp_recall: '<kbd>1</kbd>\u2013<kbd>9</kbd>, <kbd>0</kbd> \u2014 Recuperar ranura de memoria (Edit)',
    sp_transpose: '<kbd>\u2190</kbd><kbd>\u2192</kbd> \u2014 Transporte cromático (todas las notas \u00B11)',
    sp_inv: '<kbd>\u2191</kbd><kbd>\u2193</kbd> \u2014 Inversión (nota más grave \u21911oct / nota más aguda \u21931oct)',
    sp_clear: '<kbd>x</kbd> \u2014 Borrar todo',
    sp_transfer: '<b>Cambiar a Chord</b> \u2014 Transferir el acorde detectado a Chord Mode',
    shortcut_perform: 'Perform Mode',
    pf_layout: '<kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><kbd>4</kbd> / <kbd>q</kbd><kbd>w</kbd><kbd>e</kbd><kbd>r</kbd> / <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> / <kbd>z</kbd><kbd>x</kbd><kbd>c</kbd><kbd>v</kbd> \u2014 Cuadr\u00EDcula 4\u00D74 activa Slots 1\u201316',
    pf_midi: 'Los pads MIDI (notas 36\u201354) tambi\u00E9n activan Slots',
    shortcut_common: 'Com\u00FAn (Todos los modos)',
    sc_perform: '<kbd>p</kbd> \u2014 Alternar vista Perform',
    sc_undo: '<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>+<kbd>z</kbd> \u2014 Deshacer Memory Slots (hasta 30)',
    sc_shift_save: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Guardar el acorde / voicing actual en un Memory Slot',
    sc_capture_current: '<kbd>Shift</kbd>+<kbd>C</kbd> \u2014 Guardar el acorde / voicing actual en un Memory Slot',
    sc_save: '<kbd>Option</kbd>+<kbd>1234</kbd><kbd>qwer</kbd><kbd>asdf</kbd><kbd>zxcv</kbd> \u2014 Guardar directamente en un Memory Slot',
    sc_space: '<kbd>Space</kbd> \u2014 Reproducir acorde actual',
    sc_esc: '<kbd>Esc</kbd> \u2014 Deseleccionar Voicing Box / cerrar Ayuda',
    sc_help: '<kbd>?</kbd> \u2014 Mostrar/ocultar Ayuda',
    sc_slash: '<kbd>/</kbd> \u2014 Enfocar entrada de texto de acordes',
    sc_tasty_nav: "<kbd>z</kbd> / <kbd>x</kbd> — Voicing TASTY/STOCK/Guitar anterior/siguiente",
    shortcut_display: 'Alternar visualización (\u2318\u2325 / Ctrl+Alt)',
    sc_cmd_guitar: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>G</kbd> \u2014 Guitar',
    sc_cmd_bass: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>B</kbd> \u2014 Bass',
    sc_cmd_piano: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>P</kbd> \u2014 Piano',
    sc_cmd_circle: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>F</kbd> \u2014 Circle of Fifths',
    sc_cmd_staff: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>S</kbd> \u2014 Staff',
    sc_cmd_audio: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>A</kbd> \u2014 Audio',
    sc_cmd_memory: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>M</kbd> \u2014 Memory Slot',
    sc_cmd_text: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>T</kbd> \u2014 Text Input',
    sc_cmd_quality: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>Q</kbd> \u2014 Quality/Tension',
    sc_cmd_voicing: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>V</kbd> \u2014 Voicing',
    sc_cmd_key: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>K</kbd> \u2014 Key Display',
    sc_cmd_header: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>H</kbd> \u2014 Header / Info Bar',
    sc_cmd_badge: '<kbd>\u2318</kbd><kbd>\u2325</kbd>+<kbd>I</kbd> \u2014 Show/hide shortcut key hints',
    tips_toggle: 'Mostrar consejos al inicio',
    badge_toggle: 'Show shortcut key hints',
    c_fixed_toggle: 'Fijar en Do mayor',
    color_coding_toggle: 'Colorear notas características y de acorde',
    show_all_positions_toggle: 'Mostrar todas las posiciones del acorde',
    c_fixed_tip: 'El pad muestra siempre la escala de Do mayor, independientemente de Key/Scale/Chord.',
    layout: 'Diseño',
    footer: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
  },
  legend: {
    characteristic: 'Nota característica',
    scale_note: 'Scale Note',
    chord_tone: 'Chord Tone',
    scale_root: 'Raíz de la escala',
  },
  ui: {
    close: 'Cerrar',
    perform: 'Perform',
    memory_slot: 'Memory Slot',
    clear: 'Clear',
    save: 'Save',
    memory: 'Memory',
    slot_hint: '<span><b style="color:var(--text);opacity:0.6;">Click</b> select</span><span><b style="color:var(--text);opacity:0.6;">Shift+C</b> save</span><span><b style="color:var(--text);opacity:0.6;">Opt+key</b> direct save</span><span><b style="color:var(--text);opacity:0.6;">Shift+Click</b> delete</span><span><b style="color:var(--text);opacity:0.6;">Opt+Drag</b> copy</span>',
    save_settings: 'Guardar configuración',
    sound_hint: 'Selecciona un preset de sonido para activar el audio',
    tap_to_start: 'Toca para activar el sonido',
    tap_to_start_sub: 'Your browser requires a tap before audio can play',
    tap_pads: '¡Toca cualquier pad para tocar!',
    load_vst: 'Cargar plugin VST/AU...',
    affiliate_label: '',
    staff: 'Partitura',
    circle: 'Círculo',
    help: 'Ayuda',
    view_settings: 'Ajustes de vista',
    show_all_positions: 'Todas las posiciones',
    view_focus: 'Vista',
    view_layout: 'Disposición',
    view_all: 'Todos los paneles',
    view_pad: 'Solo pad',
    view_chord: 'Solo constructor de acordes',
    view_info: 'Solo info / memoria',
    layout_abc: 'Pad → Acorde → Círculo',
    layout_acb: 'Pad → Círculo → Acorde',
    layout_bac: 'Acorde → Pad → Círculo',
    layout_bca: 'Acorde → Círculo → Pad',
    layout_cab: 'Círculo → Pad → Acorde',
    layout_cba: 'Círculo → Acorde → Pad',
    view_setup_note: 'En la versión Desktop, Push 3 Setup también abre esta pantalla. Jog Wheel izquierda/derecha selecciona vista o disposición, girar cambia el valor, y pulsar Jog Wheel o Setup la cierra.',
    oct_down: 'Bajar octava',
    oct_up: 'Subir octava',
    toggle_guitar: 'Mostrar/ocultar diapas\u00F3n de guitarra (\u2318\u2325G)',
    toggle_bass: 'Mostrar/ocultar diapas\u00F3n de bajo (\u2318\u2325B)',
    toggle_piano: 'Mostrar/ocultar teclado de piano (\u2318\u2325P)',
    mode_scale: 'Modo Scale \u2014 ver notas de la escala en los pads (Tab para cambiar)',
    mode_chord: 'Modo Chord \u2014 construir acordes con voicings (Tab para cambiar)',
    mode_input: 'Modo Input \u2014 tocar pads libremente para detectar acordes (Tab para cambiar)',
    play_chord: 'Reproducir acorde actual (Space)',
    toggle_staff: 'Mostrar/ocultar partitura (\u2318\u2325S)',
    toggle_circle: 'Mostrar/ocultar c\u00EDrculo de quintas (\u2318\u2325F)',
    toggle_sound: 'Mostrar/ocultar controles de sonido',
    sound_mute: 'Sonido ON/OFF',
    sound_expand: 'Mostrar/ocultar ajustes detallados de sonido',
    input_keys_disabled: 'La selección de tonalidad no se usa en el modo Input',
  },
  label: {
    note_name: 'Nota',
    degree: 'Grado',
    chord_input: 'Introducir acorde',
    chord_hint: 'Tensiones en ( ): C7(b9,#11) | dim, h=m7\u266D5 soportados',
    key_hint: 'También configurable desde el modo Scale o el Círculo de quintas',
  },
  header: {
    portal: 'HPS Portal',
    blog: 'Mi Blog',
    guide: 'Gu\u00EDa',
    wishlist: 'Wishlist',
  },
  input: {
    status_idle: 'Pulsa Capture para empezar a construir acordes',
    status_capturing: 'Capturando: Ranura {slot}/16 \u2014 Haz clic en los pads y luego Capture para guardar',
    status_editing: 'Editando: Ranura {slot} \u2014 Haz clic en los pads para modificar',
    notes_label: 'Notas: ',
  },
  notify: {
    slot_saved: 'Slot {slot} \u2190 {chord}',
    memory_full: 'Los Memory Slots están llenos',
    no_current_chord: 'No hay acorde actual para guardar',
    slot_selected: 'Ranura {slot} seleccionada',
    slot_cleared: 'Ranura {slot} borrada',
    undo: 'Deshacer',
    settings_saved: 'Configuración guardada',
    no_chords: 'No hay acordes en las ranuras de memoria',
    midi_imported: 'Imported {count} chords from MIDI',
  },
  info: {
    ep_rhodes: 'Pickup level / tone balance for the electric piano sound',
    ep_voicing: 'Voicing color for the electric piano sound',
    ep_mechanical: 'Mechanical noise level for the electric piano sound',
    default: 'Pasa el cursor sobre cualquier control para ver qué hace',
    mode_scale: 'Modo Scale \u2014 Ver notas de la escala en la cuadrícula de 64 pads [Tab]',
    mode_chord: 'Modo Chord \u2014 Construir acordes paso a paso: Root \u2192 Quality \u2192 Tension [Tab]',
    mode_input: 'Modo Input \u2014 Toca los pads libremente, los acordes se detectan automáticamente [Tab]',
    guitar: 'Mostrar/ocultar diapasón de guitarra [\u2318\u2325G]',
    bass: 'Mostrar/ocultar diapasón de bajo [\u2318\u2325B]',
    piano: 'Mostrar/ocultar teclado de piano [\u2318\u2325P]',
    link_mode: 'Modo Link \u2014 las notas tocadas se sincronizan en todos los instrumentos en tiempo real [\u2318\u2325L]',
    staff: 'Mostrar/ocultar partitura [\u2318\u2325S]',
    circle: 'Circle of Fifths \u2014 Tónica, Subdominante, Dominante mostrados en colores correspondientes [\u2318\u2325F]',
    cof_major: 'Anillo exterior \u2014 seleccionar tonalidad Mayor',
    cof_minor: 'Anillo interior \u2014 seleccionar tonalidad menor',
    cof_natural: 'Menor Natural',
    cof_harmonic: 'Menor Armónica',
    cof_melodic: 'Menor Melódica',
    sound: 'Mostrar/ocultar panel de controles de audio [\u2318\u2325A]',
    memory: 'Mostrar/ocultar panel Memory Slot \u2014 guardar/recuperar acordes en 16 ranuras [\u2318\u2325M]',
    sect_key: 'Mostrar/ocultar selección de tonalidad',
    sect_input: 'Mostrar/ocultar entrada de texto de acordes [\u2318\u2325T]',
    sect_quality: 'Mostrar/ocultar selectores Root/Quality/Tension [\u2318\u2325Q]',
    sect_voicing: 'Mostrar/ocultar controles de voicing (Omit, Shell, Inversion, Drop) [\u2318\u2325V]',
    text_input: 'Escribe el nombre del acorde directamente \u2014 Cm7, G7(b9,#11), Am7/G [/]',
    parent_scales: 'Muestra escalas disponibles para el acorde actual. Los slash chords con bajo no perteneciente al acorde se reinterpretan desde la nota del bajo',
    sort_practical: 'Ordenación práctica \u2014 prioriza escalas de uso común. Incluye escalas de dominante secundaria (ej., Mixolydian b13 para V7/ii)',
    sort_diatonic: 'Ordenación diatónica \u2014 ordena por distancia teórica desde la tonalidad actual',
    omit5: 'Omitir la 5ª del voicing [O]',
    rootless: 'Omitir la fundamental [R]',
    omit3: 'Omitir la 3ª del voicing',
    shell137: 'Shell voicing: Root-3rd-7th [S]',
    shell173: 'Shell voicing: Root-7th-3rd [S]',
    shell_off: 'Desactivar shell voicing [S]',
    shell_ext: 'Añadir notas al shell voicing (+1 o +2 notas del acorde)',
    inv_root: 'Posición fundamental [\u2193]',
    inv: 'Inversión [\u2191][\u2193]',
    drop2: 'Drop 2 [Shift+D]',
    drop3: 'Drop 3 [Shift+D]',
    tasty: 'Tasty Voicing \u2014 voicings refinados ordenados por nota superior. Funciona con \u25B37, m7, 7 (exclusivo HPS) [T]',
    tasty_nav: 'Ciclar variaciones [Z / X]',
    stock: 'Stock Voicing \u2014 voicings comunes de piano (exclusivo HPS) [K]',
    stock_nav: 'Ciclar variaciones [Z / X]',
    root_notation: 'Alternar entre notación \u266F y \u266D',
    root_grid: 'Seleccionar nota raíz',
    quality_grid: 'Seleccionar calidad del acorde (Maj, m, 7, dim, aug, sus...)',
    tension_grid: 'Añadir tensiones al acorde (9, b9, #9, 11, #11, 13, b13) \u2014 selección múltiple OK',
    diatonic: 'Acordes diatónicos de la escala actual \u2014 clic para entrar en Chord Mode [1\u20137]',
    harm_mel: 'Harm/Mel \u2014 Comparar acordes diatónicos de Menor Armónica y Melódica lado a lado [\u2318\u2325N]',
    parallel_key: 'Tonalidad paralela \u2014 Muestra acordes diatónicos mayor/menor para la misma raíz. Descubre el origen de los acordes prestados [\u2318\u2325R]',
    secdom: 'Dominante secundaria \u2014 Muestra V7 resolviendo a cada acorde diatónico. Clic para mostrar Available Scale automáticamente [\u2318\u2325D]',
    harmonic_fn: 'T/SD/D \u2014 Color diatonic chords by harmonic function: Tonic, Subdominant, Dominant [\u2318\u2325F]',
    capture: 'En modo Input, capturar toques de pad en Memory Slots en secuencia [C]',
    capture_current: 'Guardar el acorde / voicing TASTY / STOCK / Guitar actual en un Memory Slot [Shift+C]',
    capture_end: 'Finalizar captura y guardar en la ranura actual [E]',
    save: 'Guardar todos los ajustes actuales (tonalidad, escala, sonido, memoria, disposición)',
    tutorial: 'Tutoriales interactivos \u2014 aprende los fundamentos paso a paso',
    help: 'Abrir modal de ayuda con referencia completa de atajos [?]',
    affiliate: 'Las compras a través de estos enlaces apoyan el desarrollo\u2026',
    lang: 'Cambiar idioma de visualización',
    octave: 'Desplazar rango de octava de los pads \u2014 Push/Launchpad también pueden controlar con botones de octava',
    show_all_positions: 'Cuando está activado, muestra todas las posiciones del acorde en la cuadrícula y los recuadros de voicing. Cuando está desactivado, muestra solo una forma básica.',
    play: 'Reproducir el acorde actual [Space]',
    scale_select: 'Seleccionar una escala',
    chord_key: 'Alternar entre tonalidad Mayor y menor',
    chord_key_picker: 'Abrir selector de tonalidad para cambiar sin pasar al modo Scale',
    builder_clear: 'Borrar el acorde actual y empezar de nuevo [X]',
    builder_back: 'Deshacer el último paso en la construcción del acorde [\u232B]',
    slash_chord: 'Slash chord (acorde con bajo alterno)',
    guitar_diagram: 'Voicings comunes de guitarra reflejados al seleccionar acorde en el constructor',
    guitar_label: 'Mostrar/ocultar nombres de notas en el diapasón de guitarra',
    genre_preset: 'Cambiar género de voicing de guitarra \u2014 Standard / Folk/Open / Bossa / Jazz / Funk/Soul / Neo Soul',
    pos_nav: 'Ciclar posiciones de voicing de guitarra/bajo [, .]',
    to_pad: 'Reflejar el voicing de guitarra/stock en la cuadrícula de 64 pads [V]',
    inst_clear: 'Borrar notas introducidas en el diagrama del instrumento',
    inst_play: 'Reproducir notas introducidas en el diagrama del instrumento',
    plain_clear: 'Borrar todas las notas en modo Input [X]',
    midi_export: 'Exportar todas las ranuras de memoria como archivo MIDI para tu DAW',
    chs_export: 'Exportar todas las ranuras de memoria en formato CHS (Clover Chord Systems)',
    midi_import: 'Importar un archivo MIDI en las ranuras de memoria',
    chs_import: 'Importar un archivo CHS en las ranuras de memoria',
    midi_device: 'Seleccionar entrada MIDI',
    midi_panic: 'All Notes Off \u2014 detener cualquier nota MIDI atascada',
    sound_mute: 'Sonido ON/OFF',
    sound_preset: 'Seleccionar preset de sonido',
    volume: 'Volumen maestro',
    sound_fx: 'Efectos \u2014 Lo Cut, Hi Cut, Drive, Tremolo, Phaser, Flanger, Reverb',
    auto_filter: 'Auto Filter \u2014 el filtro se abre/cierra con cada nota. Tipo LP/BP, pendiente 2P/4P',
    velocity: 'Curva de velocidad',
    mem_view: 'Vista de memoria \u2014 guardar y organizar acordes en 16 ranuras [M]',
    perform_view: 'Vista Perform \u2014 tocar acordes guardados en tiempo real con 16 pads [P]',
    bank: 'Bancos de memoria \u2014 16 ranuras \u00D7 hasta 16 bancos. [ ] para cambiar',
    slot_save: 'Guardar el acorde actual en la ranura seleccionada',
    play_slots: 'Reproducir todos los acordes guardados en secuencia',
    locut: 'Lo-cut \u2014 Elimina graves para claridad (casilla ON/OFF, deslizador = frecuencia de corte)',
    hicut: 'Hi-cut \u2014 Elimina agudos para un tono m\u00E1s redondo (casilla ON/OFF, deslizador = frecuencia)',
    drive: 'Drive \u2014 Cantidad de overdrive. M\u00E1s alto = m\u00E1s distorsi\u00F3n',
    tremolo: 'Profundidad de tr\u00E9molo \u2014 Profundidad de modulaci\u00F3n de amplitud (modelado f\u00EDsico Peterson + CdS)',
    tremolo_speed: 'Velocidad de tr\u00E9molo \u2014 Frecuencia de modulaci\u00F3n (Hz)',
    phaser: 'Phaser \u2014 Barrido con desplazamiento de fase',
    flanger: 'Flanger \u2014 Delay muy corto, barrido met\u00E1lico',
    af_on: 'Auto Filter ON/OFF',
    af_type: 'Tipo de filtro \u2014 LP=Pasabajos / BP=Pasabanda',
    af_poles: 'Pendiente \u2014 2P=12dB/oct (suave) / 4P=24dB/oct (pronunciada)',
    af_depth: 'Depth \u2014 Rango de apertura/cierre del filtro',
    af_decay: 'Decay \u2014 Velocidad con la que se cierra el filtro (menor = m\u00E1s r\u00E1pido)',
    af_q: 'Q \u2014 Resonancia (nitidez del pico)',
    af_wet: 'WET \u2014 Cantidad del efecto (0 = totalmente seco, 10 = totalmente mojado)',
    af_vol: 'VOL \u2014 Trim de salida (baja si el amplificador satura)',
    eq_bass: 'Baxandall Bass \u2014 EQ shelving de graves. Centro = plano',
    eq_treble: 'Baxandall Treble \u2014 EQ shelving de agudos. Centro = plano',
    reverb_type: 'Tipo de reverb \u2014 Spring (cola ondulante estilo Twin) / Plate (cola densa met\u00E1lica)',
    reverb_amount: 'Cantidad de reverb \u2014 Mezcla de se\u00F1al wet',
    reverb_decay: 'Decay de reverb \u2014 Longitud de la cola',
    reverb_stereo: 'Est\u00E9reo \u2014 ON esparce la reverb por L/R',
    reverb_dwell: 'Dwell \u2014 Nivel de entrada al tanque de muelles',
    vel_thresh: 'Umbral de velocidad \u2014 Golpes m\u00E1s suaves se tratan como velocidad m\u00EDnima',
    vel_drive: 'Velocity Drive \u2014 Inclinaci\u00F3n de la curva (positivo = acent\u00FAa, negativo = aplana)',
    vel_compand: 'Compand \u2014 Comprime/expande alrededor de la velocidad media',
    vel_range: 'Range \u2014 L\u00EDmite m\u00E1ximo de velocidad',
    note_count: '{n} notas',
  },
  builder: {
    step_root: 'Root',
    step_quality: 'Quality',
    step_tension: 'Tension',
    step_bass: 'Bass Note',
    select_root: 'Selecciona la raíz',
    minor: 'Minor',
    major: 'Major',
  },
  midi: {
    all_devices: 'All Devices',
  },
  memory: {
    slot_empty: 'Ranura {slot}: Vacía',
    midi_selected: 'MIDI Export {chord}',
    midi_all: 'MIDI Export All',
    chs_selected: 'CHS: {chord}',
    chs_all: 'CHS Export All',
    play_selected: 'Play: {chord}',
    play_all: 'Play All \u25B6',
    stop: 'Stop \u25A0',
    capture: 'Capture',
    recall: 'Recuperar',
    play: 'Reproducir',
    duplicate: 'Duplicar',
    delete: 'Eliminar',
    save_here: 'Guardar aquí',
    save_current: 'Save',
    clear_esc: 'Clear (Esc)',
    end: 'End',
  },
  bank: {
    click_rename: 'Clic para renombrar',
    rename: 'Renombrar',
    duplicate: 'Duplicar',
    delete: 'Eliminar',
    rename_prompt: 'Nombre del banco:',
    confirm_delete: '\u00BFEliminar "{name}"?',
    limit_reached: 'M\u00E1ximo 16 bancos',
    cannot_delete_last: 'No se puede eliminar el \u00FAltimo banco',
  },
  diatonic: {
    parallel: 'Tonalidad paralela',
    relative: 'Relativa',
    harm_mel: 'Harm/Mel',
    secdom: 'Dominante secundaria',
    harmonic_fn: 'T/SD/D',
  },
  parent: {
    toggle: 'Available Scale',
    header: 'Available Scales ({n})',
    expand: 'Mostrar todo',
    sortPractical: 'Practical',
    sortDiatonic: 'Diatonic',
  },
  guide: {
    page_title: '64 Pad Explorer \u2014 Gu\u00EDa',
    tagline: 'Una herramienta de navegador para explorar escalas, acordes y voicings en una cuadr\u00EDcula de 64 pads.<br>No necesitas fuente de sonido \u2014 solo Chrome.',
    cta: 'Abrir App',
    features: 'Caracter\u00EDsticas',
    feat_sound: '<strong>Sin fuente de sonido necesaria</strong> \u2014 El sonido se reproduce directamente en Chrome. 4 presets de \u00F3rgano + 8 de piano el\u00E9ctrico integrados. Efectos incluidos (drive, reverb, phaser, flanger, tr\u00E9molo, lo cut, hi cut, auto filter)',
    feat_input: '<strong>Sin habilidades de pad necesarias</strong> \u2014 Construye acordes en 3 pasos. Tensiones mostradas. Haz clic en los pads para ingresar directamente',
    feat_text_input: '<strong>Entrada de texto de acordes</strong> \u2014 Pulsa "/" para escribir Cm7, G7(b9,#11), Am7/G etc. directamente. Autocompletado. Abreviaturas como dim, h(=m7\u266D5)',
    feat_detect: '<strong>Detecci\u00F3n de acordes</strong> \u2014 Detecci\u00F3n en tiempo real del nombre del acorde a partir de las notas clicadas. Soporta omit, acordes con bajo alterno y m\u00FAltiples candidatos',
    feat_instruments: '<strong>Visualizaci\u00F3n de Guitar / Bass / Keyboard</strong> \u2014 Muestra las notas del acorde en el diapas\u00F3n de guitarra, bajo y piano. La entrada de digitaci\u00F3n de guitarra se refleja autom\u00E1ticamente en los pads. En modo Chord, las posiciones se agrupan por cuerda ra\u00EDz',
    feat_scales: '<strong>Visualizaci\u00F3n de escalas</strong> \u2014 31 escalas \u00D7 12 tonalidades. Diat\u00F3nica, Menor Arm\u00F3nica, Menor Mel\u00F3dica, Pentat\u00F3nica, Bebop y m\u00E1s',
    feat_diatonic: '<strong>Visualizaci\u00F3n de acordes diat\u00F3nicos</strong> \u2014 Los acordes diat\u00F3nicos se muestran en una barra para la escala seleccionada. Haz clic o usa atajos para reproducir al instante. Alterna entre tr\u00EDadas y t\u00E9tradas',
    feat_voicing: '<strong>Operaciones de voicing</strong> \u2014 Inversiones, Drop 2/3, Shell Voicing, Omit, Rootless. Teclas de flechas para inversiones, botones para m\u00FAltiples digitaciones',
    feat_memory: '<strong>Memoria de acordes</strong> \u2014 Guarda tus acordes favoritos en 16 ranuras. Exporta como archivos MIDI para tu DAW',
    feat_perform: '<strong>Modo Perform</strong> \u2014 Toca los acordes de memoria en tiempo real usando 16 pads o tu teclado de PC',
    feat_parent: '<strong>B\u00FAsqueda inversa de Available Scale</strong> \u2014 Encuentra escalas que contengan tu acorde. Ve los Available Tensions de un vistazo. Alternancia Practical/Diatonic',
    feat_pivot: '<strong>Pensamiento de acorde pivote</strong> \u2014 Ingresa un acorde manualmente y la barra diat\u00F3nica desaparece, mostrando todas las tonalidades a las que tu acorde podr\u00EDa pertenecer. Ideal para an\u00E1lisis de modulaci\u00F3n',
    feat_dimming: '<strong>Visualizaci\u00F3n pr\u00E1ctica de Tensions</strong> \u2014 Para acordes de 7\u00AA no dominante, las tensiones poco comunes (b9, #9, b13, etc.) se muestran atenuadas. A\u00FAn seleccionables',
    feat_circle: '<strong>Circle of Fifths</strong> \u2014 Muestra el círculo de quintas. Vinculado a la selección de tonalidad, mostrando acordes diatónicos y funciones (T/SD/D). Compatible con cambio a modo menor',
    feat_banks: '<strong>Bancos de memoria</strong> \u2014 16 ranuras \u00D7 hasta 16 bancos. Cambiar, duplicar y renombrar bancos. Teclas <kbd>[</kbd> <kbd>]</kbd> para cambiar',
    feat_autofilter: '<strong>Auto-Filter</strong> \u2014 Filtro envolvente (Auto-Wah). 3 tipos: Cry Baby / Mu-Tron / Moog. Ajusta frecuencia, resonancia, sensibilidad y decay',
    feat_drive: '<strong>Drive</strong> \u2014 Saturación analógica. Añade una cálida distorsión al sonido',
    feat_clav: '<strong>Presets de Clavinet</strong> \u2014 2 presets de clavinet añadidos a E.PIANO (Clav Muted, Clav Bright). Perfecto para funk',
    feat_midi_sens: '<strong>Sensibilidad de velocidad MIDI</strong> \u2014 Ajuste de curva de velocidad con 4 parámetros estilo Push 3 (Threshold, Drive, Compand, Range). Visualización de curva en tiempo real. Funciona con todos los controladores MIDI',
    feat_push_oct: '<strong>Sincronización de octava Push 3</strong> \u2014 Los botones de octava \u25B2\u25BC de Push 3 se sincronizan automáticamente con el desplazamiento de octava de la app',
    feat_i18n: '<strong>Multiling\u00FCe</strong> \u2014 9 idiomas (EN / JA / ZH / ES / FR / PT / DE / KO / IT)',
    screenshots: 'Capturas de pantalla',
    ss_scale: '<span class="mode-badge scale">Scale</span> Scale Mode',
    ss_scale_desc: 'Selecciona una tonalidad y escala para ver las notas de la escala codificadas por color en la cuadr\u00EDcula de 64 pads. Elige acordes de la barra diat\u00F3nica.',
    ss_scale_alt: 'Scale Mode \u2014 Visualizaci\u00F3n de la escala C Major (Ionian)',
    ss_scale_caption: 'C Major (Ionian) \u2014 Ra\u00EDz (naranja), notas de escala (azul), notas caracter\u00EDsticas (amarillo)',
    ss_chord: '<span class="mode-badge chord">Chord</span> Chord Mode',
    ss_chord_desc: 'Construye acordes en 3 pasos: Root \u2192 Quality \u2192 Tension. Ajusta voicings con inversiones, Drop, Shell y Omit. Usa el panel Parent Scale para b\u00FAsqueda inversa de escalas.',
    ss_chord_alt: 'Chord Mode \u2014 Visualizaci\u00F3n del acorde Dm7 con cuadr\u00EDcula de tensiones',
    ss_chord_caption: 'Dm7 \u2014 Notas del acorde, 3rd (rosa), 7th (verde). Consulta las opciones de disposici\u00F3n en los Voicing Boxes',
    ss_input: '<span class="mode-badge input">Input</span> Input Mode',
    ss_input_desc: 'Haz clic en los pads libremente para detecci\u00F3n de acordes en tiempo real. Entiende los acordes incluso sin conocer la teor\u00EDa.',
    ss_input_alt: 'Input Mode \u2014 Detecci\u00F3n en tiempo real de C7',
    ss_input_caption: 'C7 \u2014 Haz clic en los pads para detectar autom\u00E1ticamente nombres de acordes. Se muestran m\u00FAltiples candidatos',
    ss_perform: 'Perform Mode',
    ss_perform_desc: 'Coloca los acordes guardados en 16 pads para interpretaci\u00F3n en tiempo real usando teclado o pads MIDI.',
    ss_perform_alt: 'Perform Mode \u2014 16 ranuras con acordes',
    ss_perform_caption: 'Perform Mode \u2014 C7, Fm7, G7, Am7 guardados en ranuras. Toca usando la cuadr\u00EDcula 4\u00D74 del teclado',
    ss_parent: 'Available Scale + Acorde Pivote',
    ss_parent_desc: 'B\u00FAsqueda inversa de escalas que contengan tu acorde. Alterna entre ordenamiento Practical (por usabilidad) y Diatonic (por teor\u00EDa). La entrada manual de acordes oculta la barra diat\u00F3nica para an\u00E1lisis de acordes pivote.',
    ss_parent_alt: 'Panel Parent Scale y visualizaci\u00F3n del diapas\u00F3n de guitarra',
    ss_parent_caption: 'Dm7 \u2192 C Major (Dorian), C Mel.Min (Dorian b2), F Major (Aeolian), etc. Se muestran los Available Tensions',
    ss_parent_note: '\u203B Las escalas pentat\u00F3nicas/blues son modales (enfoque horizontal) y pertenecen a un sistema diferente de la teor\u00EDa de escalas por acorde (mapeo vertical), por lo que no se incluyen en Available Scale. En la pr\u00E1ctica, la pentat\u00F3nica suele ser la primera opci\u00F3n.',
    ss_velocity: 'Sensibilidad de velocidad MIDI',
    ss_velocity_desc: 'Ajusta la sensibilidad de velocidad del controlador MIDI con 4 parámetros estilo Push 3. Configura en la sección VELOCITY SENSITIVITY dentro del panel Sound. Visualización de curva en tiempo real.',
    ss_push_oct: 'Sincronización de botón de octava Push 3',
    ss_push_oct_desc: 'Los botones de octava \u25B2\u25BC de Push 3 (CC#55/CC#54) se sincronizan automáticamente con el desplazamiento de octava de la app. Pulsa los botones de octava en Push 3 y la octava de la pantalla se actualiza automáticamente.',
    // HPS Voicing Features
    ss_hps_voicing_title: 'Funciones de Voicing exclusivas de HPS',
    ss_hps_voicing_intro: "Los miembros de HPS tienen acceso a 3 herramientas de voicing. Elige TASTY / STOCK / Guitar dentro del builder para mostrar ese voicing automáticamente en la cuadrícula de 64 pads.",
    ss_tasty: 'TASTY Voicing \u2014 Clasificado por nota superior',
    ss_tasty_desc: '129 voicings sofisticados mostrados como arrays de grados. Selecciona un acorde, pulsa <kbd>T</kbd> para activar y pulsa de nuevo para recorrer los voicings. Selecci\u00F3n autom\u00E1tica de la posici\u00F3n \u00F3ptima en los pads.',
    ss_tasty_target: 'Objetivo: Maj7 / Dom7 / Min7',
    ss_tasty_degrees: 'El \u00E1rea de informaci\u00F3n muestra el orden de apilamiento de grados (ej.: <code>m9 (b3-b7-9-5-1)</code>). Esta es la estructura del voicing \u2014 qu\u00E9 notas se apilan de abajo hacia arriba.',
    ss_tasty_labels_title: 'Significado de las etiquetas',
    ss_tasty_rootless: '<strong>Rootless</strong> \u2014 Se omite la fundamental (1er grado). Com\u00FAn en jazz/R&B/neo-soul donde el bajista cubre la fundamental.',
    ss_tasty_omit5: '<strong>Omit5</strong> \u2014 Se omite la 5ta. La 5ta tiene poco car\u00E1cter tonal, por lo que se reemplaza con una tensi\u00F3n para un sonido m\u00E1s rico.',
    ss_tasty_omit3: '<strong>Omit3</strong> \u2014 Se omite la 3ra. Se acerca a un sonido sus o Quartal.',
    ss_tasty_ops_title: 'Controles',
    ss_stock: 'STOCK Voicing \u2014 Colecci\u00F3n de Voicings de piano',
    ss_stock_desc: "154 voicings de piano de materiales educativos, mostrados en notación de grados. Cubre Major / Minor / Dominant / Half-diminished / Diminished / Suspended / Rootless / Spread. Los voicings seleccionados aparecen automáticamente en la cuadrícula de 64 pads.",
    ss_stock_ops_title: 'Controles',
    ss_guitar_pos: 'Guitar Position \u2014 Voicings de guitarra',
    ss_guitar_pos_desc: "Calcula automáticamente las posiciones de acordes en el diapasón de guitarra. La vista Guitar de la izquierda es el área de instrumento; Guitar dentro del builder es el motor de voicing para la cuadrícula de 64 pads.",
    usecases: 'Casos de uso',
    uc1_q: '"Quiero encontrar c\u00F3mo hacer el voicing de este acorde en los pads"',
    uc1_a: '\u2192 Selecciona Root, Quality y Tension en el modo <span class="mode-badge chord">Chord</span> \u2192 Consulta las disposiciones en los Voicing Boxes',
    uc2_q: '"Quiero ver una escala de mi lecci\u00F3n en los pads"',
    uc2_a: '\u2192 Selecciona tonalidad y escala en el modo <span class="mode-badge scale">Scale</span>. 31 escalas disponibles',
    uc3_q: '"Quiero crear una progresi\u00F3n de acordes para mi DAW"',
    uc3_a: '\u2192 Guarda acordes en las ranuras de memoria \u2192 MIDI Export para importar en tu DAW',
    uc4_q: '"\u00BFA qu\u00E9 tonalidad pertenece este acorde?"',
    uc4_a: '\u2192 B\u00FAsqueda inversa en el panel Available Scale. Alterna entre ordenamiento Practical/Diatonic',
    uc7_q: '"Quiero encontrar acordes pivote para modulaci\u00F3n"',
    uc7_a: '\u2192 Ingresa un acorde manualmente en el modo <span class="mode-badge chord">Chord</span>. La barra diat\u00F3nica desaparece y Available Scale muestra todas las tonalidades posibles',
    uc5_q: '"Quiero comprobar progresiones de acordes toc\u00E1ndolos"',
    uc5_a: '\u2192 Guarda los acordes en los slots de memoria y t\u00F3calos con un controlador MIDI o el teclado del PC',
    uc6_q: '"Quiero verificar acordes de guitarra en los pads"',
    uc6_a: '\u2192 Haz clic en el diapas\u00F3n de guitarra para ingresar \u2192 Se muestra autom\u00E1ticamente en los pads \u2192 Se detecta el nombre del acorde',
    uc8_q: '"Quiero aprender voicings profesionales"',
    uc8_a: '\u2192 Construye un acorde en modo <span class="mode-badge chord">Chord</span>, luego pulsa <kbd>T</kbd> para TASTY (clasificaci\u00F3n por nota superior) o <kbd>K</kbd> para STOCK (voicings de piano). Visualiza con notaci\u00F3n de grados, guarda en memoria y exporta a DAW',
    quickstart: 'Inicio r\u00E1pido',
    qs_modes: '3 modos',
    qs_modes_desc: '<span class="mode-badge scale">Scale</span> Muestra escalas y acordes diat\u00F3nicos<br><span class="mode-badge chord">Chord</span> Construye acordes en 3 pasos. Operaciones de voicing disponibles<br><span class="mode-badge input">Input</span> Haz clic en los pads libremente \u2192 Detecci\u00F3n autom\u00E1tica de nombres de acordes',
    qs_first: 'Primeros pasos',
    qs_step1: 'Elige una tonalidad (ej. C)',
    qs_step2: 'Elige una escala (ej. Major) \u2192 Las notas de la escala aparecen en los pads',
    qs_step3: 'Haz clic en un acorde de la barra diat\u00F3nica (ej. Dm7) \u2192 Se muestran las notas del acorde',
    qs_step4: 'Haz clic en los pads para reproducir sonidos. Cambia disposiciones en los Voicing Boxes',
    qs_step5: 'Guarda tus acordes favoritos con <kbd>Shift</kbd>+<kbd>1</kbd>\u2013<kbd>0</kbd>',
    qs_shortcuts: 'Atajos de teclado',
    qs_shortcuts_desc: 'Pulsa <kbd>?</kbd> para ver la lista completa de atajos.<br><kbd>Space</kbd> para reproducir acorde. <kbd>1</kbd>\u2013<kbd>7</kbd> para acordes diat\u00F3nicos, <kbd>\u2191</kbd><kbd>\u2193</kbd> para inversiones, <kbd>\u2190</kbd><kbd>\u2192</kbd> para movimiento crom\u00E1tico.<br>En el modo Perform, usa <kbd>1234</kbd>/<kbd>qwer</kbd>/<kbd>asdf</kbd>/<kbd>zxcv</kbd> como cuadr\u00EDcula 4\u00D74.',
    footer_open: 'Abrir 64 Pad Explorer',
    footer_version: '64 Pad Explorer \u2014 HPS (Hardcore Pad Style)',
    blog_more: 'M\u00E1s informaci\u00F3n en el blog \u2192',
    // Iconos del encabezado
    header_icons: 'Iconos del encabezado',
    header_icons_desc: 'Tres botones de icono en la esquina superior derecha.',
    icon_save: '<strong>\uD83D\uDCBE Guardar</strong> \u2014 Guarda la configuración actual (sonido, efectos, opciones de visualización, etc.) en el navegador. Se restaura automáticamente en la próxima visita',
    icon_tutorial: '<strong>\uD83D\uDCD6 Tutorial</strong> \u2014 Explora 11 tutoriales interactivos. Aprende cada función paso a paso',
    icon_help: '<strong>? Ayuda</strong> \u2014 Muestra atajos de teclado, historial de versiones y descripción de modos. También se abre con la tecla <kbd>?</kbd>',
    sound_panel: 'Panel de sonido',
    sound_panel_desc: 'Selecciona presets de sonido y ajusta los efectos. Haz clic en el botón \u25B6 para expandir el panel.',
    sound_presets: 'Presets de sonido',
    sound_presets_desc: 'El motor de modelado físico Rhodes (Clean DI) es el predeterminado. Toca al instante sin descargar muestras. Usa el knob VOICING para ajustar el tono del pickup.',
    sound_effects: 'Efectos',
    sound_effects_desc: 'Arrastra cada perilla para ajustar los valores.',
    fx_drive: 'Saturación analógica. Distorsión cálida',
    fx_locut: 'Filtro de corte bajo. Elimina graves turbios',
    fx_hicut: 'Filtro de corte alto. Suaviza agudos ásperos',
    fx_reverb: 'Reverberación. Añade profundidad espacial',
    fx_phaser: 'Phaser. Modulación envolvente',
    fx_flanger: 'Flanger. Modulación tipo jet',
    fx_tremolo: 'Trémolo. Modulación periódica del volumen',
    sound_autofilter: 'Auto-Filtro (Auto-Wah)',
    sound_autofilter_desc: 'Filtro de envolvente. Ajusta FREQ, RESO, SENS y DECAY.',
    version_history: 'Historial de versiones',
    vh_540: '<b>V5.4</b> \u2014 Modelado f\u00EDsico actualizado. A\u00F1adidos par\u00E1metros de filtro (WET / VOL) y un preset exclusivo HPS (Pad Sensei MK1 AMP Vintage Envelope Filter)',
    vh_600: '<b>V6.0</b> — Physical modeling engine improvements. Preamp circuit changes, HPS-only preset updates, and filter parameters (WET / VOL) added',
    vh_520: '<b>V5.2</b> \u2014 Modelado del preamp mejorado',
    vh_510: '<b>V5.1</b> \u2014 Modo de escala fija de Do mayor a\u00F1adido',
    vh_500: '<b>V5.0</b> \u2014 Motor de sonido y efectos aut\u00F3nomos. Spring Reverb (modelado f\u00EDsico) + Plate Reverb. Modelo de amplificador Suitcase mejorado. Selector de tipo de Reverb (Spring/Plate). Baxandall Bass/Treble EQ',
    vh_49x: '<b>V4.9</b> \u2014 Reproduce al instante desde que abres (sin descarga de samples). Alternar sugerencias de atajos. Acordes diat\u00F3nicos NM/HM/MM para tonalidades menores paralelas. PU LEVEL y MECHANICAL a\u00F1adidos al E.PIANO MIXER. Mejoras en la visualizaci\u00F3n de detecci\u00F3n de acordes',
    vh_490: '<b>V4.9</b> \u2014 Motor de modelado f\u00EDsico Pad Sensei MK1',
    vh_497: '<b>V4.9.7</b> \u2014 Tremolo ahora es f\u00EDsicamente modelado. Los miembros HPS obtienen Pad Sensei MK1 Suitcase (cadena de amplificador modelada f\u00EDsicamente)',
    vh_3377: '<b>V3.37.7</b> \u2014 Revisión de usuarios: corrección de tonalidad relativa menor, badges en Title Case, fuente sans-serif en pads, toggles accesibles para daltónicos (verde\u2192azul), panel Sound abierto por defecto, corrección de desplazamiento de layout, overlay de spotlight en tutoriales, soporte de octava en Launchpad + seguimiento automático de octava para todos los controladores MIDI',
    vh_340: '<b>V3.40</b> \u2014 Posicionamiento compacto TASTY/Stock: disposici\u00F3n \u00F3ptima autom\u00E1tica en la cuadr\u00EDcula de 64 pads. Bot\u00F3n "To Pad" eliminado. Cajas de voicing ocultas durante modo TASTY/Stock',
    vh_336: '<b>V3.36</b> \u2014 Motor de voicing guitarra v2: presets de g\u00E9nero (Jazz/Bossa/Funk), tabla de referencia (120 tipos \u00D7 12 tonos), asignaci\u00F3n autom\u00E1tica de dedos con detecci\u00F3n de cejilla',
    vh_335: '<b>V3.35</b> \u2014 Mejoras UX de tutoriales (revisi\u00F3n para principiantes). Todos los tooltips traducidos a 9 idiomas. Gu\u00EDa: secciones de panel de sonido e iconos de encabezado a\u00F1adidas',
    vh_333: '<b>V3.33</b> \u2014 Tutoriales interactivos. 11 temas \u00D7 9 idiomas. Sugerencias contextuales en la primera interacci\u00F3n con cada funci\u00F3n',
    vh_332: '<b>V3.32</b> \u2014 STOCK Voicing: 154 voicings de piano con pantalla de teclado espec\u00EDfica MIDI. Gu\u00EDa actualizada con secci\u00F3n de funciones de voicing HPS',
    vh_330: '<b>V3.30</b> \u2014 TASTY Voicing. 129 voicings sofisticados ordenados por nota superior. Visualizaci\u00F3n de array de grados + optimizaci\u00F3n autom\u00E1tica de octava. Solo miembros HPS',
    vh_325: '<b>V3.25.0</b> \u2014 Voicing de guitarra \u2192 reflejar en pad (tecla <kbd>V</kbd>). Cambio de dise\u00F1o estilo guitarra (1 nota por fila) / compacto. Filtro "Todos" de posici\u00F3n de guitarra al inicio',
    vh_324: '<b>V3.24</b> \u2014 Presets de Clavinet a\u00F1adidos (2 en E.PIANO). Efecto Auto Filter (filtro envolvente / auto-wah) a\u00F1adido',
    vh_323: '<b>V3.23</b> \u2014 Entrada de texto de acordes con autocompletado. "/" para enfocar, abreviaturas (dim, h=m7\u266D5), ordenaci\u00F3n por tensiones',
    vh_322: '<b>V3.22</b> \u2014 Circle of Fifths display. Syncs with key selection, shows diatonic chords & harmonic function, minor scale mode toggle',
    vh_321: '<b>V3.21</b> \u2014 Alternancia tr\u00EDada/t\u00E9trada diat\u00F3nica. Posiciones de guitarra/bajo agrupadas por cuerda ra\u00EDz',
    vh_37: '<b>V3.7</b> \u2014 Conservaci\u00F3n de posici\u00F3n de voicing (mantener autom\u00E1ticamente la forma de la digitaci\u00F3n en movimiento crom\u00E1tico). Cuadr\u00EDcula de pads, pentagrama y detecci\u00F3n de acordes durante la reproducci\u00F3n. <a href="https://youtu.be/mHSMM4GDNkE" target="_blank" style="color:var(--accent);">Video</a>',
    vh_35: '<b>V3.5</b> \u2014 Reproducci\u00F3n de archivo MIDI \u2192 iluminaci\u00F3n de pads (reproducci\u00F3n por l\u00EDnea de tiempo, visualizaci\u00F3n del nombre del acorde, Play/Pause/Stop/Seek)',
    vh_34: '<b>V3.4</b> \u2014 Sampler E.PIANO (Rhodes Mark I). 7 presets de EP. Interruptor de sonido ON/OFF. Soporte para iPad',
    vh_31: '<b>V3.1</b> \u2014 Sensibilidad de velocidad (4 par\u00E1metros + visualizaci\u00F3n de curva). Soporte para el bot\u00F3n de octava de Push 3. <a href="https://youtu.be/4vCkISlMVxc" target="_blank" style="color:var(--accent);">Video</a>',
    vh_250: '<b>V2.50</b> \u2014 M\u00FAltiples bancos de memoria (16 slots \u00D7 hasta 16 bancos, cambiar/duplicar/renombrar)',
    vh_218: '<b>V2.18</b> \u2014 Guardado/restauraci\u00F3n autom\u00E1tica de todos los ajustes (tonalidad/escala/sonido/MIDI/memoria)',
    vh_213: '<b>V2.13</b> \u2014 Superposici\u00F3n de escala de instrumento (guitarra/bajo/piano muestran Available Scale). Etiquetas de grado en pads. Reproducci\u00F3n vinculada a octava',
    vh_27: '<b>V2.7</b> \u2014 Modo de adici\u00F3n de tensiones (s\u00EDntesis de acordes en pad/guitarra/bajo/teclado \u2192 filtrado por Available Scale)',
    vh_22: '<b>V2.2</b> \u2014 Parent Scale + Scale Overlay (Available Tensions, superposici\u00F3n de escala en pads)',
    vh_19: '<b>V1.9</b> \u2014 9 idiomas',
    vh_18: '<b>V1.8</b> \u2014 Perform Mode, 16 ranuras de memoria, Undo, D&D',
    vh_15: '<b>V1.5</b> \u2014 Modo Plain, exportaci\u00F3n MIDI/CHS',
    vh_10: '<b>V1.0</b> \u2014 Lanzamiento inicial (Scale/Chord/Voicing/Sound/MIDI)',
  },
  pos: {
    root_6: '6\u00AAR',
    root_5: '5\u00AAR',
    root_4: '4\u00AAR',
    root_3: '3\u00AAR',
    root_2: '2\u00AAR',
    open: 'Abierta',
    no_open: 'Sin abiertas',
    all: 'Todas',
    voice_3: '3v',
    voice_4: '4v',
    voice_5: '5v',
    to_pad: 'Al Pad',
    genre_default: 'Est\u00E1ndar',
    genre_folk: 'Folk/Open',
    genre_jazz: 'Jazz',
    genre_bossa: 'Bossa',
    genre_funk: 'Funk/Soul',
    genre_neo_soul: 'Neo Soul',
  },
  tips: [
    'Pulsa C para guardar el acorde actual en Memory',
    'Opt+1~V guarda directamente en un slot (16 teclas: 1234 QWER ASDF ZXCV)',
    'Shift+Clic en un slot de Memory para eliminarlo',
    'Opt+Arrastrar para copiar un slot',
    'Pulsa S para alternar Shell voicings (1-3-7 / 1-7-3)',
    'Shift+D alterna Drop 2 / Drop 3',
    '\u2318\u2325G muestra el diapas\u00F3n de guitarra',
    '\u2318\u2325F muestra el C\u00EDrculo de Quintas',
    'Tab alterna entre modos Scale / Chord / Input',
    'Espacio reproduce la escala o acorde actual',
    'Exporta todos los slots de Memory como archivo MIDI',
    'Conecta un controlador MIDI para tocar los pads',
    'Flechas \u2193\u2191 cambian la inversi\u00F3n del acorde',
    'Pulsa R para voicing sin fundamental',
    'Pulsa O para omitir la 5\u00AA',
    '\u2318\u2325S muestra la partitura',
    'El icono de guardado preserva tus ajustes entre sesiones',
    '[ ] cambia bancos de Memory \u2014 gestiona varias canciones',
    'Modo Perform: Dispara acordes con teclado (1234 / QWER / ASDF / ZXCV) o pads MIDI',
    'Pulsa / en modo Chord para escribir nombres de acordes (ej: Cm7, G7(b9,#11))',
  ],
  tips_off: 'No mostrar consejos',
  whats_new: 'Novedades',
  whats_new_497: '\u00A1El tremolo ahora es f\u00EDsicamente modelado! Los miembros HPS obtienen Pad Sensei MK1 Suitcase.',
  whats_new_61: 'El manual en línea ahora es accesible desde la Guía. Actualmente en construcción.',
  whats_new_123: 'El manual en línea ahora es accesible desde la Guía. Actualmente en construcción.',
  whats_new_51: '¡Modo Do mayor fijo añadido! Actívalo desde Ayuda (?). Push/Launchpad mostrará siempre Do mayor.',
  whats_new_50: '\u00A1Reverberaciones de muelle y placa a\u00F1adidas! Baxandall Bass/Treble EQ, ampli Suitcase mejorado.',
  whats_new_32427: 'Voicing de guitarra \u2192 reflejar en pad (tecla V). Cambio de dise\u00F1o estilo guitarra / compacto',
  whats_new_33000: '\u00A1Sistema de tutoriales! Haz clic en el icono del libro en el encabezado para aprender el modo Scale, el modo Chord y m\u00E1s.',
  whats_new_640: 'V6.4.0 ya está disponible: detección de tres tensiones, análisis UST, visualización Note/Degree y escritura # / b según la tonalidad.',
  whats_new_650: 'V6.5.0 ya está disponible: los voicings HPS TASTY / STOCK / Guitar ahora viven dentro del Chord Builder. La familia de sexta usa C6(9) / C6(9,#11), con mejores filtros de guitarra, equilibrio visual y rango de reproducción.',
  whats_new_660: 'V6.6.0 ya está disponible: los miembros HPS obtienen voicings modales por cuartas (So What) en TASTY — el sonido de Miles Davis / McCoy Tyner — para acordes menores, mayores y dominantes. El orden de los tipos en el Chord Builder también ha sido reorganizado.',

  // Tutorial (first-time onboarding)
  tutorial: {
    sound_title: 'Preset de sonido',
    sound_msg: 'Elige un preset de sonido y toca un pad para escucharlo.\nORGAN y E.PIANO \u2014 cada uno tiene m\u00FAltiples presets.',
    sound_done: '\u00A1Suena bien! Pulsa Siguiente para continuar.',
    midi_title: 'Controlador MIDI',
    midi_msg: 'Se ha detectado un controlador MIDI. Selecciona tu dispositivo del men\u00FA desplegable.\nLa sensibilidad de velocidad se puede ajustar en el panel Sound.',
    midi_no_device: 'No se detect\u00F3 controlador MIDI \u2014 no hay problema.\nPuedes usar clics en pads, entrada de guitarra/bajo/piano o entrada de texto de acordes.',
    input_title: 'Tres modos',
    input_msg: 'Scale \u2014 ver notas de escala en la cuadr\u00EDcula de 64 pads\nChord \u2014 construir acordes con voicings, inversiones y tensiones\nInput \u2014 toca los pads libremente para detectar nombres de acordes\n\nCambia con Tab o los botones de modo de arriba.',
    instruments_title: 'Entrada de instrumentos',
    instruments_msg: 'Guitarra, Bajo, Piano \u2014 activa cada visualizaci\u00F3n y haz clic para ingresar notas directamente.\nClic en el diapas\u00F3n \u2192 detecci\u00F3n de acordes \u2192 "Al Pad" (V) para convertir al layout de pads.\nEntrada de texto: pulsa / en modo Chord para escribir nombres de acordes (ej. Cm7, G7(b9,#11)).',
    done_title: '\u00A1Listo!',
    done_msg: 'Todo preparado. Explora libremente \u2014 pulsa ? para la lista completa de atajos.\nEl manual en l\u00EDnea tiene gu\u00EDas detalladas de cada funci\u00F3n.',
    next: 'Siguiente',
    skip_step: 'Siguiente',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Manual en Línea',
    close: 'Empezar',
    reset: 'Reiniciar tutorial',
  },

  // Tutorial system (tut.* namespace)
  tut: {
    // Selector UI
    selector_title: 'Tutoriales',
    cat_getting_started: 'Primeros pasos',
    cat_features: 'Funciones',
    cat_advanced: 'Avanzado',
    steps_label: 'pasos',
    reset_all: 'Reiniciar todo el progreso',
    close_selector: 'Cerrar',
    hint_available: 'Tutorial disponible',
    hint_try: 'Probar',
    // Button label
    btn_label: 'Tutoriales',
    // Shared action labels
    next: 'Siguiente',
    skip_step: 'Siguiente',
    skip_all: 'Saltar tutorial',
    open_guide: 'Abrir Manual en Línea',
    close: 'Listo',
    // Onboarding ask dialog
    onboarding_ask_title: 'Tutorial',
    onboarding_ask_msg: '\u00BFEs tu primera vez aqu\u00ED? \u00BFQuieres un recorrido r\u00E1pido de la app?',
    onboarding_yes: 'Siguiente',
    onboarding_no: 'Saltar',
    // Onboarding
    onboarding_title: 'Primeros pasos',
    onboarding_desc: 'Aprende los fundamentos de 64 Pad Explorer',
    onboarding: {
      app_version_title: 'Sobre la App de Escritorio',
      app_version_msg: 'Esta es 64Pad Explorer Desktop (Standalone / VST3 / AU).\n\nVersi\u00F3n navegador: el motor de audio integrado (ORGAN / E.PIANO) reproduce sonido directamente.\nVersi\u00F3n Desktop: no hay audio integrado. Los pads env\u00EDan MIDI \u2014 el sonido proviene de un plugin VST/AU externo (p.ej. Pad Sensei MK1) en tu DAW o como plugin cargado. La integraci\u00F3n con Push 3 est\u00E1 disponible en modo Standalone.\n\nEl tutorial se centra en la salida MIDI y las funciones de visualizaci\u00F3n.',
      sound_title: 'Preset de sonido',
      sound_title_desktop: 'Salida de sonido',
      sound_msg: 'Elige un preset de sonido y toca un pad para escucharlo.\nORGAN y E.PIANO \u2014 cada uno tiene m\u00FAltiples presets.',
      sound_msg_desktop: 'El panel de sonido contiene configuraci\u00F3n de salida MIDI.\nEl audio lo produce tu DAW o un plugin VST/AU externo. La sensibilidad de velocidad se puede ajustar aqu\u00ED.',
      sound_done: '\u00A1Suena bien! Pulsa Siguiente para continuar.',
      midi_title: 'Controlador MIDI',
      midi_msg: 'Se ha detectado un controlador MIDI. Push 3 y Launchpad funcionan de inmediato \u2014 sin configuraci\u00F3n necesaria.\nLa sensibilidad de velocidad se puede ajustar en el panel Sound.',
      midi_no_device: 'No se detect\u00F3 controlador MIDI \u2014 no hay problema.\nPuedes usar clics en pads, entrada de guitarra/bajo/piano o entrada de texto de acordes.',
      input_title: 'Tres modos',
      input_msg: 'Scale \u2014 ver notas de escala en la cuadr\u00EDcula de 64 pads\nChord \u2014 construir acordes con voicings, inversiones y tensiones\nInput \u2014 toca los pads libremente para detectar nombres de acordes\n\nCambia con Tab o los botones de modo de arriba.',
      instruments_title: 'Entrada de instrumentos',
      instruments_msg: 'Guitarra, Bajo, Piano \u2014 activa cada visualizaci\u00F3n y haz clic para ingresar notas directamente.\nClic en el diapas\u00F3n \u2192 detecci\u00F3n de acordes \u2192 "Al Pad" (V) para convertir al layout de pads.\nEntrada de texto: pulsa / en modo Chord para escribir nombres de acordes (ej. Cm7, G7(b9,#11)).',
      done_title: '\u00A1Listo!',
      done_msg: 'Todo preparado. Explora libremente \u2014 pulsa ? para la lista completa de atajos.\nEl manual en l\u00EDnea tiene gu\u00EDas detalladas de cada funci\u00F3n.',
    },
    // Scale Mode tutorial
    scale_mode_title: 'Modo Scale',
    scale_mode_desc: 'Explora escalas en la cuadr\u00EDcula de 64 pads',
    scale_mode: {
      step1_title: 'Cambiar al modo Scale',
      step1_msg: 'El modo Scale muestra las notas de la escala iluminadas en la cuadr\u00EDcula.\nToca cualquier pad iluminado para escuchar la nota.',
      step2_title: 'Elige una tonalidad',
      step2_msg: 'Elige una tonalidad ra\u00EDz. La cuadr\u00EDcula se actualiza al instante.\nPrueba a cambiar entre C, G, F \u2014 escucha c\u00F3mo cambia el patr\u00F3n de colores.',
      step3_title: 'Elige una escala',
      step3_msg: 'Major, Minor, Dorian, Mixolydian, Pentatonic...\n31 escalas disponibles. Los pads se actualizan en tiempo real.',
      step4_title: 'Barra diat\u00F3nica',
      step4_msg: 'Los acordes diat\u00F3nicos de tu escala aparecen aqu\u00ED.\nHaz clic en cualquier acorde para ir al modo Chord con ese voicing.',
    },
    // Chord Mode tutorial
    chord_mode_title: 'Modo Chord',
    chord_mode_desc: 'Construye acordes paso a paso',
    chord_mode: {
      step1_title: 'Cambiar al modo Chord',
      step1_msg: 'El modo Chord ofrece dos formas de seleccionar acordes.\n\u2460 Elige de la barra diat\u00F3nica con un clic\n\u2461 Construye el tuyo: Root \u2192 Quality \u2192 Tension',
      step_key_title: 'Selección de tonalidad',
      step_key_msg: 'Establece la tonalidad de la escala. Cuando se establece una tonalidad, la barra diatónica muestra acordes y la disponibilidad de tensiones se filtra.\nTambién puedes construir acordes libremente desde Root sin usar tonalidad.',
      step_diatonic_title: 'Barra diatónica',
      step_diatonic_msg: 'Acordes diatónicos para la tonalidad seleccionada.\nHaz clic para establecer un acorde al instante con filtrado de tensiones según la escala.',
      step2_title: 'Paso 1: Root',
      step2_msg: 'Elige una nota ra\u00EDz. C, D, E... las 12 notas.\nLa pantalla muestra tu acorde actual.',
      step3_title: 'Paso 2: Quality',
      step3_msg: 'Elige el tipo de acorde: Maj, min, 7, m7, dim, aug...\nLa cuadr\u00EDcula ilumina las notas del acorde.',
      step4_title: 'Paso 3: Tensions',
      step4_msg: 'Elige primero una Quality \u2014 los botones de tensi\u00F3n aparecen autom\u00E1ticamente.\n9, b9, #9, 11, #11, 13, b13. Se pueden seleccionar m\u00FAltiples tensiones.',
      step5_title: 'Entrada de texto',
      step5_msg: 'Escribe nombres de acordes directamente con la tecla /.\nSlash chords y voicings complejos se introducen r\u00E1pidamente.',
      step6_title: 'Encontrar escalas de dominante secundaria',
      step6_msg: 'Introduce directamente un acorde no diat\u00F3nico.\nEjemplo: Input G7 \u2192 Available Scale muestra "Mixolydian", "Mixolydian b13", etc.\nCambia a Practical sort para ver primero las escalas m\u00E1s \u00FAtiles.\nAs\u00ED encuentras la escala correcta para las dominantes secundarias.',
      step7_title: 'Slash Chords',
      step7_msg: 'Haz clic en / en el constructor de acordes para introducir una nota de bajo para Slash Chords.\nTambi\u00E9n puedes escribir C/D o F\u25B37/G en la entrada de texto.\nAvailable Scale se actualiza para coincidir con el Slash Chord.',
    },
    // Input Mode tutorial
    input_mode_title: 'Modo Input',
    input_mode_desc: 'Introduce acordes desde controlador MIDI, pads, diapas\u00F3n o teclado',
    input_mode: {
      step1_title: 'Cambiar al modo Input',
      step1_msg: 'Introduce acordes desde un controlador MIDI, haciendo clic en los pads, el diapas\u00F3n o el teclado.\nLa detecci\u00F3n de acordes funciona en todos los modos.',
      step2_title: 'Toca algunos pads',
      step2_msg: 'Haz clic en cualquier pad de la cuadr\u00EDcula.\nCada toque activa/desactiva una nota.',
      step3_title: 'Detecci\u00F3n de acordes',
      step3_msg: 'El nombre del acorde detectado aparece sobre la cuadr\u00EDcula.\nEtiquetas de grado (R, 3, 5, b7...) se muestran en cada pad.',
      step4_title: 'Guardar con Capture',
      step4_msg: 'La tecla <strong>C</strong> guarda el acorde actual en la siguiente ranura de memoria.\nConstruye progresiones de acordes una por una.',
    },
    // Diatonic Bar tutorial
    diatonic_title: 'Barra diat\u00F3nica',
    diatonic_desc: 'Acceso con un clic a los acordes diat\u00F3nicos',
    diatonic: {
      step1_title: 'La barra diat\u00F3nica',
      step1_msg: 'Cada escala tiene su propio conjunto de acordes diat\u00F3nicos.\nAparecen aqu\u00ED \u2014 listos para tocar.',
      step2_title: 'Tr\u00EDada / T\u00E9trada',
      step2_msg: 'Alterna entre tr\u00EDadas de 3 notas y acordes de s\u00E9ptima de 4 notas.\nLa barra se actualiza al instante.',
      step3_title: 'Haz clic en un acorde',
      step3_msg: 'Haz clic en un acorde de la barra.\nPuedes transformarlo con tensiones y m\u00E1s en el Chord Builder.',
      step4_title: 'Atajo de teclado',
      step4_msg: 'Pulsa 1\u20137 para seleccionar acordes diat\u00F3nicos al instante.\nSin necesidad de rat\u00F3n.',
      step5_title: 'Dominante secundaria',
      step5_msg: 'Activa "Secondary Dominant" (\u2318\u2325D).\nSe muestran los acordes V7 que resuelven a cada acorde diatónico.\nHaz clic en uno y Available Scale se muestra automáticamente.\nResolución a mayor \u2192 Mixolydian. Resolución a menor \u2192 HMP5\u2193/Altered.',
      step6_title: 'Atajos de teclado',
      step6_msg: 'Pulsa 1\u20137 para acordes diatónicos.\n\u2318\u2325N (Harm/Mel), \u2318\u2325D (SecDom), \u2318\u2325R (Tonalidad paralela) para barras de extensión.',
    },
    // Memory & Perform tutorial
    memory_title: 'Memory & Perform',
    memory_desc: 'Guarda acordes y t\u00F3calos en vivo',
    memory: {
      step1_title: 'Guardar un acorde',
      step1_msg: 'Guarda tus acordes favoritos.\nGuardar los voicings que te gustan ayuda con el beat-making y la pr\u00E1ctica.',
      step2_title: '16 ranuras de memoria',
      step2_msg: 'Funciona como un layout Drumrack de 16 pads en PUSH, Launchpad, MPC y Maschine \u2014 intuitivo de usar.',
      step3_title: 'Bancos de memoria',
      step3_msg: 'En PUSH y Launchpad, el layout Drumrack lo hace intuitivo de usar.',
      step4_title: 'Modo Perform',
      step4_msg: 'Las teclas del teclado del PC tambi\u00E9n corresponden a los 16 pads.',
      step5_title: 'Exportaci\u00F3n MIDI',
      step5_msg: 'Exporta todos los acordes de memoria como archivo MIDI.\nArr\u00E1stralo a tu DAW y empieza a producir.',
    },
    // Voicing tutorial
    voicing_title: 'Voicing',
    voicing_desc: 'Da forma a tus voicings de acordes',
    voicing: {
      step1_title: 'Controles de voicing',
      step1_msg: 'En el modo Chord Builder, varias transformaciones son posibles desde la forma b\u00E1sica.\nOmit, Shell, Inversion, Drop \u2014 todo aqu\u00ED.',
      step2_title: 'Shell Voicing',
      step2_msg: '<strong>S</strong> es para Shell voicing. Aprende los voicings R37 y R73 de forma fluida en el pad.',
      step3_title: 'Omit & Rootless',
      step3_msg: 'Los atajos de teclado suelen seguir mnemotecnia.\n<strong>O</strong>mit = omitir la 5\u00AA. <strong>R</strong>ootless = voicing sin fundamental.',
      step4_title: 'Inversiones',
      step4_msg: 'A diferencia de la mayor\u00EDa del software, puedes crear inversiones ultra-r\u00E1pido.\nTambi\u00E9n ayuda a entender los slash chords.',
      step5_title: 'Drop Voicing',
      step5_msg: 'Para cuando quieres destacar la nota superior \u2014\nlos Drop voicings tambi\u00E9n est\u00E1n disponibles.',
      step6_title: 'Voicing Box',
      step6_msg: 'Los pads pueden tener m\u00FAltiples opciones de posici\u00F3n. El Voicing Box se encarga de esto.\nHaz clic en a, b, c, d etc. en el pad, o escribe la letra, para ver m\u00FAltiples posibilidades de voicing.',
    },
    // Sound tutorial
    sound_title: 'Sound',
    sound_desc: 'Presets, efectos y volumen',
    sound: {
      step1_title: 'Presets de sonido',
      step1_title_desktop: 'Salida MIDI',
      step1_msg: 'ORGAN (4 tipos) y E.PIANO (8 tipos).\nHaz clic en un pad o usa tu controlador MIDI.',
      step1_msg_desktop: 'La versi\u00F3n Desktop no tiene audio integrado.\nAl hacer clic en un pad se env\u00EDan notas MIDI. Carga un plugin VST/AU (p.ej. Pad Sensei MK1) en tu DAW o como plugin cargado para producir sonido.\nLa sensibilidad de velocidad se puede ajustar aqu\u00ED.',
      step2_title: 'Panel de detalles',
      step2_msg: 'Haz clic en \u25BC para expandir el panel de detalles de sonido.\nEfectos, volumen y controles de filtro est\u00E1n aqu\u00ED.',
      step3_title: 'Efectos',
      step3_msg: 'Reverb, Phaser, Flanger, Tremolo, Auto-Filter, Drive.\nAj\u00FAstalos en el panel de detalles.',
      step4_title: 'Sonido ON/OFF',
      step4_msg: 'Activa y desactiva el sonido con el icono del altavoz.\nDesactivarlo puede ser pr\u00E1ctico al usar un DAW.',
    },
    // TASTY Voicing tutorial
    tasty_title: 'TASTY Voicing',
    tasty_desc: 'Mote Voicings clasificados por nota superior. Solo miembros HPS',
    tasty: {
      step1_title: 'Activar TASTY',
      step1_msg: '129 voicings sofisticados que la l\u00F3gica simple no puede producir.\nPensar desde la nota superior es \u00FAtil para arreglos de cuerdas y vientos.\n(Solo miembros HPS)',
      step2_title: 'Ciclar recetas',
      step2_msg: 'Teclas Z / X para explorar voicings hacia adelante/atr\u00E1s.\nEl contador muestra tu posici\u00F3n.',
      step3_title: 'Notaci\u00F3n de grados',
      step3_msg: 'El \u00E1rea de info muestra el apilamiento de grados \u2014 ej. m9 (b3-b7-9-5-1).\nEs la estructura del voicing de abajo a arriba.',
      step4_title: 'Al Pad',
      step4_msg: 'Optimizaci\u00F3n de pads que el software t\u00EDpico no puede hacer.\nDisfruta tocando voicings elegantes en los pads tambi\u00E9n.',
      fb_step1_title: '\u00BFQu\u00E9 es TASTY Voicing?',
      fb_step1_msg: '129 voicings sofisticados ordenados por nota superior.\nCompatible con Maj7 / Dom7 / Min7. Mostrado en notaci\u00F3n de grados.\nSolo miembros HPS.',
      fb_step2_title: 'C\u00F3mo acceder a TASTY',
      fb_step2_msg: 'Disponible al unirse a HPS (Hardcore Pad Style).\nPulsa T en modo Chord para activar. Teclas Z/X para explorar voicings.\nVer la Gu\u00EDa para m\u00E1s detalles.',
    },
    // STOCK Voicing tutorial
    stock_title: 'STOCK Voicing',
    stock_desc: 'Voicings idiom\u00E1ticos cl\u00E1sicos de piano. Solo miembros HPS',
    stock: {
      step1_title: 'Activar STOCK',
      step1_msg: 'Conocer voicings espec\u00EDficos de piano te ayuda a salir del juego de solo forma b\u00E1sica.\n154 voicings de piano en notaci\u00F3n de grados.\n(Solo miembros HPS)',
      step2_title: 'Ciclar voicings',
      step2_msg: 'Teclas Z / X para explorar voicings hacia adelante/atr\u00E1s.',
      step3_title: 'Vista de teclado',
      step3_msg: 'Activa la visualizaci\u00F3n de Piano para ver las posiciones reales.\nEl voicing cobra vida en el teclado.',
      step4_title: 'Al Pad',
      step4_msg: 'Haz clic en "Al Pad" para mapear el voicing al layout de pads.\nGuarda en memoria y exporta a tu DAW.',
      fb_step1_title: '\u00BFQu\u00E9 es STOCK Voicing?',
      fb_step1_msg: 'Presenta voicings de piano de uso com\u00FAn.\nLa notaci\u00F3n de grados muestra la estructura.\nSolo miembros HPS.',
      fb_step2_title: 'C\u00F3mo acceder a STOCK',
      fb_step2_msg: 'Disponible al unirse a HPS (Hardcore Pad Style).\nPulsa K en modo Chord para activar.\nVer la Gu\u00EDa para m\u00E1s detalles.',
    },
    // Minor 3 Scales tutorial
    minor_scales_title: 'Comparar 3 escalas menores',
    minor_scales_desc: 'Natural, Armónica y Melódica lado a lado',
    minor_scales: {
      step1_title: 'Establecer una tonalidad menor',
      step1_msg: 'Am (Natural Minor) está seleccionada.\nLa barra diatónica muestra los acordes de Menor Natural.',
      step2_title: 'Activar Harm/Mel',
      step2_msg: 'Haz clic en "Harm/Mel" (\u2318\u2325N).\nLos acordes diatónicos de Menor Armónica y Melódica aparecen debajo.',
      step3_title: 'Comparar',
      step3_msg: 'Observa las diferencias con Menor Natural (barra superior).\nEn HM, el acorde V cambia de Em7 a E7 \u2014 permitiendo movimiento dominante.\nEn MM, el acorde IV también cambia de Dm7 a D7.\nHaz clic en cualquier acorde para verlo en los pads.',
      step4_title: 'Tonalidad paralela',
      step4_msg: 'Activa "Parallel Key" (\u2318\u2325R) para ver los acordes diatónicos de la tonalidad mayor con la misma raíz.\nEsto revela el origen de los acordes prestados (intercambio modal).',
    },
    // Secondary Dominant tutorial
    secdom_title: 'Dominante secundaria',
    secdom_desc: 'Experimenta la puerta de entrada a la modulación',
    secdom: {
      step1_title: 'Comenzar en C Major',
      step1_msg: 'C Major está establecida.\nLa barra diatónica muestra C\u25B37, Dm7, Em7, F\u25B37, G7, Am7, Bm7(b5).',
      step2_title: 'Activar Dominante secundaria',
      step2_msg: 'Haz clic en "Secondary Dominant" (\u2318\u2325D).\nAparecen acordes V7 que resuelven a cada acorde diatónico.\nEn C Major: C7, D7, E7, A7, B7 (5 en total).',
      step3_title: 'Resolución a Mayor',
      step3_msg: 'Haz clic en C7 (\u2192F\u25B37) o D7 (\u2192G7).\nAvailable Scale muestra Mixolydian como primera opción.\nPorque el destino de resolución es un acorde mayor.',
      step4_title: 'Resolución a menor',
      step4_msg: 'Haz clic en A7 (\u2192Dm7) o E7 (\u2192Am7).\nAvailable Scale muestra HMP5\u2193 (Phrygian Dominant) y Altered como primeras opciones.\nPorque el destino de resolución es un acorde menor.',
      step5_title: 'La regla: solo 2 tipos',
      step5_msg: 'La selección de escala para dominantes secundarias es sencilla:\n\u2022 Resolución a mayor \u2192 Mixolydian\n\u2022 Resolución a menor \u2192 HMP5\u2193 o Altered\nEso es todo lo que necesitas recordar.',
    },
    // Circle of Fifths tutorial
    circle_title: 'C\u00EDrculo de quintas',
    circle_desc: 'Relaciones entre tonalidades de un vistazo',
    circle: {
      step1_title: 'Abrir el c\u00EDrculo',
      step1_msg: 'Pulsa \u2318\u2325F o haz clic en el bot\u00F3n del c\u00EDrculo.\nEl c\u00EDrculo de quintas aparece debajo.',
      step2_title: 'Enlace de tonalidad',
      step2_msg: 'Consulta r\u00E1pidamente acordes sustitutos y diat\u00F3nicos importantes para la interpretaci\u00F3n y la composici\u00F3n.',
      step3_title: 'Funciones diat\u00F3nicas',
      step3_msg: 'A diferencia del c\u00EDrculo de quintas t\u00EDpico, 64 Pad Explorer te permite seleccionar 3 tipos de menor (Natural/Harmonic/Melodic) al elegir una tonalidad menor.\nFacilita el dominio de las complicadas tonalidades menores.',
      step4_title: 'Seleccionar tonalidad menor',
      step4_msg: 'El anillo interior del c\u00EDrculo muestra tonalidades menores.\nHaz clic en una tonalidad del anillo interior para seleccionar una tonalidad menor.\nLa visualizaci\u00F3n de acordes diat\u00F3nicos cambiar\u00E1.',
      step5_title: '3 tipos de escala menor',
      step5_msg: 'Cuando se selecciona una tonalidad menor, aparecen los botones Nat / Harm / Mel en el centro.\nNat = Natural Minor (forma est\u00E1ndar)\nHarm = Harmonic Minor (aparece V7)\nMel = Melodic Minor (cambian los grados VI, VII)',
      step6_title: 'Intenta cambiar',
      step6_msg: 'Haz clic en Nat \u2192 Harm \u2192 Mel y observa c\u00F3mo cambian los acordes diat\u00F3nicos.\nObserva c\u00F3mo aparece V7 en Harmonic Minor.',
    },
    // Guitar tutorial
    guitar_title: 'Diagrama de guitarra',
    guitar_desc: 'Introduce acordes desde guitarra y refl\u00E9ctalos en los pads',
    guitar: {
      step1_title: 'Mostrar diapas\u00F3n',
      step1_msg: 'Pulsa \u2318\u2325G o haz clic en el bot\u00F3n Guitar.\nLas notas del acorde aparecen en el diapas\u00F3n.',
      step2_title: 'Ver posiciones de acorde',
      step2_msg: 'Selecciona un acorde en modo Chord y el diapas\u00F3n muestra autom\u00E1ticamente las posiciones correspondientes.\nUsa las teclas coma (,) y punto (.) para ciclar posiciones.',
      step3_title: 'Introducir desde guitarra',
      step3_msg: 'Cambia al modo Input. Intenta hacer clic en los trastes del diapas\u00F3n para introducir notas.\nLos nombres de acordes se detectan en tiempo real.',
      step4_title: 'Reflejar en pad',
      step4_msg: '"Reflejar en pad" mapea el voicing de guitarra a la cuadr\u00EDcula de pads.',
    },
    // Link Mode tutorial
    link_title: 'Modo Link',
    link_desc: 'Sincronizar notas tocadas en todos los instrumentos',
    link: {
      step1_title: 'Botón Link',
      step1_msg: 'El botón Link está junto a Guitar / Bass / Piano.\nActívalo para ver las notas tocadas en todos los instrumentos en tiempo real.',
      step2_title: 'Modo Link activado',
      step2_msg: 'Cuando Link está activo, las visualizaciones de instrumentos se atenúan.\nToca pads o MIDI \u2014 solo las notas tocadas se iluminan.',
      step3_title: 'Toca los pads',
      step3_msg: 'Pulsa un pad y observa cómo la misma nota se ilumina en guitarra, bajo y piano.\nDescubre qué posiciones en cada instrumento producen el mismo tono.\nSuelta para borrar.',
      step4_title: 'Atajo',
      step4_msg: '\u2318\u2325+L activa/desactiva el modo Link.\nPerfecto para aprender cómo se mapean las notas entre instrumentos.',
    },
    // Shortcuts tutorial
    shortcuts_title: 'Atajos de teclado',
    shortcuts_desc: 'Teclas esenciales para operar con eficiencia',
    shortcuts: {
      step1_title: 'Cambio de modo',
      step1_msg: 'Tab \u2014 Cambiar modos (Scale \u2192 Chord \u2192 Input)\nShift+Tab \u2014 Direcci\u00F3n inversa\n\nCambia r\u00E1pidamente entre modos.',
      step2_title: 'Diat\u00F3nica & navegaci\u00F3n',
      step2_msg: '1\u20137 \u2014 Seleccionar acorde diat\u00F3nico\n\u2191\u2193 \u2014 Ciclar inversiones\n\u2190\u2192 \u2014 Transportar ra\u00EDz por semitono (mantiene forma del acorde)\n\nOpera acordes sin rat\u00F3n.',
      step3_title: 'Operaciones de voicing',
      step3_msg: 'S \u2014 Ciclo Shell (apagado \u2192 1-3-7 \u2192 1-7-3)\nO \u2014 Toggle Omit 5\nR \u2014 Toggle Rootless\nShift+D \u2014 Ciclo Drop (apagado \u2192 Drop2 \u2192 Drop3)\nT \u2014 TASTY ON/OFF, K \u2014 STOCK ON/OFF\nZ / X \u2014 voicing TASTY/STOCK anterior/siguiente\n\u2190\u2192 \u2014 Transportar voicing por semitono (durante TASTY/STOCK)\nV \u2014 Reflejar en pad / cambio de layout\n/ \u2014 Entrada de texto de acorde',
      step4_title: 'Memoria & bancos',
      step4_msg: 'Option+1234/qwer/asdf/zxcv \u2014 Guardar en ranura\n[ ] \u2014 Cambiar bancos\nM \u2014 Toggle vista memoria\nP \u2014 Toggle modo Perform\nSpace \u2014 Reproducir\nShift+Space \u2014 Reproducir todo (secuencial)',
      step5_title: 'M\u00E1s',
      step5_msg: '? \u2014 Ayuda (lista completa de atajos)\n\u2318\u2325+G/B/P/F/S \u2014 Toggles Instrumento/C\u00EDrculo/Partitura\n\u2318\u2325+A/M/T/Q/V/K/H \u2014 Toggles de secciones\nCmd/Ctrl+Z \u2014 Deshacer (hasta 30 veces)\nEsc \u2014 Deseleccionar / Cerrar modales',
    },
    // Settings tutorial
    settings_title: 'Pantalla y ajustes',
    settings_desc: 'Personaliza tu espacio de trabajo',
    settings: {
      step1_title: 'Paneles de instrumentos',
      step1_msg: 'Guitar muestra voicings de uso com\u00FAn al seleccionar un acorde en el Chord Builder.\nEn el modo Input, tambi\u00E9n puedes introducir desde guitarra, bajo y teclado.',
      step2_title: 'Nombres / Grados',
      step2_msg: 'Alterna entre nombres de notas (C, D, E) y grados (R, 2, 3).\nSe aplica a los pads y a la visualizaci\u00F3n de guitarra.',
      step3_title: 'Desplazamiento de octava',
      step3_msg: 'Usa \u25B2\u25BC para desplazar el rango de los pads una octava arriba o abajo.\nLos botones de octava de Push 3 y Launchpad se sincronizan autom\u00E1ticamente.',
      step4_title: 'Colapsar secciones',
      step4_msg: '\u2318\u2325+Q (Quality/Tension) / V (Voicing) / K (Key) / M (Memory) / T (Text) para colapsar secciones.\nMuestra solo lo que necesitas.',
      step5_title: 'Orden de layout',
      step5_msg: 'En ? Ayuda, usa el desplegable "Layout" para reordenar los 3 paneles.\n6 presets: Chord, Pad, Circle en cualquier orden.\nEn m\u00F3vil, el orden de deslizamiento tambi\u00E9n cambia.',
      step6_title: 'Guardar todo',
      step6_msg: 'Haz clic en el icono de guardar para conservar todos los ajustes.\nTonalidad, escala, sonido, memoria, voicing \u2014 todo se preserva.',
    },
  },
});
